canonical/ubuntu-pro-client

- requirements.txt
- tests/test_ubuntu_advantage.py
- ubuntu-advantage
Note that the script is not yet fully functional, since the GPG key is not imported.
Also, it currently points at staging.
> Add actions to the script to enable/disable the repository

- .travis.yml
- requirements.txt
- tests/test_ubuntu_advantage.py
- ubuntu-advantage
Import the GPG key used to sign the ESM repository.
Currently, the public key is the one for staging.
> Import GPG key for the repository

- update-motd.d/99-esm
Signed-off-by: Alberto Donato <alberto.donato@gmail.com>
> Use here-document for motd text.

- README.md
- tests.py
- ubuntu-advantage
Signed-off-by: Alberto Donato <alberto.donato@gmail.com>
> Run apt-get update.

- debian/copyright
- ubuntu-advantage
> Fix copyright version.

- tests.py
- ubuntu-advantage
> written .list file should be og-rwx (Fixes #22).

- .travis.yml
- ubuntu-advantage
- update-motd.d/99-esm
- update-motd.d/99-livepatch
Run shellcheck in Travis builds.
Also, a couple of minor cleanups in the script
> Add shellcheck linter

- ubuntu-advantage.1
> Document return codes on the manpage

- ubuntu-advantage
> Fix word wrapping on some messages

- tests.py
- ubuntu-advantage
- ubuntu-advantage.1
> Only enable/disable ESM on precise

- tests/test_esm.py
- tests/test_livepatch.py
- tests/test_script.py
- tests/testing.py
- ubuntu-advantage
Ack's PR #53 has test failures. Here I added just the needed fixes for the 3 failing tests.
> Tests setup refactor from ack

- tests/fakes.py
- tests/test_esm.py
- tests/test_livepatch.py
- tests/testing.py
- ubuntu-advantage
Rework tests from https://github.com/CanonicalLtd/ubuntu-advantage-script/pull/56 to add explicit tests for apt-get being called with right parameters.
> Apt not inteactive (based on Andreas' #56)

- tests/test_fips.py
- ubuntu-advantage
> Check if FIPS just needs reboot to enable

- debian/changelog
debian/changelog update for a new release into ubuntu bionic
> Release v13

- tests/test_fips.py
- tests/testing.py
- ubuntu-advantage
> check for CPU hardware support when enabling FIPS

- ubuntu-advantage
> reorder status output and remove extra newlines

- tests/test_fips.py
- tests/testing.py
- ubuntu-advantage
- group and reorder global variables
- add an `error_msg` helper, write all error messages to stderr
- make the function to create an APT source file generic
> a few cleanups

- tests/test_fips.py
- ubuntu-advantage
- ubuntu-advantage.1
> Disable fips

- modules/service-esm.sh
- modules/service-fips.sh
- modules/service-livepatch.sh
- modules/support.sh
- modules/utils.sh
- tests/test_esm.py
- tests/test_fips.py
- tests/test_livepatch.py
- ubuntu-advantage.1
> Check that arch is supported when enabling livepatch

- modules/apt.sh
- modules/service-esm.sh
- modules/service-fips.sh
- tests/test_esm.py
- tests/test_fips.py
- tests/testing.py
- ubuntu-advantage
> Use APT auth.conf for storing credentials

- modules/service-fips.sh
- tests/test_fips.py
- ubuntu-advantage
> fix return value for FIPS arch check

- Makefile
- debian/rules
- tests/fakes.py
- tests/test_livepatch_motd.py
- tests/test_script.py
- tests/testing.py
- update-motd.d/99-esm
- update-motd.d/99-livepatch
This branch adds a MOTD script for Livepatch, and tests. Lots of tests.
> Livepatch motd

- modules/service.sh
- tests/fakes.py
- tests/test_esm.py
- tests/test_fips.py
- tests/test_livepatch.py
- tests/testing.py
- ubuntu-advantage.1
> Check if a service is already enabled before enabling

- modules/service-fips.sh
- modules/service-livepatch.sh
- modules/service.sh
- modules/support.sh
- tests/test_esm.py
- tests/test_fips.py
- tests/test_livepatch.py
- tests/testing.py
- ubuntu-advantage
- ubuntu-advantage.1
> Refactor disable commands

- modules/apt.sh
- modules/credentials.sh
- modules/service-fips.sh
- modules/service-livepatch.sh
- modules/service.sh
- modules/snap.sh
- modules/support.sh
- modules/utils.sh
- ubuntu-advantage
> A few bash-powered cleanups

- tests/fakes.py
- tests/test_livepatch_motd.py
- update-motd.d/99-livepatch
I can squash the commits before merging.
> Don't update cache inside motd script (Fixes: #130)

- debian/changelog
- debian/tests/update-motd-run
This PR brings in d/changelog changes from what was uploaded to ubuntu recently. It also fixes #136 (DEP8 test failure) and opens up v17 for development.
> V16 release (Fixes #136)

- modules/service-livepatch.sh
- tests/fakes.py
- tests/test_script.py
Make sure extra blank lines are removed from the canonical-livepatch output.
> Extra blank line 145

- README.md
This was forgotten in the CC branch.
> README.md file update for Common Criteria

- ubuntu-advantage
It's a needless implementation detail.
> Remove PPA from help output

- dev/contracts-controller.patch
- dev/contracts-schema.patch
- dev/demo-contract-service
- dev/install-contracts-server
- modules/service-livepatch.sh
- uaclient/cli.py
- uaclient/config.py
- uaclient/contract.py
- uaclient/entitlements/base.py
- uaclient/entitlements/esm.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_base.py
- uaclient/status.py
- uaclient/util.py
- ubuntu-advantage
- update-motd.d/80-ubuntu-advantage
Adapt conact api calls and request handling to some v1 paths present in full contract.yaml schema
> Python ua client v1

- .travis.yml
- debian/rules
- dev/bddeb
- setup.py
- tox.ini
- uaclient/cli.py
- uaclient/config.py
- uaclient/defaults.py
- uaclient/serviceclient.py
- uaclient/status.py
- uaclient/version.py
> Enable `pip install` in to a fresh virtualenv

- uaclient/cli.py
- uaclient/tests/test_cli_attach.py
> cli: handle failure to discharge root macaroon gracefully

- uaclient/cli.py
- uaclient/status.py
- ubuntu-advantage.1
> ux: cleans up ux per Mark's comments

- apt.conf.d/98ubuntu-advantage
- setup.py
- update-motd.d/80-ubuntu-advantage
Since we are no longer doing anyting with MOTD this removes those files
and cleans up the files installed on the system.
> setup.py: clean up installed files

- uaclient/entitlements/base.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_cis.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_livepatch.py
> apt: if contract expired, use machineToken not machineSecret

- ubuntu-advantage.1
> manpage: rewrite for new services

- uaclient/entitlements/cc.py
- uaclient/entitlements/tests/test_cc.py
> cc: fix invalid readme path for ubuntu-commoncriteria

- uaclient/entitlements/base.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/status.py
Also refactor check_affordances to limit white-space indents.
Fixes: #261
> entitlements: honor architectures affordance from ua-contracts

- debian/postinst
- debian/prerm
> d/{postinst,prerm}: set -e

- debian/rules
> d/rules: check DEB_BUILD_OPTIONS against nocheck

- debian/control
> d/control: update standards to 4.3.0

- uaclient/apt.py
- uaclient/tests/test_apt.py
- separate function add_apt_auth_conf_entry from add_auth_apt_repo
- Drop trailing ubuntu/ from repo apt auth conf format to avoid magic
pin -32768 due to invalid auth config for esm
- Parse apt auth file repo urls:
- If our repo_url is a specific subpath of an
existing repo url, insert our repo url before the matched
base url entry
- Otherwise, append to the end of the auth entries
Fixes: #275
> apt: fix apt auth format, insert specific repo subpaths before base path

- debian/changelog
> d/changelog: change version to 19.2

- debian/changelog
Mention the LP FFe bug
Fixes issue #318
> changelog update

- debian/prerm
> prerm: add back #DEBHELPER#

- uaclient/version.py
> version.py: 19.2

- debian/postinst
> d/postinst: fix deb-src urls

- uaclient/entitlements/__init__.py
Place cc before cis-audit.
Fix #304
> status: ensure alphabetized list

- debian/control
- debian/rules
- debian/ubuntu-advantage-tools.bash-completion
- tools/ua.bash
> Add bash-completion to install for 'ua'

- debian/postrm
- uaclient/apt.py
> postrm: clean up after package purge

- uaclient/config.py
> config: add path for machine-access-support

- uaclient/entitlements/base.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_cis.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/status.py
- uaclient/tests/test_apt.py
> livepatch: honor minKernelVersion affordance from ua-contracts

- debian/postinst
- debian/postrm
> esm: Install ESM keyring and remove on purge

- debian/postrm
- debian/prerm
Reverts CanonicalLtd/ubuntu-advantage-client#349
> Revert "deb: prerm and postrm cleanup no need to remove esm list file in postrm"

- debian/changelog
- incorporate disco hotfix version 19.3
- add entries for new features/fixes for upcoming 19.4
> changelog update for upcoming 19.4

- uaclient/serviceclient.py
- uaclient/util.py
As the client is Python 3 only we should know what we are dealing with
in terms of bytes of strings.
Fixes #179
> util: remove decode binary

- debian/changelog
changelog update, new version.
> OC: prepare new release with Trusty ESM

- uaclient/cli.py
- uaclient/entitlements/tests/test_base.py
- uaclient/tests/test_cli_enable.py
Also expand the `_perform_enable` documentation.
These changes will be prerequisite for my fix for #412, but can readily be reviewed/landed separately so I'm proposing them early.
> Add _perform_enable tests and refactor UAEntitlement tests

- uaclient/entitlements/base.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/entitlements/tests/test_repo.py
This is another part of the work for #411. As I'm off on Monday, I figured I'd submit it now to reduce the chances of coming back to a bunch of conflicts.
> Make it possible to suppress enable output if an entitlement is inapplicable

- uaclient/cli.py
- uaclient/entitlements/livepatch.py
- ubuntu-advantage.1
> docs: simplify livepatch url to ubuntu.com/livepatch

- uaclient/entitlements/base.py
- uaclient/entitlements/tests/test_base.py
> Don't attempt to disable inapplicable entitlements during detach

- uaclient/cli.py
> help: document cis cc and fips top-level urls in ua --help

- uaclient/entitlements/tests/test_fips.py
Including this in my final PR would make the diff hard to grok, so I'm submitting it separately.
> test_fips: convert deeply nested context managers to use ExitStack

- uaclient/apt.py
- uaclient/tests/test_apt.py
> apt: remove unused remove_auth_apt_repo and add_auth_apt_repo fingerprint parameters

- uaclient/config.py
- uaclient/entitlements/repo.py
- uaclient/util.py
I added these annotations when working out #461
> add some type annotations

- tools/read-dependencies
> ci: make deps includes libapt-pkg-dev

- uaclient/config.py
> cache: clean up local-access file on cache clean

- uaclient/entitlements/livepatch.py
- uaclient/entitlements/tests/test_livepatch.py
> livepatch: handle deltas in caCert, remoteServer and resourceToken

- uaclient/cli.py
> help: order help entitlements alphabentically, prefix with abbreviation

- uaclient/tests/test_util.py
- uaclient/util.py
> util: fix readurl calls without headers

- uaclient/status.py
Request per Product review in Lyon
> status: emit a SERVICE header in status output

- uaclient/util.py
The correct annotations for readurl correctly reveal some bugs (captured
as #510, #511 and #512) which need fixing before we annotate, so that we
don't break mypy.
>  util: add type annotations for everything but readurl

- uaclient/tests/test_util.py
- uaclient/util.py
Fixes for the minor nits I identified in my review of #497.
> util.subp: minor cleanups

- uaclient/contract.py
- uaclient/sso.py
- uaclient/status.py
I noticed one apparently unused function when looking at error messaging for #504 and then used https://github.com/jendrikseipp/vulture to detect the others.
> Prune unused functions and methods

- uaclient/status.py
- uaclient/tests/test_status.py
> status: colour standard/advanced support levels correctly

- uaclient/cli.py
- uaclient/exceptions.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_cli_refresh.py
This is the initial work for the proposal in #526.
> Introduce UserFacingError for reporting errors to users

- uaclient/sso.py
- uaclient/tests/test_sso.py
> Use UserFacingErrors for SSO responses, and change the output format

- uaclient/cli.py
- uaclient/config.py
- uaclient/status.py
- uaclient/tests/test_config.py
- uaclient/tests/test_status.py
> status: redact technical support and expiry for free contracts

- uaclient/tests/test_util.py
- uaclient/util.py
> util: don't disable logging to console if we're at DEBUG level

- uaclient/cli.py
- uaclient/tests/test_cli.py
> cli: ensure log file is only readable by root 

- uaclient/config.py
- uaclient/defaults.py
- uaclient/serviceclient.py
- uaclient/tests/test_config.py
- uaclient/tests/test_sso.py
- uaclient/tests/test_util.py
- uaclient/util.py
> config: allow contract_url and sso_auth_url to have a trailing slash

- uaclient/contract.py
There was a concern that we should be calling this on detach; I'm opening up this PR to serve as a place for us to work that out. We can either close or merge it depending on our determination.
> contract: remove unused UAContractClient.request_contract_machine_detach

- uaclient/tests/test_util.py
- uaclient/util.py
> logs: no longer redact secrets as logfile is root read-only

- uaclient/apt.py
- uaclient/tests/test_apt.py
> apt: write commented -updates lines instead of omitting them

- uaclient/conftest.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_cis.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_cli_refresh.py
> Replace mocking of sys.stdout with capsys fixture

- uaclient/entitlements/cc.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_repo.py
> cc: add a warning about download size before install

- uaclient/entitlements/cc.py
- uaclient/entitlements/cis.py
> Remove duplicated disable methods

- debian/changelog
- ubuntu-advantage.1
> Add --no-auto-enable to man page and d/changelog

- uaclient/entitlements/fips.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_fips.py
> Refresh FIPS repo_url values, and ensure that we match on only one of them in application_status

- Makefile
> Makefile: add `make deps` target to install build/dev dependencies

- uaclient/apt.py
- uaclient/tests/test_apt.py
> apt: correct get_installed_packages format option

- tools/multipass.md
I've been using this for a few days now, and have knocked off a few rough edges I found. This also switches to using `make deps` as #633 has landed.
> tools/multipass.md: update to my current configuration

- debian/changelog
Eoan upload is ready to migrate, waiting for apt 1.9. Nothing else for us to do there, so this PR is open for grabs now.
> changelog update from eoan

- uaclient/status.py
> Update refresh messages

- README.md
> README.md: remove reference to `make deb`

- uaclient/status.py
> status: right align the upper status output

- uaclient/status.py
- uaclient/tests/test_status.py
> status: do not emit color when not using a tty

- uaclient/tests/test_serviceclient.py
I think this should fix the build failures we're currently seeing, though I wasn't able to reproduce them locally.
> test_serviceclient: fix up mocking

- uaclient/apt.py
- uaclient/defaults.py
- uaclient/entitlements/__init__.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_cis.py
- uaclient/entitlements/tests/test_esm.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/tests/test_apt.py
Reformat files in the just-landed PR, now that we won't cause conflicts.
> uaclient: black formatting (phase 2)

- uaclient/tests/test_gpg.py
In the packaging test runs, HOME points to a nonexistent directory, so
we need to do this for GPG to be able to create its .gpg directory when
it runs.
> test_gpg: run tests with HOME pointing at a tmpdir

- uaclient/cli.py
- uaclient/contract.py
- uaclient/entitlements/base.py
- uaclient/entitlements/livepatch.py
- uaclient/testing/fakes.py
- uaclient/tests/test_cli_refresh.py
- uaclient/tests/test_contract.py
Also adjust request_updated_contract raise a UserFacingError if any
auto-enabled service fails to get enabled during the attach.
Fixes: #428
> attach: exit non-zero on failure to auto-enable services during attach

- .pre-commit-config.yaml
- .travis.yml
- dev-requirements.txt
- tox.ini
- uaclient/cli.py
- uaclient/contract.py
- uaclient/entitlements/base.py
- uaclient/entitlements/livepatch.py
- uaclient/testing/fakes.py
- uaclient/tests/test_cli_refresh.py
- uaclient/tests/test_contract.py
> Apply black formatting to the whole project and add tools to enforce it

- uaclient/cli.py
Update "livepatch" in the comment detailing available services in cli.py.
> Trivial update to comment in cli.py

- uaclient/tests/test_cli.py
> tests: root user should be able to dpkg-buildpackage mock getuid test

- uaclient/tests/test_util.py
- uaclient/util.py
> util: handle empty machine ID files in get_machine_id

- uaclient/cli.py
- uaclient/tests/test_cli_detach.py
This is the next step for #729. It's not very big, but the next part will be the Y/n prompting, which will warrant its own PR with no other changes to consider.
> detach: emit list of services before disabling them

- uaclient/cli.py
- uaclient/tests/test_cli_detach.py
- uaclient/tests/test_util.py
- uaclient/util.py
This is the last of the changes required to fix #729.
> detach: prompt for user confirmation before detach

- uaclient/config.py
- uaclient/tests/test_config.py
> config: display correct status to non-root users when attached

- uaclient/tests/test_apt.py
> test_apt: fix test failures on bionic/disco

- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_esm.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/status.py
This is part of addressing #726, along with #769.
> repo: update package lists after disable

- uaclient/entitlements/base.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/status.py
- uaclient/tests/test_config.py
* Use yes/no for the ENTITLED column
* Change unentitled resources from being "n/a" to being unavailable (i.e. —)
> Two tweaks to status output

- uaclient/cli.py
- ubuntu-advantage.1
> Update CLI help and manpage for new status output

- uaclient/config.py
- uaclient/tests/test_config.py
> status: non-root user can query contract-server/v1/resources to see availability

- uaclient/config.py
- uaclient/tests/test_config.py
> status output: display inapplicable and unavailable appropriately

- .travis.yml
- Makefile
> Add package builds to CI

- debian/postrm
> d/postrm: only need to purge config files dynamically created

- ubuntu-advantage.1
> Fix status --format documentation

- uaclient/apt.py
- uaclient/cli.py
- uaclient/conftest.py
- uaclient/entitlements/base.py
- uaclient/util.py
> uaclient: replace double spaces after full stops with single spaces

- uaclient/status.py
- uaclient/tests/test_status.py
> status: unattached status output headers alignment off by one

- apt-hook/hook.cc
> hook.cc: update to match UX documentation

- uaclient/entitlements/livepatch.py
- uaclient/entitlements/tests/test_livepatch.py
> livepatch: call apt-get update if snapd needs to be installed

- uaclient/status.py
- uaclient/tests/test_status.py
> status: remove spurious newline from unattached output

- uaclient/entitlements/base.py
- uaclient/entitlements/tests/test_livepatch.py
> livepatch: fix minKernelVersion comparison to account for major.minor

- uaclient/cli.py
- uaclient/tests/test_cli.py
> cli: add `ua help` command

- uaclient/entitlements/tests/test_livepatch.py
> test_livepatch: add missing mocking of util.is_container

- uaclient/entitlements/tests/test_base.py
- uaclient/status.py
> status: update wording of MESSAGE_UNENTITLED_TMPL

- debian/tests/usage
This updates the dep8 tests to call new commands and new subcommands
that will not reach outside of the network.
> d/tests/usage: Update tests

- features/unattached_commands.feature
> features: update for changed strings

- .travis.yml
> .travis.yml: add integration test run

- features/steps/steps.py
- features/util.py
- tox.ini
This refactors a number of helper functions into a new `features/util.py`, while also adding docstrings and type annotations for them.
These functions will be used in the next PR in this series, which will introduce a `features/environment.py` to share a single image build across every test. As this is an improvement to the codebase in and of itself, I've proposed it separately to make reviewing the second part easier (as well as because I still have some loose ends to tie up in that work, so this expedites review a little).
> features: preparatory refactoring

- README.md
- features/environment.py
- tox.ini
This should speed up local iteration substantially. See the README.md changes for further details.
> Integration tests: introduce support for image reuse

- uaclient/entitlements/__init__.py
- uaclient/entitlements/esm.py
- uaclient/entitlements/tests/test_esm.py
In preparation for another ESM entitlement.
> entitlements: rename ESMEntitlement to ESMInfraEntitlement

- uaclient/clouds/aws.py
- uaclient/clouds/azure.py
- uaclient/clouds/identity.py
- uaclient/clouds/tests/test_azure.py
- uaclient/clouds/tests/test_identity.py
- uaclient/tests/test_cli_auto_attach.py
The final Azure Pro support branch: 
*   azure-pro: add azure cloud instance module and tests
*  azure-pro: add azure auto-attach instance as valid cloud_instance_factory
> azure-pro: part 2, add azure auto-attach support and detection to uaclient

- features/util.py
The capture_output parameter to subprocess.run was introduced in Python
3.7.  To allow developers to run the behave tests on the most recent
Ubuntu LTS, we introduce a shim for it in lxc_exec.
> features/util: fix capture_output for pre-3.7 Python versions

- .travis.yml
- tools/constraints-disco.txt
- tox.ini
(And start testing eoan package builds.)
> Stop testing disco

- uaclient/clouds/identity.py
- uaclient/clouds/tests/test_identity.py
> azure-pro: fix detection of DatasourceAzureNet as azure on trusty

- uaclient/cli.py
- uaclient/tests/test_cli.py
> cli: log sys.argv (once logging is configured)

- ubuntu-advantage.1
> man: create reporting bugs section

- features/attached_enable.feature
add tests for each one of the available services when attached to an UA subscription
> add tests for behaviour of enable command when attached to an UA subscription

- debian/changelog
- uaclient/version.py
Leaving as WIP until we finish our upload to focal.
> Open upstream 20.4 for development

- features/attached_commands.feature
- features/unattached_commands.feature
add an auto-attach scenario
Fixes: #1041
> integration tests: add auto-attach

- README.md
- tools/ua-dev-cloud-config.yaml
Add more context around to ua-client architecture and code.
> README: add architecture and directory overview

- .travis.yml
We have a cron job running on master. It will install UA from the dailly PPA.
This closes issue #856
> add integration testing to master Travis runs

- features/attached_enable.feature
- features/steps/steps.py
As stated by #1118 and #1119 , we need to create more test for livepatc/fips for both Bionic and Xenial. This PR is an initial effort towards that direction
> Add test more behave tests for livepatch

- uaclient/entitlements/tests/test_livepatch.py
When on a machine already attached, some livepatch tests were
querying the unmocked application_status which would report the
current state of livepatch on the system and break tests which
expected livepatch in DISABLED state.
Mock appropriate status responses.
> tests: fix livepatch leaky application_status calls

- .travis.yml
- features/azure-ids.yaml
- features/cloud.py
- features/environment.py
- features/steps/steps.py
- features/ubuntu_pro.feature
- features/util.py
- tox.ini
This PR adds the Azure Pro test infrastructure into our integration tests. Besides that, it also implements the following changes:
* Refactor how cloud tests are performed
* Update how we select scenarios to skip based on the `machine_type` token
Right now, this is a WIP because I am experiencing an issue regarding how the paramiko SSH keys are being clean. In the end of the test, the following exception is being throw:
```
Exception ignored in: <function BaseInstance.__del__ at 0x7f82b93168b0>                                                                                                                                            
Traceback (most recent call last): …
```
> Azure integration

- README.md
Update the docs regarding how to run behave tests
> Update how to run behave tests in docs

- features/attached_enable.feature
- features/steps/steps.py
Add integration test to check that when running apt update, esm-infra updates will appear in the output of the command.
This PR address #1127
> Add apt update notify integration test

- debian/changelog
- uaclient/entitlements/cc.py
- uaclient/entitlements/cis.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/conftest.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_cis.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/version.py
Backport cfde36746b2d2f5d8949ba2cc0f605b77cf81085 to release-24 branch to fix issues on Bionic Ubuntu PRO FIPS pre-release images.
Fixes: #1173
> Release 24 fips

- debian/changelog
Update changelog for beta release
> changelog for 25.0~beta release

- .travis.yml
- tools/base_travis_integration_tests.sh
- tools/run_aws_travis_integration_tests.sh
- tools/run_azure_travis_integration_tests.sh
- tools/run_lxd_travis_integration_tests.sh
Create scripts to reuse on similar integration tests scenarios on travis yaml
> Refactor travis file

- uaclient/cli.py
- uaclient/tests/test_cli.py
> Cli error newlines

- .travis.yml
- tools/run_azure_travis_integration_tests.sh
Test pycloudlib new dependecies specified on this [PR](https://github.com/canonical/pycloudlib/pull/42)
> Update azure jobs on travis

- .travis.yml
- debian/changelog
- debian/rules
- features/attach_invalidtoken.feature
- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/cloud.py
- features/environment.py
- features/staging_commands.feature
- features/steps/steps.py
- features/ubuntu_upgrade.feature
- features/unattached_commands.feature
- features/util.py
- lib/upgrade_lts_contract.py
- sru/release-26/xenial-enable-fips
- systemd/ua-auto-attach.path
- systemd/ua-auto-attach.service
- tools/run_aws_travis_integration_tests.sh
- tools/run_azure_travis_integration_tests.sh
- tools/run_lxd_travis_integration_tests.sh
- uaclient/cli.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_upgrade_lts_contract.py
Sync all outstanding commits from master into release-25. 
Also cherry-pick the commits from  #1258 and #1256 PRs under review.
> Release 25b3

- tools/tox-lxd-runner
Allows to run tox in a LXD container.
> Add tools/tox-lxd-runner

- features/staging_commands.feature
Some commands were failing on the fips service upgrade integration tests. The first one was related to using
a wildcard in the `egrep` command, which is not supported on the current way we shellify commands on pycloudlib.
Also, we are now covering possibilities were we need to downgrade a package on dist-upgrade or that a package
requires reboot after upgrading it
> Fix upgrade scenario tests for fips

- .gitignore
- Jenkinsfile
- features/environment.py
- features/util.py
- tox.ini
> WIP: Ci with jenkins

- Jenkinsfile
- features/attach_validtoken.feature
It seems that after we released the SRU for update notifier, some of the expected messages have changed. This updates
the message we expect to see in the test
> Fix esm package messages test

- debian/changelog
- uaclient/config.py
- uaclient/tests/test_config.py
- uaclient/version.py
Open release 27 for active development
> Open release 27

- features/attach_validtoken.feature
- features/staging_commands.feature
Create FIPS tests for the generic bionic images on Azure and AWS
> Add FIPS test to AWS and Azure bionic images

- features/cloud.py
- features/gcp-ids.yaml
- features/ubuntu_pro.feature
- tox.ini
Add GCP PRO image support to integration tests
Fixes: #1289
> Add GCP pro test for focal machine

- features/attach_validtoken.feature
- features/attached_enable.feature
- features/ubuntu_pro.feature
With the recent FIPS changes, some tests are now expecting
wrong ua status output. We are now fixing those fips related
tests
fix ua status for fips related tests
Run the modified integration tests in this PR
> Fix FIPS tests

- integration-requirements.txt
pycloudlib: pin integration tests to a latest version of pycloudlib
Avoid integration test failures as pycloudlib continues development.
We therefore pin to a specific commit and will update occassionally
as needed.
run any integration test, this PR CI should suffice
> pycloudlib: pin integration tests to a latest version of pycloudlib

- README.md
docs: add readme docs about mastering clean golden images
Also drop the unused demo documentation from README.me
View the attached README.md
- [*] I have updated or added any documentation accordingly
> docs: add readme docs about mastering clean golden images

- features/cloud.py
Check cloudinit status after launching image
pycloudlib is no longer checking the cloudinit status when launching an image. Since our integration tests may perform weirdly if
cloud-init fails to run, we are explicitly checking cloud-init status after we launch an image
Run any of the existing integration tests
> Check cloudinit status after launching image

- features/environment.py
- features/steps/steps.py
tests: capture user-data and vendor-data in the event of failures as well as process stdout/stderr resultcode info.
tests: capture: last running process stdout, stderror and returncode as log artifact on failure
Use rebase and merge for commits msgs
```bash
sed -i 's/Auto/BOGUS/' features/unattached_commands.feature
tox -e behave-lxd-18.04 features/unattached_commands.feature
find artifacts
```
- [x Rebase and merge, no merge commit, rely only on existing commit messages
- [x ] I have updated or added any unit tests accordingly
> test improvements via artifacts collection

- features/environment.py
flake8: fix issue on features/environment.py
Run flake8-bionic using tox
> flake8: fix issue on features/environment.py

- uaclient/security.py
- uaclient/tests/test_security.py
CVE and USN classes will now more closely represent the response from
the Security API.
- Remove CVE.title because this is an attribute of USN.
- Rename CVE._get_related_notices -> public get_notices_metadata.
- Add comparable cached USN.get_cves_metadata
to avoid costly API round trips
Perform usn.title lookup for a given CVE up in
get_cve_affected_packages_status instead of via a CVE.title property.
This is a refactor to ensure CVE and USN more cleanly represent the API response. 
Any costly "lookups" are now placed below a get_X_metadata method which will cache the response.
But, to test locally
```bash
PYTHONPATH=. python3 -m uaclient.cli --debug fix CVE-2020-1472
PYTHONPATH=. python3 -m uaclient.cli --debug fix USN-4510-1
```
- [n/a] I have updated or added any integration tests …
> security: closer representation of cve and usn responses

- uaclient/entitlements/livepatch.py
- uaclient/entitlements/tests/test_livepatch.py
Add retry when running canonical-livepatch status
When running canonical-livepatch status, we may stumble on some flaky errors. If this command fails, we will shown livepatch to
be disabled, which may not be true if it is indeed a flaky error. To try to avoid that, we are now adding retries to that command when it fails
Fix #1360
Run the new unit tests in the PR
> Add retry when running canonical-livepatch status

- features/environment.py
Add disable_auto_attach config to all test PRO vms
To launch a PRO machine without ua enabled, we need to perform some operations on the base image. This PR
extends these operations by running them on all PRO machines that we are going to test
Run a 14.04 PRO integration test
> Add disable_auto_attach config to all test PRO vms

- .gitignore
- Jenkinsfile
- README.md
- debian/changelog
- features/cloud.py
- features/environment.py
- features/gcp-ids.yaml
- features/staging_commands.feature
- features/steps/steps.py
- features/ubuntu_pro.feature
- uaclient/contract.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/status.py
- uaclient/tests/test_contract.py
- uaclient/tests/test_util.py
- uaclient/util.py
- uaclient/version.py
> Release 26.1 changelog

- debian/changelog
- features/ubuntu_pro.feature
- uaclient/config.py
- uaclient/tests/test_config.py
Add changelog for release 26.2
> Release 26.2 changelog

- Jenkinsfile
Properly match and attach test artifacts to the test-run.
CI should do this for us and if CI fails, expect to be able to see test artifacts on jenkins test runner
> wip: test artifacts

- uaclient/cli.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/status.py
Add missing punctuation
Some FIPS related messages were missing the "." stop punctuation
Run these integration tests:
```
Attached enable fips on a machine with livepatch active
Attached enable livepatch on a machine with fips active
Attached enable fips on a machine with fips-updates active
```
> Add missing punctuation

- features/ubuntu_pro.feature
tests: fix gcp pro integration tests
Fix GCP PRO integration tests
> tests: fix gcp pro integration tests

- README.md
> docs: small readme fixes
>
> * Fixes some small grammatical mistakes.
> * Adds details of the three PPAs available for the client.
> * Adds the `make testdeps` step to the Testing section with a brief explanation.
Read the proposed changes to the readme and decide if they make sense or not.
> docs: add ppas and fix typos

- debian/changelog
Add changelog for first version of release 27
> changelog for 27.0 release

- integration-requirements.txt
> test deps: bump pycloudlib
Run all integration tests and ensure they're still working
Note that I don't have creds to run the aws/azure integration tests yet, so someone else should probably run those as a smoke test.
> test deps: bump pycloudlib

- RELEASES.md
docs: add entry for uploading new version to ppa
Add documentation informing how we should upload new uaclient packages to our maintained ppas
Verify if this guide is enough to allow new users to upload new uaclient packages to the ppa
> docs: add entry for uploading new version to ppa

- debian/ubuntu-advantage-tools.postinst
- tools/test_xenial_upgrade.sh
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/status.py
> test: manual test script for xenial upgrade
>
> When v27 is introduced to xenial, it will be installed over v10 which
> is an older version of the ua client based on bash instead of python.
> This test script runs through upgrading the old version to v27 to
> validate that nothing breaks in the process.
>
> Fixes: #1552 
>  fips: add notice when installing over old fips
>
> When fips was enabled with the old client, it used a
> different repo. We are now detecting if this old repo
> is being used and if so, providing a notice for the user
> to enable fips with the new client, which will update
> the repo appropriately.
`bash tools/test_xenial_upgrade.sh` and follow along with steps. Verify nothing unexpected occurs.
Run new unit tests
> test: manual test script for xenial upgrade

- uaclient/security.py
- uaclient/tests/test_security.py
fix: do not prompt user for beta services
When running ua fix, we may need a package fix that can only be installed using a beta service. In that situation, we will
only permit that the fix is installed if the service is already enabled. This means that we will not prompt user for enabling a
beta service or even attaching to UA if we found out that the service that will provide the fixes is a beta one.
Fixes: #1544
Run the new and modified unit tests
> fix: do not prompt user for beta services

- debian/changelog
> summary: no more than 70 characters
>
> A description of what the change being made is and why it is being
> made, if the summary line is insufficient.  The blank line above is
> required. This should be wrapped at 72 characters, but otherwise has
> no particular length requirements.
>
> If you need to write multiple paragraphs, feel free.
>
> LP: #NNNNNNN (replace with the appropriate Launchpad bug reference if applicable)
> Fixes: #NNNNNNN (replace with the appropriate github issue if applicable)
> changelog: pull in missing changelog entry for 26.3 from release-26

- uaclient/security.py
- uaclient/tests/test_security.py
> fix: dont say reboot required when unnecessary
> 
> Before, we were assuming that if the system reboot
> flag was set, then it was because of our fix operation.
> Now, we are carving out a case where we can safely know
> that the reboot is not required because of our fix.
> Specifically, if our fix operation didn't actually install
> anything, then it couldn't have caused the reboot to be
> required.
>
> LP: #1926183
* Run new unit tests.
* Start a vm and do something that requires reboot. Then run a fix command  that doesn't do anything. Verify it doesn't claim that you need to reboot to complete the fix
> fix: dont say reboot required when unnecessary

- apt-hook/20apt-esm-hook.conf
> apt-hook: mitigate failures with true
>
> In case something catastrophic happens
> in our apt hooks, we now make sure the subprocess
> always returns successfully by calling `true`
> if our hook fails.
> apt-hook: mitigate failures with true

- features/environment.py
> summary: no more than 70 characters
>
> A description of what the change being made is and why it is being
> made, if the summary line is insufficient.  The blank line above is
> required. This should be wrapped at 72 characters, but otherwise has
> no particular length requirements.
>
> If you need to write multiple paragraphs, feel free.
>
> LP: #NNNNNNN (replace with the appropriate Launchpad bug reference if applicable)
> Fixes: #NNNNNNN (replace with the appropriate github issue if applicable)
> wip CI for custom userdata

- features/staging_commands.feature
It doesn't appear that any changes to the uaclient code itself will be necessary for CIS on focal. However, the command doesn't yet succeed due to the packages not being available in the archive yet. We should re-assess when they are available.
***Marked draft because this test doesn't yet pass, but will as soon as the focal cis packages are available. Do not merge.***
> tests: test enabling CIS on focal
> 
> Now that CIS is available on focal, we should
> start running our CIS integration test on focal
> to test for regressions.
> 
> Fixes: #1582
> tests: test enabling CIS on focal

- features/attach_validtoken.feature
> tests: fix motd message for bionic
> 
> Fixes: #1615
Let jenkins pass (hopefully)
> tests: fix motd message for bionic

- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/ubuntu_pro.feature
- features/unattached_status.feature
- uaclient/entitlements/fips.py
- uaclient/status.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_status.py
> fips: clarify messaging
>
> Fixes: #1631
in a vm with this version of ua installed:
```bash
sudo ua status
sudo ua enable fips
sudo ua enable fips-updates
```
> fips: clarify messaging

- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/staging_commands.feature
- uaclient/entitlements/cis.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_disable.py
- uaclient/tests/test_cli_enable.py
- uaclient/tests/test_cli_status.py
cis: make service non-beta
Turn CIS into a non-beta service and update the integration test to run the CIS script on the machine
> cis: make service non-beta

- features/environment.py
tests: allow downgrade when installing uaclient
When testing uaclient through the integration tests, we may end up with a machine that contains a higher version of uaclient
that the one we are testing. In that situation, we should allow downgrading uaclient for testing purposes.
This is true for the current situation on the clouds, were uaclient from the ppa is on version 27.0 while the one in archives has version 27.0.2. In that situation, we will not be able to install the required version of uaclient from our PPA or using `BUILD_PR`.
Run any aws/azure generic tests using BUILD_PR=1 and BUILD_PR=0
> tests: allow downgrade when installing uaclient

- RELEASES.md
Replacement of https://github.com/canonical/ubuntu-advantage-client/pull/1628
sync released debian/changelog changes from our recent impish upload of 27.0.2
* fix a couple of lintian warnings/errors
* Open 28.0 for active development because we are manipulating d/changelog past 27.0
* Add RELEASE documentation updates based on review recommendations during last SRU about branch structuring.
Targeting upstream/main, and we'll need to cherry-pick most of these commits (with the exception of the version bump for 28 and the changelog entry for 28.0) back down into release-27 after this PR lands.
```bash
sed -i 's/UNRELEASED/focal/' debian/changelog
git commit -am 'changelog bump for testing'
build-package
sbuild-it ../out/*dsc
should emit less lintian warnings
```
> docs: update releases.md per SRU review feedback on branch structuring

- features/attach_validtoken.feature
- features/ubuntu_pro.feature
- features/unattached_commands.feature
- features/unattached_status.feature
> tests: update messages in integration tests
> 
> Fixes: #1635 
Watch integration tests pass
Make sure the changes to the tests are actually what we want.
> tests: update messages in integration tests

- Jenkinsfile
- features/attach_validtoken.feature
- features/attached_commands.feature
- features/ubuntu_pro.feature
- features/ubuntu_upgrade.feature
- features/unattached_status.feature
Fix some integration tests that were affected by the recent cis and messaging changes
> Fix integration tests

- features/attach_validtoken.feature
- features/attached_commands.feature
Bring the latest test fixes commits into release-27
> Update release 27 changelog

- debian/changelog
Double check by going to the new referenced LP bug
> changelog: fix LP bug reference

- RELEASES.md
docs: update release guide
Add an extra step on the RELEASE.md docs and fix the script we are using to upload the new release to past distros
Reproduce the steps in the script and run the new script
> docs: update release guide

- debian/control
> d/control: add comments to explain complex build-depends
Read the comments and decide if they are adequate.
Ensure the package still builds
> d/control: add comments to explain complex build-depends (SC-104)

- features/environment.py
tests: add flag to enable proposed pocket
When running verification tests for uaclient, we sometimes need to run the tests from the package that is found on the proposed pocket. We are now introducing a flag to allow this behavior
Run any integration test with `UACLIENT_BEHAVE_ENABLE_PROPOSED=1`  and verify that the daily ppa is not configured and the package was installed from the proposed pocket
> tests: add flag to enable proposed pocket

- features/attach_validtoken.feature
- tox.ini
- types-requirements.txt
- uaclient/cli.py
- uaclient/entitlements/base.py
- uaclient/entitlements/esm.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_esm.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/status.py
- uaclient/tests/test_cli_enable.py
> refactor: remove side effects from can_enable
> 
> Fixes: #1654
> Fixes: #1571
> refactor: remove unused silent enable param 
> refactor: return CanEnableFailure reason from enable 
Everything should still work :)
> refactor: remove side effects from can_enable (SC-64)

- features/attach_validtoken.feature
- features/staging_commands.feature
> tests: noninteractive mode when installing ssh components in tests
Run the bionic azure generic tests to make sure they pass.
> tests: noninteractive mode when installing ssh components in tests

- README.md
readme: add instruction to generate MOTD messages
Add instructions to force MOTD messages to be updated in the system
Launch a xenial container and follow the instructions in this guide.
Verify if the MOTD message possess ESM references on it
> readme: add instruction to generate MOTD messages

- apt-hook/20apt-esm-hook.conf
apt.conf variables must end with ';'
Fixes: ea85ef1 ("apt-hook: new json hook for security update counts")
Fixes: 8257679 ("apt-hook: print static messages on apt upgrade/dist-upgrade (#1540)")
LP: #1930741
https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1930741
> summary: no more than 70 characters
>
> A description of what the change being made is and why it is being
> made, if the summary line is insufficient.  The blank line above is
> required. This should be wrapped at 72 characters, but otherwise has
> no particular length requirements.
>
> If you need to write multiple paragraphs, feel free.
>
> LP: #NNNNNNN (replace with the appropriate Launchpad bug reference if applicable)
> Fixes: #NNNNNNN (replace with the appropriate github issue if applicable)
> apt-hook: fix invalid 20apt-esm-hook.conf syntax.

- debian/control
> d/control: add version requirement to distro-info
> 
> LP: #1932028
I uploaded packages with this change to a ppa for xenial/bionic/focal for testing
on xenial
```
sudo add-apt-repository ppa:orndorffgrant/uaclient-distro-info-version-testing
sudo apt-get update
sudo apt install distro-info=0.14build1 distro-info-data=0.28
sudo apt install ubuntu-advantage-tools
python3 /usr/lib/ubuntu-advantage/ua_update_messaging.py
```
on bionic
```
sudo add-apt-repository ppa:orndorffgrant/uaclient-distro-info-version-testing
sudo apt-get update
sudo apt install distro-info=0.18 distro-info-data=0.37
sudo apt install ubuntu-advantage-tools
python3 /usr/lib/ubuntu-advantage/ua_update_messaging.py
```
on focal
```
sudo add-apt-repository ppa:orndorffgrant/uaclient-distro-info-version-testing
sudo …
```
> d/control: add version requirement to distro-info (SC-124)

- README.md
readme: add support matrix info
> readme: add support matrix info

- features/staging_commands.feature
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
fips: add focal test for fips-updates
Add fips-updates test for focal while also fixing a bug where we don't install the fips version of openssh packages on focal.
Run the new fips-updates integration test
> Fips updates on focal

- README.md
> readme: small text fix

- debian/ubuntu-advantage-tools.postinst
- lib/patch_status_json.py
postinst: fix typo in json patch comments
Fix code comment for json patch function
> postinst: fix typo in json patch comments

- debian/changelog
> changelog: fix badly formatted trailer line

- ubuntu-advantage.1
doc: update manpage to include yaml status format
run `man ./ubuntu-advantage.1` and verify the entry has been documented
> doc: update manpage to include yaml status format

- features/attached_status.feature
- features/steps/steps.py
- features/unattached_status.feature
Add integration tests to verify that `ua status --format json` or `ua status --format yaml` have the correct output, with the expected keys in them.
Run the integration tests, verify it passes
> tests: add scenarios for ua status --json|yaml

- RELEASES.md
release: more docs on proper release process for SRU
> release: more docs on proper release process for SRU

- features/attached_commands.feature
- features/attached_enable.feature
- features/unattached_status.feature
Now we have it available
Signed-off-by: Renan Rodrigo <renanrodrigo@canonical.com>
Run the integration tests
> tests: update FIPS tests on Focal (SC-271)

- RELEASES.md
```
docs: reorganize release process docs
The goal of this doc reorganization is to more closely align the
documented steps with the chronological tasks that we take while going
through the release process. Ideally one person can follow this doc from
top to bottom and have a reasonably efficient and successful release.
```
Read the new docs. Look for things I lost during the reorganization, or for things that are wrong/don't make sense/out of order.
> docs: reorganize release process docs (SC-263)

- Jenkinsfile
jenkins: use ephemeral instances for lxd tests
We will now use ephemeral instances for the lxd jenkins jobs we will trigger during a pull request
Just wait for CI to run
> jenkins: use ephemeral instances for lxd tests

- debian/changelog
```
d/changelog: bring main up to date with pkg/ubuntu/devel
```
```
git-ubuntu clone ubuntu-advantage-tools
cd ubuntu-advantage-tools
git checkout pkg/ubuntu/devel
git remote add grant git@github.com:orndorffgrant/ubuntu-advantage-client.git
git fetch grant
git diff grant/27.0.1-timestamp debian/changelog
```
Make sure the only difference is that this branch has the v28 entry.
> d/changelog: bring main up to date with pkg/ubuntu/devel

- features/attach_validtoken.feature
- features/unattached_commands.feature
- lib/timer.py
- systemd/ua-messaging.service
- uaclient/config.py
- uaclient/jobs/update_messaging.py
- uaclient/tests/test_ua_timer.py
- uaclient/tests/test_update_messaging.py
lib: add timer script
Add an initial implementation of the timer script. This script has the logic to verify if a job should run in a given moment and
it also persist information about all jobs that have run during its execution
Run the unit tests added for this script.
However, there are a lot more tests that should be implemented
> lib: add timer script (SC-284)

- features/aws-ids.yaml
Update the AMI codes used for the integration tests, for the latest Ubuntu Pro images on AWS in us-east-2.
> chore: update AWS AMIs for Pro images

- RELEASES.md
- features/aws-ids.yaml
- tools/refresh-aws-pro-ids
Fix and document usage of tools/refresh-aws-pro-ids during PRO image release process.
```bash
PYTHONPATH=. ./tools/refresh-aws-pro-ids
```
> update: AWS Ubuntu PRO marketplace AMIs

- lib/timer.py
- uaclient/jobs/update_state.py
- uaclient/tests/test_ua_timer.py
jobs: add status update job
Add job to update status cache on a daily basis
Run the modified unittest
> jobs: add status update job (SC-329)

- uaclient/clouds/identity.py
- uaclient/clouds/tests/test_identity.py
Since the Xenial release, cloud-init provides us `cloud-id` to determine on which cloud are we running, if any. We used to check for fallback files in the case cloud-id was not present. The same logic applied to instance ID.
The proposal here is that, for the future releases, this is not needed anymore.
LP: #1940131
> cloud: rely only on cloud-init to determine cloud and instance IDs (SC-337)

- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
Now that groovy is EOL, focal upgrades directly to hirsute.
```
tests: focal upgrades to hirsute now 
```
Run `tox -e behave-upgrade-20.04` and ensure it passes.
> tests: focal upgrades to hirsute now

- README.md
- ubuntu-advantage.1
Draft for timer interval configuration documentation.
> docs: add timer config to README and manpage

- features/attached_commands.feature
- features/unattached_commands.feature
- lib/reboot_cmds.py
- lib/timer.py
- uaclient.conf
- uaclient/cli.py
- uaclient/config.py
- uaclient/contract.py
- uaclient/jobs/metering.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_cli_auto_attach.py
- uaclient/tests/test_cli_config_set.py
- uaclient/tests/test_cli_config_show.py
- uaclient/tests/test_cli_config_unset.py
- uaclient/tests/test_cli_detach.py
- uaclient/tests/test_cli_disable.py
- uaclient/tests/test_cli_fix.py
- uaclient/tests/test_cli_refresh.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_config.py
- uaclient/tests/test_contract.py
- uaclient/tests/test_reboot_cmds.py
- uaclient/tests/test_ua_timer.py
timer: add metering job
Add metering job to inform contract about current activity token and enabled services in the machine
> timer: add metering job (SC-301)

- README.md
> readme: add information about isort

- RELEASES.md
docs: Add instructions to review changelog entries
We are now adding some points that must be checked when we are reviewing a new changelog entry for the product.
Verify if the suggested checks are enough/necessary for a complete changelog review
> docs: Add instructions to review changelog entries

- README.md
- features/attached_commands.feature
- features/unattached_commands.feature
- uaclient/cli.py
- uaclient/config.py
- uaclient/tests/test_cli_collect_logs.py
- ubuntu-advantage.1
Add the collect-logs command.
The command picks up all relevant data for debugging possible problems in UA, and creates a tarball with it.
Fixes: #463
Signed-off-by: Renan Rodrigo <renanrodrigo@canonical.com>
> cli: add collect-logs command (SC-407)

- features/attach_validtoken.feature
- features/attached_enable.feature
Lets not merge this until we've finished running all tests against staging and are sure there aren't any more similar bugs
To test:
Please run the edited integration tests
After merging, I will cherry-pick to `release-27` and push directly to github without a PR if thats okay
> tests: fix more tests for using ua-apps token

- RELEASES.md
- tools/create-lp-release-branches.sh
This turns what is currently an inline script in the RELEASES.md instructions into a separate script that can be run as part of our release process.
```
tools: create script to generate lp release branches
```
Try running the new script.
> tools: create script to generate lp release branches (SC-448)

- systemd/ua-timer.timer
As this is our lower timer now.
> timer: set the frequency to 6h

- systemd/ua-license-check.path
- systemd/ua-license-check.service
- systemd/ua-license-check.timer
```
license-check: add explanation to systemd units
```
If Jenkins passes that means the systemd files are still valid.
Please read the comments and descriptions to make sure they adequately explain whats going on.
> license-check: add explanation to systemd units

- debian/changelog
```
changelog: add missing LP bug refs for 27.3
```
```
changelog: update ua-timer.timer frequency
```
Ensure these are the correct bugs and associated with the correct lines in the changelog
> changelog: add missing LP bug refs for 27.3

- debian/changelog
- debian/ubuntu-advantage-tools.logrotate
- features/attached_commands.feature
WIP: Touching integration test failures
>  logs: update logrotate to glob capture all /var/log/ubuntu-advantage*log
>  
>  Provide `su root root` to avoid messaging about parent directory perms
>  being insecure and allowing syslog group to write this file.
```bash
UACLIENT_BEHAVE_CONTRACT_TOKEN=<REDACTED>   UACLIENT_BEHAVE_BUILD_PR=1 UACLIENT_BEHAVE_DEBS_PATH=DEBS tox -e behave-lxd-18.04 features/attached_commands.feature:46
```
> logs: update logrotate to glob capture all /var/log/ubuntu-advantage*log

- features/attach_validtoken.feature
- features/ubuntu_pro.feature
tests: fix livepatch status for azure focal
Update some azure tests to show livepatch as enabled on azure focal instances
Run the modified azure tests in this PR
> tests: fix livepatch status for azure focal

- features/attached_commands.feature
- uaclient/cli.py
- uaclient/security_status.py
- uaclient/tests/test_cli_security_status.py
- uaclient/tests/test_security_status.py
```
security-status: add a schema version and required beta flag
```
Verify that you can't run the command without the beta flag.
Verify that the schema version in the output is sensible. (is a string okay?)
> Security status beta flag and schema version (SC-528)

- features/attached_commands.feature
- features/enable_fips_vm.feature
```
tests: enable livepatch then fips-updates
```
Run the new integration test (it is marked slow so will not be run by jenkins on this PR)
> tests: enable livepatch then fips-updates

- ubuntu-advantage.1
```
fix: include return code info in help
```
Check if the new help output makes sense.
> fix: include return code info in help

- ubuntu-advantage.1
Update fix manpage entry to add extra space in the title
> fix: update manpage entry

- README.md
- uaclient/tests/test_apt.py
- uaclient/tests/test_security.py
- uaclient/tests/test_upgrade_lts_contract.py
We've had this in our backlog for a while. I only found a couple things in my searches.
```
refactor: follow inclusive naming best practices
```
Ensure everything still works and the new language still makes sense.
> refactor: follow inclusive naming best practices (SC-192)

- RELEASES.md
```
docs: update release process with recent improvements
```
Read the updates and verify that they reflect reality and make sense.
> docs: update release process with recent improvements

- uaclient/tests/test_util.py
- uaclient/util.py
token redaction: redact token logged when enabling livepatch service
Run the test_util test.
> token redaction: redact token logged when enabling livepatch service (SC-582)

- uaclient/tests/test_util.py
- uaclient/util.py
token-refresh: redact token when machine-token.json change is logged
> token-refresh: redact token when machine-token.json change is logged

- features/attached_enable.feature
- uaclient/entitlements/cis.py
cis: update docs url
Updated the url to cis docs though the previous url was being redirected to the new one.
Fixes: #1808
> cis: update docs url

- uaclient/security_status.py
- uaclient/tests/test_security_status.py
There can be available security-updated versions which are not the latest.
Thus we check all the versions above the currently installed one.
- Run the modified unittests
- Spin a Xenial container, and:
- Install `linux-libc-dev=4.4.0-21.37`
- Run `ua security-status`
- Verify that version `4.4.0-210.242` is available from the Security pocket, available immediately
- Verify that version `4.4.0-210.250` is available from the ESM Infra pocket, pending attach
> security-status must show all available updates (SC-580)

- uaclient/entitlements/tests/test_fips.py
fips: tests run with livepatch enabled
The fips test were failing when the livepatch service is enabled. Livepatch service is included in the list of incompatible services and thus the fips test failed.
> fips: tests pass with livepatch enabled

- sru/release-27.4/test-unattached-status-job.sh
As posted in [the related LP bug](https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1950813)
> sru: add test instructions to unattached status job (SC-599)

- README.md
- debian/rules
- debian/ubuntu-advantage-tools.postrm
- features/attached_commands.feature
- features/daemon.feature
- features/unattached_commands.feature
- lib/daemon.py
- systemd/ua.service
- uaclient-devel.conf
- uaclient.conf
- uaclient/cli.py
- uaclient/config.py
- uaclient/defaults.py
- uaclient/tests/test_cli_collect_logs.py
- uaclient/tests/test_config.py
- ubuntu-advantage.1
```
daemon: add daemon configuration and entrypoint
```
Verify the daemon starts on boot and logs correctly.
Review all the systemd settings.
Review all places where I had to add log file configuration - did I miss anything?.
Verify systemctl start|stop|restart work as expected
> daemon: add daemon configuration and entrypoint (SC-551)

- tools/create-lp-release-branches.sh
Add impish to the `create-lp-release-branches` script
> tools: add impish to lp release script

- features/attached_commands.feature
- features/unattached_commands.feature
- uaclient/cli.py
- uaclient/defaults.py
- uaclient/tests/test_cli_collect_logs.py
- uaclient/util.py
logs: redact older unredacted logs
Fixes: #1889 
- Run **ua collect-logs** with current ua tool. Get the compressed logs.
- Build and install this update and then run **ua collect-logs** and collect the logs.
- Compare the logs esp. the ubuntu-advantage.log files for any sensitive data like tokens
> logs: redact older unredacted logs

- sru/release-27.4.2/test-postinst-check-service-is-enabled-fix.sh
Add manual tests script used for release 27.4.2
> tests: add manual test for postinst status error

- features/_version.feature
- features/attach_invalidtoken.feature
- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/install_uninstall.feature
- features/license_check.feature
- features/unattached_commands.feature
- features/unattached_status.feature
- tools/run-integration-tests.py
- tox.ini
tests: add jammy integration tests
Add some integration tests for 22.04 (jammy)
> tests: add jammy integration tests (SC-663)

- uaclient/serviceclient.py
- uaclient/tests/test_util.py
- uaclient/util.py
logs: redact tokens sent from contract server
**On pro machines:** 
- run auto-attach to see the logged contractToken
- run auto-attach on gcp and see the logged jwt with machine data and details.
**On both pro and non-pro machines:**
- enable cis/cc-eal and see the logged resourceToken
- change machine token and then try enabling livepatch
> logs: redact tokens sent from contract server

- debian/ubuntu-advantage-tools.postinst
- sru/release-27.5/cleanup_failed_old_license_check_timer.sh
```
postinst: clean up ephemeral failed state of ua-license-check
```
Run the new manual test script.
> postinst: clean up ephemeral failed state of ua-license-check

- uaclient/tests/test_util.py
- uaclient/util.py
logs: log to stdout/stderr when subp fails
> logs: log to stdout/stderr when subp fails

- tools/build.sh
- tools/test-in-lxd.sh
***Ultra low priority***
```
tests: small niceties when building/testing interactively
```
Make sure the notification works.
Try out `env SHELL_BEFORE=1 ./tools/test-in-lxd.sh focal`
> tests: small niceties when building/testing interactively

- debian/changelog
- features/attached_enable.feature
- help_data.yaml
- uaclient/entitlements/cis.py
Quick fixes for the 27.5 release.
> Fixes for 27.5

- README.md
- RELEASES.md
- features/environment.py
- features/util.py
- tools/build.py
- tools/setup_sbuild.sh
```
builds: script to seed sbuild chroots with dependencies
```
```
time ./tools/build.sh xenial # notice how long it takes
rm /tmp/uaclient-behave/deb-cache/xenial-* # clear build cache
env RELEASES="xenial" ARCHS="amd64" OPERATION="create" bash ./tools/setup_sbuild.sh
time ./tools/build.sh xenial # notice how long it takes
```
On my laptop, the second build is about 6x faster :D
> Make sbuild 6x faster with this one simple trick!

- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
- features/unattached_status.feature
This is fixing the tests involving Focal and USG.
There is another test that is failing for me, however I cannot reproduce it for some reason. It is
features/ubuntu_upgrade_unnatached.feature#53 , `Unattached upgrade across LTS releases`
> Fix failing CI tests

- features/enable_fips_vm.feature
Marked draft because we cannot merge until https://github.com/CanonicalLtd/ua-contracts/issues/2626 is resolved.
```
tests: use actual contract for fips-updates + livepatch test
```
Run the modified integration tests (they are marked slow and wont run on jenkins)
> tests: use actual contract for fips-updates + livepatch test

- debian/ubuntu-advantage-tools.postinst
- uaclient/cli.py
- uaclient/tests/test_cli.py
logs: make log file world readable
Fixes: #1473
> logs: make log file world readable

- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/ubuntu_pro.feature
- features/unattached_status.feature
CC-EAL is available for Bionic! This is the PR to adjust the integration tests.
Fixes: #1794
> tests: update integration tests to include CC-EAL for Bionic (SC-724)

- features/gcp-ids.yaml
- tools/refresh-gcp-pro-ids.py
tools: add script to refresh gcp pro images
Add script that will look for updated gcp pro image ids and update our features/gcp-ids.yaml file with the latest version of the images
Run the tools script and see if the image ids are updated
Run the GCP pro tests with the new image ids
> tools: add script to refresh gcp pro images

- uaclient/cli.py
When checking for `presentedAs` we ended up calling the resources endpoint for every CLI run, on the `get_parser` call, when we only need it on help calls. 
This PR moves the logic to call the resources endpoint to that specific method.
> cli: only go for resources on explicit help calls (SC-738)

- debian/changelog
- features/attached_enable.feature
- features/license_check.feature
- help_data.yaml
- uaclient/entitlements/cis.py
Bring commits with fixed from release `27.5` to `main`.
Verify that all those commits are present in 27.5
> Bring 27.5

- features/_version.feature
- features/aws-ids.yaml
- features/cloud.py
- features/ubuntu_pro_fips.feature
- tools/refresh-aws-pro-ids
- tox.ini
fips: integration tests for aws pro fips
WIP for the integration tests for fips machine, starting with aws then azure.
> fips: integration tests for aws pro fips

- Jenkinsfile
We should start running these tests on jammy regularly as we approach release.
This will make CI take longer though :/
> ci: run jammy tests

- features/_version.feature
- features/azure-ids.yaml
- features/ubuntu_pro_fips.feature
- tox.ini
fips: integration tests for azure pro fips 
WIP for the integration tests for azure pro fips machine.
> fips: integration tests for azure pro fips

- features/attach_validtoken.feature
- features/attached_enable.feature
- features/enable_fips_container.feature
- features/steps/steps.py
- uaclient/cli.py
- uaclient/entitlements/base.py
- uaclient/entitlements/cc.py
- uaclient/entitlements/cis.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/status.py
- uaclient/types.py
- uaclient/util.py
```
fips: allow fips on containers
```
Try out `ua enable fips` on containers and vms to make sure it works like you would expect.
> fips: allow fips on containers

- features/attached_commands.feature
- uaclient/cli.py
- uaclient/tests/test_cli_detach.py
detach: allow returning json response
Add support for a json response for the detach command
> detach: allow returning json response (SC-772)

- features/unattached_commands.feature
- uaclient/status.py
- uaclient/tests/test_security.py
```
fix: specify source package in message
Fixes: #1511
```
Make sure the message still makes sense
> fix: specify source package in message

- features/ubuntu_pro.feature
cis: update azure pro cis/usg enabling tests
Add tests for azure pro machines to test the enabling and disabling of usg/cis service.
> cis: update azure pro  cis/usg tests

- features/detached_auto_attach.feature
- uaclient/actions.py
- uaclient/cli.py
- uaclient/tests/test_actions.py
cloud: fix detaching in auto-attach
Stop the detaching process when calling auto-attach after a manual attach command.
> cloud: fix detaching in auto-attach

- debian/changelog
- features/attached_enable.feature
Just brings in a couple changes present on the release-27 branch from 27.6 back into main - in preparation for rebasing all our main changes onto release-27.
> 27.6 changes to main

- docs/howtoguides/enable_ua_in_dockerfile.md
- docs/tutorials/create_a_fips_docker_image.md
- features/docker.feature
- features/steps/steps.py
- tox.ini
```
tests: test using ua in docker builds
```
Try both of the following:
```
env UACLIENT_BEHAVE_BUILD_PR=1 tox -e behave-docker
```
```
tox -e behave-docker
```
> Dockerfile tests and docs

- .github/workflows/ci.yaml
```
Run CI in GitHub Actions
For the moment only run the LXD/LXDVM integration tests that do not
require secrets.
```
> Run CI in GitHub Actions

- debian/ubuntu-advantage-tools.postinst
- uaclient/messages.py
postinst: Adapt script for new messages module
Run any of the PRO FIPS tests we have and assert that no package related issues are raised
> postinst: Adapt script for new messages module

- uaclient/tests/test_util.py
tests: reduce locale issues when testing
Fix some locale issues raised when running tests e.g. spelling differences
> tests: reduce locale issues when testing

- .pre-commit-config.yaml
- dev-requirements.txt
- setup.py
- uaclient/apt.py
- uaclient/cli.py
- uaclient/contract.py
- uaclient/entitlements/base.py
- uaclient/entitlements/cis.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/jobs/update_messaging.py
- uaclient/security_status.py
- uaclient/util.py
- uaclient/version.py
Bump Black to latest, fixing the Click problem and updating some formatting.
```
make clean
tox -e black
```
> fix: bump Black to 22.3.0

- .github/workflows/ci-base.yaml
- .github/workflows/ci-integration.yaml
```
CI: add separate workflow for the integration tests and add secrets
The workflow for the non-integration tests will run on both 'push'
and 'pull_request', thus allowing basic testing on forks, as these
tests do not require secrets.
The integration tests requires secrets, and therefore the integration testing
workflow only has a pull_request trigger. The base branch has to be pushed to
the main project repository, otherwise secrets won't be exported.
```
> CI: separate integration jobs and enable tests requiring contract_token

- features/_version.feature
```
tests: require exact version in version check test
```
Ensure version check doesn't pass unless given the exact dpkg version string
> tests: require exact version in version check test

- .github/workflows/ci-integration.yaml
- .github/workflows/cloud-cleanup.yaml
```
CI: add awspro integration testing:
```
> CI: add awspro integration testing (SC-906)

- .github/workflows/ci-base.yaml
- .github/workflows/ci-integration.yaml
- .github/workflows/cloud-cleanup.yaml
```
CI: minor fixups
Changes:
- CI: cleanup ec2: invert logic to make it errexit friendly
- CI: restrict the cloud-cleanup jobs to the base repository
- CI: give names to jobs
- CI: delete leftover debugging echo
```
> CI: minor fixups

- CONTRIBUTING.md
- docs/howtoguides/enable_ua_in_dockerfile.md
- docs/tutorials/create_a_fips_docker_image.md
Fixes the things pointed out by @lucasmoura here: https://github.com/canonical/ubuntu-advantage-client/pull/2000
I skipped removing the "Iterating locally" section only because I think we should test those features to discover the status of them before removing their docs, and I haven't done that yet :)
> Docs fixes

- .github/workflows/check-secrets-available.yaml
- .github/workflows/ci-integration.yaml
- .github/workflows/cloud-cleanup.yaml
```
CI: skip integration testing if secrets are missing
Inspired by [1] but implemented with a reusable workflow.
[1] https://github.com/actions/runner/issues/520#issuecomment-907427748=
```
> CI: skip integration testing if secrets are missing (SC-911)

- .github/workflows/.yamllint
- .github/workflows/ci-workflows.yaml
```
CI: add basic CI (yamllint) for the workflow definitions
```
> CI: add basic CI (yamllint) for the workflow definitions (SC-910)

- tools/run-integration-tests.py
- tools/ua-test-credentials.example.yaml
- tox.ini
Add the new fips-pro tests, add version to the docker test for consistency, and remove the requirement for credentials since those now come from the `pycloudlib` config file.
> chore: update the run-integration-tests script

- .github/workflows/cloud-cleanup.yaml
- tools/constraints-mypy.txt
```
CI: fix ec2 cloud-cleanup
Remove extra field that prevents the output of describe-instances
from being passed to terminate-instances.
```
> CI: fix ec2 cloud-cleanup

- features/unattached_status.feature
```
tests: update jammy staging esm status
```
CI should run the new tests
> tests: update jammy staging esm status

- .github/workflows/ci-integration.yaml
- .github/workflows/cloud-cleanup.yaml
- features/cloud.py
```
CI: add gcepro integration testing
When setting up credentials use printf instead of echo as dash's echo
always interpretes control sequences (e.g. \n).
```
> CI: add gcepro integration testing (SC-916)

- CONTRIBUTING.md
- README.md
- contributing-docs/references/terminology.md
- docs/explanations/what_is_the_daemon.md
- docs/howtoguides/configure_proxies.md
- docs/howtoguides/create_pro_golden_image.md
- docs/references/support_matrix.md
Look through the new organization and see if it makes sense to you. I'm trying to generally start following the [diataxis](https://diataxis.fr/) principles.
> docs: reorganize readme

- README.md
docs: fix link to supported matrix file.
> docs: fix link to supported matrix file.

- features/_version.feature
- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/install_uninstall.feature
- features/proxy_config.feature
- features/staging_commands.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
- features/unattached_commands.feature
- features/unattached_status.feature
- tox.ini
Same as #2060 cherry-picked into main
> tests: updates for jammy

- features/fix.feature
- uaclient/security.py
- uaclient/serviceclient.py
- uaclient/tests/test_serviceclient.py
- uaclient/util.py
```
fix: don't redact large http responses unnecessarily
```
Run the new steps on the integration test. Without these changes, it will take a very long time to finish. With these changes, it should take a few seconds.
> fix: don't redact_sensitive_logs on huge json blobs

- integration-requirements.txt
```
integration-reqs: bump pycloudlib pinned commit
Main reason: use variable expansion in pycloudlib.toml in CI,
see a16ba9a5bd1778da295e4cbb77164bb8a248466.
```
> integration-reqs: bump pycloudlib pinned commit (SC-979)

- features/realtime_kernel.feature
- tox.ini
- uaclient/messages.py
```
realtime: adjust warning message
```
> realtime: adjust warning message

- features/attach_validtoken.feature
- uaclient/cli.py
- uaclient/config.py
- uaclient/contract.py
- uaclient/messages.py
- uaclient/tests/test_cli_refresh.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_contract.py
- uaclient/util.py
status: check if contract is updated when running status
The user can get a notification of refreshing the contract when they run ua status and their is a change in their contract details from the server.
> status: check if contract is updated when running status

- debian/changelog
- features/attach_validtoken.feature
- features/attached_enable.feature
- features/realtime_kernel.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
- uaclient/entitlements/realtime.py
- uaclient/messages.py
> Bring in 27.8 changes to main

- .pre-commit-config.yaml
- debian/ubuntu-advantage-tools.postinst
- dev-requirements.txt
- tools/base_travis_integration_tests.sh
- tools/create-lp-release-branches.sh
- tools/make-release
- tools/refresh-keyrings.sh
- tools/run_aws_travis_integration_tests.sh
- tox.ini
shell-linting: add shellcheck for shell scripts
Adding linting for shell scripts using shellcheck
Fixes #1305
> shell-linting: add shellcheck for shell scripts

- tools/create-lp-release-branches.sh
> tools: update script to include latest releases

- dev-docs/howtoguides/building.md
- docs/howtoguides/configure_proxies.md
- docs/howtoguides/enable_fips.md
- docs/howtoguides/enable_ua_in_dockerfile.md
- docs/tutorials/create_a_fips_docker_image.md
> docs: use github markdown warning/note feature

- README.md
- docs/explanations/motd_messages.md
docs: add explanation for UA related MOTD messages
Add explanation about UA related messages that are shown on MOTD
Double check if the document covers all of the MOTD messages we deliver that are related to UA
> docs: add explanation for UA related MOTD messages

- README.md
- docs/explanations/status_columns.md
- docs/explanations/what_refresh_does.md
- docs/howtoguides/how_to_simulate_attach.md
- docs/tutorials/basic_ua_commands.md
Add tutorial for basic ua commands
Run the tutorial and see if the flow makes sense and everything works as expected
> Add tutorial for basic ua commands (SC-1056)

- README.md
- docs/tutorials/ua_fix_scenarios.md
- uaclient/messages.py
docs: add ua fix tutorial
Add tutorial that cover some of the main scenarios an user can face when running `ua fix`
Verify if all the steps on the tutorial are correct, meaning that the command matches the expected output.
> docs: add ua fix tutorial

- lib/timer.py
- uaclient/serviceclient.py
- uaclient/tests/test_serviceclient.py
Fix timer issues
Fix issue related to timer issue running forever due to a stuck request.
Additionally, we are now logging when a timer job has started running
Run the modified unit test
> Fix timer issues

- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/aws-ids.yaml
- features/azure-ids.yaml
- features/gcp-ids.yaml
- features/ubuntu_pro.feature
- features/unattached_status.feature
- tox.ini
tests: add jammy pro test support
Run new the jammy pro tests
> tests: add jammy pro test support (SC-868)

- README.md
- docs/explanations/how_to_interpret_the_security_status_command.md
- docs/explanations/why_trusty_is_no_longer_supported.md
docs: explain the security-status command output
Add explanation of the machine readable structure of the `security-status` command
Verify if the the description of the command and structure is accurate
> docs: explain the security-status command output

- README.md
docs: update readme for diataxis structure
Small readme update for diataxis structure
> docs: update readme for diataxis structure

- debian/ubuntu-advantage-tools.postinst
- sru/release-27.9/cleanup_cloud_id_shim.sh
- sru/release-27.9/cleanup_cloud_id_shim_ppa.sh
Run the new manual test script
> postinst: cleanup cloud-id-shim on xenial->bionic

- features/attached_commands.feature
- features/collect_logs.feature
- features/unattached_commands.feature
- uaclient/cli.py
- uaclient/defaults.py
- uaclient/tests/test_cli_collect_logs.py
rotate your log files
run `ua collect-logs`
ensure the resulting tarfile includes the rotated logs
> collect-logs: collect rotated log files

- features/attach_validtoken.feature
- features/proxy_config.feature
- features/ubuntu_pro.feature
> tests: minor fixes from release 27.9

- ubuntu-advantage.1
man: update proxy config
We are updating the man pages to include the information about the global and scoped proxy configuration.
> man: update proxy config

- docs/explanations/status_columns.md
- features/_version.feature
- features/attached_commands.feature
- features/steps/steps.py
- features/ubuntu_pro_fips.feature
- features/unattached_status.feature
- uaclient/cli.py
- uaclient/status.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_status.py
- uaclient/tests/test_version.py
- uaclient/version.py
Advertise the enabled features on status instead of changing the version string
> status: bring features from ua version to ua status

- docs/explanations/how_to_interpret_the_security_status_command.md
- features/attached_commands.feature
- features/schemas/ua_security_status.json
- uaclient/security_status.py
- uaclient/tests/test_security_status.py
> security-status: include download_size of package updates

- .github/workflows/ci-base.yaml
- tools/check-versions-are-consistent.py
- uaclient/tests/test_version.py
- uaclient/version.py
mess with the version.py and changelog version strings and run the new script
Fixes: #381
> ci: check for version consistency (SC-1159)

- uaclient/api/tests/test_u_pro_attach_magic_wait_v1.py
- uaclient/api/u/pro/attach/magic/wait/v1.py
magic-attach: improve connection error retry
Only raise connection error after three sequential ConnectivityError exceptions
Run the integration test and verify it is working as expected
> magic-attach: improve connection error retry

- debian/control
> Update vcs references

- features/attach_validtoken.feature
- features/unattached_status.feature
Getting CI green after server changes
> tests: update jammy livepatch support

- uaclient/data_types.py
- uaclient/tests/test_data_types.py
data object: add enum data type.
Adding enum type support in data object. We have enum support in the contract server response.
> data object: add enum data type

- debian/changelog
- debian/ubuntu-advantage-tools.postinst
- sru/_archive/release-27.9/cleanup_cloud_id_shim.sh
- sru/_archive/release-27.9/cleanup_cloud_id_shim_ppa.sh
bring changes from release 27.9
Bring changelog changes and fixes performed on release 27.9
Verify that all 27.9 only changes are on this PR
> Bring changes from release 27.9

- features/api.feature
- features/ubuntu_pro.feature
- uaclient/api/api.py
- uaclient/api/tests/test_api_u_pro_attach_auto_should_auto_attach.py
- uaclient/api/tests/test_api_u_pro_attach_magic_wait_v1.py
- uaclient/api/u/pro/attach/auto/should_auto_attach/v1.py
- uaclient/apt.py
- uaclient/tests/test_apt.py
api: add detect is_pro endpoint
Add endpoint that detect if we are running on a Pro machine or not
Run the updated integration tests
> Detect pro api

- uaclient/data_types.py
- uaclient/tests/test_data_types.py
> data_types: datetime data value

- .github/workflows/ci-integration.yaml
We should build the package in CI for all releases under active development.
> ci: add kinetic to the releases list when building the package

- apport/source_ubuntu-advantage-tools.py
- features/collect_logs.feature
- setup.py
- uaclient/actions.py
- uaclient/cli.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_cli_auto_attach.py
- uaclient/tests/test_cli_collect_logs.py
- uaclient/tests/test_cli_detach.py
- uaclient/tests/test_cli_disable.py
- uaclient/tests/test_cli_enable.py
- uaclient/tests/test_cli_refresh.py
Submit a bug and make sure the tar file is uploaded properly. See https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1979084 as an example.
```
APPORT_DISABLE_DISTRO_CHECK=1 ubuntu-bug ubuntu-advantage-tools
```
Also just run that on every supported series to make sure the logs are collected successfully, but no need to actually create a bug for each series.
> ubuntu-bug integration

- README.md
- docs/source/howtoguides/create_pro_golden_image.md
- docs/source/tutorials/create_a_fips_updates_pro_cloud_image.md
- features/cloud_pro_clone.feature
- features/steps/steps.py
- features/util.py
> tests: test required flow for custom pro-based cloud images

- apt-hook/hook.cc
```
apt-hook: Fix kinetic build
Add #include <array> to apt-hook/hook.cc to let the compiler
see full types.
```
```bash
$ sbuild --dist=kinetic --resolve-alternatives --no-clean-source --nolog --verbose --no-run-lintian
...
+------------------------------------------------------------------------------+
| Summary                                                                      |
+------------------------------------------------------------------------------+
Build Architecture: amd64
Build Type: binary
Build-Space: 8424
Build-Time: 18
Distribution: kinetic
Host Architecture: amd64
Install-Time: 16
Job: /home/aciba/canonical/ubuntu-advantage-tools_28.0.dsc
Machine Architecture: amd64
Package: ubuntu-advantage-tools
Package-Time: 139
Source-Version: 28.0
Space: 8424
Status: successful …
```
> Fix kinetic build

- docs/source/howtoguides/create_pro_golden_image.md
- docs/source/tutorials/create_a_fips_updates_pro_cloud_image.md
- features/attached_commands.feature
- features/cloud_pro_clone.feature
- features/detached_auto_attach.feature
- features/ubuntu_pro.feature
- features/ubuntu_pro_fips.feature
- uaclient/cli.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/tests/test_cli_auto_attach.py
> dont detach on autoattach

- uaclient/exceptions.py
- uaclient/files.py
- uaclient/messages.py
- uaclient/tests/test_files.py
Edit a file to create a DataObjectFile.
Write code to `write` an invalid object or wrong type. Verify that mypy catches it
Write code to use the return value of `read` improperly (e.g. dont check for None, or look at wrong field name). Verify mypy catches it
> data object file

- CONTRIBUTING.md
- dev-docs/explanations/how_auto_attach_works.md
- dev-docs/howtoguides/use_staging_environment.md
add more docs
Add docs explaining how to use the contracts staging environment and how auto-attach works.
Verify if both docs are properly explaining the concepts
> Add more docs

- .github/workflows/cla-check.yaml
Adds https://github.com/canonical/has-signed-canonical-cla
> ci: add cla check

- features/cloud_pro_clone.feature
- features/daemon.feature
- features/enable_fips_cloud.feature
- features/enable_fips_container.feature
- features/enable_fips_pro.feature
- features/enable_fips_vm.feature
- features/fix.feature
- features/realtime_kernel.feature
- features/steps/steps.py
- features/ubuntu_pro.feature
- features/ubuntu_pro_fips.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
> tests: simplify reboot step

- features/ubuntu_pro.feature
Merging the last two PRs led to a couple outdated tests.
> tests: fix a couple reboot lines on behave

- uaclient/messages.py
- uaclient/system.py
- uaclient/tests/test_system.py
On your system or a test system:
- `env PYTHONPATH=1 python3`
- `from uaclient import system`
- `system.get_lscpu_arch()`
> get arch from lscpu output for livepatch

- dev-docs/references/directory_layout.md
- dev-docs/references/what_happens_during_attach.md
- docs/source/explanations/what_are_the_timer_jobs.md
```
docs: update machine-token and status documentation
We are updating the documentation for the machine-token files, since we added one more world readable
`machine-token.json` file.
```
> docs: update machine-token and status documentation

- features/unattached_commands.feature
- uaclient/cli.py
Fixes: #672
Try a couple wrong invocations on the base command
`pro --debug`
`pro --wrong-flag`
> cli: better error message on unrecognized flags (SC-1158)

- apt-hook/hook.cc
- debian/control
- features/fix.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
- uaclient/cli.py
- uaclient/messages.py
- uaclient/util.py
Bring the following changes into release-27:
* Drop focal->impish upgrade tests
* Remove ca-certificates as a dependency
* fix the apt hooks build on kinetic
> Update release 27

- uaclient/api/tests/test_api_u_pro_attach_magic_wait_v1.py
- uaclient/api/u/pro/attach/magic/wait/v1.py
- uaclient/contract.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/tests/test_contract.py
magic-attach: Add another failure check
Add exception handling for the situation where the magic-attach endpoint is unavailable
Run the new unit tests for this feature
> magic-attach: Add another failure check

- features/api_full_auto_attach.feature
- uaclient/actions.py
- uaclient/api/api.py
- uaclient/api/exceptions.py
- uaclient/api/tests/test_api.py
- uaclient/api/tests/test_u_pro_attach_auto_full_auto_attach_v1.py
- uaclient/api/u/pro/attach/auto/full_auto_attach/v1.py
- uaclient/cli.py
- uaclient/contract.py
- uaclient/entitlements/__init__.py
- uaclient/entitlements/tests/conftest.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_cis.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/messages.py
- uaclient/tests/test_apt.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_auto_attach.py
auto_attach: add short retry loop api endpoint
We are adding an api endpoint to perform auto-attach with short retries incase of failures;
this is before the process of longer retries.
> auto_attach: add short retry loop api endpoint

- docs/source/howtoguides/enable_cc.md
- docs/source/howtoguides/enable_realtime_kernel.md
- features/attached_enable.feature
- features/realtime_kernel.feature
- uaclient/actions.py
- uaclient/cli.py
- uaclient/entitlements/base.py
- uaclient/entitlements/cc.py
- uaclient/entitlements/cis.py
- uaclient/entitlements/entitlement_status.py
- uaclient/entitlements/realtime.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/conftest.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/messages.py
- uaclient/security.py
- uaclient/tests/test_cli_enable.py
> enable: access-only flag for usecases where auto-install is undesired

- features/motd_messages.feature
CI should pass (unlike https://github.com/canonical/ubuntu-advantage-client/runs/8001645584?check_suite_focus=true)
> tests: apt update before apt upgrade in motd tests

- CONTRIBUTING.md
- dev-docs/howtoguides/how_to_use_magic_attach_endpoints.md
- features/api_magic_attach.feature
docs: add magic attach docs for api endpoints
Add docs explaining how to use the magic attach endpoints.
Additionally, add extra step on the magic attach test to see the wait output for a invalid token
Verify if the docs are covering all it should for the magic attach endpoints
Verify if the new step introduced on the magic attach test is working as expected
> Magic attach guide

- README.md
- docs/source/explanations/motd_messages.md
- docs/source/explanations/status_columns.md
- docs/source/howtoguides/enable_ua_in_dockerfile.md
- docs/source/howtoguides/get_token_and_attach.md
- docs/source/howtoguides/how_to_simulate_attach.md
- docs/source/index.rst
- docs/source/tutorials/basic_ua_commands.md
- docs/source/tutorials/ua_fix_scenarios.md
- features/api_full_auto_attach.feature
- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/detached_auto_attach.feature
- features/motd_messages.feature
- features/proxy_config.feature
- features/staging_commands.feature
- features/ubuntu_pro.feature
- features/ubuntu_pro_fips.feature
- features/unattached_commands.feature
- features/unattached_status.feature
- help_data.yaml
- uaclient/entitlements/esm.py
- uaclient/messages.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_gpg.py
- ubuntu-advantage.1
esm: rename service description
Update description of esm-infra and esm-apps
Verify if the integration tests are still working as expected
> esm: rename service description

- uaclient/actions.py
- uaclient/clouds/gcp.py
- uaclient/daemon.py
- uaclient/lock.py
- uaclient/tests/test_daemon.py
Everything should still work as expected
> pro: renaming locks and loggers

- uaclient/status.py
> status: catch exceptions from astimezone

- features/apt_messages.feature
> tests: update esm-apps package for xenial

- dev-docs/explanations/how_auto_attach_works.md
> docs: fix typo in contract server URL

- features/attached_status.feature
- uaclient/config.py
- uaclient/system.py
New integration test should pass
> status: make lock world readable so non-root status --wait works

- debian/ubuntu-advantage-tools.links
Run `lintian` and make sure there is no complain about a missing manpage
> chore: add link for the 'pro' manpage

- features/proxy_config.feature
- features/steps/steps.py
> tests: add proxy test for a system without internet

- README.md
- docs/tutorials/basic_ua_commands.md
Fix links in README.md after https://github.com/canonical/ubuntu-advantage-client/pull/2231.
```
README.md: Fix links
```
> README.md: Fix links

- docs/explanations/motd_messages.md
- features/motd_messages.feature
- uaclient/messages.py
Integration tests should still pass
> messaging: correct num covered packages

- uaclient/contract.py
- uaclient/serviceclient.py
```
ua attach $token
ufw default deny incoming
ufw default deny outgoing
ufw allow out 53
ufw enable
time ua status
```
above should finish in about 4 seconds now (before was 1minute)
> status: set contract check timeout lower to let status finish

- lib/timer.py
At least until we find something better, or find out we can enable it safely.
> jobs: don't run the EOL job

- uaclient/contract.py
- uaclient/tests/test_contract.py
Easier to catch API side, still UserFacingError for the CLI error handler.
> tests: use ConnectivityError where possible

- uaclient/api/u/pro/attach/auto/full_auto_attach/v1.py
> chore: remove a couple unused imports

- features/api_security_package_manifest.feature
- uaclient/api/api.py
- uaclient/api/tests/test_api.py
- uaclient/api/tests/test_api_security_status_get_package_manifest.py
- uaclient/api/tests/test_api_u_pro_attach_auto_should_auto_attach.py
- uaclient/api/u/security/package_manifest/v1.py
- uaclient/apt.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/snap.py
- uaclient/tests/test_apt.py
- uaclient/tests/test_snap.py
security-status: list packages in oci manifest format
Add an endpoint where we can get a list of packages installed with their versions.
The output is in the OCI manifest file format so that cloud providers can use it with 
OVAL data.
> security-status: list packages in oci manifest format

- README.md
- docs-requirements.txt
- docs/conf.py
- docs/references/api.md
- uaclient/api/u/pro/attach/auto/full_auto_attach/v1.py
Document the current endpoints for the API, and set a basic structure for documenting the next ones.
Also, fix a couple details to make the HTML rendering look nice.
`tox -e docs`, open the results and behold!
> add API documentation (SC-1251)

- features/attached_enable.feature
- features/enable_fips_vm.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
Same as #2258 for a few more tests
> tests: call status with --all to check on services overall

- features/security_status.feature
- uaclient/cli.py
- uaclient/messages.py
- uaclient/security_status.py
- uaclient/tests/test_cli_security_status.py
This will only be available when it is GA, and it is according to what was discussed with Lech.
Aside from the message change, it is the same @orndorffgrant had sent before. Thanks much for that.
Integration tests have a good coverage of the scenarios
> Remove apps information from security-status

- features/api_full_auto_attach.feature
- features/apt_messages.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/motd_messages.feature
- features/security_status.feature
- features/unattached_commands.feature
- features/unattached_status.feature
- uaclient/api/tests/test_u_pro_attach_auto_full_auto_attach_v1.py
- uaclient/entitlements/esm.py
- uaclient/entitlements/ros.py
- uaclient/entitlements/tests/test_esm.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_disable.py
- uaclient/tests/test_cli_enable.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_status.py
revert services to beta
Revert esm-apps, ros and ros-updated to beta services
Verify if the modified integration tests are working as expected
> Revert services to beta

- debian/changelog
- uaclient/version.py
And yet again we do this
Includes a change done in the LP branch after changelog review.
> new release 27.11.2

- uaclient/actions.py
- uaclient/tests/test_actions.py
collect-logs: Do not fail if we can't read a file
Currently, if we fail to read a file, we will error out during the execution of the command. We are updating that so that we will just warn the user that a file could not be read and proceed with the command.
LP: #1991858
Run the new unittest
> collect-logs: Do not fail if we can't read a file

- debian/changelog
- uaclient/actions.py
- uaclient/tests/test_actions.py
- uaclient/version.py
> Release 27.11.3

- debian/changelog
- debian/ubuntu-advantage-tools.postinst
- features/unattached_commands.feature
- uaclient/defaults.py
- uaclient/tests/test_version.py
- uaclient/version.py
make sure version upgrade notification still works
> version: use /run for candidate-version cache

- uaclient/api/u/pro/attach/auto/full_auto_attach/v1.py
- uaclient/entitlements/__init__.py
- uaclient/entitlements/tests/test_entitlements.py
Try the api with a nonexistend service name. Expect an exception after a successful auto attach
> api: fail on nonexistent service names in args

- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/realtime_kernel.feature
- features/unattached_status.feature
- help_data.yaml
- uaclient/api/tests/test_u_pro_attach_auto_full_auto_attach_v1.py
- uaclient/entitlements/realtime.py
- uaclient/messages.py
- uaclient/tests/test_cli_disable.py
- uaclient/tests/test_cli_enable.py
- uaclient/tests/test_cli_status.py
realtime-kernel: make service non-beta
Make realtime-kernel a non-beta service and update the messages around it
> realtime-kernel: make service non-beta

- features/environment.py
tests: clean ssh keys if instance is destroyed
If we choose to delete the instance after an integration test is complete, we should also remove the ssh key associated with it
Run an integration test with `UACLIENT_BEHAVE_DESTROY_INSTANCES=1` and verify if the ssh keys are removed.
Run an integration test with `UACLIENT_BEHAVE_DESTROY_INSTANCES=0` and verify if the ssh keys are kept.
> tests: clean ssh keys if instance is destroyed

- features/apt_messages.feature
- features/motd_messages.feature
- features/steps/files.py
- uaclient/cli.py
- uaclient/contract.py
- uaclient/files/files.py
- uaclient/jobs/tests/test_update_messaging.py
- uaclient/jobs/update_messaging.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_contract.py
contract-expiry: update expiry to update motd
Updating the contract expiry date when the expiry date is approaching or lapsed.
> contract-expiry: update expiry to updated motd

- docs/index.rst
```
- added "Code of Conduct" link
- added "Contribution" link
- moved all links to the bottom of the page for ease of reference and updating
This is a "test" commit, to make sure I have understood the process whilst making a useful change. If I have done anything incorrectly, please let me know!
```
```
This PR does not address any bugs.
```
> docs: RTD home page links added

- docs/howtoguides/check_pro_version.md
- docs/tutorials/basic_commands.md
- docs/tutorials/create_a_fips_docker_image.md
- docs/tutorials/fix_scenarios.md
docs: minor improvements on tutorials
Addressing feedback for some of our tutorials
Verify if the docs are still building properly
> docs: minor improvements on tutorials

- features/steps/airgap.py
- features/steps/shell.py
- tox.ini
- uaclient/apt.py
- uaclient/cli.py
- uaclient/config.py
- uaclient/entitlements/base.py
- uaclient/entitlements/esm.py
- uaclient/exceptions.py
- uaclient/files/files.py
- uaclient/security.py
- uaclient/security_status.py
- uaclient/util.py
This should only be adjusting things to make the type checker happy.
Run `tox -e mypy` and make sure there are no errors with the new flag
> mypy: use check-untyped-defs

- docs/references/api.md
- uaclient/api/u/security/package_manifest/v1.py
- uaclient/security_status.py
Docs should now cover all API functionality.
Adjusted small pieces in the code for safety / compliance with the standards.
> Add missing docs for the API endpoints

- docs/howtoguides/enable_realtime_kernel.md
- features/proxy_config.feature
- features/realtime_kernel.feature
- help_data.yaml
- uaclient/messages.py
> rt-kernel: standardize capitalization in all references

- apt-hook/json-hook.cc
json_hook: correct hello message response
Just added a needed brace at the end.
> json_hook: correct hello message response

- features/steps/packages.py
To test the full output of security-status, we install packages to count them as third-party and unknown.
We install `code` to be the third party option, and `gh` to be the unknown package. The reason for that is that the `code` deb sets up a parts file with a source entry (thus being recognized as third-party) and `gh ` does not.
However, `gh` just landed on `universe` from `kinetic` on. So, when testing for the release (when u-a-t is installed from `-proposed`), there is no unknown package anymore :|
[EDITED] 
~The """"fix"""" here is to change the `gh` package to any other which is not in the archive. The chosen one is `surfshark-release` just because I could not find a `.deb` in the wild which wouldn't setup a repository. This one does, but we remove the parts file to make sure it is …
> tests: change the packages for the security status test (SC-1353)

- docs/howtoguides/configure_proxies.md
corrects some formatting, and updates guidance to recommend newer config variables
> docs: update proxy how to guide

- features/_version.feature
- features/airgapped.feature
- features/apt_messages.feature
- features/environment.py
- features/motd_messages.feature
- features/proxy_config.feature
- features/retry_auto_attach.feature
- features/steps/contract.py
- features/steps/files.py
- features/ubuntu_pro.feature
- features/util.py
All modifed tests should still pass
> tests: unify templatized steps into one function

- features/fix.feature
> tests: this test requires updated package cache

- features/cloud.py
> tests: remove old sleep that is no longer needed

- uaclient/cli.py
> status: contract requests should never cause status to fail

- docs/tutorials/basic_commands.md
- docs/tutorials/fix_scenarios.md
docs: replace LXD for Multipass on the tutorials
To avoid the confusing setup of LXD in the tutorials, we are now replacing it for Multipass. For the tutorials, Multipass provide the same functionality we need without a pontentially confusing setup for the user
Verify that the tutorial work correctly with Multipass
> docs: replace LXD for Multipass on the tutorials

- uaclient/system.py
- uaclient/tests/test_system.py
> util: all file writing is now done atomically by renaming a temp file

- features/steps/ubuntu_advantage_tools.py
tests: fix integration test for upgrade scenario
Fix call to `build_debs` for the upgrade flow
> tests: fix integration test for upgrade scenario

- uaclient/jobs/update_messaging.py
> messaging: don't fail if apt-hook exe isn't present

- features/apt_messages.feature
- features/environment.py
- lib/apt_news.py
- uaclient/apt.py
- uaclient/apt_news.py
- uaclient/cli.py
- uaclient/conftest.py
- uaclient/entitlements/esm.py
- uaclient/entitlements/tests/test_esm.py
- uaclient/jobs/tests/test_update_messaging.py
- uaclient/jobs/update_messaging.py
- uaclient/messages.py
- uaclient/tests/test_apt_news.py
Make sure the new contract expiration notices match what you expect.
> apt_news: treat contract expiration notices as apt news overrides

- features/apt_messages.feature
- features/motd_messages.feature
- uaclient/jobs/tests/test_update_messaging.py
- uaclient/jobs/update_messaging.py
uncommented tests should pass
ensure announcement shows up on systems where esm-apps is not enabled
> motd: reveal esm-apps announcement

- features/steps/packages.py
Well we don't need the S3 buckets anymore - PPAs are set on launchpad and dummy packages are there.
This test is FINALLY rounded up.
> chore: change S3 PPAs to Launchpad PPAs on integration tests (SC-1362)

- uaclient/entitlements/base.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_repo.py
I spent some time on this. We could easily spend a lot more time on it. But let's start with this.
everything should pass
make sure I didn't lose coverage of anything important during the refactors
> Refactor some enable unittests

- uaclient/actions.py
actions: remove unused variable from module
Remove the event_logger from the action module, since it is not being used directly
Verify if no tests break because of this change
> actions: remove unused variable from module

- features/cloud.py
Try to run an awsgeneric-16.04 test before and after this. It should work after this commit.
> tests: use released image for awsgeneric-16.04

- debian/changelog
- debian/control
- docs/howtoguides/enable_realtime_kernel.md
- features/api_configure_retry_service.feature
- features/daemon.feature
- features/proxy_config.feature
- features/realtime_kernel.feature
- features/retry_auto_attach.feature
- help_data.yaml
- uaclient/messages.py
Those were the adjustments done to the `release` branch directly, which need to be brought to `main`.
> Bring things from 27.12

- features/steps/packages.py
cherry-picked from main to make this test work after infra changes
> chore: change S3 PPAs to Launchpad PPAs on integration tests

- features/steps/machines.py
- features/steps/output.py
Running full proxy set of tests should work now
> Tests fix instance cleanup

- dev-docs/howtoguides/detach_pro_instances.md
```
dev-doc: add guide to permanently detach Pro instances
Fixes: #2177
```
> dev-doc: add guide to permanently detach Pro instances (SC-1214)

- debian/changelog
- uaclient/version.py
> new release 27.13.2

- debian/changelog
- uaclient/version.py
> release 27.13.3

- apt-hook/20apt-esm-hook.conf
- debian/changelog
- debian/ubuntu-advantage-tools.postinst
- debian/ubuntu-advantage-tools.postrm
- debian/ubuntu-advantage-tools.preinst
- features/attached_enable.feature
- features/fix.feature
- features/steps/machines.py
- features/steps/output.py
- features/ubuntu_pro.feature
- features/ubuntu_upgrade_unattached.feature
- sru/release-27.13.2/python-apt-snippet.py
- sru/release-27.13.2/test-apt-hook-nonroot.sh
- uaclient/apt.py
- uaclient/tests/test_apt.py
Already released, should come to main anyway
> Pull things from 27.13.2

- features/apt_messages.feature
- features/attached_status.feature
- features/motd_messages.feature
- uaclient/apt_news.py
- uaclient/files/files.py
- uaclient/jobs/update_messaging.py
- uaclient/security.py
- uaclient/status.py
- uaclient/tests/test_security.py
New integration tests should pass
> Cant assume effectiveto is there

- lib/timer.py
- uaclient/tests/test_ua_timer.py
If the file is corrupted/invalid, erase it, run the jobs and create a new one.
LP: #2006261
new unit test added
test for SRU: create the jobs-status file with random stuff, run it, see it works
> fix: recycle invalid jobs-status.json file

- debian/changelog
> Fix wrong changelog entry

- docs/references/api.md
- docs/references/support_matrix.md
Double check that the recommended techniques for version and feature detection work.
> Api reference min version docs

- tools/test-in-lxd.sh
- tools/test-in-multipass.sh
```
tools: improve test-in-{lxd,multipass}.sh
- remove dead code
- enable errexit and nounset flags
- provide default for series
- fix jq argument
```
> tools: improve test-in-{lxd,multipass}.sh

- docs/howtoguides.rst
- docs/howtoguides/pro_in_airgapped.md
Adding documentation on how to use Ubuntu Pro in an airgapped environment.
Pro client: Lucas Moura (@lucasmoura).
Product Management: Lech Sandeski (@lechsandecki).
Field Engineering: Calvin Hartwell (@CalvinHartwell).
Documentation: Sally Makin (@s-makin).
> Docs: use Ubuntu Pro in airgapped environment

- ubuntu-advantage.1
esm -> esm-infra and esm-apps
added realtime-kernel
"Oh but this is not the way you write options with a line break" well probably, please enlighten me... I am no Java specialist, and this is 2023, we should be [using markdown](https://eddieantonio.ca/blog/2015/12/18/authoring-manpages-in-markdown-with-pandoc/) or something I guess.
Fixes: #2457
See the manpage
> manpage: update list of services for enable/disable

- debian/changelog
- features/apt_messages.feature
- uaclient/apt_news.py
- uaclient/version.py
> Release 27.13.6

- features/_version.feature
- features/steps/ubuntu_advantage_tools.py
Run the version tests and verify that apt policy output is included
> tests: show apt policy output in version test for manual source verification (SC-1417)

- uaclient/actions.py
- uaclient/cli.py
- uaclient/config.py
- uaclient/data_types.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/livepatch.py
- uaclient/security_status.py
- uaclient/status.py
- uaclient/tests/test_cli_config_set.py
- uaclient/tests/test_cli_config_unset.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_config.py
- uaclient/tests/test_data_types.py
- uaclient/tests/test_livepatch.py
- uaclient/tests/test_security_status.py
- uaclient/tests/test_status.py
No functionality change, all tests should still pass
> refactor: prep for new livepatch support status of "kernel upgrade required"

- uaclient/cli.py
- uaclient/daemon/__init__.py
- uaclient/log.py
- uaclient/security.py
- uaclient/serviceclient.py
- uaclient/system.py
- uaclient/tests/test_cli_api.py
- uaclient/tests/test_log.py
- uaclient/tests/test_serviceclient.py
- uaclient/util.py
logging: Added Redaction Filter for logs
This is adds the redaction filter for the logging mechanism. 
It is the first of many PRs to come, from the same branch.
> logging: Added Redaction Filter for logs

- features/api_packages.feature
CI should pass for these tests again
> tests: update curl versions in package list test

- features/api_packages.feature
- features/environment.py
- features/steps/misc.py
- features/steps/packages.py
- features/util.py
test: modify package check on package list test
For this test, we need the package candidate version. We are are creating now a way to not have to manually specify the package candidate version for the test
> test: modify package check on package list test

- .github/workflows/ci-base.yaml
> ci: github is removing bionic support, stop running unit-tests against the correct version of python (aside from package builds)

- features/realtime_kernel.feature
realtime integration tests should pass now
> tests: fix realtime tests

- features/logs.feature
- uaclient/cli.py
- uaclient/daemon/__init__.py
- uaclient/log.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_log.py
logging: Added Redaction Filter for logs
This is adds the redaction filter for the logging mechanism.
> logging: Added JsonArrayFormatter

- uaclient/apt.py
- uaclient/tests/test_apt.py
still need to address what to do on systems where the cache is already present, we will probably have to remove it...
LP: #2004018
I added unit tests, but the verification on a real system was manual on a system that does not actually support ESM.
> apt-cache: only setup the local cache if the service is available

- docs/conf.py
- uaclient/config.py
- uaclient/tests/test_config.py
A few things I found passing by while looking at our code
> Gardening chores

- debian/changelog
- uaclient/version.py
> new release 27.14.1

- .github/actions/bug-refs/action.yml
- .github/actions/bug-refs/index.js
- .github/actions/bug-refs/package-lock.json
- .github/actions/bug-refs/package.json
- .github/workflows/custom_pr_checks.yaml
- .gitignore
Take a look at the logic and lmk if you think this would be useful.
We can expand on this action (or create new actions based on this template) to do more custom checks for things in the future like e.g. "if the diff is big, at least one commit message should contain a message > 3 lines" or something like that.
> experiment: custom pr check actions

- docs/explanations.rst
- docs/explanations/how_to_interpret_output_of_unattended_upgrades.md
- docs/references/api.md
docs: add references to unattended-upgrades api
Add documentation to the unattended upgrades endpoint
Assert that docs are building without an issue and the content of the docs reflect the api endpoint
> Unattended upgrades api docs

- uaclient/entitlements/livepatch.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/livepatch.py
- uaclient/messages.py
- uaclient/security.py
- uaclient/security_status.py
- uaclient/tests/test_livepatch.py
- uaclient/tests/test_security.py
- uaclient/tests/test_security_status.py
Everything should still pass. Including existing livepatch.feature test
> livepatch: using support status in reboot-required (SC-1307)

- uaclient/clouds/tests/test_identity.py
- uaclient/config.py
- uaclient/tests/test_config.py
Everything except this feature should still work
> config: no longer load uaclient.conf from cwd

- debian/changelog
- uaclient/version.py
> new release 27.14.4

- .github/actions/bug-refs/index.js
a silly JS mistake
no-lp no-gh no-jira
> ci: fix bug when bug-refs are found

- dev-docs/howtoguides/how_to_release_a_new_version_of_ua.md
- dev-docs/references/version_string_formatting.md
- tools/create-lp-release-branches.sh
> docs: update versioning guidance for devel release numbers and extra .1

- uaclient/conftest.py
- uaclient/tests/test_cli_collect_logs.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_config.py
- uaclient/tests/test_util.py
logging_revamp: fix unittests logging leak
We are having some issues with logging leaks in unittests.
no-lp no-gh no-sc
Run the all the tests `tox -e py310-test`.
Run the tests in test_util.py `tox -e py310-test uaclient/tests/test_util.py`.
> logging_revamp: fix unittests logging leak SC-1530

- uaclient/clouds/tests/test_identity.py
- uaclient/config.py
- uaclient/tests/test_config.py
I'm removing this from release, so putting it back here as a PR into main
> config: no longer load uaclient.conf from cwd - again

- docs/explanations/apt_messages.md
- docs/howtoguides/enable_fips.md
- docs/howtoguides/get_rid_of_corrupt_lock.md
```
summary: Minor typo fixes in docs
This is my first time contributing on GitHub to Canonical documentation. 
Please let me know if I am doing anything incorrectly or if there is something I can do to be a more effective contributor.
Thanks for your time reviewing this pull request!
```
> Typo Fixes in docs

- docs/_static/js/github_issue_links.js
This feature is now added to the starter pack, changing button text
to be consistent with that
no-jira
no-lp
no-gh
> Change feedback button text

- docs/index.rst
Making reference to feedback button text consistent with proposed
change to feedback button
no-jira
no-lp
no-gh
> Update to feedback button text

- features/environment.py
- features/steps/airgap.py
- features/steps/attach.py
- features/steps/files.py
- features/steps/fix.py
- features/steps/machines.py
- features/steps/status.py
- features/steps/ubuntu_advantage_tools.py
- features/util.py
- tools/run-integration-tests.py
Some ideas for improvements I had during verification testing.
(well there are lots more ideas too, but these were small enough I went ahead and did them).
Try out user data for configuring a test run. e.g. `tox -e behave-lxd-16.04 -- -D install_from=archive`
Cause a test failure and then check out the contents of `./artifacts/latest/logs`
> tests: some integration test UX enhancements

- docs/explanations/status_columns.md
> docs: explain json output of status

- apt-hook/json-hook.cc
- features/apt_messages.feature
no-lp no-gh no-jira
The following tests should pass
```
tox -e behave-awsgeneric-16.04 -- -D install_from=local features/apt_messages.feature:630
tox -e behave-awsgeneric-18.04 -- -D install_from=local features/apt_messages.feature:631
tox -e behave-awsgeneric-20.04 -- -D install_from=local features/apt_messages.feature:632
tox -e behave-azuregeneric-16.04 -- -D install_from=local features/apt_messages.feature:650
tox -e behave-azuregeneric-18.04 -- -D install_from=local features/apt_messages.feature:651
tox -e behave-azuregeneric-20.04 -- -D install_from=local features/apt_messages.feature:652
tox -e behave-gcpgeneric-16.04 -- -D install_from=local features/apt_messages.feature:670
tox -e behave-gcpgeneric-18.04 -- -D install_from=local features/apt_messages.feature:671
tox -e …
```
> apt messaging: add bionic-specific urls

- features/attached_commands.feature
- features/attached_status.feature
- features/unattached_status.feature
no-lp no-gh no-jira
jammy tests should pass again
> tests: usg is on jammy now

- .github/workflows/ci-base.yaml
- docs/references/network_requirements.md
- tox.ini
```
docs: Wall and fix broken link
Treat Sphinx warnings as errors and add a GH check to verify the
docs are generated without errors.
```
`tox -e docs`
> docs: Wall and fix broken link

- features/i8n.feature
tests: adding i8n test support
Adding integration tests to check if all commands run successfully 
in systems with different locales/languages.
no-lp no-gh
> tests: adding i8n test support (SC-1476)

- features/util.py
no-lp no-gh
Desired merge method: Squash and Merge
```
tests: optimize sbuild execution time
Disable unittest in while building debs within behave.
```
> sbuild: optimize execution time (SC-1473)

- features/environment.py
no-jira no-gh no-lp
Does this default make sense for you too? I set install_from=local probably 95% of the time
> tests: default to testing local build

- .github/PULL_REQUEST_TEMPLATE.md
> github: update PR template

- debian/changelog
This brings in changelog fixes that were made in git-ubuntu but never brought over to github. This is part of the effort to make the git-ubuntu and github release branches identical.
Make sure these match the released changelog
> Bring changelog fixes from actual release

- uaclient/contract.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/testing/fakes.py
- uaclient/tests/test_contract.py
We are renaming more contract module methods to align with their definition on the contract backend.
Verify that no integration tests are failing due to this change
> contract: rename more functions

- docs/conf.py
- tools/run-integration-tests.py
This PR solves all of ~our~ my problems because `black .` is bothering me all the time
> chore: make black happy

- docs/references/network_requirements.md
The network requirements doc was a bit out of date and could use a refresh.
Read it and see if it makes sense.
> docs: update network_requirements.md

- features/daemon.feature
- lib/daemon.py
- systemd/ubuntu-advantage.service
- tox.ini
- uaclient/clouds/azure.py
- uaclient/clouds/tests/test_azure.py
- uaclient/daemon/poll_for_pro_license.py
- uaclient/daemon/tests/test_poll_for_pro_license.py
- ubuntu-advantage.1
This PR makes it possible for azure to have in-place upgrade
from the standard license to the pro license.
> azure: add in-place upgrade feature SC-1550

- docs/explanations/how_to_interpret_the_security_status_command.md
This PR solves all of our problems because people will have docs about the security-status human readable output - which was missing in the docs.
readthedocs
> docs: add explanation about security-status output (SC-1552)

- dev-docs/explanations/systemd_units.md
- dev-docs/howtoguides/how_to_use_magic_attach_endpoints.md
- dev-docs/howtoguides/release_a_new_version.md
- dev-docs/references/directory_layout.md
- dev-docs/references/enabling_a_service.md
- dev-docs/references/terminology.md
- dev-docs/references/what_happens_during_attach.md
This PR solves all of our problems because improves / updates the dev-doc.
> chore: improve dev-docs

- debian/changelog
- debian/source/lintian-overrides
Cherry-picking #2607 into the release branch to include in 28.
Please double-check the changelog entry
> Release 28 lintian override

- features/apt_messages.feature
- features/motd_messages.feature
Bionic now is on ESM mode and the message tests should reflect that by messaging about esm-infra instead of esm-apps
Verify that the modified integration tests are working
> tests: fix test for esm messages on bionic

- sru/release-28/azure_auto_attach_on_boot.sh
Adds a manual integration test for in-place upgrade on azure for SRU testing.
```
bash sru/release-28/azure_auto_attach_on_boot.sh
```
> azure: adding manual test for Azure inplace upgrade (SC-1550)

- .github/workflows/ci-integration.yaml
- dev-docs/howtoguides/testing.md
- docs/references/support_matrix.md
- features/_version.feature
- features/api.feature
- features/api_unattended_upgrades.feature
- features/apt_messages.feature
- features/attach_invalidtoken.feature
- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/collect_logs.feature
- features/config.feature
- features/daemon.feature
- features/fix.feature
- features/i8n.feature
- features/install_uninstall.feature
- features/livepatch.feature
- features/logs.feature
- features/timer.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
- features/unattached_commands.feature
- features/unattached_status.feature
- tools/run-integration-tests.py
- tox.ini
- uaclient/upgrade_lts_contract.py
This PR solves all of our problems because we want to build and test on mantic now, and want to include as many lunar tests as possible to the CI.
no-gh no-lp no-jira
> Mantic testing step one

- dev-docs/devdocs_styleguide.md
- dev-docs/howtoguides/release_a_new_version.md
Please check if everything makes sense - those are short explanations based on what we had discussed about the docs maintenance.
> dev-docs: document the process to update and release documentation (SC-1580)

- docs/explanations/status_columns.md
- docs/howtoguides/enable_livepatch.md
- docs/tutorials/basic_commands.md
```
Update command output for pro status in the tutorial.
Also update pro status output (and related context for
two additional pages).
```
Fixes: #2627
> Update command output

- debian/changelog
- features/attached_enable.feature
- features/ubuntu_pro.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
- systemd/ua-auto-attach.service
- systemd/ua-reboot-cmds.service
- systemd/ua-timer.service
- systemd/ua-timer.timer
- systemd/ubuntu-advantage.service
- tools/run-integration-tests.py
- uaclient/apt.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_cis.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/security.py
- uaclient/status.py
- uaclient/system.py
- uaclient/tests/test_system.py
These are all the changelog entries and other fixes that went into the release branch as part of the 28 release process that need to be brought into main (including the minor test fixes still in a PR in #2648)
> Bring 28.1 commits to main

- docs/references/api.rst
> docs: api: u.apt_news.current_news.v1

- features/attached_status.feature
- features/steps/ubuntu_advantage_tools.py
- features/util.py
- tools/build.py
This PR solves all of our problems because it addresses specific test failures we saw on Jenkins.
In the end, it adds functionality by letting us choose architectures when running our build scripts.
- Run CI and see the updated tests pass
- create some other-arch-chroot for ua, and build the package there (:
- Jenkins will be able to build other arches using InstallationSource.LOCAL
> Few fixes and tweaks to tests

- features/fix.feature
This PR solves all of our problems because, well, it fixes CI.
Run the modified test and see it passing
> tests: add missing related usn to Fix behave test

- features/anbox.feature
- help_data.yaml
- uaclient/entitlements/base.py
- uaclient/entitlements/tests/test_base.py
- uaclient/messages.py
- uaclient/snap.py
We are updating some items around enabling Anbox based on the feedback received by the Anbox team.
We updating some messages we show during enabling the service, adding a help text and allowing LXD to installed from a given channel
> Anbox updates

- help_data.yaml
Update help text for the Anbox service
Test if `pro help anbox-cloud` is correctly displaying the text
> anbox: update help text

- features/anbox.feature
- features/unattached_commands.feature
- tools/ua.bash
- uaclient/messages.py
Adds anbox-cloud to bash completion and fixes messaging phrasing.
Check integration test still passes.
> Anbox fixups

- features/fix.feature
- features/unattached_status.feature
fips got added to jammy on staging only
a new related usn got added to one we test
This fixes the tests that were failing because of the above
Let CI pass
> Test fixups

- debian/changelog
- preferences.d/ubuntu-pro-esm-apps
- preferences.d/ubuntu-pro-esm-infra
This addresses some of @sergiodj 's comments and nitpicks while reviewing our beloved release
> First round of reviews for release 29

- docs/howtoguides/enable_index.rst
- docs/howtoguides/enable_landscape.rst
- docs/index.rst
> pro enable landscape docs

- docs/howtoguides/configure_index.rst
- docs/howtoguides/configure_proxies.md
- docs/howtoguides/configure_tls_in_tls_proxy.rst
- docs/howtoguides/get_token_and_attach.md
> docs for tls in tls

- tools/create-lp-release-branches.sh
This was actually feedback from version 28 that I forgot to implement until now.
> tools: better backport changelog message

- uaclient/exceptions.py
- uaclient/files/files.py
- uaclient/messages.py
- uaclient/tests/test_config.py
This removes several strings that aren't actually used anywhere.
CI should pass
> i18n prep: remove unused messages (SC-1601)

- apport/source_ubuntu-advantage-tools.py
- features/attached_commands.feature
- features/collect_logs.feature
- features/daemon.feature
- features/schemas/ua_status.json
- lib/daemon.py
- lib/migrate_user_config.py
- lib/timer.py
- uaclient-devel.conf
- uaclient/actions.py
- uaclient/config.py
- uaclient/conftest.py
- uaclient/defaults.py
- uaclient/log.py
- uaclient/tests/test_cli_collect_logs.py
- uaclient/tests/test_config.py
- ubuntu-advantage.1
We are replacing the 2 extra log files i.e. daemon and timer log files with systemd 
logging since they are called via systemd services.
> logging_revamp: add journald logging for daemon and timer (SC-1595)

- features/api.feature
- uaclient/api/u/pro/status/enabled_services/v1.py
This moves an import down into the function where it is used to ~~fix~~ workaround a circular import problem
The new test should pass
> Fix enabled services circular import

- features/attached_enable.feature
- features/cloud.py
- features/enable_fips_vm.feature
- tools/run-integration-tests.py
Tweaks to the integration tests to validate the release
> Integration tests adjustments for 29.3

- features/api_packages.feature
An update of libcurl4 was presumably pushed to esm repos in bionic.
Discovered in https://github.com/canonical/ubuntu-pro-client/actions/runs/6156502630/job/16705466921?pr=2732.
tox -e behave-lxd-20.04 -vvv -- features/api_packages.feature:35
> tests: fix integration test in api_packages

- docs/index.rst
Small change in the phrasing in the main page, suggested by @vorlonofportland while describing Pro in the SRU documentation.
> Adjust product description

- features/anbox.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/cloud_pro_clone.feature
- features/enable_fips_cloud.feature
- features/enable_fips_container.feature
- features/enable_fips_pro.feature
- features/enable_fips_vm.feature
- features/fix.feature
- features/landscape.feature
- features/realtime_kernel.feature
- features/ubuntu_pro_fips.feature
- features/ubuntu_upgrade.feature
- uaclient/apt.py
- uaclient/entitlements/base.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_cis.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/messages/__init__.py
- uaclient/snap.py
```
feat(entitlements): update specific sources list on service enable
Repo services will apt-update while enabling only its associated ppa source list,
and `/etc/apt/sources.list` if require packages are needed to be installed.
The Snap service only apt-updates `/etc/apt/sources.list`.
This change improves boot time on Ubuntu Pro instances by 10s-15s depending
on the series.
Fixes: #1482
Fixes: #1311
```
[SC-186](https://warthogs.atlassian.net/browse/SC-186)
[SF: #00313994](https://bootstack.canonical.com/cases/00313994)
Attach time comparing tip-main vs this PR with a token with esm-infra and esm-apps enabled by default is improved from 10s to 15s depending on the Ubuntu series:
- [n/a] Changes here need to be documented, and this was done in: 
[SC-186]: …
> feat(entitlements): update specific sources list on service enable (SC-186)

- features/apt_messages.feature
This PR solves all of our problems because the package(s) we used to have in place to count standard security LTS updates received esm updates, and now we need a new subject package.
Run the modified integration test.
> tests: change target package in JSON hook test

- features/anbox.feature
After the message refactor, we are now updating the Anbox test to reflect those changes
> tests: update anbox messages

- features/airgapped.feature
- features/attached_enable.feature
- features/ubuntu_pro.feature
- features/ubuntu_pro_fips.feature
- preferences.d/ubuntu-pro-esm-apps
- preferences.d/ubuntu-pro-esm-infra
- setup.py
Bring the "reverted" changes from release 29.4
> Bring reverted changes

- features/attached_commands.feature
- features/unattached_status.feature
Fix tests for fips-preview on the help and status --simulate-with-token commands for Focal and Jammy
Verify that the tests are now working as expected
> fips-preview: fix remaining tests

- features/cloud.py
- integration-requirements.txt
There are instances where all AWS PRO FIPS marketplace images are deprecated for a given series and pycloudlib was not able to locate them.
Upgrade pycloudlib and instruct it to include deprecated in that lookup.
https://warthogs.atlassian.net/browse/CPC-3030
https://github.com/canonical/pycloudlib/issues/312
Covered by CI.
> test(aws): include deprecated aws pro fips images (CPC-3030)

- features/attached_commands.feature
- features/cloud.py
- features/unattached_status.feature
- integration-requirements.txt
This is picking test-change commits from main which we will need for the verification.
Those don't need to go to LP... yet. If commits are needed as part of the review, we include the testing changes and show that it is only tests.
> Bring test changes from main to release

- CONTRIBUTING.md
- dev-docs/explanations/string_changes_policy.md
- dev-docs/explanations/translations.md
- dev-docs/howtoguides/spellcheck.md
This adds explanations around our new support for translations in pro client.
> Strings translations policy

- docs/explanations.rst
- docs/explanations/purging_services.md
- docs/howtoguides/enable_anbox.md
- docs/howtoguides/enable_cc.md
- docs/howtoguides/enable_cis.md
- docs/howtoguides/enable_esm_infra.md
- docs/howtoguides/enable_fips.md
This is the documentation for `pro disable <service> --purge`.
> Add docs explaining disable --purge

- debian/changelog
- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/attached_commands.feature
- features/unattached_commands.feature
- uaclient/apt.py
- uaclient/cli/tests/test_cli.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/files/files.py
- uaclient/messages/__init__.py
- uaclient/system.py
- uaclient/tests/test_apt.py
- uaclient/tests/test_system.py
This commit addresses review comments made in Launchpad regarding release 30
> Release 30 review

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/i18n.feature
- uaclient/messages/__init__.py
- uaclient/status.py
This translates the yes/no in unattached status
run the edited test
> status: translate unattached yes/no available column

- debian/changelog
> changelog: change development release to noble

- .github/actions/create-issue/action.yaml
- .github/actions/create-issue/index.js
- .github/actions/create-issue/package-lock.json
- .github/actions/create-issue/package.json
- .github/workflows/merge-actions.yaml
> github: add CI job to create issues on merge

- .github/actions/create-issue/action.yaml
- .github/actions/create-issue/index.js
- .github/actions/create-issue/package.json
> fix the thing

- features/_version.feature
This PR solves all of our problems because I can prove we create issues when merging PRs.
Merge the PR and see the magic happen
> add dummy message for the lightning talk example

- features/unattached_commands.feature
- tools/ua.bash
The main thing here is adding api endpoint autocomplete - the rest are very small refactors that I think are slight improvements
Test some autocomplete scenarios in bash
- `pro api `-tab
- `pro `-tab
- `pro enable `-tab
- `pro enable ros-updates r`-tab
> cli: small improvments to bash autocomplete

- features/reboot_cmds.feature
We want CI to be green
The test relies on downgrading the version of strongswan in focal. It was previously set to downgrade to the version in focal-updates, but that changed. After this commit, the test downgrades to the version in focal, which will not change.
Fixes: #2863
CI should pass
> tests: fix reboot_cmds.feature

- debian/changelog
- uaclient/version.py
better late than never :upside_down_face:
> bring release 30.1 to main

- dev-docs/howtoguides/troubleshoot_apt_news_security_confinement.md
This complements https://github.com/canonical/ubuntu-pro-client/pull/2794 with a documentation update.
> Docs apparmor update

- lib/reboot_cmds.py
- uaclient/api/tests/test_api_u_pro_attach_auto_full_auto_attach_v1.py
- uaclient/api/u/pro/attach/auto/full_auto_attach/v1.py
- uaclient/cli/__init__.py
- uaclient/daemon/poll_for_pro_license.py
- uaclient/daemon/retry_auto_attach.py
- uaclient/daemon/tests/test_poll_for_pro_license.py
- uaclient/livepatch.py
- uaclient/lock.py
- uaclient/tests/test_lock.py
- uaclient/tests/test_reboot_cmds.py
This addresses comments in this review: https://github.com/canonical/ubuntu-pro-client/pull/2913#pullrequestreview-1844021599
> Release 31 fixes

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/collect_logs.feature
- features/logs.feature
- uaclient/cli/__init__.py
- uaclient/cli/tests/test_cli_collect_logs.py
- uaclient/messages/__init__.py
- ubuntu-advantage.1
Some files in the code still refer to `ua`, this changes them to refer to `pro` instead.
Fix for Issue [#2849].
All tests should behave as earlier.
> Updated references to ua_logs

- docs/howtoguides/how_to_collect_logs.md
Updates the collect logs documentation. Changes `ua` reference to `pro`.
Fix for [#2849]
No changes
> Changing ua_logs to pro_logs

- dev-docs/tutorials/getting-started.md
When updating boot parameters to run xenial builds, an extra boot parameter is required.
> Boot parameter update

- .github/workflows/ci-integration.yaml
See inline comment
CI should at least reach the behave tests
> Disable noble builds for now

- docs/explanations/motd_messages.md
> docs: fix file name on the disable MOTD explanation

- features/attach_validtoken.feature
- features/attached_enable.feature
Adds an integration that attaches on a lxd-vm and asserts that esm-infra, esm-apps, and livepatch are all enabled by default.
> tests: Added lxd vm test for attach validtoken

- features/docker.feature
Remove the new ubuntu-pro-client package on the docker build recipe.
Run the docker tests with the proposed package
> tests: fix docker tests

- features/attached_enable.feature
- features/cloud_pro_clone.feature
- features/steps/misc.py
Fix some broken integration tests
Verify that possible CI errors now are due to flaky tests
> Fix some integration tests

- features/fix.feature
This PR solves all of our problems because Bionix never got released
trigger the tests to make sure they run?
> tests: fix typo on fix tests release selector

- features/api_fix_plan.feature
This PR solves all of our problems because we want CI to be green.
Fixes: #3016
Run modified test.
> tests: fix output of fix test on Bionic

- features/attach_validtoken.feature
- features/proxy_config.feature
- features/realtime_kernel.feature
- features/security_status.feature
These are fixes from the jenkins triage I just did.
Run the modified tests.
> Jenkins triage fixes

- features/attached_status.feature
This fixes a couple tests after this change on the backend.
CI should be greener
> tests: cloud pro entitled to landscape now

- uaclient/api/u/pro/detach/v1.py
Something we missed while merging related things
CI for api detach should pass
> detach: fix disable call after refactor

- debian/apparmor/ubuntu_pro_apt_news.jinja2
- debian/apparmor/ubuntu_pro_esm_cache.jinja2
- debian/clean
- debian/rules
- features/environment.py
- features/fix.feature
- features/logs.feature
- systemd/esm-cache.service
- uaclient/actions.py
- uaclient/defaults.py
I pinged #security and they added some comments already which I responded to.
> ua security isolation for the esm-cache service

- features/api_full_token_attach.feature
- features/attach_validtoken.feature
- features/config/protest.yaml
- features/schemas/attach.json
- features/steps/attach.py
- uaclient/actions.py
- uaclient/api/api.py
- uaclient/api/tests/test_api_u_pro_attach_full_token_attach.py
- uaclient/api/u/pro/attach/token/full_token_attach/v1.py
- uaclient/cli/cli_api.py
- uaclient/cli/tests/test_cli_attach.py
- uaclient/contract.py
- uaclient/tests/test_actions.py
Add API endpoint for the attach operation. Note that there are still some other additions needed to this work:
* use the endpoint on the CLI
* Guarantee that the token can be passed through cat (i.e. `cat token.json | pro api u.pro.attach.token.full_token_attach.v1 --data`)
> Add API endpoint for the attach operation

- features/environment.py
This PR solves all of our problems because it moves the file that can contain secrets out of the git repo entirely. This means it is less likely to accidentally commit the secrets.
Ensure the config fields are picked up from the new location `~/.config/protest.yaml`
> tests: move config file out of repo

- test-requirements.txt
tiobe needs pylint installed. Our tiobe jenkins job does  `pip install -r requirements.txt -r test-requirements.txt` and runs on main.
> include pylint in test-requirements.txt for tiobe jenkins job

- features/environment.py
Fixes: #3071
I temporarily applied this diff https://pastebin.canonical.com/p/68W67tpDYj/
That diff _inconsistently_ causes xenial tests to cause apparmor denials.
Then I ran the following:
```
tox run -e behave -- --logging-level warning --no-junit --no-color features/_version.feature -D check_version=1:1+devel -D releases=xenial,jammy -D machine_types=lxd-container,lxd-vm
```
It might take a couple tries because it doesn't consistently trigger the apparmor denials, but eventually you can get a run where the xenial lxd-container test fails and displays apparmor DENIED logs from your host that are specific to that xenial test container. And you can get a xenial lxd-vm test fail with DENIED logs from the xenial vm. The jammy tests will always pass even if the xenial tests fail during the …
> tests: more specific apparmor check

- requirements.tiobe.txt
- test-requirements.txt
tiobe has certain requirements that don't make sense in our other dependency lists, so it now has its own file.
This will be coordinated with a PR for the tiobe jenkins job here https://github.com/canonical/server-jenkins-jobs/pull/314
> move tiobe requirements into their own file

- debian/ubuntu-pro-client.postinst
- lib/postinst-migrations.sh
Addresses https://github.com/canonical/ubuntu-pro-client/pull/3052#discussion_r1579420613 and https://github.com/canonical/ubuntu-pro-client/pull/3052#discussion_r1579423005
> release 32 feedback postinst fixes

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/fix.feature
- uaclient/messages/__init__.py
This PR solves all of our problems because this updates the output for the CVE dry run to suggest the recommended way to attach a pro subscription.
Fixes: #3040
> Update command output for pro fix dry-run

- features/steps/airgap.py
This commit uses regex instead of the echo command to extract service tokens to prevent the leak into stdout
> test: Fix credential leak on airgapped feature

- features/environment.py
This fixes the error occurring in features/cloud_pro_clone.feature:54 and discussed here: https://github.com/canonical/ubuntu-pro-client/pull/3096#issuecomment-2091188582
features/cloud_pro_clone.feature:54 should log a warning about skipping the apparmor check after the snapshot check but continue succeed
> tests: skip apparmor log check if there is an SSH error

- debian/apparmor/ubuntu_pro_apt_news.jinja2
- debian/apparmor/ubuntu_pro_esm_cache.jinja2
- features/apt_messages.feature
Further automated testing showed a few more apparmor rules to be needed.
Fixes: #3079
Run automated tests here in GH, and the ones from jenkins.
> More apparmor fixes

- debian/changelog
Just some aesthetic fixes for the v32 changelog.
> changelog: formatting and standardizing adjustments

- features/enable_fips_cloud.feature
Update messages to check when enabling FIPS in the clouds
Check that the modified tests are passing now
> Fix FIPS cloud messages on tests

- features/api_fix_execute.feature
- features/api_fix_plan.feature
- features/attached_commands.feature
- features/daemon.feature
- features/fix.feature
- features/install_uninstall.feature
- features/security_status.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
- features/unattached_commands.feature
Next batch of test fixes to validate the 32.2 release
> More fixes to 32.2 tests

- features/attached_status.feature
- features/cloud_pro_clone.feature
- features/landscape.feature
- features/proxy_config.feature
- features/retry_auto_attach.feature
- uaclient/cli/__init__.py
Some tests fixes for the upcoming release
Verify that the modified tests are now passing
> Some test fixes for v33

- .github/workflows/ci-integration.yaml
- features/attached_status.feature
- features/ubuntu_pro.feature
- features/unattached_status.feature
Add more test fixed for v33
Guarantee that the modified tests are working now
> Test fixes v33

- debian/changelog
- uaclient/version.py
Add devel version to our changelog
Guarantee that the package builds with the specified version
> changelog open to development

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/subscription_attach_restrictions.feature
- lib/timer.py
- lib/upgrade_lts_contract.py
- uaclient/actions.py
- uaclient/api/u/pro/detach/v1.py
- uaclient/defaults.py
- uaclient/exceptions.py
- uaclient/files/notices.py
- uaclient/files/state_files.py
- uaclient/messages/__init__.py
- uaclient/system.py
- uaclient/tests/test_ua_timer.py
- uaclient/timer/tests/test_update_contract_info.py
- uaclient/timer/update_contract_info.py
This PR introduces a change to the Ubuntu Pro Client to enforce contract-specific restrictions on Ubuntu releases for Pro attachment as per the new `onlySeries` field in the contracts which specify the LTS release a contract is tied to.
> One time pro subscription attached to a specific release

- uaclient/api/tests/test_api_u_pro_services_enable_v1.py
- uaclient/api/u/pro/services/enable/v1.py
- uaclient/entitlements/realtime.py
This PR solves all of our problems because if fixes the unnecessary variant auto-selection prompts in situations where they weren't helpful
```
tox run -e behave features/realtime_kernel.feature:400 features/realtime_kernel.feature:44
```
> Non applicable no variant prompt

- .github/actions/release-checklist/index.js
> DO NOT MERGE: testing release checklist

- debian/changelog
- uaclient/version.py
Changelog and version bump for release 33
> New upstream release: 33

- dev-docs/howtoguides/release_a_new_version.md
This adds the announcement post to our post-release actions.
I can be the one who actually writes/posts these, but we should include it in our process regardless.
Read the new item and ensure it has all necessary details.
---
> release process: add announcement post to post-release actions

- features/ubuntu_pro.feature
Addressing this comment https://github.com/canonical/ubuntu-pro-client/pull/3159#discussion_r1643402971
---
> tests: use more specific journalctl command

- features/environment.py
- uaclient/actions.py
- uaclient/api/u/pro/security/fix/_common/__init__.py
- uaclient/cli/tests/test_cli_fix.py
- uaclient/entitlements/__init__.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/realtime.py
- uaclient/entitlements/ros.py
- uaclient/files/files.py
- uaclient/files/machine_token.py
- uaclient/messages/__init__.py
- uaclient/system.py
- uaclient/util.py
This PR doesn't even solve all of our problems. I was just bored and decided to remove noqas where it was easy to.
tox + behave. Nothing should change
---
> chore: get rid of some unneeded noqas in the code

- debian/changelog
- features/i18n.feature
- uaclient/snap.py
- uaclient/system.py
- uaclient/tests/test_system.py
- uaclient/version.py
Fix the problems related to UTF-8 found as part of the v33 release.
---
> New release: 33.1

- debian/changelog
Add changelog entry for release 33.2
> new release 33.2

- uaclient/version.py
> bump version to 33.2

- features/util.py
We are now logging the error output of sbuild in case it fails, instead of just alerting that the command failed
Make a modification that will break sbuild and check we are now logging the full output of the command
---
> tests: log sbuild error

- features/attached_enable.feature
- features/proxy_config.feature
- features/schemas/ua_operation.json
This PR fixes small issues in vm tests that were missed during development of v33.
```
tox run -e behave -- features/proxy_config.feature:1173 features/attached_enable.feature:666 features/attached_enable.feature:706 -D install_from=proposed
```
---
> tests: minor fixups

- docs/howtoguides/enable_realtime_kernel.rst
This PR solves all of our problems because...There was an accidental indent on the page that
made the first paragraph render incorrectly.
> [docs] Fix weird indentation/formatting

- docs/references/api_endpoints.txt
> apidocs: add network requirements for each endpoint

- custom_wordlist.txt
- docs/explanations/data_collection.rst
accidentally merged with these errors
> fix spelling errors

- docs/howtoguides/create_pro_golden_image.rst
- docs/links.txt
Updates the golden image pro document with links to each cloud guide and fixes: #2822
> docs: Update Pro custom cloud image doc

- custom_wordlist.txt
- docs/explanations.rst
- docs/explanations/pro_token_and_machine_usage.rst
- docs/links.txt
This PR adds the documentation for frequently asked questions regarding the Pro subscription and the usage of Pro tokens. It lists out information regarding machine limits for a pro subscription and how tokens are counted.
> docs: Token usage and machine limits

- docs/explanations/cves_and_usns_explained.rst
- docs/explanations/what_are_the_timer_jobs.rst
This PR was to review and update docs for any missing internal references. So far everything looks great, I could only find one instance on review which could use an internal reference to a connected page.
Also includes a very tiny bug fix
> docs: minor updates

- features/airgapped.feature
- features/apt_messages.feature
- features/security_status.feature
- features/steps/airgap.py
- features/steps/ubuntu_advantage_tools.py
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
Fixes minor bugs in the lxd-container tests
---
> tests: minor fixes to lxd-container test bugs

- uaclient/tests/test_upgrade_lts_contract.py
- uaclient/upgrade_lts_contract.py
reopened #3242 which was already approved
> tests: fix upgrade_lts_contract tests

- features/enable_fips_vm.feature
- features/realtime_kernel.feature
- uaclient/entitlements/fips.py
- uaclient/entitlements/realtime.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_realtime.py
- uaclient/messages/__init__.py
reopening #3187 which was already approved
> Kernel non generic warning

- debian/changelog
- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- uaclient/version.py
> release 34 changelog

- debian/changelog
- features/util.py
- ubuntu-advantage.1
This addresses most of @sergiodj's feedback on #3247 
Check for consistent styling in the manpage.
Read the changelog to ensure style of entries is consistent.
Verify logging level change is accurate.
---
> V34 review feedback

- debian/changelog
- uaclient/version.py
This lets our daily PPA continue working
---
> open v35 for dev

- features/proxy_config.feature
We are better consolidating our proxy tests by removing whole scenarios that only test setting the proxy by writing directly in the user-config.json file while also removing some redundant scenarios on the proxy tests
Verify that the modified proxy tests are still working and that we are not loosing any coverage regarding the tests I removed
---
> tests: consolidate proxy tests

- debian/changelog
Updating the changelog for last minute v34 fixes
> changelog: v34 last minute inclusions

- features/api/api.feature
- features/api/token_info.feature
- features/cli/status.feature
- features/environment.py
- features/schemas/api_token_info_response.json
- features/util.py
- uaclient/api/api.py
- uaclient/api/tests/test_api_u_pro_token_info_v1.py
- uaclient/api/u/pro/token_info/v1.py
- uaclient/cli/tests/test_cli_status.py
- uaclient/exceptions.py
- uaclient/messages/__init__.py
- uaclient/status.py
- uaclient/tests/test_contract.py
Adds the token simulation endpoint:
`u.pro.token_info.v1`
---
> api: u.pro.token_info.v1

- features/ubuntu_pro.feature
- lib/auto_attach.py
- uaclient/clouds/aws.py
- uaclient/clouds/tests/test_aws.py
- uaclient/tests/test_lib_auto_attach.py
See CPC0069.
```
feat(auto-attach): skip if no codes on aws (CPC-4926)
On aws, ua-auto-attach.service will only try to auto-attach if the instance identity document[0] contains any billing product or marketplace product code.
Refs:
- [0] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html#verify-iid
- [1] CPC-4926
- [2] CPC0069
Signed-off-by: Alberto Contreras <alberto.contreras@canonical.com>
```
```
tox -e behave -- features/ubuntu_pro.feature:191 -D releases=jammy -D machine_types=aws.pro
```
---
> feat(auto-attach): skip if no codes on aws (CPC-4926)

- uaclient/apt.py
> Update apt error logging

- features/landscape.feature
- uaclient/entitlements/landscape.py
- uaclient/messages/__init__.py
- uaclient/messages/urls.py
> Update landscape inapplicability message

- docs/explanations/how_to_interpret_the_security_status_command.rst
Documentation update for the PR #3297 
---
> Update security status enum documentation

- uaclient/api/u/pro/config/v1.py
- uaclient/clouds/lxd.py
- uaclient/http/__init__.py
Address the review feedback from @bryceharrington 
Check that no integration tests are now failing due to this change
---
> Review 35 feedback

- docs/explanations.rst
- docs/howtoguides.rst
- docs/howtoguides/attach_index.rst
- docs/howtoguides/configure_index.rst
- docs/howtoguides/enable_index.rst
- docs/references.rst
- docs/tutorials.rst
This PR solves all of our problems because...I did a review of the previous landing page
work with Daniele and got some final feedback from him. This PR contains fixes for his
feedback.
---
> Final landing page polishing

- .github/actions/create-issue/package-lock.json
See #3381.
Let CI run. Not that it will make that big difference as this will only impact the `Breaks:` behavior. 
---
> build(deps): bump undici in /.github/actions/create-issue

- docs/explanations/using_pro_offline.rst
This PR rewords the Landscape section to include links to Landscape's airgapped documentation.
---
> docs: Update links and wording for Landscape airgapped docs

- .github/actions/create-issue/package-lock.json
- .github/actions/release-checklist/package-lock.json
This PR solves all of our problems because dependabot says so.
This always remind me to create a proper action for the create-issue thing...
> Dependabot changes from past PRs

- debian/changelog
- uaclient/version.py
Changelog and version change.
---
> Release 36
