- features/attached_commands.feature
- features/proxy_config.feature
- features/steps/steps.py
- lib/timer.py
- uaclient-devel.conf
- uaclient.conf
- uaclient/cli.py
- uaclient/config.py
- uaclient/tests/test_cli_config_set.py
- uaclient/tests/test_cli_config_show.py
- uaclient/tests/test_cli_config_unset.py
- uaclient/tests/test_cli_refresh.py
- uaclient/tests/test_config.py
- uaclient/tests/test_ua_timer.py
User can now set the desired run_interval for jobs in the `uaclient.conf` file, as in:
```
ua_config:
<job_name>_timer: <run_interval_value>
```
It has the config for the messaging and status jobs.
> Allow timed jobs' intervals to be overriden by config (SC-308)

- features/_version.feature
- features/attach_invalidtoken.feature
- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/install_uninstall.feature
- features/proxy_config.feature
- features/staging_commands.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
- features/unattached_commands.feature
- features/unattached_status.feature
- tox.ini
Current behave tests can be decorated to run on top of specific platforms. If no platform is specified, lxd.container is selected by default. However, documentation points to lxd.container as a machine type and it is there for some tests, but it is the same as defining no machine_type.
Besides being ambiguous and not consistent, this behavior can be misleading: by looking at the patterns, one can think that tests without a machine_type decorator are running on all platforms, which is not true.
This PR is a refactor to explicitly tell which tests should be executed in containers.
> tests: make lxd.container machine type explicit (SC-310)

- features/environment.py
- integration-requirements.txt
tests: allow snapshot images to be ephemeral
We have recently allowed pycloudlib to make snapshot from ephemeral instances. We are nos updating uaclient
to also use ephemeral instances for the base images that will be snapshoted when running the tests
Run any integration test with UACLIENT_BEHAVE_SNAPSHOT_STRATEGY=1 and verify that the base images are ephemeral
> tests: allow snapshot images to be ephemeral

- features/attached_commands.feature
- features/steps/steps.py
- lib/timer.py
- uaclient/config.py
- uaclient/tests/test_config.py
If there is no config entry in `ua_config` for a timer or if it is set to null, just use the default values.
> config: ignore null / absent configuration for the timers (SC-369)

- help_data.yaml
- uaclient/cli.py
- uaclient/security.py
- uaclient/tests/test_security.py
- uaclient/tests/test_util.py
- uaclient/util.py
When running an ua fix command, we tell at the end if the issue is resolved or not. In that message, we have some unicode characters that are displayed. If the user is running on a system that doesn't support those characters, the printing that last message will fail. We are now redacting the code to not fail under this condition.
Fixes: #1463
Run the new unittest provided in the system.
Another way to test is to launch an instance and change the locale to `ANSI_X3.4-1968`. Run an ua fix command and verify that it doesn't break on the message
> fix: do not fail if non-utf8 locale is being used (SC-368)

- features/environment.py
With the random suffix, there will be no conflicts even when running many tests exactly at the same time
Trigger two or more integration test runs on the same cloud, at the same time. There should be no naming conflict.
> Enable running many tests in parallel in clouds (SC-366)

- features/environment.py
- integration-requirements.txt
This reverts commit ec7a0e65e2c0e014932ecb7ec95ab5be41343bca.
lxd xenial tests are now stuck because of this commit. We are reverting it now until we can figure out why this is happening
> Revert "tests: allow snapshot images to be ephemeral"

- features/environment.py
- features/steps/steps.py
The main thing here is fixing a bug I introduced in #1751. I had just used the instance name instead of calling `cloud_manager.get_instance_id` which returns the instance id for some platforms. We now are correctly using the result of `get_instance_id`.
I also changed some parameter names to be called `id` instead of `name` to match the name of `get_instance_id`
```
tests: use correct instance ids for snapshots
```
Run a test on each platform with `UACLIENT_BEHAVE_SNAPSHOT_STRATEGY=1`
> tests: use correct instance ids for snapshots

- .gitignore
- tools/run-integration-tests.py
- tools/ua-test-credentials.example.yaml
A CLI script to run the integration tests, organizing the credentials, storing the results (`stdin` and `stderr`).
If testing from Proposed, check that all tests pass and create a tarball with the results.
There is an example file with the yaml structure.
> tests: add script to run integration tests (SC-197)

- tools/run-integration-tests.py
Fix the command line for running the `@wip` tests in the test script.
Pass `-w` to `tools/run-integration-tests.py` and verify it does run the tests.
> tests: fix integration test script wip scenarios

- features/attach_validtoken.feature
- features/attached_commands.feature
- uaclient/jobs/gcp_auto_attach.py
- uaclient/jobs/tests/test_gcp_auto_attach.py
jobs: do not run gcp job on non-gcp instances
When running the gcp_auto_attach job on an instance we can detect that the running instance is not a GCP one. If that happens, we will not update the gcp job time interval to 0. This will guarantee that this job will not run on the machine anymore.
> jobs: do not run gcp job on non-gcp instances (SC-363)

- features/attach_validtoken.feature
- features/enable_fips_cloud.feature
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
fips: block enabling on focal clouds
There is no cloud optimized FIPS kernel for focal clouds yet.
Because of that, we are momentarily blocking enabling FIPS on focal
clouds.
Run the modified integration tests for fips on focal clouds
> fips: block enabling on focal clouds (SC-385)

- features/proxy_config.feature
- uaclient/tests/test_util.py
- uaclient/util.py
proxy: better handle port errors
We are showing a better error message when an user tries to set up a proxy wih an invalid port
> proxy: better handle port errors (SC-387)

- README.md
- features/attach_validtoken.feature
- features/proxy_config.feature
- lib/timer.py
- uaclient-devel.conf
- uaclient.conf
- uaclient/tests/test_config.py
Metering should be disabled,
GCP auto attach should be 5 minutes.
(this is the first PR where I checked all 3 of those I guess hahaha)
> timer: adjust interval values for gcp_auto_attach and metering (SC-390)

- sru/release-27.3/gcp_auto_attach_test.sh
- uaclient/clouds/gcp.py
- uaclient/jobs/gcp_auto_attach.py
- uaclient/jobs/tests/test_gcp_auto_attach.py
Only try to auto attach if the PRO license is detected in the instance metadata.
> timer: check for GCP PRO License before trying to auto attach (SC-389)

- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
fips: fix focal cloud block on PRO instances
On PRO instances, the contract does return the cloud specific fips metadata to be installed. However, this package doesn't exist
yet and the check we are performing for the PRO instances is not taking that into consideration. We are updating the logic to properly handle the PRO instances
1. Launch a focal PRO machine with the proposed changes
2. Try to enable fips on it and verify that it outputting the correct message stating why fips can't be enabled
> fips: fix focal cloud block on PRO instances

- features/attached_commands.feature
- lib/patch_status_json.py
- lib/reboot_cmds.py
- lib/timer.py
- lib/upgrade_lts_contract.py
- systemd/ua-timer.service
- uaclient-devel.conf
- uaclient.conf
- uaclient/cli.py
- uaclient/config.py
- uaclient/conftest.py
- uaclient/defaults.py
- uaclient/jobs/gcp_auto_attach.py
- uaclient/jobs/metering.py
- uaclient/jobs/tests/test_gcp_auto_attach.py
- uaclient/jobs/update_messaging.py
- uaclient/jobs/update_state.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_config.py
- uaclient/tests/test_ua_timer.py
- uaclient/util.py
- ubuntu-advantage.1
This PR changes the way we set up the logging, so we have better control of our handlers, and uses that change to make the timer and the timer jobs run without logging everything they see.
The `setup_logging` function now accepts a `logger` parameter, so we can configure any logger instance, and not just the root logger. It gives us control to configure module based loggers.
Also, it will wipe out existing handlers, and add the uaclient handlers (for console and log file), ensuring we have a single instance of each handler every time the loggers are configured / reconfigured. For this to work, it's important that setup_logging is inside our main entrypoints (CLI and the `lib/` scripts). When importing anything from our modules, the root logger will not be changed by default. …
> Change `setup_logging` and the timer logger (SC-370)

- debian/ubuntu-advantage-tools.postinst
postinst: remove old ua-messaging.timer services
The postrm script will mask the service `ua-messaging.timer` since it will no longer be delivered by the package. Although this operation will indeed disable the service, we can still see it when running `systemctl list-timers --all`. The reason for that is because the mask operation creates a symlink on `/etc/systemd/system/timer.target.wants/` for this service that points to `/lib/systemd/system/ua-messaging.timer` . We cannot unmask the service, since the unit will not be there anymore, so one way to avoid this service to appear when running `list-timers` is by deleting this symlink and perfoming a `systemctl daemon-reload` operation.
1. Launch a xenial container
2. Upgrade UA to the daily version
3. Verify that `systemctl list-timers …
> postinst: remove old ua-messaging.timer services (SC-409)

- systemd/ua-timer.timer
This is something I meant to bring more attention to during the gcp timer PR but forgot. I had set the ua-timer frequency much lower, but we may want it more like this to make adding the metering job easier in the future. Also should we change it back to using OnCalendar or no?
```
timer: change frequency to 2 hours
```
> timer: change frequency to 2 hours

- features/attach_validtoken.feature
- features/enable_fips_cloud.feature
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
fips: allow enabling fips on GCP bionic instances
GCP has now a FIPS optimized kernel on bionic. We are now updating
the code to allow enabling the service on those types of instances
PS: FIPS Updates test is not passing at the moment because of openssh package releated issues that we still need to debug.
> fips: allow enabling fips on GCP bionic instances

- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/ubuntu_pro.feature
- features/ubuntu_upgrade_unattached.feature
- features/unattached_status.feature
- uaclient/entitlements/cc.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_disable.py
- uaclient/tests/test_cli_enable.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_config.py
This PR makes cc-eal non-beta.
- Will be listed without the --all flag
- Can be enabled without the --beta flag
> cc-eal: remove beta flag

- features/unattached_commands.feature
- uaclient/cli.py
- uaclient/security.py
- uaclient/tests/test_cli_fix.py
- uaclient/tests/test_security.py
fix: update return code
Currently, ua fix will always return 0 no matter what happens during the execution of the command. We are updating the command to only return 0 if the system ends up in a non-vulnerable state. Meaning that either the CVE/USN does not affect the system, the packages required by the fix are already installed or that we have successfully installed all of the packages necessary for the fix.
Run the modified integration/unit tests
> fix: update return code

- .github/PULL_REQUEST_TEMPLATE.md
- features/environment.py
- features/util.py
- tools/build.py
- tools/build.sh
Not urgent at all.
This is a build caching idea I've been messing with a bit while testing PRs and has worked pretty well. Feel free to say its a bad idea or point out flaws :). It has the potential to make iterating on an integration test less cumbersome.
Also includes a little build script to just call the build function we have for our integration tests.
```
test: automatically cache debs based on git repo state
```
Try out `./tools/build.sh`
make changes to features and build again
make changes to uaclient code and build again
Ensure integration tests still work
> Deb build cache for tests (SC-449)

- debian/changelog
- debian/ubuntu-advantage-tools.postinst
- sru/release-27.3/ua-messaging-disabled.sh
postinst: make check for gce instance more robust
Currently, we have a check on postinst to verify if we are on a gce cloud. We only verify if the gce string is in the cloud-id of the instance. Therefore, we are open to matching non-gce clouds that have the gce string on their cloud-id. We are now updating this part of the code to make the match more robust by verifying if the cloud-id starts if the gce string.
Check if the license check tests are still working
> postinst: make check for gce instance more robust

- features/attached_enable.feature
- uaclient/cli.py
- uaclient/tests/test_cli_detach.py
cli: detach won't ask to disable dependent service
Currently, when running detach without --assume-yes we will ask to disable dependent services if we have ros enabled services during the operation. We are now sorting the services to be disabled based on the length of the depedent services tuple of each entitlement.
> cli: detach won't ask to disable dependent service (SC-455)

- features/cloud.py
- features/proxy_config.feature
- features/steps/steps.py
- features/ubuntu_pro.feature
- integration-requirements.txt
- uaclient/tests/test_util.py
- uaclient/util.py
```
* tests: bump pycloudlib commitish to include azure inbound_ports
* tests: accept inbound_ports during launch to allow network ingress
This is required on Azure because the squid proxy port 3128 is not
allowed for public ingress.
Azure is complicated as well by the fact that we create instances
in their own subnet, so even private IP accessibility between proxy
and test instance is prohibited.
* tests: do not delete proxy instances when destroy_instances is false
* proxy: no_proxy defaults for link-local IMDS routes
Set no_proxy environment variables to avoid using http_proxy
or https_proxy settings in our ProxyHandler when talking to
link-local cloud IMDS endpoints.
Avoid issues with auto-attach for PRO images in network-limited
environments.
```
```bash …
```
> proxy: no_proxy defaults for link-local IMDS routes (SC-518)

- features/attached_commands.feature
- uaclient/contract.py
- uaclient/tests/test_contract.py
- uaclient/tests/test_util.py
- uaclient/util.py
contract: save machine id during attach operation
When running an attach operation we are now saving the machine-id into our cache. We need to have that information saved on the cache to properly perform the detach operation. We are now updating our contract logic to save that information after we receive the machine token during an attach operation
Run the new integration and unit tests
> Save machine id during attach operation (SC-531)

- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_repo.py
repo: update apt url check for commented source
When we are running the process_contract_deltas function, we verify if the delta apt url is already on the service apt source file. However, there are situations were there will no apt url deltas and we still want to regenerate the service apt source file, for example if we have a commented apt source file. We are updating the code to address that situation.
PS: If we agree on that solution, we will also need to update the contracts side to generate a delta when comparing the `bionic` and `xenial` contracts
PS: The CS has updated the ROS product on staging, we can now better test this PR
1. Launch a xenial container
2. Install the latest version of UA (27.3)
3. Use the staging token to perform an attach
4. Enable `ros` on the container
5. …
> repo: update apt url check for commented source (SC-483)

- debian/changelog
- debian/rules
- debian/ubuntu-advantage-tools.postinst
- debian/ubuntu-advantage-tools.prerm
- features/install_uninstall.feature
Fix pythonpath issue
Instead of setting the PYTHONPATH to guarantee that uaclient will be present in the user environment, we are now running the python scripts through /usr/bin/python3. This will guarantee that if the user has not replaced that path with a custom version, that uaclient will be imported successfully.
> Fix pythonpath issue

- features/attached_commands.feature
- uaclient/security_status.py
- uaclient/tests/test_cli_security_status.py
- uaclient/tests/test_security_status.py
A non-root user cannot read internals like `UAConfig.is_attached`, for instance.
Using the `.status` dict makes sure the same information surfaced to `ua status` reflects in the `security-status` output.
(Then, since we already have the status dict, we can check the services there as well)
Run the related integration test
> Show non-root user updated information in security-status

- README.md
- uaclient/apt.py
- uaclient/tests/test_util.py
- uaclient/util.py
token redaction: redact token log if apt-helper download-file fails.
This redacts the token logged during apt-helper failure e.g. when there the tokens are incorrect. 
It also corrects the path to the *machine-token.json* file in the README. 
Fixes: #1860
Run the test_util test.
> token redaction: redact token log if apt-helper download-file fails

- features/enable_fips_cloud.feature
- features/enable_fips_vm.feature
fips: update integration tests for focal
Initially, there was no strongswan-hmac FIPS package for Focal. Therefore, during the enable operation we state that this package could not be installed. Now that the package can be installed on a Focal machine, we are removing that message from the integration tests
> fips: update integration tests for focal

- uaclient/jobs/update_state.py
If a machine is not attached, there is no need to query for the UA status to update the data.
> fix: only run the status job on attached machines

- debian/ubuntu-advantage-tools.postrm
purge: remove all the gpg files during apt purge
Now we can delete the gpg files in **/etc/apt/trusted.gpg.d/** folder belonging to ubuntu-advantage-tools.
> purge: Remove all gpg files during apt purge (SC-537)

- features/attach_validtoken.feature
- features/attached_commands.feature
- features/ubuntu_pro.feature
- uaclient/cli.py
- uaclient/exceptions.py
- uaclient/status.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_auto_attach.py
- ubuntu-advantage.1
No attach for the attached.
Consider attaching a machine that is already attached to an UA subscription as an error, and return `2` as a specific error code. More context in the bug.
Fixes: #1867
> Return 2 when attaching an already attached machine (SC-573)

- uaclient/entitlements/tests/test_fips.py
fips: avoid writing to real file when testing
Tests were failing when some services when enabled and mainly because they, tests, are writing to a real life i.e. **/etc/apt/auth.conf.d/90ubuntu-advantage** resulting to **PermissionError**
Enable services e.g. esm-infra or cis and run the tests.
> fips: avoid writing to real file when testing

- sru/manual-tests/test-aws-ipv6.sh
- sru/release-27.5/test-aws-ipv6.sh
- uaclient/clouds/aws.py
- uaclient/clouds/tests/test_aws.py
- uaclient/tests/test_util.py
- uaclient/util.py
aws: support using IPv6 metadata endpoint
We are now adding support for AWS instances to query the IPv6 metadata endpoint. However, we are defaulting to use the IPv4 endpoint first. Only if that fails, we will try to query the IPv6 endpoint.
Run the manual test introduced in this PR.
PS: Guarantee that your awscli supports the `--metadata-options`, otherwise the IPv6 endpoint will not work as expected.
PS 2: I still need to confirm that disabling the IPv4 address will generate an URLError exception. I am assuming that
is true because this is what happens if we try to query the IPv6 endpoint without properly configuring the instance. This exception is raised because of the timeout issue we get when trying to query the IPv6 endpoint. I will perform this test, but I think the PR can already …
> aws: support using IPv6 metadata endpoint (SC-515)

- features/_version.feature
tests: add dpkg-query check for version test
Add dpkg-query check to verify the package version.
We cannot compare if the ua version is equal to the dpkg-query output because of our config overrides on some tests (PRO instances)
However, we now also don't need to provide the package version if the config overrides details on it, which I think is an improvement
> tests: add dpkg-query check for version test

- debian/ubuntu-advantage-tools.postinst
postinst: fix service check for unattached machine
When running in a LTS machine with an architecture that is different from i386 and amd64 we will try to unconfigure esm services on these non-supported architectures. Before we unconfigure those services, we check to see if they are enabled. However, the code that performs that check is looking for a key in the status cache that is only present when machine is attached to a subscription. We are now updating the code to not fail if the machine is unattached.
LP: #1951705
Fixes: #1888
To reproduce that error:
1. Launch an ubuntu machine:
`lxc launch ubuntu-daily:xenial dev-x`
2. SSH into the machine and update ubuntu-advantage-tools to 27.4.1
3. Run `ua status`
4. Go into `/var/lib/dpkg/info/ubuntu-advantage-tools.postinst` and change the …
> postinst: fix service check for unattached machine

- features/ubuntu_pro.feature
- uaclient/config.py
- uaclient/tests/test_cli_status.py
If an entitlement does not exist in the Contracts Server, then we don't need to surface it.
> status: show only entitlements which exist in the server

- uaclient/cli.py
- uaclient/clouds/identity.py
- uaclient/clouds/tests/test_identity.py
- uaclient/exceptions.py
- uaclient/tests/test_cli_auto_attach.py
This is part of a series of PRs to support migrating the gcp auto attach job to the daemon. They should be reviewed/merged in the following order:
```
refactor: decouple cloud factory from cli
```
Ensure auto-attach still works correctly
> refactor: decouple cloud factory from cli

- lib/reboot_cmds.py
- uaclient/cli.py
- uaclient/lock.py
- uaclient/tests/test_lock.py
- uaclient/tests/test_reboot_cmds.py
This is part of a series of PRs to support migrating the gcp auto attach job to the daemon. They should be reviewed/merged in the following order:
```
refactor: decouple lock from cli
```
Ensure all locking cli commands still work and correctly conflict with each other.
Ensure trying to run an attach while a pro instance is auto-attaching fails
> refactor: decouple lock from cli

- uaclient/actions.py
- uaclient/cli.py
- uaclient/tests/test_actions.py
- uaclient/tests/test_cli_auto_attach.py
This is part of a series of PRs to support migrating the gcp auto attach job to the daemon. They should be reviewed/merged in the following order:
```
refactor: decouple attach from cli
```
Ensure attach and auto-attach still function properly
> refactor: decouple attach from cli

- uaclient/cli.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/tests/test_cli_collect_logs.py
livepatch: Add full path to all cmds
When interacting with livepatch, if the user does not have /snap/bin in the PATH, the pure canonical-livepatch command
will fail. We are now specifying the full path for all livepatch commands we are running.
LP: #1951954
Run any integration test that enable/disables livepatch
> livepatch: Add full path to all cmds (SC-627)

- features/attached_status.feature
- features/steps/steps.py
- features/unattached_status.feature
- uaclient/cli.py
- uaclient/config.py
- uaclient/contract.py
- uaclient/status.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_contract.py
- ubuntu-advantage.1
This adds the `--simulate-with-token` option to the `status` command.
Using it requires a valid UA token, and will output information about services, as: 
- service name and description
- availability of the service for the archuitecture/series/kernel
- entitlement status from the contract perspective
- whether the service is marked to be enabled automatically.
This would give all information needed to execute a preflight check before users attach during installation time, as well as provide token information for any attached/unattached user.
> Add status endpoint to execute a preflight check of a specific token (SC-623)

- debian/changelog
... which was missing, because the changelog was created before the bug
> changelog: add 27.5 SRU bug reference

- features/unattached_status.feature
See https://github.com/canonical/ua-contracts/blob/develop/products/resource-cis.yaml#L9
> tests: cis is not available on non-lts

- features/enable_fips_vm.feature
- uaclient/status.py
fips: update prompt messages
Update FIPS enable/disable prompt messages to better inform the user of what will happen on the system after the operation is completed.
> fips: update prompt messages

- features/attached_enable.feature
- features/enable_fips_vm.feature
- features/schemas/enable.json
- features/steps/steps.py
- features/unattached_commands.feature
- integration-requirements.txt
- uaclient/apt.py
- uaclient/cli.py
- uaclient/config.py
- uaclient/conftest.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_esm.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/event_logger.py
- uaclient/exceptions.py
- uaclient/snap.py
- uaclient/status.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_enable.py
- uaclient/tests/test_config.py
- uaclient/tests/test_event_logger.py
- uaclient/util.py
cli: add json output for enable command
We are now allowing users to modify the output of enable to a machine readable json format. This format will include
all the error and warnings that were generated during the command, while also pointing to which services succeeded and failed during the execution of the command.
Run the modified integration test.
> cli: add json output for enable command (SC-699)

- uaclient/actions.py
- uaclient/cli.py
- uaclient/config.py
- uaclient/entitlements/esm.py
- uaclient/entitlements/tests/test_esm.py
- uaclient/tests/test_actions.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_cli_detach.py
fix update apt and motd messages call
When performing some operations, we want to call the code that update both apt and motd messages. However, the code that does that is importing a module that doesn't exist anymore. We are correctly calling the function that updates those messages directly
Run the modified unit tests.
Run any integration test that performs an operation that requires updating messages, like disabling esm-infra, and verify that it has occurred
> fix update apt and motd messages call

- features/enable_fips_cloud.feature
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
fips: allow enabling FIPS on focal clouds
The focal clouds now possess fips optimized kernel on the focal release. We are now allowing FIPS to be enabled on those
clouds
> fips: allow enabling FIPS on focal clouds

- features/license_check.feature
- uaclient/cli.py
jobs: disable jobs after attach/auto-attach
After a attach/auto-attach opeartion, we are now disabling jobs if necessary, for example, the license check job for GCP
Run the license check integration tests
> jobs: disable jobs after attach/auto-attach

- uaclient/tests/test_cli_collect_logs.py
- uaclient/tests/test_cli_security_status.py
- uaclient/tests/test_security.py
tests: fix tests for jammy
On jammy, we are using new versions of the libraries and also Python 3.10. That means that some of our tests are making assumptions with old libraries. We have updated the tests to behave properly on jammy
Build a jammy package without the fix applied and see that it fails
Apply the test fix and run the build again
> tests: fix tests for jammy

- README.md
I just removed the same thing from the Azure and EC2 sections because the context should make it clear where the instances are being launched
> docs: remove erroneous ec2-specific comment

- features/attached_enable.feature
- uaclient/entitlements/base.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/status.py
enable: show incompatible services message on json
We are now adding the incompatible services message to the json output of the enable command
> enable: show incompatible services message on json (SC-734)

- features/attached_enable.feature
- features/enable_fips_vm.feature
- features/unattached_commands.feature
- uaclient/cli.py
- uaclient/entitlements/base.py
- uaclient/entitlements/tests/test_base.py
- uaclient/event_logger.py
- uaclient/status.py
- uaclient/tests/test_cli_enable.py
enable: show required services message on json
We are now adding the required services message to the json output
of the enable command
> enable: show required services message on json

- RELEASES.md
After the release, pinging CPC should be sufficient to update the cloud
images.
> docs: update information about PRO images

- features/enable_fips_vm.feature
- features/steps/steps.py
- uaclient/config.py
- uaclient/conftest.py
- uaclient/entitlements/base.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/tests/test_base.py
- uaclient/status.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_config.py
- uaclient/tests/test_gpg.py
- uaclient/tests/test_security.py
- uaclient/tests/test_util.py
```
status: include blocked_by for each service
blocked_by is a per-service field. If populated for a given service, the
value is an array of other services that are currently enabled and
incompatible with the given service. Disabling all of the services in
"blocked_by" will allow you to enable the blocked service.
```
Run `ua status --format=json` on a vm with combinations of fips, fips-updates, and livepatch enabled and make sure the "blocked_by" values are appropriate.
Also maybe run the updated fips integration tests (they are marked `@slow`)
> status: blocked_by services

- README.md
Current link leads to deprecated site (_"This PPA is retired as of 03/23/2021."_). Change the link to the one already used in line 276.
[doc] Fix link to ua-client-daily PPA
> [doc] Fix link to ua-client-daily PPA

- features/attach_invalidtoken.feature
- features/attach_validtoken.feature
- features/steps/steps.py
- features/ubuntu_pro.feature
- features/unattached_commands.feature
- uaclient/actions.py
- uaclient/cli.py
- uaclient/config.py
- uaclient/contract.py
- uaclient/entitlements/__init__.py
- uaclient/entitlements/base.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_entitlements.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/exceptions.py
- uaclient/security.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_contract.py
attach: allow json response format
This will allow users to have a json response when running `ua attach`
> attach: allow json response format (SC-769)

- uaclient/contract.py
- uaclient/jobs/metering.py
- uaclient/tests/test_contract.py
contract: send activity info during machine token update operations
Updates the machine_token_update request to also include activity information if available, in a similar fashion to how the report_machine_activity request is behaving.
Updated and ran unit tests.
> contract: send activity info during machine token update operations

- features/proxy_config.feature
proxy: delete default route on container tests
On the container tests, we are now deleting the default route to guarantee that the ua request are actually going through the proxy
Run the modified proxy test
> proxy: delete default route on container tests

- debian/ubuntu-advantage-tools.logrotate
- debian/ubuntu-advantage-tools.postinst
- features/attached_commands.feature
- sru/release-27.7/test_world_readable_logs.sh
- uaclient/cli.py
- uaclient/tests/test_cli.py
make only new logs world readable
We are now modifying our logs to be world readable only when we are creating new log file, either through logrotate
or when ua set up logs. This means that old logs will not be modified
Run the manual test script in this PR.
> make only new logs world readable

- features/steps/steps.py
- features/unattached_commands.feature
- uaclient/security.py
- uaclient/tests/test_security.py
fix: dont raise issue if usn has no related cves
Some USNs do not have related CVEs. If that happens, we should rely entirely on the USN release packages to fix the underlying system. We are now adapting the code to identify that scenario and act accordingly
Run the modified bionic integration test and confirm that the provided USN does not have any CVEs associated with it
> fix: dont raise issue if usn has no related cves (SC-162)

- features/proxy_config.feature
- features/steps/steps.py
Currently the first proxy test where we delete the default route is failing for bionic and focal. That is because it is trying to enable esm before the apt proxy is set up.
This commit fixes that by using `--no-auto-enable` during the attach step.
```
tests: fix apt proxy test
```
Run `env UACLIENT_BEHAVE_BUILD_PR=1 tox -e behave-lxd-20.04 -- features/proxy_config.feature` for each series
> tests: fix apt proxy test

- features/attached_commands.feature
- uaclient/cli.py
- uaclient/contract.py
- uaclient/tests/test_contract.py
detach: remove contract detach call
The contract server is no longer detaching machines on their end. Therefore, we need to remove that call from detach, since it is doing nothing at the moment.
Just verify that detach is still working as expected on the machine
> detach: remove contract detach call

- features/attached_commands.feature
- features/schemas/ua_security_status.json
- uaclient/cli.py
- uaclient/security_status.py
- uaclient/tests/test_cli_security_status.py
- uaclient/tests/test_security_status.py
This PR addresses feedback received from the beta version of `ua security-status`.
The main changes requested are:
- to include the origin site for the updates shown in the JSON
- to include the amount of packages installed from ESM
Aside from that, this PR also removes the `--beta` flag from the command and sets the schema version to `0.1`.
> ua security-status round of improvements (SC-433)

- features/enable_fips_cloud.feature
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
fips: allow enabling fips on azure xenial clouds
Currently, on Azure Xenial PRO FIPS machine we install the non-optimized fips kernel. Therefore, we are now expanding that
to other Azure Xenial machines.
> fips: allow enabling fips on azure xenial clouds

- debian/ubuntu-advantage-tools.postinst
```
postinst: remove unneeded check for deb-systemd-helper
deb-systemd-helper is a part of init-system-helpers, which is
Essential: yes, so the check here was superfluous.
```
Install an old version of ua that has ua-messaging.timer. Upgrade to this version and make sure ua-messaging.timer is cleaned up correctly.
Or say "this doesn't really benefit us and we don't want to bother with the extra testing here so lets just leave it as it was" - that would make sense too :) - then we can just close this PR
> postinst: remove unneeded check for deb-systemd-helper

- features/attached_enable.feature
- uaclient/clouds/identity.py
- uaclient/clouds/tests/test_identity.py
- uaclient/config.py
- uaclient/contract.py
- uaclient/entitlements/base.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_util.py
- uaclient/util.py
Support generic overrides from the contract server.
Currently, the supported overrides are `series` and `cloud`, but more can be added in the future.
Further testing, mainly integration testing, can be performed once contracts starts applying those specific overrides with anything different than the regular `series` one that we had before. Right now, no flow has changed.
> Cloud overrides core

- features/unattached_commands.feature
- uaclient/cli.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/tests/test_cli_disable.py
- uaclient/tests/test_cli_enable.py
When trying to enable/disable, check if the services are valid and
present messages accordingly.
Added a new message name/content for the case when the user provides valid and invalid services to the CLI at the same time.
Fixes: #1976
> cli: validate services when unattached (SC-805)

- features/attach_invalidtoken.feature
- features/schemas/ua_operation.json
- features/steps/steps.py
- uaclient/cli.py
- uaclient/contract.py
- uaclient/event_logger.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_event_logger.py
cli: add additional_info to json response errors
If users want to modify the error messages delivered by us, we need to provide additional info to some of those error messages. We are now adding that information only for expired contract errors but we can add more additional info in the future if needed.
> cli: add additional_info to json response errors

- features/ubuntu_pro_fips.feature
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
fips: enable fips-update on fips-pro
A fips pro machine could not enable fips-updates. After testing, unholding these two libgcrypt packages helped solve this issue.
> Fips fips update correction

- debian/ubuntu-advantage-tools.postinst
- lib/upgrade_lts_contract.py
- tools/ua.bash
- uaclient/actions.py
- uaclient/cli.py
- uaclient/config.py
- uaclient/contract.py
- uaclient/entitlements/__init__.py
- uaclient/entitlements/base.py
- uaclient/entitlements/tests/test_entitlements.py
- uaclient/jobs/update_messaging.py
- uaclient/security.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_cli_auto_attach.py
- uaclient/tests/test_cli_collect_logs.py
- uaclient/tests/test_cli_detach.py
- uaclient/tests/test_cli_disable.py
- uaclient/tests/test_cli_enable.py
- uaclient/tests/test_cli_security_status.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_config.py
- uaclient/tests/test_contract.py
- uaclient/tests/test_update_messaging.py
Remove unnecessary creation of UAConfig instances
Creating an UAConfig instance can be an expansive operation that can be avoided if we share the instance we create for every cli call throught the code. We are refactoring the code to allow that reuse of the instance when possible
I have tested this work to see if we would get any speedup when running some UA commands:
`ua status` from around 2.5s to 2.0s
`ua attach` form around 17s to 16.2s
Tests were performed with a bionic LXD container running both commands around 3 times using the latest package of UA and another with the config refactor applied.
Run the integration steps for attach/enable/disable/deach and verify that the package doesn't break and that it still work as expected
> Remove unnecessary creation of UAConfig instances

- features/ubuntu_pro_fips.feature
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
unhold fips package when enabling fips-updates
Currently, we only unhold fips related packages when we enable fips. Since on FIPS PRO machines, users might want to enable fips-updates, we are now also unholding packages on that operation.
Launch a PRO FIPS machine, install an updated version of UA with this change and verify that running `ua enable fips-updates` works as expected
> unhold fips package when enabling fips-updates

- features/ubuntu_upgrade.feature
- lib/upgrade_lts_contract.py
- uaclient/tests/test_upgrade_lts_contract.py
lib: fix upgrade script for unsupported releases
The upgrade_lts_script fails if it cannot find a codename for the current Ubuntu version it is running on. We are updating the script to properly finish if that situation happens
Run the new unit test added
> lib: fix upgrade script for unsupported releases

- .github/workflows/cloud-cleanup.yaml
```
CI: cleanup-ec2: only clean instances started by the current principal
We can have CI instances running under the same AWS account but started
by a different principal (~ IAM user). We want the CI cloud-cleanup
workflow to only deal with instances created by the same principal that
is used in the CI runs.
Fixes: #2051
```
> CI: cleanup-ec2: only clean instances started by the current principal

- Makefile
- debian/rules
- debian/ubuntu-advantage-tools.postinst
- features/aws-ids.yaml
- features/daemon.feature
- features/gcp-ids.yaml
- lib/cloud-id-shim.sh
- sru/release-27.8/gcp_auto_attach_long_poll.sh
- sru/release-27.8/gcp_auto_attach_on_boot.sh
- systemd/ubuntu-advantage-cloud-id-shim.service
- systemd/ubuntu-advantage.service
```
daemon: cloud-id file shim
This introduces a new systemd service that will run on startup only if
the version of cloud-init does not create the cloud-id file. The service
creates the same cloud-id file that cloud-init does in newer versions.
This is specifically necessary for xenial, and is a noop if cloud-init
is new enough.
It also runs the same script on postinst to cover the scenario where the
new version of cloud-init is installed but the instance has not
rebooted, and so cloud-init hasn't yet created the cloud-id file.
```
run the edited integration tests
> daemon: cloud-id file shim

- features/_version.feature
- features/gcp-ids.yaml
- features/ubuntu_pro_fips.feature
- tools/refresh-gcp-pro-ids.py
- tox.ini
gcp-pro-fips: add integration tests for gcp fips
We are adding integration tests for gcp pro fips machines. It should be noted that we do not have gcp xenial fips machines, thus we have not included tests for them. If the situation changes, then we will add xenial tests.
> gcp-pro-fips: add integration tests for gcp fips

- .github/workflows/ci-integration.yaml
```
CI: build debs in schroots without -proposed enabled
Later testing (integration testing) is done in an environment which
doesn't have -proposed enabled. Building the package with -proposed
enabled can cause dependency issues.
```
> CI: build debs in schroots without -proposed enabled

- uaclient/apt.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_cis.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/security.py
- uaclient/tests/test_apt.py
We currently use the output to check if each repo entitlement is enabled in the system. This happens for example when we are
running an ua status operation, where we run an apt-cache policy for each entitled repo service the user has. We can cache that command if no update calls are performed. Therefore, we are speeding up the execution of ua status by caching the result of apt-cache policy calls.
Testing this changeset on a xenial container, `ua status` response average turns from `1.42s` to `0.57`.
Please, run status with and without this change to confirm the speed up.
Additionally, run attach integration tests where more than one repo service is being enabled, to confirm the status in the end is not incorrect.
> apt: allow caching apt-cache policy commands

- features/schemas/ua_security_status.json
- uaclient/cli.py
- uaclient/security_status.py
- uaclient/tests/test_cli_security_status.py
- uaclient/tests/test_security_status.py
Should essentially be the same as #2033 but backwards compatible. Once we start implementing our versioned API, we can move this functionality there and introduce a new versioned schema using that infrastructure.
```
cli: add package counts based on archive components to security-status
We count how many packages are from main, restricted, universe,
multiverse, and present it in the summary
```
Run `ua security-status --format yaml` in different systems. Compare the numbers to what `ubuntu-security-status` says and what you know.
> Add package counts for different components (minimal backwards compatible version)

- features/daemon.feature
- features/steps/steps.py
- lib/daemon.py
- uaclient/cli.py
- uaclient/defaults.py
The tests are mostly so that we can keep an eye on memory usage. They're aren't "hard limits" necessarily.
This lowers memory usage by 2Mb by avoiding importing the cli module and using a smaller daemon-tailored `setup_logging` function.
```
daemon: lower memory with less imports and start testing memory
```
Run the gcp daemon test with new steps on all series
> daemon: lower memory with less imports and start testing memory

- features/attached_enable.feature
- uaclient/entitlements/base.py
- uaclient/entitlements/tests/conftest.py
After this, an empty list for the series affordance will mean that no series are supported.
The same will be true for architectures and kernel flavors.
```
enable: treat empty list affordance differently from null
```
Run the new integration test.
Use machine token overlays to test that an empty affordance list behaves as you expect.
> enable: treat empty list affordance differently from null

- CONTRIBUTING.md
- README.md
- docs/howtoguides/update_motd_messages.md
- features/attach_validtoken.feature
- features/attached_commands.feature
- uaclient/cli.py
- uaclient/jobs/update_messaging.py
- uaclient/messages.py
- uaclient/tests/test_cli_refresh.py
cli: add refresh subcommand to update motd message
Right now, users have no direct way to update the MOTD messages UA deliver. For example, if a contract is renewed, users will need to wait for our timer job to run so they can see the expiry message on MOTD disappear. We are now adding a `ua refresh motd` command that updates the MOTD message
> cli: add refresh subcommand to update motd message

- features/steps/steps.py
- lib/reboot_cmds.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/tests/test_reboot_cmds.py
fips: clean notice for older PRO FIPS images
We currently detect that an user is on an old PRO FIPS machine on our postinst script and emit a notice for that. However, even
after we fix the issue on the older image, we don't remove the notice. We are now properly cleaning up that notice.
LP: #1972026
Run the modified unit tests
> fips: clean notice for older PRO FIPS images

- uaclient/security_status.py
Tell me if that is understandable, or if I should document it differently / somewhere else.
> chore: better document the get_origin_for_package function

- .github/workflows/ci-integration.yaml
- features/cloud.py
- tox.ini
```
Use pycloudlib.toml gce.credentials_path
Have pycloudlib handle the GCE credentials rather than using
the special GOOGLE_APPLICATION_CREDENTIALS, which is handled
directly by the gcloud library.
```
Let CI run.
> Use pycloudlib.toml gce.credentials_path (SC-987)

- uaclient/actions.py
- uaclient/cli.py
- uaclient/clouds/gcp.py
- uaclient/clouds/tests/test_gcp.py
- uaclient/exceptions.py
- uaclient/messages.py
gcp-pro: handle metadata endpoint error
We are handling for the errors raised when using gcp pro and the service account is not enabled.
Fixes #1936
> gcp-pro: handle metadata endpoint error

- README.md
Only including LTS release badges.
I think this looks like a cool way to advertise the consistency of version across all LTS releases of `ua`
> docs: badges to advertise that same version is released to all LTS

- README.md
- docs/howtoguides/how_to_run_ua_fix_in_dry_run_mode.md
- features/fix.feature
- uaclient/cli.py
- uaclient/conftest.py
- uaclient/messages.py
- uaclient/security.py
- uaclient/tests/test_cli_fix.py
- uaclient/tests/test_security.py
- uaclient/tests/test_status.py
fix: add --dry-run option
Add support for --dry-run option for ua fix command. This option allow users to see what will happen in their system once if the fix command is actually used.
Run the modified integration test added
> fix: add --dry-run option

- features/environment.py
- features/ubuntu_pro_fips.feature
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
fips: remove message when enabling fips-updates
When we have fips enabled and we enable fips-updates, we don't want to emit a notice stating that to disable fips we need to reboot the system. However, we still want to warn users that a system reboot is needed to boot on the fips-updates kernel
Run the modified ubuntu-pro-fips tests and also normal fips tests to confirm no behavior change
> fips: remove message when enabling fips-updates

- uaclient/apt.py
- uaclient/config.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_esm.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/tests/test_apt.py
- uaclient/util.py
By using the util.remove_file everywhere we are removing files, we get
consistent logging whenever we remove a file. This will help debug
future issues.
I noticed we weren't logging the removal of some files while debugging a recent issue. I had to check the source to verify my understanding of what was happening. It would've been easier if we just logged it. I also noticed some duplicate functionality that this will simplify.
All tests should still pass
> refactor: use remove_file fn everywhere

- README.md
- docs/references/ppas.md
Some small readme tweaks to streamline things.
* Moved the ppa details to a reference doc
* Replaced the ppa section with a short "Quickstart" section
* Standardized on question marks for explanation doc titles, and no question marks for how to guides
> docs: move ppa details to reference doc

- uaclient/cli.py
- uaclient/tests/test_cli_refresh.py
cli: add missing refresh option on help text
Verify that the `messages` option is now appearing
> cli: add missing refresh option on help text

- uaclient/contract.py
- uaclient/tests/test_contract.py
contract: send platform info for resource requests
Right now, when attached, we don't send any platform information when requesting machine token resources. This is because the contract side that information stored on their side. To make this process better, can send that request directly to the contract backend.
Verify that the commands that use the modified endpoint still work as expected
> contract: send platform info for resource requests

- features/attach_validtoken.feature
- uaclient/data_types.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_data_types.py
As we start to rely on data types more, we should avoid printing values of things we're parsing, in case we end up using these for sensitive information in the future.
> data_types: safer error messages

- sru/daemon_stall_cloned_machine.py
- uaclient/cli.py
- uaclient/daemon.py
- uaclient/tests/test_daemon.py
~~Note that this does not fix the root cause of the stalled daemon reported in https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1980865~~
~~Debugging that may take some more time and I think we should include this mitigation in the upcoming release.~~
The daemon was stalling because it is configured "After: ua-auto-attach.service" but was started during that service. This results in a deadlock. So simply not starting the daemon during the auto attach service is the full fix here.
build the deb and store at `./ua.deb`. Then run the test script here using this branch of pycloudlib: https://github.com/canonical/pycloudlib/pull/204
It should successfully boot the snapshotted image.
If you comment out the lines that install the deb, then the snapshotted image would never …
> prevent unneeded daemon activation and mitigate stalled daemon bug

- features/magic_attach.feature
- features/schemas/magic_attach.json
- features/steps/steps.py
- uaclient/api/tests/test_u_pro_attach_magic_wait_v1.py
- uaclient/api/u/pro/attach/magic/initiate/v1.py
- uaclient/api/u/pro/attach/magic/wait/v1.py
- uaclient/contract.py
- uaclient/tests/test_contract.py
- uaclient/tests/test_util.py
- uaclient/util.py
api: change magic-attach key names
The contract server has modified some key names in the response of some magic-attach endpoints. We are now reflecting those changes here as well.
Run the modified unit and integration tests
> api: change magic-attach key names

- uaclient/api/tests/test_u_pro_attach_magic_wait_v1.py
- uaclient/api/u/pro/attach/magic/wait/v1.py
- uaclient/contract.py
- uaclient/exceptions.py
magic-attach: Don't fail on first connection error
When running the wait endpoint, we will now try at least 3 times if we receive a connectivity error. The rationale for that is
to avoid flake connectivity errors to stop the execution of the command
Run the new unit test and check that the integration test for magic attach is still working as expected
> magic-attach: Don't fail on first connection error

- lib/timer.py
- uaclient/apt.py
- uaclient/entitlements/esm.py
- uaclient/jobs/eol_status.py
- uaclient/messages.py
- uaclient/tests/test_eol_status.py
eol-check: check if unattached system is eol
Adding a timer job to check if the system has reached EOL.
This is specifically for an unattached system.
Fixes: #1587
> eol-check: check if unattached system is eol

- features/attached_commands.feature
- features/attached_enable.feature
- features/unattached_status.feature
- uaclient/entitlements/ros.py
- uaclient/tests/test_cli_disable.py
- uaclient/tests/test_cli_enable.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_status.py
ros: make service non-beta
Make `ros` and `ros-updates` non beta services
Verify we can enable those services without the `--beta` flag in the integration tests
> ros: make service non-beta

- features/api_magic_attach.feature
tests: use prod env for magic-attach tests
The magic-attach changes are now released on prod. We are updating the tests to use it instead of staging
Check the magic-attach tests are working as expected on the prod env
> tests: use prod env for magic-attach tests

- features/api_magic_attach.feature
- features/schemas/magic_attach.json
- uaclient/api/tests/test_api_u_pro_attach_auto_should_auto_attach.py
- uaclient/api/tests/test_api_u_pro_attach_magic_wait_v1.py
- uaclient/api/tests/test_api_u_pro_version.py
- uaclient/api/u/pro/attach/auto/should_auto_attach/v1.py
- uaclient/api/u/pro/attach/magic/initiate/v1.py
- uaclient/api/u/pro/attach/magic/revoke/v1.py
- uaclient/api/u/pro/attach/magic/wait/v1.py
- uaclient/api/u/pro/version/v1.py
make sure the python script experience of using our api doesn't requiring touching any ua-internals like the UAConfig
> api: adjustments to not require config as an arg

- uaclient/messages.py
- uaclient/security.py
- uaclient/tests/test_security.py
Adds a check of livepatch output during ua fix
Adds a subprocess call of canonical-livepatch with verbose flag
within the fix_security_issue_id method, parses the output as json,
and checks for the presence of the cve issue id in the output's fixes
property, if present.
Resolves #2181
> Added livepatch check in fix_security_issue_id

- dev-docs/howtoguides/testing.md
- docs/source/references/support_matrix.md
- features/_version.feature
- features/api.feature
- features/attach_invalidtoken.feature
- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/collect_logs.feature
- features/daemon.feature
- features/fix.feature
- features/install_uninstall.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
- features/unattached_commands.feature
- features/unattached_status.feature
- lib/upgrade_lts_contract.py
- tools/create-lp-release-branches.sh
- tools/run-integration-tests.py
- tox.ini
- uaclient/clouds/tests/test_gcp.py
We won't release to Impish anymore, and we will for Kinetic for a while.
This is changing Impish to Kinetic in tests and docs.
> chore: change Impish to Kinetic in tests

- features/environment.py
- features/steps/steps.py
- features/ubuntu_pro.feature
- lib/auto_attach.py
- systemd/ua-auto-attach.path
- systemd/ua-auto-attach.service
- uaclient/clouds/aws.py
- uaclient/clouds/azure.py
- uaclient/clouds/gcp.py
- uaclient/clouds/tests/test_aws.py
- uaclient/clouds/tests/test_azure.py
- uaclient/clouds/tests/test_gcp.py
- uaclient/tests/test_lib_auto_attach.py
auto-attach: no-op when ua info on cloud-init data
When we detect the ubuntu_advantage key on cloud-init userdata, we should no-op the ua-auto-attach service. That's because if we detect that key, cloud-init will be responsible for orchestrating the auto-attach operation on their side.
> auto-attach: no-op when ua info on cloud-init data

- uaclient/cli.py
- uaclient/conftest.py
- uaclient/contract_data_types.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/files.py
- uaclient/status.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_status.py
status: correct data in non-root
Currently, when `ua status` as non-root it gets its status from status cache file.
Incase of any changes on the contract server concerning the machine's account,
we do not get up to date info.
> status: correct data in non-root

- features/staging_commands.feature
- features/steps/steps.py
- features/unattached_commands.feature
- uaclient/api/api.py
- uaclient/api/errors.py
- uaclient/api/tests/test_api.py
- uaclient/apt.py
- uaclient/cli.py
- uaclient/conftest.py
- uaclient/defaults.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_cis.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/messages.py
- uaclient/security.py
- uaclient/tests/test_apt.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_security.py
- uaclient/tests/test_version.py
- uaclient/version.py
Warn users about a new version of the client being available.
If executed from the CLI, print a warning to stderr.
If it's an API call, include a warning in the JSON.
> Warn about new versions (SC-552)

- features/attach_validtoken.feature
- features/attached_status.feature
- features/steps/steps.py
- features/ubuntu_pro.feature
- features/unattached_status.feature
- uaclient/actions.py
- uaclient/cli.py
- uaclient/event_logger.py
- uaclient/security_status.py
- uaclient/status.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_event_logger.py
- uaclient/tests/test_status.py
status: don't show unavailable services by default
We are not only showing unavailable services if the user provides
the --all flag to status.
Fixes: #2156
Fixes: #2159
Run the modified unit and integration tests
> status: don't show unavailable services by default

- features/attached_enable.feature
- uaclient/apt.py
The regex was failing to grab the entire url and would only match
"esm.ubuntu.com" for each line. Because every service is a more specific
path of esm.ubuntu.com and there was no check to prevent multiple
additions of a new line, then a new line would be inserted before every
existing line each time.
This changes to a simpler split-based approach to get each line's url
and compare. We also add an integration test to insure the behavior is
not inflating the size of the file.
LP: #1985863
> enable: fix apt auth line replacement

- features/ubuntu_pro.feature
- uaclient/contract.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/serviceclient.py
- uaclient/tests/test_contract.py
auto-attach: better error for invalid Pro image
We are now creating a specific exception for the situation
where the Pro image is is not registered on the contract side.
Additonally, we are also adding a specific logging for this
situation as well.
Fixes: #2180
Verify if the existing tests are passing
> auto-attach: better error for invalid Pro image (SC-1211)

- uaclient/files.py
- uaclient/status.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_status.py
Use the system's locale and timezone when presenting the expiry date in
the human readable status output.
Fixes: #695
Run `pro status` and ensure the Valid Until date looks good
> status: format expiry date (SC-1157)

- uaclient/entitlements/base.py
- uaclient/files.py
status: reduce calls to read machine token file when unattached
We had almost 231 machine token access when running `pro status` as root. This PR reduces this to about 5.
> status: reduce calls to read machine token file when unattached SC1063

- tools/run-integration-tests.py
No need to use it in local tests, as sbuild is being executed just once for sure.
> tests: remove snapshot_strategy from the test script

- uaclient/security_status.py
- uaclient/tests/test_security_status.py
With the current bug being fixed in #2217 ua fails to run on a kernel that doesn't match the broken regex.
It fails so early that it isn't even able to log anything or print why it failed. It fails that early because of this use of `get_platform_info` that happens at module import time.
The fix is to just only make this function call when it is needed and cache the result, rather than compute it at module import time
> security-status: remove module level logic

- docs/source/explanations/how_to_interpret_the_security_status_command.md
- features/attached_commands.feature
- features/schemas/ua_security_status.json
- uaclient/cli.py
- uaclient/security_status.py
- uaclient/tests/test_cli_security_status.py
- uaclient/tests/test_security_status.py
Add a list with the CVEs fixed by livepatch to the output of `security-status`.
> security-status: add CVEs fixed by Livepatch to the JSON output (SC-1233)

- debian/changelog
- debian/control
- features/docker.feature
- features/fix.feature
- uaclient/cli.py
- uaclient/messages.py
This brings changes from the `27.10.1` release from the `release-27` branch. The extra commit with the latest changelog entry (which existed only in Launchpad) was uploaded directly to `release-27` and is cherry-picked here as well.
> Bring changes from 27.10.1

- debian/ubuntu-advantage-tools.postinst
- features/attached_commands.feature
create public machine-token for attached machines
On already attached machines, we won't have the public machine-token file. We need that file for non-root status calls. Because of that, we are creating that file during postinst to guarantee the correct behavior of non-root status
> create public machine-token for attached machines

- uaclient/apt.py
- uaclient/cli.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/tests/test_apt.py
Don't import it from util anymore
And list only installed packages in `get_installed_packages`
> fix: use is_installed from s̶y̶s̶t̶e̶m̶ apt in cli.py

- tools/create-lp-release-branches.sh
For a system without the Deb niceties set, the `create-lp-release-branches.sh` script will rely on local data (username, machine name) to generate the Maintainer line (Name and <email>) for the backport entry in the changelog.
Yes I know, it's just a temporary entry...
But for consistency sake we can use the `-m` flag to `dch`, so the new entry has the same information as the previous one (which should be accurate for the release shepherd anyway)
Run the script and check that the new backport entry has the same Maintainer entry as the previous one.
> chore: keep the maintainer name in the backport changelog entry

- features/attached_enable.feature
- features/schemas/ua_security_status.json
- uaclient/api/api.py
- uaclient/api/tests/test_api_u_pro_security_status_reboot_required_v1.py
- uaclient/api/tests/test_api_u_pro_security_status_reboot_v1.py
- uaclient/api/u/pro/security/status/reboot/v1.py
- uaclient/api/u/pro/security/status/reboot_required/v1.py
- uaclient/cli.py
- uaclient/security_status.py
- uaclient/tests/test_cli_reboot_required.py
- uaclient/tests/test_security_status.py
reboot-required: add api endpoint for reboot info
Add endpoint to verify the reboot state of a machine taking into
consideration livepatch as well. We have also added this information
on the output of running security-status
Run the new integration and unittests
> reboot-required: add api endpoint for reboot info (SC-1266)

- debian/ubuntu-advantage-tools.postinst
- uaclient/apt.py
- uaclient/entitlements/esm.py
- uaclient/entitlements/tests/test_esm.py
- uaclient/tests/test_apt.py
From the associated LP bug:
```
With u-a-t 27.11, currently on -proposed, upgrading from Xenial to Bionic fails when unattached.
The reason is: Bionic has some updates available in esm-apps, and the repositories are present due to the postinst script seeing that the service is not beta anymore.
However, the preferences file only pins esm for Xenial, and do-release-upgrade:
1. Sees the packages in the Bionic ESM repository
2. Ignores the pinning to 'never'
3. Fails to get those packages - all of them are 401ed
4. Fail to calculate the diffs and exits 1.
Although found and reproducible when upgrading from Xenial to Bionic, this bug may affect any upgrade across releases where the system is unattached, and has any given package installed which is present in the ESM repository of the next …
```
> Fix esm across release upgrade

- debian/changelog
postinst should be in the changelog, and the change is actually to the apport hook
> chore: fix the changelog entry for 27.11.3

- features/ubuntu_pro.feature
- features/ubuntu_pro_fips.feature
- systemd/ua-auto-attach.service
systemd: add machine token condition for auto-attach
This is a simple improvement. Just an extra check for the auto-attach.service - make sure that the machine is not attached.
> systemd: add machine token condition for auto-attach

- lib/auto_attach.py
```
lib/auto_attach: Fix cloud-init ua config presence
In order to let cloud-init drive the auto attach
UA checks the presence of UA config in cloud-init
user-data.
Check for the presence of `ubuntu-advantage` in
user-data. This is the deprecated way to define
the config of cc_ubuntu_advantage.
```
> lib/auto_attach: Fix cloud-init ua config presence

- uaclient/config.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/conftest.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/files/__init__.py
- uaclient/files/data_types.py
- uaclient/files/files.py
- uaclient/files/state_files.py
- uaclient/files/tests/test_data_types.py
- uaclient/files/tests/test_files.py
- uaclient/files/tests/test_state_files.py
- uaclient/messages.py
files: extract services-once-enabled from config
Extract the services-once-enabled state file from the UAConfig class and handle it on a dedicated module.
This PR also proposed a refactoring on the structure of how we manage files on UA.
Run the integration scenario`Attached enable of FIPS-updates in an ubuntu lxd vm` on the `enable_fips_vm`  feature
> files: extract services-once-enabled from config (SC-1267)

- docs/references/api.md
- uaclient/api/exceptions.py
- uaclient/api/tests/test_u_pro_attach_auto_full_auto_attach_v1.py
- uaclient/api/u/pro/attach/auto/full_auto_attach/v1.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/testing/helpers.py
full_auto_attach.v1 will no longer raise exceptions about invalid
arguments before attempting to attach. Instead it will attempt to auto
attach and enable all services. If any services fail, they will all be
reported in a single error.
This also adds a check for the disable_auto_attach configuration and
raises an error if that is true before the attempt to attach.
This is technically a breaking change, but because we caught this early
and we know of the only current consumer of this function we can make it
safely without bumping the version.
everything should still pass
> api: best effort full_auto_attach instead of fail fast

- uaclient/entitlements/base.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/tests/test_util.py
- uaclient/util.py
Fixes: #917
Run `pro enable` in a way that causes the arch affordance check to fail. Ensure that a de-duplicated list of arches is printed.
> enable: show deduplicated list of supported arches

- features/attached_commands.feature
- features/detached_auto_attach.feature
- features/ubuntu_pro.feature
- features/ubuntu_pro_fips.feature
- lib/auto_attach.py
- uaclient/actions.py
- uaclient/api/tests/test_u_pro_attach_auto_full_auto_attach_v1.py
- uaclient/api/u/pro/attach/auto/full_auto_attach/v1.py
- uaclient/cli.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/testing/helpers.py
- uaclient/tests/test_actions.py
- uaclient/tests/test_cli_auto_attach.py
- uaclient/tests/test_lib_auto_attach.py
```
auto-attach: Refactor cli entry-point to use the api
In order to simplify the code base, make use of
full_auto_attach api endpoint in cli `pro auto-attach` command.
Behavior change:
Previously, in the case where the user tried to auto attach using
the cli `pro auto-attach` on instances that were already attached
or have disable_auto_attach configured as true in the
uaclient.conf file, the cli exited with a 0 exit_code.
Now, the cli returns non 0 exit codes in both cases. The cli returned
0s because we would call the cli command on the
ua-auto-attach.service systemd unit. If we detected that the user 
was already attached or hand explicit config disabling that service,
we didn't want to show that this service failed.
After previous and this refactoring, both entry-points make use of …
```
> auto-attach: use api in cli entry-point (SC-1274)

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- dev-docs/howtoguides/how_to_release_a_new_version_of_ua.md
- dev-docs/references/early_review_signoff.md
As we decided after the (rather traumatic) 27.11 release, some features will need special approvals before we implement them, to avoid problems in the SRU process. This changeset adds that information to the dev docs.
> Add documentation for features which require pre-reviews

- docs/_static/css/github_issue_links.css
- docs/_static/js/github_issue_links.js
- docs/conf.py
The goal here is to add a link to each page to easily open a GitHub
issue related to that page's contents. This can be an easy way to ask a
question or report a problem with that piece of documentation.
Instead of forking the furo theme, this uses some custom CSS/JS to add
an extra element to the theme after the page loads. We will likely
switch to a more Ubuntu-styled theme in the future, so this is just a
hack for now to prove the concept. This hack can be adapted to a
future theme, or, ideally, this feature would get built into the
future theme.
`tox -e dev-docs` and open the docs in your browser. Make sure the link at the top of each page makes sense and links to an appropriate github issue form.
> docs: add github issue feedback link to each page

- .github/workflows/ci-integration.yaml
- dev-docs/howtoguides/testing.md
- features/airgapped.feature
- features/cloud_pro_clone.feature
- features/environment.py
- features/fix.feature
- features/proxy_config.feature
- features/steps/airgap.py
- features/steps/contract.py
- features/steps/files.py
- features/steps/machines.py
- features/steps/network.py
- features/steps/output.py
- features/steps/packages.py
- features/steps/shell.py
- features/steps/ubuntu_advantage_tools.py
- features/ubuntu_pro.feature
- features/util.py
This is a somewhat holistic refactor of our behave machine provisioning and u-a-t installing code. It does a few things that I think in combination make the code simpler and clearer:
1. Adds a new installation source: "prebuilt" for CI. Previously "local" was used in that scenario but I think separating it makes each scenario more straightforward.
2. Redefines how we store machine instance objects on the behave `context`. We now store a tuple of the series and the pycloudlib instance. (Before we didn't keep the series info for each instance).
3. Uses commands to install u-a-t instead of user data. This allows us to separate the function for launching an instance from the function for installing u-a-t. So each can be reused.
4. Defines one function for launching an instance and uses it …
> tests: install uat with commands instead of user-data

- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
`kinetic` is not the devel release anymore - the upgrade tests depend on this change to pass.
Run the changed integration tests.
> tests: fix upgrade test from jammy to kinetic

- dev-docs/howtoguides/testing.md
- features/steps/machines.py
Driveby suggestion to align human-readable naming for integration tests so LXD cleanup scripting on shared jenkins workers can more easily match and force delete stale instances on worker nodes.
Note: this makes the existing instance tests one character longer than current names.
I'm not sure if we'll hit a length limit on some clouds.
```
tests: integration instance name human-readable %m%d-%H%M%S
To aid in cleanup of stale test instances and quick human-readable inspection of VMs on shared hardware, encode the time in the instance name in an easy to read format:
upro-behave-focal-lxd-vm-<month><day>-<hour><minute><second><micro>
Update test readme with valid line for tox -e behave-lxd exampleapplicable)
```
> tests: integration instance name human-readable %m%d-%H%M%S

- docs/explanations.rst
- docs/howtoguides.rst
- docs/index.rst
- docs/references.rst
- docs/tutorials.rst
```
The navigation menu is now consistent with those docs
rendered via Discourse, where the default state is for the
Diataxis sections to be collapsed by default.
The spelling inconsistencies were my own fault when I 
created the landing pages, so I have taken the opportunity
to fix them. 
Finally, I added the CC EAL acronym to the front page list
of services, to be consistent with the other services that
already had their acronyms shown.
```
> LHS nav bar now collapsed by default

- setup.py
- uaclient/event_logger.py
- uaclient/version.py
We rely on `version.py` (mainly on `get_version` to determine the version for the client for pretty much all situations, and this included `setup.py` of course.
The thing is: our package is installed on Ubuntu using apt, and all of the machinery is in place to properly version the package when building (whether locally or on PPAs) and report it appropriately.
The only tooling that relies on installing through setup.py is `tox`, for the tests, and we could not care less of what version it sees - currently it thinks it is running on 20.3 because of git tagging and runs fine.
The problem with `setup.py` importing from `version` brings the fact that `version` itself imports other modules, and:
a) There is no guarantee that those modules will not import version again, generating a circular …
> Do not import version on setup.py

- features/apt_messages.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/motd_messages.feature
- features/security_status.feature
- features/unattached_commands.feature
- features/unattached_status.feature
- uaclient/cli.py
- uaclient/entitlements/esm.py
- uaclient/entitlements/ros.py
- uaclient/entitlements/tests/test_esm.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_disable.py
- uaclient/tests/test_cli_enable.py
- uaclient/tests/test_cli_security_status.py
- uaclient/tests/test_cli_status.py
make esm-apps non-beta
Make `esm-apps` non-beta again. Because of that we are also making both `ros` and `ros-updates` non-beta as well
Verify that all existing esm-apps are not commented out and passing as expected
> Esm apps non beta

- CONTRIBUTING.md
- dev-docs/references/pr_review_policy.md
dev-docs: add PR review policy
Add document describing how the team handle PR reviews
Double check to see if the policy is correct
> dev-docs: add PR review policy

- lib/auto_attach.py
- uaclient/tests/test_lib_auto_attach.py
auto-attach: remove motd message if failure happen
On auto-attach, we add a MOTD message informing the users that auto-attach is running. However, we don't clear that message if the operation fails and returns early. We are changing that logic to always cleanup that message.
* Launch a Pro instance
* Check if the instance endup attached after boot
* Run `pro detach`
* Add the `disable_auto_attach` under `features` on config on `/etc/ubuntu-advantage/uaclient.conf`
* Reboot the machine
* Verify that the message no longer appears on MOTD
> auto-attach: remove motd message if failure happen

- .github/workflows/ci-base.yaml
ci_base: install -dev for older python versions
Solves this error when running flake8 command
```
fatal error: pyconfig.h: No such file or directory
#include "pyconfig.h"
```
> ci_base: install -dev for older python versions

- features/security_status.feature
- uaclient/messages.py
- uaclient/security_status.py
Finish reverting the commit which hid and "re-betaed" `esm-apps`.
Check and run integration tests for security status.
> security-status: advertise esm-apps again as non beta

- .github/PULL_REQUEST_TEMPLATE.md
We don't really use this for anything.
1. Rebase and merge is the chosen strategy for the team for a long while now
2. Merge commits are not a thing for a while too
3. Squashing implies commits divided for review but on the same functionality, which implies complexity, which implies (by PR policy) that we won't merge it without paying attention - so we will know when it is needed.
> chore: remove preferred commit type from GH PR template

- uaclient/system.py
system: make tempfile on the dir as target file
When calling the write_file function, we write the content of the file first on a temp file moving it to target file. We are now creating the temp file on the same folder of the target file to avoid errors due to the files being on different filesystems
Check if we can use the function to write a file on `/run` (This folder was the one that raised the issue being fixed)
> system: make tempfile on the dir as target file

- .github/workflows/check-secrets-available.yaml
- .github/workflows/ci-base.yaml
- .github/workflows/ci-integration.yaml
- .github/workflows/ci-workflows.yaml
```
ci: fix gh actions' warnings
Upgrade to actions/checkout@v3 and migrate to Environment Files instead of `set-output`.
```
> ci: fix gh actions' warnings

- features/api_packages.feature
There was an update to `libcurl4` which is our test reference package.
I decided to bump it instead of turn it into `\d+` so we can check for the specific output. Please let me know if you prefer the regex.
Run the integration test.
> tests: fix package versions in api integration test output

- features/magic_attach.feature
- features/util.py
- uaclient/cli.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/tests/test_cli_attach.py
cli: add magic-attach flow on CLI
Add support for the magic-attach flow through the `pro attach` CLI. This flow allows users to attach to Ubuntu Pro subscription without a token. When running `pro attach` without providing a token, the Pro client will output a user code on the screen and the user will then login into the Pro portal url and input that token there. Once that is done, our code will detect that and fetch the token directly from the Contract Server. Once we have the token, we can than attach as usual.
PS: We are still waiting on some functionality to be delivered to make that flow useful
> cli: add magic-attach flow

- features/security_status.feature
- uaclient/messages.py
- uaclient/security_status.py
Redesign the phrasing of outputs of security status to make support and update counts more explicit.
LP: #2002407
Verify and run the modified integration tests
> security-status: redesign output to properly show support (SC-1344)

- docs/howtoguides.rst
- docs/howtoguides/check_pro_version.md
- docs/howtoguides/configure_proxies.md
- docs/howtoguides/configuring_timer_jobs.md
- docs/howtoguides/create_pro_golden_image.md
- docs/howtoguides/enable_cc.md
- docs/howtoguides/enable_cis.md
- docs/howtoguides/enable_esm_infra.md
- docs/howtoguides/enable_fips.md
- docs/howtoguides/enable_in_dockerfile.md
- docs/howtoguides/enable_livepatch.md
- docs/howtoguides/enable_realtime_kernel.md
- docs/howtoguides/get_token_and_attach.md
- docs/howtoguides/how_to_attach_with_config_file.md
- docs/howtoguides/how_to_collect_logs.md
- docs/howtoguides/how_to_run_fix_in_dry_run_mode.md
- docs/howtoguides/how_to_simulate_attach.md
- docs/howtoguides/update_motd_messages.md
- docs/tutorials.rst
- docs/tutorials/basic_commands.md
- docs/tutorials/create_a_fips_docker_image.md
- docs/tutorials/create_a_fips_updates_pro_cloud_image.md
- docs/tutorials/fix_scenarios.md
```
Part 1 polishing (tutorials/how-tos)
- Tutorial and How-to landing pages have been revised/expanded.
- All tutorial/how-to pages have been "polished".
- Headings in the nav bar have been shortened for readability.
- All pages specifically ordered (no longer "random"). See below.
Goals here were improving navigation, readability, and
standardising.
Polishing = making sure pages conform to the Ubuntu style guide. 
Also includes minor language edits for clarity or to avoid word
repetitions, etc. Changed from passive to active, where possible.
All "notes" of all kinds have been standardised to the most
prevalent style used, which was the MyST Markdown format. I will 
add the various options for this to our style guide (current WIP).
The headings were good (descriptive :+1:) but a bit too …
```
> Part 1: docs styleguide polishing

- .github/workflows/ci-integration.yaml
- features/_version.feature
- features/api.feature
- features/attach_invalidtoken.feature
- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/collect_logs.feature
- features/daemon.feature
- features/detached_auto_attach.feature
- features/fix.feature
- features/install_uninstall.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
- features/unattached_commands.feature
- features/unattached_status.feature
- tools/run-integration-tests.py
- tox.ini
Also build the Lunar package on CI runs.
This way we can keep up with anything happening in builds, and have the option to test new things in the devel release.
Wait until the moon is lit and shining on the dark sky, grab a lobster, and then run the added/modified integration tests.
> tests: add first Lunar integration tests

- debian/ubuntu-advantage-tools.postinst
```
postinst: refactor PREVIOUS_PKG_VER as global var
Fixes: #2300
```
```bash
debuild -S
sbuild --dist=<dist> ../ubuntu-advantage-tools*.dsc
```
> postinst: refactor PREVIOUS_PKG_VER as global var (SC-1338)

- features/ubuntu_pro.feature
```
test ubuntu pro: add correct cloud-init user-data
```
https://github.com/canonical/ubuntu-advantage-client/pull/2277
> test ubuntu pro: add correct cloud-init user-data (SC-1270)

- debian/ubuntu-advantage-tools.postinst
- uaclient/contract.py
- uaclient/contract_data_types.py
- uaclient/data_types.py
- uaclient/event_logger.py
- uaclient/files/files.py
- uaclient/jobs/update_messaging.py
- uaclient/messages.py
- uaclient/serviceclient.py
- uaclient/status.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_contract.py
- uaclient/util.py
machine-token: avoid extra json parsing step by recognizing datetime fields
* uses DatetimeDataValue in PublicMachineToken data object to avoid an extra json.loads (DatetimeDataValue didn't exist at the time that was written)
data_types: fix error classes to be proper UserFacingErrors
* while fixing test cases from these changes, I found out that IncorrectFieldType errors fail during our main_error_handler function because they don't have msg_code or additional_info defined.
* This commit is the simplest fix to this - maybe not the best. I want a common IncorrectTypeError that all the more specific errors inherit from, and can't find a better way to make the constructors call super nicely. LMK what you think
util: always parse datetimes in readurl
* uses JsonDatetimeAwareDecoder in …
> more datetime json decoding

- features/fix.feature
- uaclient/security.py
- uaclient/tests/test_security.py
fix: better output structure
Separate blocks of content generated by ua fix using newlines.
PS: Note that this doesn't fully solve the Launchpad [issue](https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1926182), because when are actually installing package, we might prompt users and I am unsure if we should adapt the prompts too
> fix: better output structure

- uaclient/apt.py
- uaclient/tests/test_apt.py
This isolates the local apt esm cache in the function where it is updated.
There is no need to change it in the other places it is instantiated (security-status, stats hook) because there we only read the package names.
"Acquire" related vars are not cleared, so we can use the same download machinery as the system apt does.
This clears the concerns we had about our internal Cache writing/triggering things it should not.
- logs are dependent on the 'Dir' config entry, so we never log to `/var/log/apt` at all
- Hooks are removed when the config is clear and reinitialized, so none of them are triggered when our update runs
- Acquire related configuration defines how apt downloads things, and we need them preserved to make sure we can get our files the same way as the system is configured to …
> fix: make sure the local apt cache is isolated on update

- features/attached_enable.feature
- features/fix.feature
Fix the following integration tests by:
1) Update some CVE output on a xenial fix test, since the Security has
update them recently
2) Update the esm-infra check for the libkrad0 package
> tests: fix integration tests for new release

- debian/ubuntu-advantage-tools.postinst
- debian/ubuntu-advantage-tools.postrm
- debian/ubuntu-advantage-tools.preinst
Add check to not prompt user on apt_news changes
In the previous release we have changed the uaclient.conf file to capitalized a word. If the user has changed apt_news through pro config, the user will now get a debconf prompt because of it. This is not ideal, since we are the ones that instruct the user to run that command if they don't want apt advertisement on their system. This PR is creating a mechanism to avoid that prompt if the has just changed the apt_news config
Launch a lxd machine with an older version of the pro client (27.12) and runs either `pro config set apt_news=false` or `pro config set apt_news=true` and verify that upgrading to a package with those fixes applied do not generate a debconf prompt and keep the `apt_news` setting for the user
> Add check to not prompt user on apt_news changes

- apt-hook/20apt-esm-hook.conf
- sru/release-27.13.2/python-apt-snippet.py
- sru/release-27.13.2/test-apt-hook-nonroot.sh
There is a corner case happening in other people's test suites when updating the apt cache as non-root presents errors because systemd can't trigger the services we inserted in our hook.
This guarantees we only try to run stuff when we are root, which is the only case we are interested in.
Added a script to the `sru/` folder. 
Before merging, use the script as a base for a manual test.
For staging/proposed it is a matter of adapting the script when running.
> fix: only run the services in the apt hook when root

- debian/ubuntu-advantage-tools.preinst
preinst: fix md5sum check
The md5sum for for the situation where the user set apt_news to false on 27.13.1 and later is not entirely correct, as it is missing some values in the beginning of the hash. We are adding those missing characters
Guarantee that there is no prompt if the user modifies `apt_news` on either 27.13.1 or 27.13.2 and upgrades to this version of pro client
> preinst: add more md5sum checks

- debian/ubuntu-advantage-tools.preinst
preinst: restore correct uaconfig
If we need to restore a default uaconfig, we need to check which package version the user is running on, so that we can select the appropriate default values for the config
Launch a container and install pro version 27.13.1
Run `pro config set apt_news=true`
Upgrade to the version that contains this change
Verify that uaclient.conf is the default version for 27.13.1 (missing `update_status_timer` key)
> preinst: restore correct uaconfig

- features/steps/network.py
- features/unattached_commands.feature
CI does not always have ipv6 so it complains when changing `ufw`.
I'll follow @simondeziel 's suggestion here and just modify `/etc/hosts`
Run the renamed integration test
> tests: fix step to disable website for CI

- debian/ubuntu-advantage-tools.postinst
- sru/release-27.13.4/test-no-esm-apps-duplicates-attached.sh
- sru/release-27.13.4/test-no-esm-apps-duplicates.sh
Removes those from any release, as it shouldn't be there unless by mistake or accident.
LP: #2004193
Scripts provided under the `sru/` folder. The most important one is the unattached scenario, as it is the one which has problems with duplication.
The other script is used to show that nothing changes for an attached system.
To run:
`sru/release-27.13.4/test-no-esm-apps-duplicates.sh <release> 27.11.1~<release-number>.1 <how-to-install-new-ua>`
`sru/release-27.13.4/test-no-esm-apps-duplicates-attached.sh <release> 27.11.1~<release-number>.1 <how-to-install-new-ua> <token>`
The base UA version is 27.11.1, as this is the one which caused trouble - just adjust the numbers after the `~`.
"how to install new UA" is:
- 'proposed' if you want to install from proposed
- 'staging' to use the UA …
> postinst: remove stale esm-apps unauthenticated caches

- lib/esm_cache.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/system.py
- uaclient/tests/test_esm_cache.py
- uaclient/tests/test_system.py
system: use VERSION_CODENAME if needed
When parsing the VERSION field from `/etc/os-release`, we might not have the series in the `VERSION` string. If we detect that, we now fallback to `VERSION_CODENAME` for that info
Guarantee that no integration test fails due to this change or that we don't incorrectly fallback to `VERSION_CODENAME`
> system: use VERSION_CODENAME if needed

- uaclient/security_status.py
- uaclient/tests/test_security_status.py
If a package is installed, has a single origin reference, and the installed version is not even a candidate, then there is nothing we can say about the package.
LP: #2006049
> fix: consider packages without a candidate as 'unknown'

- dev-docs/howtoguides/building.md
- features/api_security.feature
- features/steps/shell.py
test: pin oscap to 1.3.7
We are pinning our tests to the latest,as of the pr time, of the oscap tool. 
It has solved the issue with the `invalid epoch` error message.
This [Oscap PR](https://github.com/OpenSCAP/openscap/commit/ce34cd227439e17248dfdf55b0fc19859c88d075) better explains.
> test: pin oscap to 1.3.7 to avoid epoch error message

- uaclient/cli.py
- uaclient/defaults.py
- uaclient/messages.py
- uaclient/security.py
- uaclient/tests/test_security.py
fix: add support for attach without a token
If during the fix operation we identify that we need a Pro service to install the package fix, we can now allow user to attach without a token.
On an unattached xenial machine, try running:
$ pro fix USN-5079-2
And type the `s` option when prompted for attach.
After that, make sure that the attach flow work as expected.
> fix: add support for attach without a token

- docs/index.rst
```
Now that the docs are live, they need to be linked up
with the forums. I have therefore added a link to the
beta invitation post made by Lech on Discourse. 
I have also reformatted the "get help" section slightly.
Please let me know if you think I need to tweak the
wording, or if you can think of any other links we should
add while I'm at it! 
```
> docs: add Discourse link to front page

- docs/howtoguides.rst
- docs/howtoguides/get_rid_of_corrupt_lock.md
- features/attached_enable.feature
- uaclient/config.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/tests/test_config.py
lock: alert the user about corrupted lock
If we detect we have a corrupted lock in the system, we are now alerting the user about that with steps to solve that scenario
LP: #1996931
Run the new integration test for this feature
> lock: alert the user about corrupted lock

- features/attach_validtoken.feature
- features/motd_messages.feature
- features/security_status.feature
- lib/timer.py
- uaclient/cli.py
- uaclient/files/state_files.py
- uaclient/jobs/tests/test_update_contract_info.py
- uaclient/jobs/update_contract_info.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_ua_timer.py
```
status: refactor update contract info to be a background job
At the moment, the backend service call to check if the
contract info has to be updated can be slow under load,
and this was executed during `pro status`, blocking it
during some seconds.
Move the update contract info check as a background job
to improve user experience.
```
> status: refactor update contract info to be a background job (SC-1411)

- uaclient/files/notices.py
- uaclient/files/tests/test_notices.py
```
notices: do not issue notices for non-root users
Prevent dummy warnings to appear in the status json output and
logging console for non-root users
LP: #2006138
```
https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/2006138
```sh
./tools/test-in-lxd.sh jammy
root@jammy$ pro attach <token>
root@jammy$ su ubuntu
root@jammy$ pro status --format=json
```
Previously, a bunch of `Trying to remove notice as non-root user` warnings appeared.
> notices: do not issue notices for non-root users

- docs/howtoguides.rst
- docs/howtoguides/disable_enable_apt_news.md
- features/apt_messages.feature
- uaclient/apt_news.py
On a fresh machine. make sure `/run/ubuntu-advantage` doesn't exist. Then run `apt update` and `apt upgrade` and verify that the apt news about phased updates is displayed.
> apt news bugfix and document how to disable

- docs/index.rst
```
FAQ has been published. This PR adds a link to the FAQ
from our docs index page. 
```
> docs: add link to FAQ from front page

- docs/index.rst
Fix typo in docs front page 
("official" was misspelled as "offical")
```
summary: no more than 70 characters
A description of what the change being made is and why it is being
made, if the summary line is insufficient.  The blank line above is
required. This should be wrapped at 72 characters, but otherwise has
no particular length requirements.
If you need to write multiple paragraphs, feel free.
LP: #NNNNNNN (replace with the appropriate Launchpad bug reference if applicable)
Fixes: #NNNNNNN (replace with the appropriate github issue if applicable)
```
> docs: fix typo ("offical") in front page

- features/environment.py
- features/util.py
I noticed that recently our test runs included some unexpected logging output. I found that the cause was calling `logging.debug` in the `before_scenario` behave hook. This commit fixes it.
Run the _version.feature and ensure that no logging is included in the output.
> tests: ensure logging doesn't leak into test output

- uaclient/cli.py
- uaclient/tests/test_cli_config.py
- uaclient/tests/test_cli_config_set.py
- uaclient/tests/test_cli_config_show.py
- uaclient/tests/test_cli_config_unset.py
```
cli: fix config subcommands usage help
Fixes: #2278
```
```
pro config set --help
pro config unset --help
pro config show --help
```
Verify that the `usage` part contains `pro config <sub-cmd> ...`
> cli: fix config subcommands usage help

- features/unattached_commands.feature
- uaclient/cli.py
- uaclient/config.py
- uaclient/entitlements/base.py
- uaclient/event_logger.py
- uaclient/files/data_types.py
- uaclient/messages.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_config.py
- uaclient/tests/test_event_logger.py
- uaclient/tests/test_yaml.py
- uaclient/yaml.py
When users install a new pyyaml using pip, it will end up in pythonpath with a higher priority.
This PR introduces some logic to import yaml only directly from the system dist-packages.
This fixes two bugs:
LP: #2007234 : If yaml is not present, then a UserFacingError is thrown - this can only happen if the `python3-yaml` deb is not present or was directly modified, and as it is a dependency, it does not make sense to support anything like this.
LP: #2007241 : The system yaml won't have a version which is incompatible with the python version, so the safe_load bug is prevented.
Added unit tests and integration tests to verify the fix.
> Force importing yaml from the system dist-packages

- uaclient/apt.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_cis.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/tests/test_apt.py
apt: remove one call to apt-cache policy
When checking if a repo service is enabled, we don't need to call apt-cache policy directly, as the information we need can be directly extract from python apt modules. This allow us to change the implemantion to not call that command directly, but instead using the python tools avaiable on python-apt to perform that check
I have also performed time comparison between `pro status` on a Xenial container with and without this change:
without: 2.095s
with: 2.234s
Notice however that I have not implemented any cache mechanisms for this code, which we can further discuss if it is necessary
Verify that are no integration test failures related to this change
> apt: remove one call to apt-cache policy

- docs/_static/css/custom.css
- docs/_static/css/github_issue_links.css
- docs/conf.py
```
A series of cosmetic docs changes that will make them look more like the
documentation produced on Ubuntu.com. It's not *exactly* the same, but
close enough to make it look recognisable as Canonical docs.
I made the "Have a question" link (top of the page) more prominent and
easier to spot. Hacky or not, it's a great feature that most docs miss
and I want people to be able to find it!
Although I tried to test this on a variety of screen sizes, if you spot
anything that doesn't render right or looks weird, please let me know. The
default font sizes were problematic from an accessibility pov so I made
them larger. They are still variable so they should render right on smaller
screens but it's possible I missed some.
Code literals are now the same size as regular font for the same …
```
> docs: cosmetic improvements

- docs/explanations/status_columns.md
- uaclient/contract.py
- uaclient/system.py
- uaclient/tests/test_contract.py
- uaclient/tests/test_system.py
contract: send machine_type when getting resources
When unattached, we send platform information to the contract server that replies with which services are available. One gap that we have is that some services are not available on all machine types. For example, Livepatch cannot be enabled on a container. We are now sending that information to the contract server so that they can take that information in consideration when informing which services are available.
Verify if the integration tests for unattached scenarios are still working as expected
> contract: send machine_type when getting resources

- debian/rules
- features/apt_messages.feature
apt-news: deliver hook on interim releases
We are now delivering the apt hook on interim releases to allow apt-news messages to appear during apt upgrade
Verify if the APT news integration test is now passing for Kinetic as well as the other LTS series
> apt-news: deliver hook on interim releases

- features/fix.feature
- uaclient/apt.py
- uaclient/messages.py
- uaclient/security.py
- uaclient/tests/test_security.py
fix: verify if package can be installed
When running a pro fix command, we check if the fixed package version is higher than the one currently installed. If it is, we try to update the package, but we don't check if the package can indeed be upgrade. For example, if the version that fix the error is higher than the package candidate version, we cannot install that fix. To address that, We are now checking the target package candidate version to address those potential scenarios
LP: #2006705
Run the new integration test for this scenario
> fix: verify if package can be installed

- features/realtime_kernel.feature
- features/steps/shell.py
- uaclient/apt.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/realtime.py
- uaclient/livepatch.py
- uaclient/messages.py
Run the existing fips_vm tests
Run the edited realtime test
Test the UX of enabling and disabling realtime in a VM
> realtime-kernel: remove `ubuntu-realtime` package on disable

- features/api_unattended_upgrades.feature
- features/util.py
- uaclient/api/api.py
- uaclient/api/data_types.py
- uaclient/api/exceptions.py
- uaclient/api/tests/test_api_u_unattended_upgrades_status_v1.py
- uaclient/api/u/unattended_upgrades/status/v1.py
- uaclient/apt.py
- uaclient/messages.py
- uaclient/system.py
- uaclient/tests/test_apt.py
- uaclient/tests/test_system.py
api: add support for unattended-upgrades status
We are now addding an endpoint to return unattended-upgrades status for users.
Run the new integration test for the api endpoint
> api: add support for unattended-upgrades status

- README.md
- docs/_static/js/github_issue_links.js
Our Readme TOC of docs was getting out of date, and now that we have rtd, we don't really need it.
I also added some new badges and made our existing badges link to more interesting things than the badge itself.
LMK if this does or doesn't make sense.
> readme changes - link to docs instead of a separate TOC

- features/fix.feature
- features/logs.feature
removing ca-certificates doesn't actually remove the file anymore
the log file may have old non-json lines at the beginning from test setup
> tests: fixups discovered while testing lunar

- uaclient/apt.py
- uaclient/conftest.py
- uaclient/security_status.py
- uaclient/tests/test_apt.py
apt: use context manager for handling apt config
Some apt functions require us to change the global apt config. Since we might be changing behavior on other parts of the code that require apt functionality, we are now using a context manager to guarantee that the original system config is kept after we call an apt function
> apt: use context manager for handling apt config

- debian/ubuntu-advantage-tools.postinst
- debian/ubuntu-advantage-tools.preinst
- sru/release-27.14/test-migrate-user-config.sh
save uaclient.conf backup after config migration
Since we are now migrating some of the uaclient.conf items into a different file, we are also leaving a backup file behind, uaclient.conf.dpkg-bak, in case the user has made some comments on the original config file. This will allow the user to retrieve those comments if needed
Run the modified `sru/release-27.14/test-migrate-user-config.sh` test script
> save uaclient.conf backup after config migration

- uaclient/apt.py
apt: modify check for Acquire keys for esm cache
Use regex to guarantee that only `Acquire` keys are left in the apt configuration when creating the esm cache
Check if the esm-cache creation is still working as expected
> apt: modify check for Acquire keys for esm cache

- debian/changelog
- features/livepatch.feature
- tools/run-integration-tests.py
- tox.ini
- uaclient/entitlements/livepatch.py
- uaclient/version.py
livepatch treats Ubuntu Release version support differently from how it treats kernel version/flavor/arch support. The Ubuntu Release is checked against hardcoded list and causes the canonical-livepatch command to raise errors. Because of this, we need to use the Contract Server-defined series affordance to prevent even attempting to install and run canonical-livepatch on unsupported releases (interim releases).
`pro attach` on an interim release vm. ensure we don't try (and fail) to enable livepatch
> livepatch: check series affordances again

- apport/source_ubuntu-advantage-tools.py
- lib/apt_news.py
- lib/auto_attach.py
- lib/daemon.py
- lib/esm_cache.py
- lib/reboot_cmds.py
- lib/timer.py
- uaclient/cli.py
- uaclient/data_types.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_api.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_cli_auto_attach.py
- uaclient/tests/test_cli_collect_logs.py
- uaclient/tests/test_cli_disable.py
- uaclient/tests/test_cli_enable.py
- uaclient/tests/test_cli_fix.py
- uaclient/tests/test_cli_reboot_required.py
- uaclient/tests/test_cli_refresh.py
- uaclient/tests/test_cli_security_status.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_data_types.py
Continuation of #2486.
```
logging: setup logging with defaults before the config is read
Previously, we didn’t call setup_logging until after reading
the config (because the config can affect how we setup logging).
Set up the logging with defaults before reading the config to
capture logs from the start of the cli and lib entry-points.
Capture those default log files in apport.
data_types: warn on wrong data types.
```
```
$ ./tools/test-in-lxd.sh
$ pro status
$ head /var/log/ubuntu-advantage.log
["2023-03-14T10:50:12.797", "DEBUG", "uaclient.config", "parse_config", 670, "Using client configuration file at /etc/ubuntu-advantage/uaclient.conf", {}]
["2023-03-14T10:50:12.797", "DEBUG", "root", "load_file", 373, "Reading file: /etc/ubuntu-advantage/uaclient.conf", {}] …
```
> logging: setup logging with defaults before the config is read (SC-1428)

- debian/ubuntu-advantage-tools.postinst
The old warning would be shown even if ua_config: was commented out. By ensuring we only warn when the line begins with ua_config: we don't warn in this situation where it is unnecessary.
On the previous version of pro-client edit uaclient.conf to say
```
#ua_config:
{{ <- this causes the migration to fail
```
Then upgrade to this version. Ensure there is no warning about "ua_config" being present in the config
> postinst: more specific regex for ua_config warning

- uaclient/security_status.py
- uaclient/tests/test_security_status.py
This state also indicates that because Livepatch seems to be working correctly for your kernel. It just means no Livepatches have been issued yet.
In a fresh jammy vm with this version of pro-client installed:
- fake a kernel reboot-required by running `touch /run/reboot-required && echo "linux-image" >> /run/reboot-required.pkgs`
- `pro attach`
-  ensure `canonical-livepatch status --format json` says "nothing-to-apply"
- ensure `pro system reboot-required` says "yes-kernel-livepatches-applied"
> reboot-required: livepatch is working when "nothing-to-apply"

- uaclient/system.py
Inspired by #2414, but different because, per the [manpage of os-release](https://manpages.ubuntu.com/manpages/lunar/man5/os-release.5.html): "The file /etc/os-release takes precedence over /usr/lib/os-release. Applications should check for the former, and exclusively use its data if it exists, and only fall back to /usr/lib/os-release if it is missing."
Also remove unused argument to parse_os_release
Tests should still pass
> system: fall back to /usr/lib/os-release

- features/security_status.feature
- uaclient/messages.py
- uaclient/security_status.py
Those are output changes to security-status to mitigate some problems while a deeper redesign of the outputs is not defined.
- instead of `apt-cache policy`, tell users to run `apt=cache show` to get information about packages
- only show those hints if calling with `--esm-infra` or `--esm-apps` flags, and if there is some actual relevant package
- always show the counts for installed and available updates from ESM
- organize the package lists for better readability and grepability (is this a word?)
Fixes: #2442
Fixes: #2443
Check the outputs and integration test changes
no-lp btw
> Security status output improvements (SC-1470) (SC-1471) (SC-1404)

- uaclient/system.py
- uaclient/tests/test_system.py
no-lp
subp: use system environment vars by default
We are now always using the default system environment variable when running a subprocess command. This will allow user setting to be propagated to other tools we run during some Pro operations.
Fixes: #2527
Run the new unit test
> subp: use system environment vars by default (SC-1529)

- features/attach_validtoken.feature
- features/attached_status.feature
- features/unattached_status.feature
- uaclient/cli.py
- uaclient/messages.py
- uaclient/status.py
- uaclient/tests/test_cli_status.py
Instead of showing an empty services table on pro status, just put a message saying no service is available. Plus, add a hint for the `-all` flag if one wants to see everything Ubuntu Pro has to offer.
Integration tests properly added/modified.
no-lp no-gh
> `pro status` improvements (SC-1360)

- tox.ini
- uaclient/tests/constraints/constraints-jammy.txt
Those match the package versions released in Jammy.
This PR solves all of our problems because we need to verify that all works well not only using Python3.10, shipped in Jammy, but also all other dependencies with specific versions.
`tox -e py310-test`
`tox -e py310-flake8`
verify that all is good
- [kinda] I have updated or added any unit tests accordingly
> chore: add constraints to the Python 3.10 testing

- features/fix.feature
- uaclient/apt.py
- uaclient/messages.py
- uaclient/security.py
- uaclient/tests/test_apt.py
- uaclient/tests/test_security.py
fix: check candidate related to package origin 
When checking the candidate version during the pro fix command, we must ensure that we are fetching the candidate version for the origin that the CVE/USN says contains the fix
> fix: check candidate related to package origin 

- features/fix.feature
- uaclient/security.py
- uaclient/tests/test_security.py
no-lp no-gh no-jira
This PR fixes a couple of integration tests that are related to the `fix` command by:
* Changing the way we check if a CVE/USN doesn't exist
* Sorting binary packages that cannot be installed
Check if the modified integration tests are now working properly
> Update fix tests

- features/realtime_kernel.feature
- features/steps/shell.py
- uaclient/actions.py
- uaclient/cli.py
- uaclient/contract.py
- uaclient/entitlements/__init__.py
- uaclient/entitlements/base.py
- uaclient/entitlements/realtime.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_entitlements.py
- uaclient/entitlements/tests/test_realtime.py
- uaclient/event_logger.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/status.py
- uaclient/system.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_cli_detach.py
- uaclient/tests/test_cli_disable.py
- uaclient/tests/test_cli_enable.py
- uaclient/tests/test_cli_status.py
- uaclient/tests/test_contract.py
- uaclient/tests/test_status.py
- uaclient/tests/test_system.py
no-lp no-gh
Add support for realtime-kernel variants
This PR is adding the whole variant support to the Pro client, while also defining specific variants for the realtime-kernel service. I still need to add the affordances check for the nvidia variant, but this should not block the review for this PR.
Run the modified realtime-kernel integration test
> Add variant support to realtime-kernel (SC-1465)

- features/livepatch.feature
- uaclient/defaults.py
- uaclient/files/files.py
- uaclient/files/state_files.py
- uaclient/log.py
- uaclient/system.py
- uaclient/tests/test_system.py
Fixes: #2567
no-jira no-lp
Designed so that it should integrate nicely with #2503 
`time pro status`
see /home/ubuntu/.cache/ubuntu-pro/livepatch-kernel-support-cache.json
`time pro status` - much shorter because cache was used now
change the kernel and reboot
`time pro status` - longer again because cache was invalid
see /home/ubuntu/.cache/ubuntu-pro/livepatch-kernel-support-cache.json was updated
`time pro status` - much shorter because cache was used now
> cache: use user owned cache for livepatch support

- uaclient/tests/test_util.py
- uaclient/util.py
no-gh no-jira
If we cannot handle unicode characters in the output we remove any of those characters from the message.
This is to guarantee that users that are not using UTF-8 by default can still use the tool
Run the new unittest added
> ignore any unicode char if we can't print it

- uaclient/actions.py
- uaclient/contract.py
- uaclient/tests/test_actions.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_contract.py
- uaclient/timer/metering.py
- uaclient/timer/tests/test_update_messaging.py
- uaclient/timer/update_messaging.py
We are renaming some of the contract module methods to align with their definition on the contract backend.
The idea is to make it easier to communicate with the contract team and to debug the code together
Verify that no integration tests are now breaking because of this change
> contract: rename function to align with backend

- .github/actions/bug-refs/index.js
This PR is exploring adding a comment to each PR explaining the results of the bug-refs (future "does doc PR also exist") action.
We no-longer need to write no-jira no-lp no-gh. Instead we'll just ack the comment, and part of review is making sure the comment is acked and correct.
> ci: change bug-refs action to post comment

- uaclient/security_status.py
- uaclient/tests/test_security_status.py
This PR solves all of our problems because we have bugs open about security status, or more precisely the updates API endpoint, not working without an internet connection.
That's because we call `status` while unattached, and try to hit the unauthenticated endpoint.
Now we don't anymore.
Fixes: #2536
LP: #2015286
- cut your access to `contracts.canonical.com`
- run `pro security status` and see now it runs fine
- run `pro api u.pro.packages.updates.v1` and see now it runs fine
> security-status: don't call status

- features/livepatch.feature
- uaclient/entitlements/livepatch.py
- uaclient/livepatch.py
- uaclient/messages.py
- uaclient/status.py
- uaclient/tests/test_livepatch.py
The new integration test should pass.
Notice that the older integration test -- the first one in livepatch.feature -- is failing with the new implementation. This is exposing a bug in livepatch where unsupported kernels are being reported as "unknown" support by the livepatch-client. So it is "correct" to be failing :/
> livepatch: display tailored warnings for new support statuses (SC-1538)

- features/unattached_commands.feature
- tools/ua.bash
Instead of relying on pro --help and the valid_services function, we are now directly listing the available services and commands. The reason for that is because the past approach was making unwanted requests to the contract server.
Fixes: #2556
Check if the modified integration tests are still working
> autocomplete: update services and commands

- features/unattached_commands.feature
- uaclient/cli.py
- uaclient/messages.py
- uaclient/tests/test_cli.py
This PR solves all of our problems because we will change human readable outputs and, if people are scripting it, we want to warn them that there is machine readable output instead.
> cli: warn users not to use human readable output in scripts (SC-1553)

- uaclient/actions.py
- uaclient/api/exceptions.py
- uaclient/contract.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/tests/test_cli_attach.py
- uaclient/tests/test_cli_auto_attach.py
If we can attach the machine, but we fail to enable any service during the process, we will exit with a return code of 3
Verify that the new unit test is working as expected
> auto-attach: add new return code

- features/realtime_kernel.feature
- uaclient/contract_data_types.py
- uaclient/util.py
Save variant related information on the public machine token file. This allow non-root users to see variant information when running pro status
1. Launch a jammy machine
2. Attach a staging token
3. run pro status as non-root and confirm that you can variant information
> variant: save info on public machine token file

- debian/source/lintian-overrides
This overrides an invalid lintian error. We'd like to fix this for version 28.
Build and run lintian. Make sure there are no errors on jammy++
> lintian: override invalid error where lintian doesn't evaluate second debhelper dep

- features/environment.py
If we have not set the ssh keys when running integration tests, we might accidentally delete the ssh keys stored in the user .ssh folder. We are checking to see if the keys are stored in that folder before deleting it
Run any integration test requesting the `wip` tag to be present. Certify that no test will run and the `.ssh` keys are not deleted.
> tests: do not delete user ssh keys on cleanup

- features/util.py
Helps maintain the user's system sbuild config
This PR will make it easy for anyone who has any configuration in one's .sbuildrc file to build the debs;
especially if the config specifies `build_dir`
```bash
#!/bin/bash
RED='\033[0;31m'
BLUE='\033[0;36m'
NC='\033[0m'
mkdir /tmp/pro_ua_sbuild
echo "# Adding sbuild configuration from pro client testing">>~/.sbuildrc
echo "\$build_dir='/tmp/pro_ua_sbuild';">>~/.sbuildrc
echo "1;" >> ~/.sbuildrc
./tools/build.sh jammy
echo -e "${BLUE}ls /tmp/pro_ua_sbuild${NC}"
ls /tmp/pro_ua_sbuild
echo -e "${BLUE}ls /tmp/uaclient-behave/sbuild/${NC}"
ls /tmp/uaclient-behave/sbuild/
echo -e "${BLUE}ls /tmp/uaclient-behave/deb-cache${NC}"
ls /tmp/uaclient-behave/deb-cache
rm -rf /tmp/pro_ua_sbuild
echo -e "${RED}Please delete the extra lines in …
```
> sbuild: specify build dir

- systemd/ua-auto-attach.service
- systemd/ua-reboot-cmds.service
- systemd/ua-timer.service
- systemd/ua-timer.timer
- systemd/ubuntu-advantage.service
- uaclient/apt.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_cc.py
- uaclient/entitlements/tests/test_cis.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/security.py
- uaclient/system.py
- uaclient/tests/test_system.py
See https://code.launchpad.net/~orndorffgrant/ubuntu/+source/ubuntu-advantage-tools/+git/ubuntu-advantage-tools/+merge/443833/comments/1184537 for the reasoning behind these changes.
Copying the commit message about the changes to subp env here for convenience:
```
refactor: replace confusing env arg to subp
The only reason the env argument was used was for inserting values that
were intended to be additional environment variables on top of the
current process' environment. There were also issues with modifying
default arg values and modifying caller-provided dicts to the env
argument.
To address this, I'm renaming the argument to make it clear it is
treated differently than the stdlib's "env" argument to various
subprocess functions. I've also removed all related default arg values
of {} …
```
> Release 28 rc feedback

- README.md
- debian/control
- debian/copyright
- dev-docs/howtoguides/code_formatting.md
- dev-docs/howtoguides/release_a_new_version.md
- dev-docs/howtoguides/testing.md
- docs/index.rst
- setup.py
- sru/README.md
- tools/setup_sbuild.sh
- uaclient/util.py
This PR solves all of our problems because we are not advantage anymore, we are pro now.
Plus copyright is updated.
> Rename more ubuntu-advantage occurrences to ubuntu-pro

- debian/changelog
- features/unattached_commands.feature
- uaclient/version.py
This PR solves all of our problems because we used to have 28 as the devel version, but now 28 is being released, and will be followed by 29, 30, etc - bumping an epoch makes the devel version greater than any released version. Making 'devel' part of the version makes it explicit that this is not a supported version.
build from source locally
install the deb
see version is now `1:1+devel'
> chore: bump development version in the changelog

- features/fix.feature
- uaclient/security.py
- uaclient/tests/test_security.py
When we are gathering related USNs, we must ensure that they are indeed USNs. To do that, we are ignoring any security id that doesn't start with USN
> fix: ignore non-USN items on related usns

- debian/changelog
- uaclient/entitlements/fips.py
- uaclient/status.py
- uaclient/version.py
`pro enable fips && reboot` on a focal machine with secureboot resulted in a broken machine.
`pro status && pro status --simulate-with-token token` resulted in inaccurate availability results.
We consider these show-stoppers for release 28.
```
tox -e behave-lxd-18.04 -- features/unattached_status.feature -n "Simulate"
tox -e behave-lxd-20.04 -- features/unattached_status.feature -n "Simulate"
tox -e behave-lxd-22.04 -- features/unattached_status.feature -n "Simulate"
tox -e behave-vm-20.04 -- features/enable_fips_vm.feature:394
tox -e behave-vm-20.04 -- features/enable_fips_vm.feature:540
```
> Release 28.1

- debian/README.source
This PR solves all of our problems because it brings a readme file explaining where the u-a-t source code lives, and files from the source package that are not present in the binaries - and thus don't need a very strict review on SRUs.
This is enough to
Fix: #2463
> debian/README: add file with basic explanation on the source code

- features/apt_messages.feature
- features/attached_enable.feature
- features/collect_logs.feature
- features/logs.feature
- features/motd_messages.feature
- features/security_status.feature
- features/ubuntu_upgrade_unattached.feature
This PR solves all of our problems because now we have the tests which require a token to run well defined.
If the whole feature requires attachment, require it on feature level. If the feature does not imply attachment, require it on scenario level.
Run the CI suite without a token, see that no test fails because you don't have the token, and that those which require the token were skipped.
> tests: require contract token in the correct tests

- uaclient/system.py
This PR solves all of our problems because this avoids a possible inconsistent state between checking if a file exists and trying to remove it.
LP: #2025731
Unsure on how to replicate this without mocks...
> system: try/except logic to remove files and folders

- features/apt_messages.feature
- features/steps/machines.py
- uaclient/api/api.py
- uaclient/api/u/apt_news/current_news/v1.py
- uaclient/apt_news.py
- uaclient/files/state_files.py
- uaclient/messages.py
- uaclient/tests/test_apt_news.py
Desktop update-manager needs to integrate apt-news, so we need to provide an api function for them to get the current apt news. This way they won't need to re-implement any of the aptnews.json parsing logic.
Run the new version of the apt-news test
> api: u.apt_news.current_news.v1

- features/apt_messages.feature
- features/attached_enable.feature
- features/motd_messages.feature
- features/ubuntu_pro.feature
- tools/run-integration-tests.py
These were the extra test fixes needed on top of the release branch for verifying 28.1
First commit is already in main. The second will be brought over to main in a separate PR.
> Release 28 verification fixes

- features/steps/machines.py
- features/steps/ubuntu_advantage_tools.py
- features/util.py
This PR solves all of our problems because if we set the install_from and debs_path variables correctly, but the debs_path has no debs for the specific series, we silently run the test with whatever version if u-a-t is in the image. This leads to unexpected errors.
Create some empty folder, run CI with debs_path pointing there and set install_from to prebuilt.
See it crash.
> tests: fail if installing from 'prebuilt' but no debs are found

- features/anbox.feature
- uaclient/entitlements/base.py
- uaclient/entitlements/tests/test_base.py
We are changing `classic_confinment_support` to the
cammel case representation. That is because cammel case is the standard support on the Contract server
> anbox: turn contract directive to cammel case

- features/attached_enable.feature
- uaclient/api/tests/test_api_u_pro_security_status_reboot_required_v1.py
- uaclient/api/u/pro/security/status/reboot_required/v1.py
- uaclient/security_status.py
- uaclient/system.py
- uaclient/tests/test_security_status.py
- uaclient/tests/test_system.py
The reboot required enpoint just inform the users if a reboot is required or not. However, it does not provide the data we used to generate that decision. We are updating the endpoint to provide all of this data, allowing our users to better understand the decision making process or even adapt it based on their own needs.
Run the new integration test added
> Add more data to reboot_required endpoint

- CONTRIBUTING.md
- README.md
This PR solves all of our problems because the links are broken - the files they reference now live in a different branch.
It is not ideal that we use the /blob/ links, but the links in CONTRIBUTING should be updated again to point to readthedocs when the development documentation is published there.
click all the links and make sure they are not broken (:
> docs: fix broken links in README and CONTRIBUTING

- .readthedocs.yaml
This PR will skip the RTD build on dev PRs.
RTD job on this PR should get skipped :crossed_fingers: 
> docs: skip PR builds on PRs to main

- uaclient/entitlements/base.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/exceptions.py
- uaclient/messages.py
- uaclient/snap.py
- uaclient/tests/test_snap.py
This PR solves all of our problems because we don't need two ways to check if snapd is there. If the package is installed, then the command exists. Otherwise, we install it and it creates the binary. Weird combinations (overriding the binary??) is not supported, so we don't need to check for that.
It is refactor-ish, so CI should take care of this.
> Look for the snapd package instead of looking for the snap command

- features/airgapped.feature
- features/attached_enable.feature
- features/ubuntu_pro.feature
- features/ubuntu_pro_fips.feature
- preferences.d/ubuntu-pro-esm-apps
- preferences.d/ubuntu-pro-esm-infra
- setup.py
- sru/release-29/test-esm-pinning.sh
This PR solves all of our problems because it 
Fixes: #2580
context is provided in the issue and the internal spec
This is a version of #2664 which does not change the existing FIPS logic - thus, we have both ways to pin repositories (static and dynamic) at the same time. #2680 was created to reflect the next steps of this work.
Run CI and the new `sru/` test.
> Pin esm but only esm

- uaclient/contract.py
Machines attached with a pro version <=28.1 don't have a lastAttachment time. The fallback value of "" was trying to be parsed by the contract server, which resulted in errors. The new fallback value of `None` is treated as nil by the backend and isn't parsed.
```
env SHELL_BEFORE=1 ./tools/test-in-lxd.sh xenial
apt update
apt install ubuntu-advantage-tools
pro attach $token
exit # new version gets installed after exit and lxc shell is re-started
sudo pro disable esm-infra
```
> contract: change default value of lastAttachment so server doesn't try to parse empty string

- preferences.d/ubuntu-pro-esm-apps
- preferences.d/ubuntu-pro-esm-infra
This PR solves all of our problems because it explains in the preference files that we are pinning services for when those are enabled.
Nothing should really change
> esm: add comment to preference files

- features/magic_attach.feature
- features/util.py
The staging esm environment is presenting some problems when the apt-helper command tries to verify the credential for some services. We are now switching for the production environment to mitigate that issue
> tests: use prod environment for magic-attach test

- docs/references/network_requirements.md
This PR solves all of our problems because it adds the security URL to the network requirements.
> docs: update network requirements with fix endpoint info

- docs/explanations/about_esm.md
This PR solves all of our problems because it exposes the pinning of the esm services, and adds a pointer to the relevant configuration documentation.
> docs: add entry about pinning esm-infra and esm-apps

- uaclient/config.py
In Livepatch UAConfig is called directly, when it should actually receive the current cfg as an argument.
Solves some mocking issues when we have config files on our machines, i.e. user-config.json
- Create the file `/var/lib/ubuntu-advantage/user-config.json` with the following content:
```
{"metering_timer": "notanumber", "update_messaging_timer":-10}
```
- run `tox -e test`
> config: pass cfg object to Livepatch

- features/attached_commands.feature
- features/steps/machines.py
iscsid.service has been getting intermittent resource errors when restarted as part of a full apt upgrade to ESM on xenial containers. This only seems to happen on our github runners and I haven't been able to reproduce it locally. Since this service isn't necessary for testing pro-client, we can mask it to let the tests continue.
All I want is for CI to be green
> tests: mask iscsi service to avoid intermittent errors on github runners

- lib/reboot_cmds.py
- lib/timer.py
- uaclient/actions.py
- uaclient/cli.py
- uaclient/config.py
- uaclient/contract.py
- uaclient/entitlements/base.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/landscape.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/files/notices.py
- uaclient/http/__init__.py
- uaclient/livepatch.py
- uaclient/snap.py
- uaclient/system.py
- uaclient/tests/test_cli.py
- uaclient/tests/test_esm_cache.py
- uaclient/tests/test_util.py
- uaclient/timer/update_contract_info.py
- uaclient/util.py
- uaclient/yaml.py
This removes some old code around conditionally logging messages to the console. In most cases, that is what we do, and in some of the few cases where we didn't disable the console logger, that was a bug.
We should treat the console as our cli UX and treat the logs as logs. There should be no instance where a log message is also part of our UX. In the rare case where we want to print the same message to the User and our logs, then that can be two separate statements.
The exception is the `--debug` flag which is useful to include log statements in the middle of the console output - that functionality is kept and enhanced by removing the formatter that stripped a lot of useful information from those logs.
CI should pass.
Please review all instances of logging.info, logging.warn, …
> logging: no more cli console logging

- lib/patch_status_json.py
- lib/upgrade_lts_contract.py
During the refactor that changed cli.setup_logging to no longer setup a console logger, not all callsites were updated. This should fix the last of them.
Search for all callsites of cli.setup_logging. Make sure they are all correct.
> logging: fix calls to cli.setup_logging

- docs/explanations.rst
- docs/explanations/how_to_interpret_output_of_fix_plan_api.md
This is an explanation of how the fix plan API endpoint works. It details the operations, warnings and errors that can happen
> docs: add explanation for the fix plan API

- features/anbox.feature
- features/attached_enable.feature
- features/steps/packages.py
- features/ubuntu_pro.feature
- features/ubuntu_pro_fips.feature
This is an accidental wrong word, it is only used inside the tests and not bleeding to a user or any such. Hence it can be fixed, but has no urgency.
Fixes: #2719
It resolves an accidental typo
Run the tests and watch the output no more speaking of "url permission" but instead of "priority".
(This isn't in the code active on a Ubuntu system, only in the self tests)
> tests: fix typo permission -> priority

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
This PR solves all of our problems because it adds issue templates to guide users when opening an issue.
And it 
Fixes: #2646
- Merge this PR
- Try to open an issue against the `ubuntu-pro-client` repository
- If something is odd/wrong, please open an issue against the `ubuntu-pro-client` repository
> github: add issue templates

- features/cloud.py
- features/enable_fips_cloud.feature
Add a scenario where cloud-init is disabled after boot. In that situation there is no cloud-id command anymore. To test that the Pro client doesn't break, we will enable FIPS on a cloud instance to show that service is indeed enabled even though the cloud metapackage is not installed
This is also needed because there is a Launchpad [bug](https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1938208) that address the lack of this test
> tests: add scenario where cloud-init is disabled

- features/attached_commands.feature
- features/attached_status.feature
- features/unattached_status.feature
Now that ros is supported on Focal, we are updating the Focal test that show the ros status in the output
Run the modified tests and guarantee they are working as expected
> tests: fix ros status on Focal

- features/realtime_kernel.feature
- uaclient/contract.py
- uaclient/tests/test_contract.py
When reporting about the machine status, we are now also sending if a variant of a service is enabled. This will allow the
Contract Server to better track which services are being use
Confirm that the `_get_activity_info` method is now correctly returning  `resourceVariants` if variants are enabled and it is empty when no variant related service is enabled
> Send variant information to cs

- lib/daemon.py
- systemd/ubuntu-advantage.service
This PR solves all of our problems because we have a dependency on python3-systemd to use the 'notify' function, which cannot be satisfied as the package is not part of ubuntu-minimal. This dependency was never declared in the debian/control file anyway, and we are removing it.
We don't lose much in the change anyway, as we are only configuring logging before notifying.
Fixes: #2692
Execute all behave features which involve the `ubuntu-advantage.service` and see them all passing
> systemd: change u-a.service type from notify to exec

- apt-hook/json-hook.hh
This PR uses the int type that the format strings expect in the apt-hook.
This is important because on non-64-bit systems we'd get warnings and errors along the lines of:
```
164 |                     gettext("%lu standard LTS security updates"),
|                              ~~^
|                                |
|                                long unsigned int
|                              %llu
165 |                     counts.standard
|                     ~~~~~~~~~~~~~~~
|                            |
|                            int64_t {aka long long int}
```
`make -C apt-hook test` on i386?
> apt-hook: use arch-dependent int types for formatting

- uaclient/cli/fix.py
The attribute of a message for Ubuntu Pro cloud advertisement need to be update, since it is no longer matching the definition on the messages module
Guarantee that the message attributes are being correctly used
> fix: update message for cloud advertisement

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/enable_fips_container.feature
- features/enable_fips_pro.feature
- features/enable_fips_vm.feature
- features/ubuntu_pro.feature
- features/ubuntu_pro_fips.feature
- features/unattached_status.feature
- uaclient/cli/tests/test_cli.py
- uaclient/cli/tests/test_cli_collect_logs.py
- uaclient/cli/tests/test_cli_disable.py
- uaclient/cli/tests/test_cli_enable.py
- uaclient/cli/tests/test_cli_status.py
- uaclient/entitlements/__init__.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/messages/__init__.py
- uaclient/tests/test_status.py
This create the necessary structure for the Pro client to support the fips-preview service
Guarantee that the new `fips-preview` test is working as expected
> fips-preview: add service support

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- uaclient/apt.py
- uaclient/cli/__init__.py
- uaclient/cli/tests/test_cli_disable.py
- uaclient/entitlements/anbox.py
- uaclient/entitlements/base.py
- uaclient/entitlements/cc.py
- uaclient/entitlements/cis.py
- uaclient/entitlements/entitlement_status.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/realtime.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/ros.py
- uaclient/entitlements/tests/conftest.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/messages/__init__.py
- uaclient/security_status.py
- uaclient/system.py
- uaclient/tests/test_apt.py
- uaclient/tests/test_security_status.py
- uaclient/util.py
This is intended to land after #2744 - it contains the commits from there and will be rebased on whatever lands on that side.
still missing: integration tests
This PR solves all of our problems because it implements the purge option when disabling services involving apt repositories. This removes/downgrades all the packages from that specific source.
Integration tests still to come - but generally run disable for all services with `--purge` and see what happens :D
> Purge option for RepoEntitlements

- features/airgapped.feature
- features/attached_enable.feature
- features/ubuntu_pro.feature
- features/ubuntu_pro_fips.feature
- preferences.d/ubuntu-pro-esm-apps
- preferences.d/ubuntu-pro-esm-infra
- setup.py
This PR solves all of our problems because we had merged this before, but needed to revert due to unforeseen image build time circumstances. Now we are bringing those changes back.
Updated integration tests show it all.
> Reinsert pinning of the ESM services

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/attached_commands.feature
- features/steps/packages.py
- uaclient/apt.py
- uaclient/entitlements/base.py
- uaclient/entitlements/entitlement_status.py
- uaclient/entitlements/realtime.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/messages/__init__.py
- uaclient/tests/test_apt.py
This PR solves all of our problems because it brings integration testing to the `disable --purge` feature, and fixes some things here and there which were not working out:
- improve on how to look for alternative package versions, considering multi-origin and keeping installed versions when feasible
- not relying on apt_pkg.Error all the time (thanks Xenial support we love it)
- defining that some services just can't be purged
This is mainly about adding integration tests so it is straightforward - run the new behave stuff
> release 30: add integration tests and fixes for the disable --purge functionality 

- debian/ubuntu-advantage-tools.prerm
- uaclient/apt.py
- uaclient/tests/test_apt.py
LP: #2021988
Importing our python module in prerm exposes the packaing script to all the complexity of our python and the risk that a seemingly unrelated change in the python could affect the prerm script.
This happened when we started relying on python3-apt and resulted in LP: #2021988
This PR removes the python import entirely and instead hardcodes the files that need to be removed.
```
./tools/test-in-lxd.sh xenial
pro attach
apt remove ubuntu-advantage-tools
ls /etc/apt/sources.list.d
```
> refactor: simplify prerm to not import python

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- uaclient/api/u/pro/security/status/reboot_required/v1.py
- uaclient/entitlements/base.py
- uaclient/entitlements/entitlement_status.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/livepatch.py
- uaclient/messages/__init__.py
- uaclient/security.py
- uaclient/security_status.py
- uaclient/tests/test_livepatch.py
If the canonical-livepatch status command fails, we can mistakenly tell the users that Livepatch is disabled. This is an incorrect behavior as we should alert the users about the error. We are now reflecting that went wrong with the command on the output of pro status.
LP: #2019997
1. Launch a Jammy LXD VM
2. Attach it to a Pro subscription
3. Verify that that there is a warning for Livepatch when running `pro status` (warning due to kernel incompatibility)
4. Switch to ubuntu user
5. Run `pro status` again and verify that we output an error running `canonical-livepatch status`
> livepatch: better inform if command fails

- features/api_fix_plan.feature
- uaclient/api/u/pro/security/fix/__init__.py
There is a corner case scenario where we end up with a src_pocket_pkgs variable unset. We are now fixing this issue by using a default value for this variable
> plan: fix error when variable is not set

- features/collect_logs.feature
- sru/release-31/test-jobs-status-world-readable.sh
- uaclient/files/state_files.py
When running collect-logs as non-root, we might fail trying to collect the jobs-status information. Since there is no private date in this file, we are making it world readable now.
Fixes: #2601
Run the modified integration test and the manual test in this PR
> timer: make jobs-status file world readable

- uaclient/apt.py
- uaclient/tests/test_apt.py
This is a simple commit addressing @bryceharrington 's comment in the LP MP
> apt: improve doc+test for get_remote_versions_for_package

- features/livepatch.feature
- uaclient/entitlements/base.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_livepatch.py
- uaclient/snap.py
- uaclient/tests/test_snap.py
If a service requires installing the `core22` snap, and snapd hasn't already bootstrapped itself as a snap (like it does when installing some other snaps), then the snap install will fail. To prevent this, we check before installing the actual snap if snapd is installed as a snap. If it isn't, we run `snap install snapd`.
New integration test will pass with these changes and fail on the archive version
```
tox -e behave-any -- -n "snapd installed as a snap if necessary" # will pass
tox -e behave-any -- -n "snapd installed as a snap if necessary" -D install_from=archive # will fail
```
> snap: install snapd as a snap before installing snaps if necessary

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/api_unattended_upgrades.feature
- uaclient/api/tests/test_api_u_unattended_upgrades_status_v1.py
- uaclient/api/u/unattended_upgrades/status/v1.py
- uaclient/messages/__init__.py
When unattended-upgrades is uninstalled in the machine, we display an error on the api endpoint that doesn't directly tell the user that the package is not installed. We are updating the logic to properly tell the user that the package is not installed.
Fixes: #2807
> api: fix unattended-upgrades for pkg not installed

- debian/changelog
- systemd/ubuntu-advantage.service
This PR solves all of our problems because 'exec' is not a valid service type on Xenial/Bionic, so the only available service type is 'simple'.
Integration tests which involve `ubuntu-advantage.service` must pass.
> systemd: change u-a.service type from exec to simple

- uaclient/config.py
Now that the mypy bug is fixed, mypy is failing us. This removes the workaround and mypy passes again
```
make clean
tox -e mypy
```
> mypy: remove workaround for mypy bug

- .github/labeler.yml
- .github/workflows/label-docs.yaml
This should auto-label any PRs against the docs branch, so that they are easily identified in the list of open Pull Requests.
> auto-label docs PRs

- features/attached_commands.feature
- features/attached_status.feature
- features/unattached_status.feature
The fips-updates service is now available for Jammy. We are now updating the Jammy tests to reflect that
> tests: update jammy tests for fips-updates

- features/enable_fips_cloud.feature
- features/enable_fips_vm.feature
Test fips-updates support on bionic.
PS: Note that we need to update the tests once the product definition goes to production
> test: add fips-updates tests for Jammy

- uaclient/cli/tests/test_cli_attach.py
This PR solves all of our problems because it fixes a unit test leak in `_post_cli_attach`.
Unit tests runs
> tests: fix missing mock in attach unit test

- features/collect_logs.feature
- uaclient/actions.py
- uaclient/cli/tests/test_cli_collect_logs.py
This PR solves all of our problems because... it
Fixes: #2860
Run collect logs with this patch and see the services there.
> collect-logs: include esm-cache and apt-news services

- custom_wordlist.txt
- docs/explanations.rst
- docs/explanations/how_to_interpret_output_of_fix_plan_api.md
- docs/explanations/purging_services.md
- docs/howtoguides/enable_anbox.md
- docs/howtoguides/enable_cc.md
- docs/howtoguides/enable_cis.md
- docs/howtoguides/enable_esm_infra.md
- docs/howtoguides/enable_fips.md
- docs/howtoguides/how_to_not_fix_related_usns.md
- docs/howtoguides/how_to_run_fix_in_dry_run_mode.md
- docs/references/api.rst
- docs/tutorials/fix_scenarios.md
This brings the documentation from docs-devel so we publish docs for release 30
> Docs for release 30

- uaclient/cli/__init__.py
- uaclient/cli/tests/test_cli_attach.py
- uaclient/cli/tests/test_cli_detach.py
- uaclient/cli/tests/test_cli_disable.py
- uaclient/cli/tests/test_cli_enable.py
- uaclient/cli/tests/test_cli_refresh.py
- uaclient/lock.py
- uaclient/tests/test_lock.py
This helps when the timer job is running in the background and a cli command happens to collide with it. The timer job is usually over quickly, so retrying several times with a small sleep time should be sufficient.
Everything should still work. Maybe try running more than one command at once and see one wait until the other is finished.
> cli: retry grabbing the lock

- features/api_configure_retry_service.feature
- features/apt_messages.feature
- features/motd_messages.feature
- features/retry_auto_attach.feature
Recently some messages were updated to have more consistent terminology around the use of the words "service" and "subscription". This commit updates the related behave tests to expect the new messages.
CI should pass
> tests: fix integration tests to expect updated messages

- .github/workflows/ci-integration.yaml
- README.md
- features/_version.feature
- features/api.feature
- features/api_packages.feature
- features/api_unattended_upgrades.feature
- features/apt_messages.feature
- features/attach_invalidtoken.feature
- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/collect_logs.feature
- features/config.feature
- features/daemon.feature
- features/fix.feature
- features/i18n.feature
- features/install_uninstall.feature
- features/livepatch.feature
- features/logs.feature
- features/security_status.feature
- features/steps/ubuntu_advantage_tools.py
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
- features/unattached_commands.feature
- features/unattached_status.feature
- tools/create-lp-release-branches.sh
- tools/run-integration-tests.py
- uaclient/upgrade_lts_contract.py
We can stop testing on lunar since our next release will go out after
lunar EOL.
Also configures CI to build package for noble, and run integration tests
for on mantic.
Fixes: #2871 
Check that CI builds for noble and runs tests on mantic. Those tests should pass.
> release-update: drop lunar

- features/logs.feature
- features/security_status.feature
This PR solves all of our problems because it fixes a test which has a wrong date.
The security status test itself
> tests: fix mantic EOL date in the security-status test

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/landscape.feature
- features/steps/output.py
- features/steps/shell.py
- features/util.py
- uaclient/entitlements/base.py
- uaclient/entitlements/entitlement_status.py
- uaclient/entitlements/landscape.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_landscape.py
- uaclient/messages/__init__.py
We adjusted, via the resource definition, the landscape UX to not uninstall landscape-client on disable. That revealed some bugs but also opportunities to simplify the `pro enable landscape` experience overall.
This also fixes the problem where pro was interfering with landscape-clients on releases prior to mantic.
Fixes: #2743
Fixes: #2839 
Fixes: #2840
Please review landscape.feature to make sure the new UX makes sense.
The most important bug to test is #2743 and there is a new behave test for this, but to manually test:
* launch a jammy container and install this version of pro-client from this ppa https://launchpad.net/~orndorffgrant/+archive/ubuntu/pro-client-landscape-test
* `pro attach`
* `apt install landscape-client`
* `landscape-config`
* `pro detach`
* ensure that …
> Landscape fixes

- docs/explanations/using_pro_offline.rst
Request from CS not to point customers to them for help in setting up offline/airgapped. This is outside their scope. 
```
Removed links to CS in our article about using Pro offline. Added link to the KB article,
with a note that paid support is required.
Fixes: #2791
```
> Remove references to customer support

- .pre-commit-config.yaml
- dev-requirements.txt
- uaclient/cli/tests/test_cli_security_status.py
- uaclient/conftest.py
In mantic+ the help output is terminal-size dependent even inside pytest. This mocks the terminal size to 80 columns which is what our tests have always been assuming.
unit tests should pass on mantic
> tests: mock terminal size for terminal-size-dependent tests

- apport/source_ubuntu-advantage-tools.py
- debian/apparmor/ubuntu_advantage_apt_news.jinja2
- debian/apparmor/ubuntu_pro_apt_news.jinja2
- debian/control
- debian/jinja2_render
- debian/rules
- features/apt_messages.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/i18n.feature
- features/motd_messages.feature
- features/steps/contract.py
- systemd/apt-news.service
- uaclient/actions.py
- uaclient/cli/tests/test_cli_collect_logs.py
- uaclient/defaults.py
- uaclient/tests/test_actions.py
This is part of [JIRA SD-1277](https://warthogs.atlassian.net/browse/SD-1277) which aims to enable security features to existing Pro systemd services. The goal is to provide reasonable AppAmor and systemd security isolation configuration for the Pro systemd services.
There are multiple services to be tackled, and this PR is about apt-news.service, and tracked via [JIRA SD-1450](https://warthogs.atlassian.net/browse/SD-1450)
This change relies mostly on the integration tests, but it can also be superficially tested manually.
Install `ubuntu-advantage-tools`, and run `apt-get update`.. Observe `dmesg -wT` and confirm there are no apparmor DENIED messages tied to the profile `ubuntu_advantage_apt_news`, and that the apt-news service performs normally.
Unsure, thinking.
> PRO security isolation: apt_news

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/unattached_status.feature
- lib/reboot_cmds.py
- uaclient/actions.py
- uaclient/api/tests/test_api_u_pro_attach_magic_wait_v1.py
- uaclient/cli/__init__.py
- uaclient/cli/tests/test_cli.py
- uaclient/cli/tests/test_cli_auto_attach.py
- uaclient/cli/tests/test_cli_refresh.py
- uaclient/cli/tests/test_cli_status.py
- uaclient/contract.py
- uaclient/daemon/retry_auto_attach.py
- uaclient/daemon/tests/test_retry_auto_attach.py
- uaclient/exceptions.py
- uaclient/http/__init__.py
- uaclient/messages/__init__.py
- uaclient/tests/test_actions.py
- uaclient/tests/test_contract.py
- uaclient/tests/test_livepatch.py
We want to make connectivity errors clearer and easier to debug for the user. To achieve that, we are now displaying the url that cause the error together with the cause behind the error.
Fixes: #2647
1. Launch a lxd container
2. Disable network on container with: `lxc config device add NAME eth0 none`
3. Run `pro fix USN-4539-1`
Expect the following message:
```
Failed to connect to https://ubuntu.com/security/notices/USN-4539-1.json
[Errno -3] Temporary failure in name resolution 
```
> update connectivity error message

- features/docker.feature
- uaclient/api/u/pro/attach/auto/full_auto_attach/v1.py
- uaclient/clouds/identity.py
This adds integration test coverage for our settings_overrides.cloud_type config option. It also adds a more ergonomic way of overriding the cloud_type for only a single auto-attach operation by adding a new optional parameter to the full_auto_attach.v1 API. This is useful in situations where cloud-id cannot identify the cloud. In particular, this is useful for making pro docker containers on auto-attached instances.
> cloud_override option in u.pro.attach.auto.full_auto_attach.v1 to support auto-attached pro docker builds

- features/airgapped.feature
- features/anbox.feature
- features/api_full_auto_attach.feature
- features/api_security.feature
- features/attach_validtoken.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/detached_auto_attach.feature
- features/enable_fips_cloud.feature
- features/enable_fips_container.feature
- features/enable_fips_pro.feature
- features/enable_fips_vm.feature
- features/landscape.feature
- features/livepatch.feature
- features/proxy_config.feature
- features/reboot_cmds.feature
- features/steps/attach.py
- features/steps/status.py
- features/steps/ubuntu_advantage_tools.py
- features/ubuntu_pro.feature
- features/ubuntu_pro_fips.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
- uaclient/api/tests/test_api_u_pro_status_enabled_services_v1.py
- uaclient/api/u/pro/status/enabled_services/v1.py
- uaclient/entitlements/base.py
Some of our integration tests are relying on the output of `pro status` to access if the machine is enabled or a specific service is enabled. We already have API features that display which services are enabled. Due to that, we are now updating our tests to rely on the API for this kind of information.
Note that not all `pro status` calls were removed. They were kept if they are evaluating that service status is `n/a` or to see that a change in the system has modified the service description in status (i.e. Livepatch support for an unsupported kernel) 
This PR also includes fixes for the `enabled_services` endpoint:
* `usg` service not being reported there
* services with `warning` status were not show as enabled on the API
Guarantee that the modified tests are working as expected and the …
> Replace status tests

- features/fix.feature
- uaclient/api/tests/test_api_u_pro_security_fix.py
- uaclient/api/u/pro/security/fix/_common/__init__.py
When fixing a CVE, we also fetch the related USNs tied to it. When doing that, we need to discard LSNs since they are not supported at the moment.
Run the modified integration test to assert that LSNs are being ignore now when fixing CVEs
> fix: ignore LSNs when fetching CVE related USNs

- features/fix.feature
- uaclient/api/tests/test_api_u_pro_security_fix_plan.py
- uaclient/api/u/pro/security/fix/_common/plan/v1.py
We fetch the CVE description from the USNs associated with the CVE. Before, we picked the first USN title as the CVE description. We are updating that logic to check first if at least one package related to the USN is installed in the system before using its description.
Fixes: #2739
> fix: update how CVE descriptions are generated

- lib/convert_list_to_deb822.py
- release-upgrades.d/ubuntu-advantage-upgrades.cfg
- uaclient/actions.py
- uaclient/apt.py
- uaclient/cli/tests/test_cli_collect_logs.py
- uaclient/entitlements/esm.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_esm.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/tests/test_apt.py
- uaclient/tests/test_util.py
- uaclient/util.py
This PR solves all of our problems because Ubuntu itself will change to deb822 sources by default, and the Client should follow. Not changing means warnings in the future, and adapting early gives us room to facilitate integration when the shift actually happens.
Except from the file format, everything should work exactly the same. CI should cover all cases.
> Convert repo files to deb822

- uaclient/api/tests/test_api_u_pro_security_fix.py
- uaclient/api/u/pro/security/fix/_common/__init__.py
When fetching the CVE notices list, we should exclude a LSNs, as they are not supported for the fix operation
Run the bionic fix test and guarantee that it is passing
> fix: don't include LSN in cve notices list

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/fix.feature
- uaclient/api/tests/test_api_u_pro_security_fix_plan.py
- uaclient/api/u/pro/security/fix/_common/plan/v1.py
- uaclient/cli/fix.py
- uaclient/cli/tests/test_cli_fix.py
- uaclient/messages/__init__.py
When running a `pro fix` command, we might need to access information on the ESM cache. If the cache is not yet updated, we will not show an accurate representation of the fix in the system.
To avoid that, we are now detecting if we need to update the ESM cache during the plan endpoint and if we can't update the ESM cache (i.e users running as non-root), we will now inform the user on the cli command and also warn them on the output of the plan endpoint API.
Verify that the modified test is working as expected
> Run fix when esm cache not updated

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- uaclient/cli/__init__.py
- uaclient/cli/tests/test_cli.py
- uaclient/cli/tests/test_cli_attach.py
- uaclient/contract.py
- uaclient/log.py
- uaclient/messages/__init__.py
- uaclient/tests/test_log.py
The unexpected error message does not reflect accurate log location when run by non root, and also the error message obfuscates the original error message so the end user has no context for what actually went wrong. This PR fixes that. 
Changes `messages.UnexpectedError` from a `NamedMessage` to a `FormattedNamedMessage` so that it must be formatted with a string representing an exception/error message to give better context on what errors actually occurred.   
cli: improved cli/log message for unexpected errors
Fixes: #2600
> Better unexpected exception msgs

- uaclient/defaults.py
- uaclient/files/files.py
- uaclient/log.py
- uaclient/system.py
- uaclient/tests/test_system.py
This PR solves all of our problems because we are trying not to concatenate paths manually.
Removes trailing and connection slashes from paths, and everything reads more pythonic.
Fixes: #2799
It is a refactor, assert nothing breaks.
> chore: use os.path.join instead of concatenating paths

- debian/ubuntu-advantage-tools.prerm
- features/ubuntu_upgrade_unattached.feature
- uaclient/apt.py
- uaclient/entitlements/base.py
- uaclient/snap.py
- uaclient/tests/test_apt.py
This PR solves all of our problems because it brings small tweaks needed for the deb822 transition, both in tests and functionality bits.
This one is interesting... the integration test changes are fine to check, but the other ones can really be tested when noble changes the format in images :D
> Some bits missing in the deb822 transition

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/realtime_kernel.feature
- tools/spellcheck-allowed-words.txt
- uaclient/entitlements/realtime.py
- uaclient/messages/__init__.py
A raspberry pi variant of realtime-kernel may become available in time for noble. This sets up the variant on our side.
run the edited lxd-vm behave test
> realtime: add raspi variant

- debian/clean
- debian/rules
- uaclient/entitlements/tests/test_base.py
This PR addresses the feedback so far on #2913 
- unit tests should pass on noble when you only have `/etc/apt/sources.list.d/ubuntu.sources`
- a build should still clean up `debian/apparmor/ubuntu_pro_apt_news`
> Release 31 review fixups

- .github/workflows/custom-pr-checks.yaml
This PR solves all of our problems because Custom PR Checks weren't running on PRs to `next-v32`
> ci: run custom pr checks on next-* branch PRs

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/attached_commands.feature
- features/enable_fips_container.feature
- features/enable_fips_pro.feature
- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/messages/__init__.py
This change adds a new message prompting the user to confirm if enabling fips downgrades the kernel.
There have been reports of people enabling FIPS (not realizing it will downgrade their kernel), and having their hardware fail as it needed the new kernel. This change adds an additional warning/prompt if a FIPS enablement is determined to downgrade the kernel.
Jira card: SC-1534
On a pro (but not FIPS) VM, enable FIPS and you should see the new messages.
> feat: warn/confirm with user if enabling fips downgrades the kernel

- dev-docs/documentation/contribute_docs.md
- dev-docs/howtoguides/testing.md
Testing documentation updated to include local testing for updates to docs.
> Update dev docs to include doc testing

- docs/explanations.rst
- docs/explanations/fix_scenarios.rst
- docs/howtoguides.rst
- docs/howtoguides/fix_scenarios.rst
- docs/howtoguides/how_to_know_what_the_fix_command_would_change.rst
- docs/howtoguides/how_to_not_fix_related_usns.rst
- docs/includes/contact.txt
- docs/includes/pro-fix-intro.txt
- docs/includes/pro-fix-simple-case.txt
- docs/tutorials.rst
- docs/tutorials/fix_intro.rst
This is based on requests I got in regard to pro fix and on searches in our docs not leading me to the answer :-)
I love that these exist
- https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/tutorials/fix_scenarios
- https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/howtoguides/how_to_run_fix_in_dry_run_mode
But while looking for documentation I realized we could help users a bit more.
Right now a lot is written well but organized for people that know what to look for.
- the tutorial on fix is overloaded with special cases
- the title of fix --dry-run assumed that people would know they look for --dry-run
- when someone just wants the explanation for the conditions encountered on fix they need to not look at the multipass/vm things in the tutorial to …
> Improve pro fix docs

- features/api_packages.feature
- features/apt_messages.feature
- features/attached_commands.feature
- features/attached_enable.feature
- features/attached_status.feature
- features/cloud.py
- features/environment.py
- features/fix.feature
- features/motd_messages.feature
- features/security_status.feature
- features/unattached_commands.feature
- types-requirements.txt
To properly test the Pro client on WSL instances, we need to have an infrastructure that allow us to launch those instance in a Windows machine, install the required Pro client package on them and run the pro commands.
This PR is adding that infrastructure, but there are still some items we need to discuss before merging.
1) Are we going to use a default name for the windows machine or should that be configurable ?
2) We are not using all of the shell safe mechanisms we have for the Ubuntu based tests, should we consider making use of them here too ?
3) Should we mark all container tests as WSL supported ?
After setting up a windows machine, use the provided infrastructure to run any test marked as supporting WSL
> Add WSL test infrastructure

- features/attached_commands.feature
- features/steps/output.py
- uaclient/cli/__init__.py
- uaclient/log.py
The redaction filter was not correctly applied to our current logs. We are now fixing this by adding the redaction filter directly in the log file handler
Run the modified integration tests and also confirm that when performing an attach operation, that all secrets are redacted in the logs
> logs: fix redaction filter

- features/api_configure_retry_service.feature
- features/daemon.feature
- features/environment.py
- features/install_uninstall.feature
- features/retry_auto_attach.feature
- lib/daemon.py
- systemd/ubuntu-advantage.service
- uaclient/system.py
- uaclient/tests/test_lib_daemon.py
- uaclient/tests/test_system.py
currently based on https://github.com/canonical/ubuntu-pro-client/pull/2887 so only look at the last two commit
When cloud-init gets "ubuntu_advantage" user-data, it may need to
install or upgrade ubuntu-advantage-tools. This happens during
cloud-config.service. The install/upgrade of ubuntu-advantage-tools
triggers a "systemctl start ubuntu-advantage.service".
ubuntu-advantage.service is configured with an
"After=cloud-config.service", so it waits to start until
cloud-config.service becomes "active". In this scenario,
cloud-config.service cannot continue until ubuntu-advantage.service
starts, creating deadlock.
We get around this deadlock by removing the "After=cloud-config.service"
from ubuntu-advantage.service. Instead we are moving the ordering dependency
enforcement into the python …
> daemon: wait for cloud-config.service to complete in python

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/airgapped.feature
- features/attach_validtoken.feature
- features/steps/airgap.py
- uaclient/actions.py
- uaclient/cli/tests/test_cli_attach.py
- uaclient/entitlements/__init__.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_entitlements.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/exceptions.py
- uaclient/messages/__init__.py
- uaclient/tests/test_actions.py
When enabling a repo service, we check to see if it apt url is present at the output of apt-cache policy. We are updating this check to also check if any suite of the service also appear together with the apt url. We need this for some setups where the service share the same apt url.
LP: #2031192
> update logic that checks if a service is enabled

- features/api_fix_execute.feature
- features/api_fix_plan.feature
- features/api_security.feature
- features/apt_messages.feature
- features/attach_validtoken.feature
- features/cloud_pro_clone.feature
- features/fix.feature
- features/i18n.feature
- features/install_uninstall.feature
- features/livepatch.feature
- features/logs.feature
- features/motd_messages.feature
- features/proxy_config.feature
- features/security_status.feature
- features/steps/machines.py
- features/steps/ubuntu_advantage_tools.py
- features/unattached_commands.feature
This PR solves all of our problems because now we don't need explicit steps to update the apt data, making the apt update calls in behave tests happen only when really testing something.
Also
Fixes: #2859
All behave should behave the same.
> tests: run apt update when creating instances in behave

- apport/source_ubuntu-advantage-tools.py
- features/collect_logs.feature
- uaclient/actions.py
- uaclient/cli/tests/test_cli_collect_logs.py
- uaclient/tests/test_actions.py
`pro collect-logs` calls itself by running `pro status` to write the current status into a json file. This avoids that by using internal functions to achieve the same outcome.
Fixes: [#2926]
To re-produce behavior and verify changes:
Launch a VM/Container
Run sudo pro collect-logs
look at /var/log/ubuntu-advantage.log
> Updated pro status call in collect-logs

- docs/explanations/motd_messages.md
This PR solves all of our problems because it tells users how to disable the ESM related messages from MOTD without losing information about regular updates.
This targets `docs-devel` because it depends on [LP#2015420](https://bugs.launchpad.net/ubuntu/+source/update-notifier/+bug/2015420) being solved before users can run this.
> docs: add note about disabling ESM related MOTD messages

- lib/auto_attach.py
- uaclient/tests/test_lib_auto_attach.py
cloud-init upstream is looking to better align with product naming changes the Ubuntu Pro instead of the former Ubuntu Advantage product name.  As a result, even cloud-config userdata will now deprecate `ubuntu_advantage` configuration key from user-data and prefer `ubuntu_pro` key instead. This changset is needed pro client because the client initially checks and cloud-init userdata for keys that will operate on Ubuntu Pro. When such keys are present, Ubuntu Pro will avoid autoattaching those VMs on launch and leave that resposibility to cloud-init.
This change is part of a planning epic [SC-1555](https://warthogs.atlassian.net/browse/SC-1555) to align Pro naming in docs and potentially backport this feature to bionic/xenial if needed. That being said, the approach taken here is flexible …
> feat(cloud-init): support ubuntu_pro user-data (SC-1555)

- features/attached_enable.feature
There is no livepatch support for WSL kernels. Because of that, we are removing the WSL machine type from a specific livepatch test
> tests: remove livepatch test for WSL

- docs/howtoguides.rst
- docs/howtoguides/how_to_better_visualise_fixing_multiple_cves.rst
- docs/howtoguides/how_to_run_fix_in_dry_run_mode.md
- docs/references/api.rst
- docs/tutorials/fix_scenarios.md
- wordlist.txt
This PR is aims at:
* Updating the output examples of `pro fix` for the latest improvement in the Pro client
* Add a how-to-guide to help users on better visualizing the status of each CVE when the fix execute API endpoint
> Update fix docs

- uaclient/entitlements/repo.py
On Anbox, we need to update that variable, since the service uses a different pattern. We are now turning this variable into a property to guarantee that this variable is overridden for the Anbox service
Run the Anbox container test
> repo: fix how repo_policy_check_tmpl is defined

- test-requirements.txt
This PR solves all of our problems because it enables us to run our unit test suite again.
`python-apt` had an update which breaks installing from source on older releases (and even Jammy is too old for that) so now we are looking at the python version, and cloning it from a git-ubuntu branch which "matches" what you have.
This implies that developers + GH CI are always running one of the supported development environments (latest LTS, latest released, or devel) and that they did NOT change their Python version on that system.
The damage is very low if you decide to change whatever though, so this is very acceptable.
- `make clean`, then run unit tests on a Jammy machine (py 3.10). All should work. Then check the venv, and see python3-apt is installed from `f043e6` (jammy-updates).
- …
> deps: pick the proper python-apt based on the Python version

- .github/actions/create-issue/package-lock.json
Same as #2948 but targeting the correct branch
> ci-deps: bump undici per dependabot's recommendation

- features/proxy_config.feature
- uaclient/http/__init__.py
Newer versions of curl/pycurl have a slightly different message for 407 http status codes. The new check only looks for "407" anywhere in the message which works for old and new versions of the message, and is hopefully a bit more future proof.
`tox -e behave -- features/proxy_config.feature:1302` should pass again
> tls-in-tls: show auth error for newer pycurl messages

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/api.feature
- features/api_services_dependencies.feature
- features/steps/output.py
- uaclient/api/api.py
- uaclient/api/tests/test_api_u_pro_services_dependencies_v1.py
- uaclient/api/u/pro/services/dependencies/v1.py
- uaclient/entitlements/__init__.py
- uaclient/entitlements/base.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/realtime.py
- uaclient/entitlements/ros.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_entitlements.py
- uaclient/messages/__init__.py
- uaclient/tests/test_status.py
This is part two of prep for the enable api. This introduces the dependencies endpoint as described in the spec.
New tests should pass
> u.pro.services.dependencies.v1

- .github/workflows/ci-integration.yaml
- debian/changelog
- debian/ubuntu-advantage-tools.maintscript
- features/attached_commands.feature
- features/logs.feature
- test-requirements.txt
- uaclient/api/u/pro/attach/auto/should_auto_attach/v1.py
- uaclient/tests/test_version.py
- uaclient/version.py
LP: #2055046
New behave test should pass
> Release 31.2

- debian/ubuntu-advantage-tools.postinst
- features/attached_commands.feature
- features/proxy_config.feature
- sru/release-32/test-user-config-created.sh
- uaclient/cli/tests/test_cli_config_set.py
- uaclient/cli/tests/test_cli_config_unset.py
- uaclient/config.py
- uaclient/conftest.py
- uaclient/files/__init__.py
- uaclient/files/state_files.py
- uaclient/files/user_config_file.py
- uaclient/status.py
- uaclient/tests/test_config.py
- uaclient/tests/test_log.py
- uaclient/util.py
`pro config show` command inaccurately displays default settings instead of reflecting changes made by the root user. Proxy secrets set by root were also not redacted when displaying to non root user.
Fixes: [#2809]
Issue #2982 raised for migration of user configs when merging next-v32 into main.
- Added behave test to config.feature
- Added unit test to test_config.py
> Config show inaccuracy

- docs/explanations/motd_messages.rst
- docs/howtoguides/enable_fips.rst
We will use a marker file rather than an option to the config file.
> docs: update method to disable ESM messages in motd

- sru/release-31/binary-package-rename-uninstall-old-not-allowed.sh
- sru/release-31/binary-package-renames-install-upc.sh
These scripts were used for verification of 31.2
> Binary package rename manual test

- features/api.feature
- uaclient/api/tests/test_api_u_pro_security_fix_plan.py
- uaclient/api/tests/test_api_u_pro_status_is_attached_v1.py
- uaclient/api/u/pro/security/fix/_common/plan/v1.py
- uaclient/api/u/pro/status/is_attached/v1.py
- uaclient/apt_news.py
- uaclient/cli/fix.py
- uaclient/cli/tests/test_cli_detach.py
- uaclient/cli/tests/test_cli_disable.py
- uaclient/contract.py
- uaclient/tests/test_apt_news.py
- uaclient/tests/test_contract.py
- uaclient/timer/tests/test_update_messaging.py
- uaclient/timer/update_messaging.py
Adding contract related information to the is_attached endpoint. This will allow user to not only verify if the machine is attached, but also verify if they have a contract that is valid on that machine
> api: add extra fields to is_attached endpoint

- uaclient/cli/tests/test_cli_attach.py
- uaclient/cli/tests/test_cli_enable.py
- uaclient/cli/tests/test_cli_status.py
- uaclient/tests/test_status.py
Fixes: #2996
This PR solves all of our problems because  a bug was introduced earlier which allowed the unit tests to read a system file, which should not be happening.
> tests: Update tests which call config status

- docs/references/api.rst
This could technically not always be true. @lucasmoura - you've been in reboot-required discussions, do you think this change is sufficient to resolve https://warthogs.atlassian.net/browse/SC-1416 ?
> more accurate reboot-required "no" description

- systemd/apt-news.service
It's possible to have a system where apparmor is enabled, but no profile is loaded. This happens when the user removed the apparmor debian package. In that situation, the ubuntu_pro_apt_news profile will not be loaded into the kernel at startup, and systemd will fail to apply it to the service when starting.
Systemd already ignores the apparmor setting when apparmor is disabled, but in this situation it is still enabled. The fix is to configure the service to also ignore errors when apparmor is enabled.
The drawback is that the service might run unconfined now if there are problems applying the selected apparmor profile on startup.
Fixes: #3002
LP: #2057937
To reproduce the problem, launch an ubuntu lxd container, or a VM, and:
* install ubuntu-advantage-tools 31 or later. It's in updates …
> apt-news.service: ignore apparmor errors when starting

- features/apt_messages.feature
Fixes: #3004
Without this change, the apt news service will be using the apparmor profile loaded into the host's kernel only (jammy), instead of the kernel in each ubuntu release.
> tests: apt_messages.feature: run APT Messages tests in VMs as well

- uaclient/actions.py
- uaclient/cli/__init__.py
- uaclient/cli/tests/test_cli.py
- uaclient/cli/tests/test_cli_attach.py
- uaclient/cli/tests/test_cli_detach.py
- uaclient/config.py
- uaclient/contract.py
- uaclient/entitlements/base.py
- uaclient/entitlements/fips.py
- uaclient/files/files.py
- uaclient/files/state_files.py
- uaclient/lock.py
- uaclient/system.py
- uaclient/tests/test_actions.py
- uaclient/tests/test_config.py
- uaclient/tests/test_contract.py
- uaclient/tests/test_system.py
The is no need for the config module to hold a cache anymore, as this cache is not tied to any particular user config.
We are creating dedicated files for each state that the config module handles and placing them on more appropriate modules.
PS: This PR is based on #2949. We need to merge it first
Guarantee that the cache files are still being created. This can be verified by running the `attach` command and verifying that all necessary files are still created
> Remove config cache

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- uaclient/cli/__init__.py
- uaclient/cli/tests/test_cli_config_set.py
- uaclient/exceptions.py
- uaclient/messages/__init__.py
Currently the user can set config proxy value to empty using `pro config set http_proxy=`
This fixes that, since the given proxy is invalid, an error is shown.
Fixes: [#2925]
> Handle empty value for config set proxy

- .coveragerc
- features/environment.py
- features/steps/machines.py
- features/steps/shell.py
We did not have code coverage for the behave integration tests. This captures code coverage for the feature files when the tests are run.
Obtaining coverage is optional. To enable it,  set the following environment variable:
`export UACLIENT_BEHAVE_COLLECT_COVERAGE=True`
The `.coverage` files are saved in the `artifacts/coverage/` directory for each run.
To obtain converage, run the following in the `ubuntu-pro-client` directory:
`python3-coverage combine --rcfile=.coveragerc /artifacts/coverage/*` 
`python3-coverage report`
This PR is for issue: #2903.
Note: 
Coverage reports only being generated for `jammy` and `mantic` currently. `xenial, bionic, focal` are excluded from the integration test coverage due to difference in python and python-coverage versions. Most current method of …
> Add coverage for behave tests

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/ubuntu_pro.feature
- uaclient/messages/__init__.py
This PR solves all of our problems because now we tell people to run `auto-attach` after upgrades, and users are seeing the generic error.
When a machine tries to auto-attach and the contract server returns an error, print hints on what could have happened together with the error details.
Integration test is good, can be tried in any cloud manually.
> auto-attach: make error message clearer

- docs/howtoguides/enable_landscape.rst
The link is not actually "broken", but it does fail link checks due to the string of redirects. I have updated it to a more direct link to the manpage in question.
> Fix broken landscape link

- .github/workflows/ci-integration.yaml
- features/unattached_commands.feature
This PR solves all of our problems because we need green CI and this test is getting annoying.
This test is being disabled because:
- it started failing on Xenial, only on GH, for no apparent reason
- it has no different logic per release
- it consistently passes on other releases
- it consistently passes on Xenial outside of Github
Rather than debugging the GH runners, we can move on.
Fixes: #3013 
Let CI run
> tests: disable flaky test from running on Github

- lib/daemon.py
- uaclient/tests/test_lib_daemon.py
Once the systemd constraint on After cloud-config.service was removed, there are situations where cloud-config.service runs so long after pro that the python code that waits for cloud-config.service to finish activating is being bypassed as if cloud-init isn't on the system.  This change forces pro to wait for cloud-config to finish if cloud-init is running at all.
Fixes #3000
```
fix: wait for cloud-init.service to fully activate
Once the systemd constraint on After cloud-config.service was
removed, there are situations where cloud-config.service runs so
long after pro that the python code that waits for
cloud-config.service to finish activating is being bypassed as if
cloud-init isn't on the system.  This change forces pro to wait
for cloud-config to finish if cloud-init is running at …
```
> fix: wait for cloud-init.service to fully activate

- .pre-commit-config.yaml
- dev-requirements.txt
- features/steps/airgap.py
- uaclient/api/u/pro/security/fix/_common/plan/v1.py
- uaclient/api/u/pro/security/status/reboot_required/v1.py
- uaclient/apt.py
- uaclient/cli/fix.py
- uaclient/contract.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_entitlements.py
- uaclient/files/tests/test_notices.py
- uaclient/http/tests/test_serviceclient.py
- uaclient/livepatch.py
- uaclient/security_status.py
- uaclient/status.py
- uaclient/tests/test_status.py
- uaclient/tests/test_ua_timer.py
- uaclient/tests/test_util.py
- uaclient/version.py
This PR solves all of our problems because it mitigates CVE-2024-21503 on our codebase.
I know the formatting changes are annoying, but our friend `Dependabot` annoyed us first [with this lovely PR](https://github.com/canonical/ubuntu-pro-client/pull/3007) which was only bumping the deps.
This resolves [a security alert](https://github.com/canonical/ubuntu-pro-client/security/dependabot/2) we have around.
Pretty much `tox` and see how the new `black` formatting is poggers or noggers depending on developer opinion, which `black` itself mostly ignores.
> chore: bump black to 24.3.0

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/attached_commands.feature
- features/attached_enable.feature
- features/landscape.feature
- features/realtime_kernel.feature
- features/unattached_commands.feature
- uaclient/cli/cli_util.py
- uaclient/cli/tests/test_cli_disable.py
- uaclient/cli/tests/test_cli_enable.py
- uaclient/messages/__init__.py
This PR solves all of our problems because it
Fixes: #2487
Those are message adjustments to indicate enable/disable are noops, both in attached and unattached scenarios.
Check the changed messages, run CI
> Better messaging for enable/disable noop fails

- CONTRIBUTING.md
- dev-docs/howtoguides/release_a_hotfix.md
- dev-docs/howtoguides/release_a_new_version.md
This attempts to document a new github-centric release process. This is mostly modeled on what we did for version 31, but some of it isn't totally tested yet. Please let me know what you think.
> new github-centric release process attempt

- features/apt_messages.feature
- uaclient/apt.py
- uaclient/apt_news.py
- uaclient/tests/test_apt_news.py
We needed APT News selectors to only display messages on systems with certain package versions or certain architectures. This adds selectors for both architectures and packages to filter APT news.
> Add architectures and packages selectors

- lib/daemon.py
We had a check to see if the cloud-config.service is not None, which is redundant given the logic we have in place
Nothing should change here
> daemon: remove unnecessary None check for state

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/attached_commands.feature
- features/attached_enable.feature
- features/ubuntu_pro_fips.feature
- uaclient/api/__init__.py
- uaclient/cli/__init__.py
- uaclient/cli/cli_util.py
- uaclient/cli/disable.py
- uaclient/cli/enable.py
- uaclient/cli/tests/test_cli_detach.py
- uaclient/cli/tests/test_cli_disable.py
- uaclient/cli/tests/test_cli_enable.py
- uaclient/entitlements/__init__.py
- uaclient/entitlements/anbox.py
- uaclient/entitlements/base.py
- uaclient/entitlements/esm.py
- uaclient/entitlements/landscape.py
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_esm.py
- uaclient/entitlements/tests/test_landscape.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/exceptions.py
- uaclient/messages/__init__.py
This refactors the disable cli command to use the progress api for printing messages to the user, which will allow the api for disable to be implemented without hacking around prompts deep in the call stack.
CI and tests should all pass
> disable: cli disable progress refactor

- features/api.feature
- features/api_detach.feature
- features/schemas/detach.json
- uaclient/api/api.py
- uaclient/api/tests/test_api_u_pro_detach_v1.py
- uaclient/api/u/pro/detach/v1.py
- uaclient/conftest.py
- uaclient/entitlements/tests/conftest.py
We are adding an endpoint for the detach functionality.
Notice that we still need to refactor it in the future to make the CLI logic use that endpoint.
> Add detach API endpoint

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/api_enable.feature
- features/steps/output.py
- uaclient/api/__init__.py
- uaclient/api/api.py
- uaclient/api/exceptions.py
- uaclient/api/tests/test_api.py
- uaclient/api/tests/test_api_u_pro_services_enable_v1.py
- uaclient/api/u/pro/services/enable/v1.py
- uaclient/cli/__init__.py
- uaclient/cli/cli_api.py
- uaclient/cli/tests/test_cli_api.py
- uaclient/daemon/retry_auto_attach.py
- uaclient/exceptions.py
- uaclient/messages/__init__.py
This is based on #3028 so that should be merged first.
This adds u.pro.services.enable.v1 with progress support and the code to allow the `--show-progress` flag for the `api` subcommand.
This does not yet refactor cli enable to use the api.
New tests should pass.
> api: u.pro.services.enable.v1

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/api_disable.feature
- uaclient/api/api.py
- uaclient/api/exceptions.py
- uaclient/api/tests/test_api_u_pro_services_disable_v1.py
- uaclient/api/u/pro/services/disable/v1.py
- uaclient/entitlements/esm.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/exceptions.py
- uaclient/messages/__init__.py
- uaclient/security_status.py
- uaclient/util.py
This is based on #3015 so that should be merged first.
This introduces u.pro.services.disable.v1 but does not refactor the cli disable command to use it.
New tests should pass
> api: u.pro.services.disable.v1

- .github/workflows/ci-integration.yaml
- .gitignore
- apt-hook/json-hook.cc
- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/config/protest.example.yaml
- features/contract_expired.feature
- features/environment.py
- features/steps/attach.py
- features/steps/contract.py
- integration-requirements.txt
- types-requirements.txt
- uaclient/apt_news.py
- uaclient/cli/enable.py
- uaclient/exceptions.py
- uaclient/files/notices.py
- uaclient/messages/__init__.py
- uaclient/status.py
- uaclient/timer/tests/test_update_messaging.py
- uaclient/timer/update_messaging.py
This improves the end-of-contract ux by doing the following:
- adds explanation to apt upgrade message that certain packages will fail to download and why and what to do
- changes generic "authentication failed" to clear error message on `pro enable`
- adds notice to status output (this is just for now until the bigger status rework happens)
Run the new test, it requires being on the vpn
> messaging: consistent messages for end of contract UX (SC-1562)

- debian/ubuntu-advantage-tools.postinst
- debian/ubuntu-pro-client.postinst
- lib/postinst-migrations.sh
I wrote a book in the file itself, please read that.
Test upgrade from older versions.
I added extra `echo executing from u-p-c` and `echo executing from u-a-t` lines to debug which postinst was executing the script.
Upgrading from current lxd daily images works well for testing a few scenarios
```
./test-in-lxd.sh xenial
./test-in-lxd.sh bionic
./test-in-lxd.sh focal
./test-in-lxd.sh jammy
./test-in-lxd.sh mantic
```
> d/postinst: ensure migrations happen in correct package postinst

- docs/references/api.rst
Add documentation for the following API related changes:
* u.pro.detach.v1 endpoint
* u.pro.attach.token.full_token_attach.v1 endpoint
* u.pro.status.is_attached.v1 new fields in the API result
Verify if the documentation page is correctly rendered and we are not missing any information related to the API changes
> Add docs for new API endpoints

- .readthedocs.yaml
- docs/_static/css/custom.css
- docs/_static/css/furo_colors.css
- docs/explanations.rst
- docs/explanations/which_services.rst
- docs/howtoguides.rst
- docs/howtoguides/enable_in_dockerfile.rst
- docs/howtoguides/get_token_and_attach.rst
- docs/howtoguides/how_to_attach_with_config_file.rst
- docs/index.rst
- docs/references.rst
- docs/tutorials/basic_commands.rst
It came to my attention that pro attach <token> is no longer the desired or recommended way for users to attach to their subscription except in specific circumstances. 
I have restructured and revamped several pages where this was the instruction we gave, and have also taken the opportunity to bring our docs visually in line with the new Pro Handbook
This includes moving the "Which services are for me?" off the front page and into its own document. 
Fixes: #2706
> Pro attach docs

- .readthedocs.yaml
- docs-requirements.txt
- docs/conf.py
The RTD build was breaking for two reasons:
- Changed dependency
- PDF file generation broken
The autobuild function removed the previous dependency and added the watchfiles dependency instead. I have added this dependency to make sure that `make run` will still work.
Also removed PDF generation option from the .readthedocs.yaml file since this was breaking the RTD build. We can add this back in the future, but it will require some work on the auto-generated LaTeX file (there is another TA investigating this).
> Add watchfiles module

- features/api_fix_execute.feature
- features/api_fix_plan.feature
- features/fix.feature
- uaclient/entitlements/livepatch.py
- uaclient/entitlements/tests/test_livepatch.py
On the `process_contract_deltas` function, there is a check to see if the entitlement delta has an enableByDefault directive. However, there was a typo on when fetching that value from the delta dict. We are now fixing this typo and adding an unittest for it
check the new unittest for this change
> livepatch: fix delta check for enableByDefault

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/attach_validtoken.feature
- features/attached_enable.feature
- uaclient/actions.py
- uaclient/messages/__init__.py
Right now, we are no longer showing enable service related messages on attach. That is because on a future refactor, we will start using our APIs for the attach operation and those messages will change. However, while this doesn't happen, it is better to at least inform the user what services are being enabled during attach.
> Add attach messages back

- features/apt_messages.feature
- uaclient/apt_news.py
- uaclient/tests/test_apt_news.py
Sorry @lucasmoura @athos-ribeiro I noticed a difference between this new feature as implemented and the spec
Fixes: #3088
The new test fails before the change and passes after this change.
> apt-news: package selectors should be ORed together

- features/attached_enable.feature
- uaclient/actions.py
- uaclient/api/tests/test_api_u_pro_attach_auto_full_auto_attach_v1.py
- uaclient/api/tests/test_api_u_pro_detach_v1.py
- uaclient/api/tests/test_api_u_pro_services_disable_v1.py
- uaclient/api/tests/test_api_u_pro_services_enable_v1.py
- uaclient/api/u/pro/attach/auto/full_auto_attach/v1.py
- uaclient/api/u/pro/detach/v1.py
- uaclient/api/u/pro/services/disable/v1.py
- uaclient/api/u/pro/services/enable/v1.py
- uaclient/cli/__init__.py
- uaclient/cli/cli_util.py
- uaclient/cli/disable.py
- uaclient/cli/enable.py
- uaclient/cli/fix.py
- uaclient/cli/tests/test_cli_attach.py
- uaclient/cli/tests/test_cli_enable.py
- uaclient/contract.py
- uaclient/entitlements/__init__.py
- uaclient/entitlements/base.py
- uaclient/entitlements/fips.py
- uaclient/entitlements/landscape.py
- uaclient/entitlements/realtime.py
- uaclient/entitlements/tests/conftest.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_fips.py
- uaclient/entitlements/tests/test_landscape.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/tests/test_util.py
- uaclient/util.py
This refactors the enable cli code to use the api for enabling services.
Some adjustments had to be made: 
- the api doesn't support landscape so we need a special case for that
- assume_yes was being set to True by the api, so I extracted that out of the enable logic to be only a cli concern
All enable tests should work exactly the same as before.
> refactor: use enable api in cli subcommand

- .github/actions/create-issue/package-lock.json
This PR solves all of our problems because it solves a couple low severity security issues in the GH report.
As a matter of fact, this replaces #3043 as CI will never pass there because of the secrets sharing.
> ci-deps: bump undici per dependabot recommendation... again

- features/apt_messages.feature
- features/fix.feature
- features/steps/machines.py
- features/steps/packages.py
On Bionic, the distro-info-data package version is bigger than what we have on ESM. Therefore, if we upgrade when attached, we will get the ESM version, due to the pin file. After we detach and run apt upgrade, distro-info-data will then be upgraded. Since our tests required that we have no packages to upgrade when checking the apt news messages, we are now adding an additional apt upgrade step after we detach just to get rid of this issue.
Check that the APT News bionic tests are now passing
> tests: fix APT news tests for bionic

- dev-docs/howtoguides/testing.md
This PR updates the integration testing document to current commands for testing the pro client.
> update integration testing doc

- tox.ini
Due to our Xenial support, we have deprecated warnings our pytest tests. Since we are aware of that,
we are remove those deprecation warnings when running the command
Run `tox -e test` and verify that the deprecation warnings are not there anymore
> test: disable deprecation warnings on pytest

- debian/apparmor/ubuntu_pro_apt_news.jinja2
- debian/apparmor/ubuntu_pro_esm_cache.jinja2
Keep `sudo dmesg -wT | grep ubuntu_pro` running in a terminal (in the same VM, if testing in a VM, or in the host, if testing with a LXD container), and then run this on the system being tested (LXD or VM):
```
sudo rm /etc/os-release
sudo cp /usr/lib/os-release /etc
sudo rm -rf /var/lib/apt/periodic/*
sudo systemctl start esm-cache.service
```
there should be no apparmor DENIED message for an access to `/etc/os-release`.
Additionally, for a more surgical test, also run these:
```
sudo rm /etc/os-release
sudo cp /usr/lib/os-release /etc
sudo aa-exec -p ubuntu_pro_esm_cache cat /etc/os-release
```
On a system with the fixed apparmor profile, you should see the contents of /etc/os-release. With the bug, the last command above will return a …
> Apparmor allow for /etc/os-release

- apport/source_ubuntu-advantage-tools.py
- debian/changelog
- uaclient/version.py
The path for the timer jobs status file is no longer being managed by the config module. Because of that, we need to update our apport script to fetch that data from the correct place. (LP: #2065616)
Run `ubuntu-bug ubuntu-advantage-tools` and check that it doesn't crash
> apport: update path for timer jobs status file

- features/cloud.py
This PR solves all of our problems because the A2_v2 VMs we have been launching is not compatible with the latest daily noble images provided by pycloudlib.
Discarded Ideas:
- Changing the daily image on pycloudlib to `gen-1`: could affect other users of the lib for no good reason
- Passing the image string ourselves instead of querying pycloudlib: a different flow in our code for no good reason. And `gen-2` should be the default from now on.
- Opening an issue against pycloudlib to ask for images of different generations: could take potentially a lot of time there, and would still be a different code flow for us for no plausible reason.
Fixes: #3121
From a branch with this patch:
`tox -e behave -- -D releases=noble -D machine_types=azure.generic`
Not sure if it passes but all machines …
> tests: change the Azure VM size on CI to B2s

- integration-requirements.txt
This PR solves all of our problems because we need to test Noble Pro on Azure
trigger Noble Pro integration tests on Azure
see they running
> chore: bump pycloudlib version

- debian/apparmor/ubuntu_pro_esm_cache.jinja2
Fixes: #3119
Run behave lxd-vm tests on xenial and focal, which are the affected version from the linked github issue.
> apparmor esm_cache: add rules for violations detected during tests

- features/attached_enable.feature
- features/realtime_kernel.feature
- uaclient/actions.py
- uaclient/api/tests/test_api_u_pro_attach_auto_full_auto_attach_v1.py
- uaclient/api/tests/test_api_u_pro_services_enable_v1.py
- uaclient/api/u/pro/attach/auto/full_auto_attach/v1.py
- uaclient/api/u/pro/services/enable/v1.py
- uaclient/cli/__init__.py
- uaclient/cli/disable.py
- uaclient/cli/enable.py
- uaclient/cli/tests/test_cli.py
- uaclient/cli/tests/test_cli_attach.py
- uaclient/cli/tests/test_cli_disable.py
- uaclient/cli/tests/test_cli_enable.py
- uaclient/cli/tests/test_cli_status.py
- uaclient/entitlements/__init__.py
- uaclient/entitlements/base.py
- uaclient/entitlements/tests/conftest.py
- uaclient/entitlements/tests/test_base.py
- uaclient/entitlements/tests/test_entitlements.py
- uaclient/files/tests/test_machine_token.py
- uaclient/status.py
- uaclient/tests/test_status.py
The Pro client doesn't support any beta services at the moment. Additionally, we want to update our beta service logic for the next beta service we support. Due to that, we are removing the current code for beta support. However, we are keeping the beta related CLI entrypoints for compatibility reasons.
Verify that none of our tests are impacted by this
> drop support for beta functionality

- debian/apparmor/ubuntu_pro_apt_news.jinja2
- debian/apparmor/ubuntu_pro_esm_cache.jinja2
Focal systems that were upgraded from bionic are experiencing a series of apparmor DENIED messages that have one thing in common: execution of binaries in `/sbin` or `/bin`.
This happens because of the [usr-merge](https://wiki.debian.org/UsrMerge) effort. On fresh focal systems, we have symlinks replacing top-level directories like /bin, /sbin, and others:
root@f-pristine:~# ls -la /{bin,lib,lib*,sbin}
lrwxrwxrwx 1 root root 7 May 24 21:40 /bin -> usr/bin
lrwxrwxrwx 1 root root 7 May 24 21:40 /lib -> usr/lib
lrwxrwxrwx 1 root root 7 May 24 21:40 /lib -> usr/lib
lrwxrwxrwx 1 root root 9 May 24 21:40 /lib32 -> usr/lib32
lrwxrwxrwx 1 root root 9 May 24 21:40 /lib64 -> usr/lib64
lrwxrwxrwx 1 root root 10 May 24 21:40 /libx32 -> usr/libx32
lrwxrwxrwx 1 root root 8 May 24 21:40 /sbin -> …
> apparmor: deal with usr-merge consequences

- features/api_fix_plan.feature
- uaclient/api/tests/test_api_u_pro_security_fix_execute.py
- uaclient/api/tests/test_api_u_pro_security_fix_plan.py
- uaclient/api/u/pro/security/fix/_common/plan/v1.py
- uaclient/cli/tests/test_cli_fix.py
This PR adds a field displaying the `current_status` of the cve to show if a system is currently affected by a cve/usn before the fix plan is executed.
The field is returned as a part of the plan api.
> api: adding current status field to plan api

- docs/howtoguides/enable_realtime_kernel.rst
Mirroring [this PR](https://github.com/canonical/ubuntu-pro-docs/pull/42) - filed against the Pro Handbook - into the Pro Client docs since it's one of the pages we maintain here.
> Add 24.04 to supported list

- debian/apparmor/ubuntu_pro_esm_cache.jinja2
- features/steps/machines.py
Systems with a `/var/lib/dpkg/arch` file will trigger an apparmor DENIED log entry when the esm-cache service tries to access that file. So far we found the following commands that will attempt that:
- apt-cache policy
- dpkg --print-foreign-architectures
The `/var/lib/dpkg/arch` file can be created, probably among other scenarios, when a subarchitecture is added. For example, on amd64 systems, it's quite common to also have i386 added via the command `sudo dpkg --add-architecture i386`. That is enough to create `/var/lib/dpkg/arch` populated with both am64 and i386, and trigger this bug.
We don't know yet (TBD) the implications of this DENIED error. The output of `apt-cache policy` remains the same, attached or unattached, with and without the apparmor fix.
LP: #2067810
Fixes: #3137
--> …
> Apparmor dpkg foreign arch

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- features/realtime_kernel.feature
- features/steps/machines.py
- uaclient/api/tests/test_api_u_pro_services_enable_v1.py
- uaclient/api/u/pro/services/enable/v1.py
- uaclient/cli/enable.py
- uaclient/entitlements/base.py
- uaclient/entitlements/realtime.py
- uaclient/entitlements/tests/test_realtime.py
- uaclient/messages/__init__.py
This helps users get the right realtime-kernel when running on a raspberry pi. It also informs users of what variant will be installed when it is auto-selected.
Ideally test on a rpi3/4/5 and test that auto-selection works as expected (select raspi on 4/5 and generic everwhere else)
Or you can trick the rpi5 detection on a multipass vm with something like this:
```
./tools/test-in-multipass.sh noble
pro attach --no-auto-enable
cat > /usr/local/bin/dpkg << EOF
#!/usr/bin/bash
echo arm64
EOF
chmod +x /usr/local/bin/dpkg
sed -i 's/(proc_file_path)/("\/home\/ubuntu\/fake")/' /usr/lib/python3/dist-packages/uaclient/entitlements/realtime.py
echo "Raspberry Pi 5 Model B Rev 1.0" > /home/ubuntu/fake
```
Then `pro enable realtime-kernel` and ensure that the raspi variant is auto-selected.
Also …
> realtime: auto-select raspi variant when appropriate

- custom_wordlist.txt
- docs/explanations.rst
- docs/explanations/deprecation_policy.rst
This adds our deprecation policy to a new explanation page.
> Deprecation policy (SC-1625)

- features/api_fix_plan.feature
Add missing field to the fix plan API return for the Focal test
Check that the modified test is now working as expected
---
> tests: add current_status to Focal api_fix_plan

- debian/rules
- tools/check-versions-are-consistent.py
Fixes: #3154
This prevents package builders and uploaders from forgetting to also update the __VERSION__ in uaclient/version.py if a new upstream version is created. Since this is a native package in ubuntu, every single upload will be a new upstream version as well.
Change version in d/changelog to something different from uaclient/version.py's __VERSION__, and build the package. The build should fail.
> d/rules: test for version mismatch

- pyproject.toml
- uaclient/entitlements/tests/conftest.py
This PR solves all of our problems because it enforces a newer and better default for a lint check.
---
> typing: add no_implicit_optional lint lint

- custom_wordlist.txt
- docs/howtoguides/enable_index.rst
- docs/howtoguides/enable_realtime_kernel.rst
Our page on "how to enable realtime" was out of date. 
```
docs: Update Real-time Ubuntu page
The contents of the page needed to be brought back into line with the
official k-team docs. I've also added some links to their docs (would 
be happy to add more if necessary). Made some formatting and minor
language changes.
Once approved/updated, I will port these changes to the Pro Handbook as well. 
```
> Update real-time ubuntu page

- docs/conf.py
- docs/howtoguides.rst
- docs/howtoguides/use_custom_apt_config.rst
This PR solves all of our problems because it documents how to use custom APT configuration in the Pro Client.
> docs: add explanation on how to use custom APT configuration

- features/security_status.feature
This PR solves all of our problems because it ensures custom APT configuration is respected by the pro client when done globally, whether through proper system configuration or using environment variables.
CI should be green, as the new integration test runs on X/N lxd-container
> tests: add scenario to assure custom APT configuration is respected

- uaclient/entitlements/fips.py
During disable, we create a notice that states that a reboot is necessary after the operation. We are now bringing that notice back, since it is still valid for FIPS
Run the `Attached enable of FIPS in an ubuntu lxd vm` test for xenial and verify the test is now passing as expected
---
> Bring back disable notice for FIPS

- features/steps/network.py
Sometimes, the aigapped tests are hanging when we try to disable the internet on a given machine. We believe this is being caused by unhandled prompts on the ufw enable command. We are now adding the --force flag to prevent that
Guarantee that airgapped tests are now unstuck on CI
---
> tests: add --force flag to ufw enable

- uaclient/entitlements/tests/test_fips.py
This PR solves all of our problems because it fixes a leak in a unittest.
It makes my spirit rejoice as I see my unit tests green on my lovely WSL development environment.
For the regular developer nothing will change
In a WSL instance, see ' tox'  go from 6 errors to 0 after this patch
---
> tests: fix FIPS unittest for WSL systems

- features/apt_messages.feature
The standard package we use to test the APT messages now have an esm-infra counterpart. We are now using another package that doesn't have an esm-infra version
Check that the modified Xenial APT test is now working as expected
> tests: fix APT messages test for xenial

- features/i18n.feature
- uaclient/system.py
- uaclient/tests/test_system.py
UTF8 on locale names works but is not the correct way of specifying it. The correct spelling that is officially supported is UTF-8.
utf8 behave test should still pass
---
> system: use correct spelling of UTF-8

- debian/apparmor/ubuntu_pro_apt_news.jinja2
- features/apt_messages.feature
- features/security_status.feature
- features/steps/machines.py
The apt-news service has grown a package selector, and therefore it needs access to the packages information on the system.
This feature is not new, but was used for the first time recently due to an [openssh security update](https://ubuntu.com/security/notices/USN-6887-1) .
LP: #2072489
Fixes: #3193
As of this writing, the apt news json is still out there and will trigger the issue, but that may not be the case in the future. Right now, just running `apt-get update` on a system should show the apparmor DENIED messages in the logs.
The behave test created for this scenario happened to not be using the systemd service file for apt-news, which means that code ran unconfined by apparmor, which is why this wasn't caught in tests before. The test will be changed in a follow-up PR.
> Apparmor apt news package selector 3193

- debian/apparmor/ubuntu_pro_apt_news.jinja2
- features/apt_messages.feature
- features/security_status.feature
- features/steps/machines.py
Cherry picks the apparmor fix to next-v34
---
> Cherry pick apparmor fix

- dev-docs/howtoguides/testing.md
The command fails without the added `--`. Also, the commands immediately following the ones in question include the `--` too. 
```
docs: add missing `--` to behave commands in testing.md
```
> Add missing "--" to behave commands in testing.md

- CONTRIBUTING.md
- dev-docs/howtoguides/integration_testing.md
- dev-docs/howtoguides/unit_testing.md
This PR splits our `testing.md` document into integration and unit testing pages as well as references the `tutorials/getting-started.md` file in each to direct the reader towards a more comprehensive setup before beginning testing.
> dev-docs: split testing doc and include prerequisite link

- docs/howtoguides.rst
- docs/howtoguides/attach_index.rst
- docs/howtoguides/check_pro_version.rst
- docs/howtoguides/configure_index.rst
- docs/howtoguides/configure_tls_in_tls_proxy.rst
- docs/howtoguides/configuring_timer_jobs.rst
- docs/howtoguides/create_a_fips_updates_pro_cloud_image.rst
- docs/howtoguides/create_pro_golden_image.rst
- docs/howtoguides/disable_enable_apt_news.rst
- docs/howtoguides/enable-disable/check-status.txt
- docs/howtoguides/enable_index.rst
- docs/howtoguides/enable_realtime_kernel.rst
- docs/howtoguides/fix_index.rst
- docs/howtoguides/get_rid_of_corrupt_lock.rst
- docs/howtoguides/how_to_attach.rst
- docs/howtoguides/how_to_attach_with_config_file.rst
- docs/howtoguides/how_to_collect_logs.rst
- docs/howtoguides/how_to_simulate_attach.rst
- docs/howtoguides/update_motd_messages.rst
- docs/howtoguides/use_custom_apt_config.rst
This PR solves all of our problems because...the LHS navigation menu in the docs needed to be reorganised. 
```
doc: organise how-to navigation
- Add extra drop-downs to gather grouped pages
- Add anchors to pages that had none
- Other housekeeping
```
> Reorganise how-to navigation

- dev-docs/howtoguides/unit_testing.md
We are now telling the user to run make deps before calling tox and also removing any mention to pyenv, as we don't use that anymore for our tests.
> docs: update unit test documentation

- docs/explanations.rst
- docs/explanations/data_collection.rst
> docs: describe all data collection

- tools/apidocgen.py
- uaclient/api/u/apt_news/current_news/v1.py
- uaclient/api/u/pro/attach/auto/configure_retry_service/v1.py
- uaclient/api/u/pro/attach/auto/full_auto_attach/v1.py
- uaclient/api/u/pro/attach/auto/should_auto_attach/v1.py
- uaclient/api/u/pro/attach/magic/initiate/v1.py
- uaclient/api/u/pro/attach/magic/revoke/v1.py
- uaclient/api/u/pro/attach/magic/wait/v1.py
- uaclient/api/u/pro/attach/token/full_token_attach/v1.py
- uaclient/api/u/pro/detach/v1.py
- uaclient/api/u/pro/packages/summary/v1.py
- uaclient/api/u/pro/packages/updates/v1.py
- uaclient/api/u/pro/security/fix/cve/execute/v1.py
- uaclient/api/u/pro/security/fix/cve/plan/v1.py
- uaclient/api/u/pro/security/fix/usn/execute/v1.py
- uaclient/api/u/pro/security/fix/usn/plan/v1.py
- uaclient/api/u/pro/security/status/livepatch_cves/v1.py
- uaclient/api/u/pro/security/status/reboot_required/v1.py
- uaclient/api/u/pro/services/dependencies/v1.py
- uaclient/api/u/pro/services/disable/v1.py
- uaclient/api/u/pro/services/enable/v1.py
- uaclient/api/u/pro/status/enabled_services/v1.py
- uaclient/api/u/pro/status/is_attached/v1.py
- uaclient/api/u/pro/version/v1.py
- uaclient/api/u/security/package_manifest/v1.py
- uaclient/api/u/unattended_upgrades/status/v1.py
This adds network requirements to the api doc metadata and renders it using `apidocgen.py`.
Results in #3223
Regenerate the api docs and double check the new network information for each endpoint.
---
> apidocs: include network requirements per api endpoint

- dev-docs/references/architecture.md
- docs/explanations.rst
- docs/explanations/what_is_the_ubuntu_advantage_pro_package.rst
rename the package from ubuntu-advantage-pro to ubuntu-pro-auto-attach, and ubuntu-advantage-tools to ubuntu-pro-client, as those are the new package names
> docs: rename pro package name

- custom_wordlist.txt
- docs/howtoguides/configure_proxies.rst
- wordlist.txt
On howtoguide for configuring proxies, we are using by default the http prefix for http proxies and https prefix for the https proxies. We are now changing the default to use http on both http and https, but adding a note that users might need to use the https prefix depending on their proxy setup.
Fixes: #2881
> docs: update proxies to use http

- ubuntu-advantage.1
Update the commands listed in the Pro manpage while also updating the services we support there as well
Check if the `man pro` outputs the new manpage
---
> docs: update Pro manpage

- docs/explanations/what_is_the_daemon.rst
Update the daemon documentation to state that it now also runs on Azure while also explaining the retry auto-attach mechanism the daemon is now running.
Fixes: #2922
> docs: update daemon documentation

- features/help.feature
- features/security_status.feature
- features/unattached_commands.feature
- uaclient/cli/__init__.py
- uaclient/cli/commands.py
- uaclient/cli/config.py
- uaclient/cli/constants.py
- uaclient/cli/help.py
- uaclient/cli/system.py
- uaclient/cli/tests/test_cli_commands.py
- uaclient/cli/tests/test_cli_config_show.py
- uaclient/cli/tests/test_cli_security_status.py
- uaclient/messages/__init__.py
This PR solves all of our problems because it applies a set of unhacks to our argparse logic, tweaking the help text and preparing fo the new format.
I changed unit and integration tests, but give it a go and check all help messages are good.
---
> Adjustments and tweaks to the help text

- debian/ubuntu-advantage-tools.lintian-overrides
- debian/ubuntu-pro-client.lintian-overrides
lintian was erroring on oracular builds + had mismatched warning overrides. This fixes that.
build and run lintian for oracular
---
> lintian: adjust overrides for oracular

- features/help.feature
- uaclient/cli/__init__.py
- uaclient/cli/api.py
- uaclient/cli/attach.py
- uaclient/cli/auto_attach.py
- uaclient/cli/collect_logs.py
- uaclient/cli/commands.py
- uaclient/cli/config.py
- uaclient/cli/detach.py
- uaclient/cli/disable.py
- uaclient/cli/enable.py
- uaclient/cli/fix.py
- uaclient/cli/parser.py
- uaclient/cli/refresh.py
- uaclient/cli/security_status.py
- uaclient/cli/status.py
- uaclient/cli/system.py
- uaclient/cli/tests/test_cli_commands.py
- uaclient/messages/__init__.py
This PR solves all of our problems because it implements the `help` structure defined for the new UX.
For all other commands we rely on argparse defaults, but for the main --help entry we want to present the available commands in a customized way.
Some commands will have their own categories, and some will not even appear in help.
This is the same as #3240.
Run help.
There is an integration test to cover the whole thing.
---
> cli: add custom help to the main 'pro' parser

- uaclient/api/tests/test_api_u_unattended_upgrades_status_v1.py
- uaclient/api/u/unattended_upgrades/status/v1.py
There are many configs in the 'Unattended-Upgrade::' prefix which can be disabled while still keeping the main functionality enabled. For example:
- Unattended-Upgrade::OnlyOnACPower "0" Allows upgrades even on battery power
- Unattended-Upgrade::Skip-Updates-On-Metered-Connections "0" Allows upgrades even on metered connections
... and many more.
You may `grep Unattended-Upgrade:: /usr/bin/unattended-upgrade` for a list of keys that may make sense to disable while keeping unattended-upgrades enabled.
`echo 'Unattended-Upgrade::OnlyOnACPower "0";' | sudo tee /etc/apt/apt.conf.d/99test`
`pro api u.unattended_upgrades.status.v1 | python3 -m json.tool`
without this change it reports:
```
"unattended_upgrades_disabled_reason": {
"code": "unattended-upgrades-cfg-value-turned-off",
"msg": …
```
> api: Do not report unattended-upgrade disabled if any config is false

- features/realtime_kernel.feature
Add missing text on the output of enabling realtime-kernel on a jammy vm
Check modified test is now working as expected
---
> tests: fix realtime-kernel test

- debian/control
- debian/rules
This forces the fix for LP#2075337 to be applied when upgrading to ubuntu-pro-client only on noble.
LP: #2075337
Test that the `debian/control` file for noble has the extra `Breaks` and builds for other releases don't
---
> d/control: breaks old python3-minimal on noble

- features/enable_fips_cloud.feature
- features/enable_fips_vm.feature
- features/steps/output.py
- features/ubuntu_pro_fips.feature
- tox.ini
We want to improve our integration tests to make them more resilient and easier to fix in case something goes wrong.
One way to achieve that is by consolidating as many tests as we can, so we have less places to apply a fix if needed.
We have reviewed our FIPS tests and we have consolidated some tests while also deleting some other tests that are
already covered by other scenarios.
All of the modified FIPS tests should pass and we need to insure that we are not loosing anything by deleting the tests in this PR
---
> Update fips tests

- uaclient/api/tests/test_api_u_unattended_upgrades_status_v1.py
- uaclient/api/u/unattended_upgrades/status/v1.py
The keys in UNATTENDED_UPGRADES_CONFIG_KEYS are considered to be mandatory in order to report unattended-upgrades as enabled.
When parsing the config files, get_apt_config_values will set missing keys to None rather than not populating the dict. Thus unattended_upgrades_cfg.get(key, fallback) for a missing key returns None rather than the fallback. Finally `int(None)` fails.
```
sudo sed -i "/APT::Periodic::Unattended-Upgrade/s/^/#/" /etc/apt/apt.conf.d/20auto-upgrades
pro api u.unattended_upgrades.status.v1
```
should not fail.
---
> api: Do not crash when a Unattended-Upgrade config is missing

- features/anbox.feature
The anbox-cloud product no longer asks to install the amc snap so we should not check for it. The amc command has been merged into the anbox-cloud-appliance snap.
The change isn't yet live in staging or production, please coordinate with @morphis before merging.
---
> tests: drop amc snap from list of required snaps

- debian/rules
This addresses v34 feedback described here: https://github.com/canonical/ubuntu-pro-client/pull/3247#discussion_r1710257188
Make a temporary change to either the changelog version or version.py version and run
```
./tools/build.sh xenial
```
---
> d/rules: check version consistency at build time

- docs/howtoguides/enable_in_dockerfile.rst
- docs/tutorials/create_a_fips_docker_image.rst
purging ubuntu-advantage-tools with autoremove only "removes" ubuntu-pro-client which doesn't remove secrets.
This is an unexpected consequence of the package rename.
Also start recommending to detach to be safe.
> Better secret cleanup instructions in docker docs

- features/attached_commands.feature
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_repo.py
To verify if we need to remove an entry from `/etc/apt/auth.conf.d/90ubuntu-advantage`, we check
if a service url is in that file, if it is, we remove the line corresponding to the service. However, we are using the wrong service url to make that check, since it is missing the `/ubuntu suffix. We are now fixing that issue, allowing detach to remove the appropriate lines and delete the file if needed
Verify that the modified integration test is working as expected
---
> detach: fix issue when removing auth file

- uaclient/api/tests/test_api_u_pro_security_fix.py
- uaclient/api/u/pro/security/fix/_common/__init__.py
- uaclient/api/u/pro/security/fix/_common/plan/v1.py
Use cves parameter instead of details to fetch USNs from the security endpoint
Check that the fix integration tests are now working as expected
---
> fix: update endpoint for fetching USNs

- features/api/unattended_upgrades.feature
We are now updating the expected value of `Unattended-Upgrade::Allowed-Origins` when that field is not present. We have recently changed the default value from null to an empty list and we are now reflecting that on the test
Check that the modified integration test is working
---
> tests: update Unattended-Upgrade::Allowed-Origins

- features/_version.feature
- features/api/api.feature
- features/api/detach.feature
- features/api/disable.feature
- features/api/enable.feature
- features/apt_messages.feature
- features/cc_eal.feature
- features/cli/attach.feature
- features/cli/auto_attach.feature
- features/cli/collect_logs.feature
- features/cli/config.feature
- features/cli/enable.feature
- features/cli/help.feature
- features/cli/magic_attach.feature
- features/cli/security_status.feature
- features/cli/status.feature
- features/daemon.feature
- features/reboot_cmds.feature
- features/subscription_attach_restrictions.feature
- features/timer.feature
@arm64 tag added to basic tests for running weekly on new arm64 jenkins job
---
> Add arm64 tag to integration tests

- debian/tests/usage
We are now calling two API endpoints on the dep8 tests. Those endpoints don't trigger any network call and their main use is to verify if any python3-apt change would change the way we interact with that library, as those API endpoints heavily rely on apt functionality.
This is being documented on: #3231 
1. Build the package
2. Use the .dsc file to run this command:
```bash
autopkgtest --no-built-binaries --apt-upgrade --setup-commands setup-testbed --shell-fail ubuntu-advantage-tools_1+devel.dsc -- lxd ubuntu-daily:<RELEASE>
```
3. Check that this passes and that the API endpoints appears in the logs 
---
> debian: add more scenarios to dep8 tests

- requirements.test.txt
This PR solves all of our problems because we want the latest compatible python3-apt in tests.
`tox` on Noble
---
> chore: use python-apt version from noble-updates in tox

- lib/timer.py
- uaclient/exceptions.py
- uaclient/messages/__init__.py
- uaclient/system.py
- uaclient/tests/test_ua_timer.py
This PR solves all of our problems because we now ignore invalid jobs-state.json files if they are corrupted and cannot be decoded, avoiding the oops which stopped phasing on noble (see LP bug)
LP: #2078737
Unit tests cover behavior
for the functionality:
- insert some weird characters in your jobs-state.json file
- `systemctl start ua-timer.service`
- see it degrade
- apply this patch
- repeat
- see it happy
---
> Ignore corrupt jobs-state.json file

- .github/workflows/ci-integration.yaml
This PR solves all of our problems because it mitigates CVE-2024-42471.
Dependabot told us about this one, but I'm reopening here to let CI run and make sure all is good.
See #3289 for context.
Just let the CI run
---
> ci: bump actions/download-artifact version

- features/network_failures.feature
- features/steps/network.py
This PR adds functionality that ensures that the various networking exception handling issues that have been raised on various LP bugs, which were resolved during the work for #2647 was completed, are properly caught, handled, and raised. 
Run the new behave tests locally:
```
tox -e behave -- features/network_failures.feature
```
---
> test(network): add behave tests to ensure network errors are handled

- features/environment.py
When collecting apparmor logs, we pull the /var/log/syslog file from the system under test. However, if the file doesn't exist, we shouldn't block the whole test, but instead alert about that
Check that we can run WSL tests again
---
> tests: handle when syslog file do not exist

- docs/references.rst
- docs/references/commands.rst
- docs/references/commands.txt
- wordlist.txt
This PR solves all of our problems because now we have a CLI reference, and it is generated from the actual source code.
check the docs
---
> docs: include generated documentation for the CLI commands

- features/security_status.feature
For the Noble securitu-status test, we need one package with an upgrade from security and another for updates. The past packages now both have candidates on the security pocket. We are now updating the package to have that distinction again
This is a cherry pick to main for verification.
> test: update packages on security status test

- features/api/config.feature
- features/cli/config.feature
- features/cli/help.feature
- uaclient/api/u/pro/config/v1.py
- uaclient/cli/config.py
- uaclient/cli/formatter.py
- uaclient/cli/tests/test_cli_config_set.py
- uaclient/cli/tests/test_cli_config_show.py
- uaclient/cli/tests/test_cli_formatter.py
- uaclient/config.py
- uaclient/files/user_config_file.py
- uaclient/tests/test_config.py
This PR solves all of our problems because users should be able to set color and suggestion output in the new CLI using the Client configuration. And the possible values should be true or false.
We also add a class to serve as global configuration for the CLI specific options. Besides the colors and suggestions, it checks for utf-8 support. It adds new constraints to use colors, so commands don't read directly from the UAConfig, but combine this with this class instead.
The class has methods which can be dinamically executed based on CLI arguments after parsing those - because it's information we don't have from the system, but rather from the user.
Unit + integration was addressed
---
> Add confg values for the new CLI

- uaclient/cli/formatter.py
- uaclient/cli/tests/test_cli_formatter.py
This PR solves all of our problems because the new UX is full of tables, and this helps with formatting the tabular information and printing it to screen in a standardized way.
This is based on top of #3304 and should be merged after that.
Unit tests cover the functionality. This will be widely used in the CLI so integration tests will include these changes, but for specific use cases.
---
> cli: add Table class

- docs/howtoguides/enable_anbox.rst
The Anbox page should include 24.04 LTS availability.
I have reworded the version note box to point to the official 
requirements page that lists the LTS versions Anbox is available on.
This will mean we don't need to update the page every time a new
LTS is released.
```
doc: update Anbox Cloud requirements
Requirements were out of date, now include a link to the official
documentation as well.
```
> Update Anbox page with version link

- uaclient/cli/formatter.py
- uaclient/cli/tests/test_cli_formatter.py
This PR solves all of our problems because it brings some tweaks to the Table implementation, includes the indented Block and SuggestionBlock implementation and adds a helper function which considers the formatter config when returning text.
This is the last base PR for the CLI before the commands start to appear.
Unit tests cover the functionality
Integration and such will come with the commands
---
> Printing standardized output for CLI commands

- uaclient/cli/formatter.py
- uaclient/cli/tests/test_cli_formatter.py
This PR solves all of our problems because it implements some needed niceties on top of the CLI tools we are working on.
This is based on #3323 and should be merged after that. (It is the same context though, I didn't push the commits there because that one is kinda approved I guess)
Unit tests cover functionality, integration will come because the new CLI commands depend on this.
---
> Add links and alignment functionality to the CLI formatter tooling

- features/apt_messages.feature
- features/steps/machines.py
- features/timer.feature
- features/ubuntu_upgrade.feature
- tox.ini
jammy -> noble needs special treatment now that do-release-upgrade disables -proposed. We need a special step to ensure that the package is actually upgraded to the noble version. We also need to mask the apparmored services so that they don't cause denials during the upgrade to the noble version.
Run the new test
---
> tests: give jammy->noble upgrade its own test

- features/cli/help.feature
- uaclient/cli/parser.py
- uaclient/messages/__init__.py
This PR solves all of our problems because This PR solves all our problems because
it deduplicates the `pro help` entries.
Integration test added
---
> help: deduplicate 'pro help' command entries

- features/schemas/ua_security_status.json
- uaclient/security_status.py
- uaclient/tests/test_security_status.py
Fix for #3184
Documentation update PR: #3328 
---
> Apt pinned packages

- features/anbox.feature
- features/steps/ubuntu_advantage_tools.py
- features/util.py
On Noble, the ubuntu-advantage-tools package is not installed by default, that means that once we install the package in our tests, all of the previous migrations would run. This was causing some issue on our Pro cloud integration tests. We configure those tests to disable the auto_attach feature on startup. However, one of the migrations was overriding our config file momentarily, allowing our daemon to run and attach the machine. Since we want to avoid that behavior, we are now masking the daemon before the package install and unmasking it just after the operation
Run the GCP Pro Noble tests and double check they are working now
---
> tests: don't install ubuntu-advantage-tools on Noble

- uaclient/api/tests/test_api_u_pro_security_vulnerabilities_common_v1.py
- uaclient/api/tests/test_api_u_pro_security_vulnerabilities_cve_v1.py
- uaclient/api/tests/test_api_u_pro_security_vulnerabilities_usn_v1.py
- uaclient/api/u/pro/security/vulnerabilities/_common/v1.py
- uaclient/api/u/pro/security/vulnerabilities/cve/v1.py
- uaclient/api/u/pro/security/vulnerabilities/usn/v1.py
- uaclient/apt.py
- uaclient/defaults.py
We are now caching the vulnerability result as well. That means that if we detect that there is now new vulnerability JSON data to be used and no dpkg related changes on the system, we can simply reuse the old results.
1. Verify that the vulnerabilities integration tests are still working 
2. Verify that the result cache is being produced
3. Verify when running two API commands in a row, the second one is way faster than the first
---
> api: update cache for vulnerabilities

- features/api_vulnerabilities_cve.feature
- features/api_vulnerabilities_usn.feature
- features/cli/help.feature
- features/cli/vulnerability_list.feature
- features/cli/vulnerability_show.feature
- features/steps/output.py
- tools/spellcheck-allowed-words.txt
- uaclient/api/exceptions.py
- uaclient/api/tests/test_api_u_pro_security_vulnerabilities_common_v1.py
- uaclient/api/u/pro/security/vulnerabilities/_common/v1.py
- uaclient/api/u/pro/security/vulnerabilities/cve/v1.py
- uaclient/api/u/pro/security/vulnerabilities/usn/v1.py
- uaclient/cli/__init__.py
- uaclient/cli/cli_util.py
- uaclient/cli/fix.py
- uaclient/cli/vulnerability/__init__.py
- uaclient/cli/vulnerability/list.py
- uaclient/cli/vulnerability/show.py
- uaclient/cli/vulnerability/update.py
- uaclient/cli/vulnerability/util.py
- uaclient/exceptions.py
- uaclient/messages/__init__.py
Add support for the following `pro vulnerability` commands:
* `show`: Show all available information we have for a CVE/USN that affects the system
* `list`: List the CVEs/USNs that affect the system
* `update`: Update the vulnerability JSON data on the machine
PS: We need to first merge #3318 and #3319 
Run the new integration tests for these commands
---
> cli: add vulnerability commands

- uaclient/api/u/pro/security/vulnerabilities/_common/v1.py
We are now caching the result _get_installed_source_pkg_version. This is because we realized we were calling dpkg-query multiple times without a reason, as the result should not change when running any of the vulnerabilities API
Test can you can run `pro vulnerability list` on a Xenial or Bionic VM and that the command only takes some seconds to complete
---
> api: cache result of source pkg version function

- debian/changelog
- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- uaclient/version.py
> Changelog release 35

- uaclient/tests/test_security_status.py
This PR solves all of our problems because this was blocking xenial builds, as there is no guaranteed dict order in python 3.5
This was a flaky issue on Xenial builds.
Those should not fail anymore.
Locally, comment the "nocheck" in the build_debs function and trigger xenial builds.
---
> tests: fix xenial security-status test

- uaclient/api/u/pro/security/fix/_common/plan/v1.py
We need to fetch the USNs related to a CVE to extract the ubuntu version of the packages affected by the CVE. In the past, we where running another request to fetch all USNs related to the CVEs. To make this process less demanding on the API side, we are now relaying on the related USNs already delivered by the CVE endpoint instead
Check that CVE related tests for the fix command are still passing
---
> fix: use USNs directly from the CVE response

- features/cli/help.feature
- features/cli/vulnerability_list.feature
- uaclient/api/tests/test_api_u_pro_security_vulnerabilities_common_v1.py
- uaclient/api/u/pro/security/vulnerabilities/_common/v1.py
- uaclient/cli/vulnerability/list.py
Instead of showing the count of applied fixes per package, we are now switching to count be vulnerability instead. The
main reason is to make the count consistent with the other summary information we have on pro vulnerability list
---
> Update vulnerability list applied fixes message

- apt-hook/20apt-esm-hook.conf
- debian/changelog
- features/apt_messages.feature
LP: #2084677
Verify new test fails before change and passes after.
---
> apt-hook: only run apt upgrade hook when run as root

- features/cli/enable.feature
- features/esm.feature
- lib/add_esm_snapshot_auth.py
- lib/postinst-migrations.sh
- uaclient/apt.py
- uaclient/entitlements/repo.py
- uaclient/entitlements/tests/test_repo.py
- uaclient/tests/test_apt.py
- uaclient/tests/test_lib_add_esm_snapshot_auth.py
esm-apps and esm-infra now have apt snapshots available; however, without the apt auth configured properly, downloads from the snapshot servers will fail. This ensures new enablements will include the snapshot urls, and it migrates existing enablements to include the snapshot urls on upgrade.
Consider how I did the one-time sru test in a feature file
---
> esm: add snapshot urls to apt auth

- tools/process_logs.py
This PR solves all of our problems because we manually scroll and toil to look at logs.
This makes it easier (hopefully) ->
Usage example
`python3 tools/process_logs.py optional_log_level -f optional_file`
```
Usage: process_logs.py [OPTIONS] [[ERROR|DEBUG|WARNING]]
Options:
-f, --file TEXT     Log file to process
-p, --pattern TEXT  Regular expression pattern to filter logs
--help              Show this message and exit
```
Currently draft since this can be made much better for our uses.
N/A
---
> tools: Pretty processor for logs

- uaclient/clouds/gcp.py
We (CPC) have recently started building Minimal Pro images (as well as the usual "Base" images). This commit adds the new license codes to the appropriate suites in gcp.py:GCP_LICENSES.
* Also edited the login in `gcp.py:is_pro_license_present()` to facilitate the new dict{list[]}
ran `tox -r` locally and all green
> Add new Minimal Pro licenses for GCP

- features/cli/help.feature
- uaclient/cli/vulnerability/__init__.py
- uaclient/cli/vulnerability/list.py
- uaclient/messages/__init__.py
Running pro vulnerability is now an alias for running pro vulnerability list
Check that `pro vulnerability` works the same way as `pro vulnerability list`
---
> cli: vulnerability alias to vulnerability list

- features/realtime_kernel.feature
For the realtime-kernel check, we are also checking the presence of the usg service on the output. We are updating the test to not check for that anymore, as it doesn't have any relation with the feature being tested
Check the integration test is now working
---
> tests: fix realtime-kernel output check

- docs/explanations/how_to_interpret_output_of_fix_plan_api.rst
- docs/howtoguides/fix_index.rst
- docs/howtoguides/how_to_know_if_system_affected_by_a_list_of_cves.rst
Replaces #3316
I'll delete docs-devel shortly - it has been too confusing of a process.
Make sure the docs build.
---
> Final docs devel merge

- CONTRIBUTING.md
- dev-docs/how-to/run_dep8_tests.md
We are now documenting our rationale for our dep8 tests while also documenting how to run them locally
This PR depends on #3353 to be merged first
These docs have already been tested, just moving to the new place.
---
> docs: add documentation for dep8 tests

- features/livepatch.feature
- uaclient/entitlements/livepatch.py
Fixes: #3156
FYI @CarlosNihelton
Run the new test.
---
> wsl: do not enable livepatch on wsl

- tools/check-versions-are-consistent.py
The daily ppa now prepends "1:1+devel-" instead of expecting it in the changelog already. This script needs to be updated to strip that prefix when looking at the changelog version.
Manually change the changelog version to what the daily PPA was just failing on: `1:1+devel-35-3475~gc001b39f~ubuntu24.10.1`.
Run the version check script, it should return 0.
---
> chore: fix daily ppa builds

- docs/explanations/about_esm.rst
This PR solves all of our problems because pinning and PPAs are not friends. We clarify the reason, and document that people must change their preferences if they want PPA versions to be preferred (or even considered) when automatically upgrading.
---
> docs: improve explanation about the ESM pinning

- features/cli/cve.feature
- features/cli/help.feature
- tools/spellcheck-allowed-words.txt
- uaclient/api/tests/test_api_u_pro_security_cves_v1.py
- uaclient/api/u/pro/security/cves/_common/v1.py
- uaclient/cli/cve.py
- uaclient/defaults.py
- uaclient/exceptions.py
- uaclient/http/__init__.py
- uaclient/messages/__init__.py
We are now improving the error message for the case where a CVE is not in the vulnerability data on `pro cve` and also improving how we fetch the vulnerability data by relying on the etag of the resource.
Guarantee that all cve related feature tests are still passing
> CVE features improvements

- apt-hook/Makefile
- debian/changelog
- features/cli/config.feature
- uaclient/cli/tests/test_cli_config_show.py
- uaclient/cli/tests/test_cli_security_status.py
This PR solves all of our problems because it syncs the LP changes with what we have here, to facilitate reviews and uploads.
A couple changes appear only in the changelog (python3-pkg-resources dependency and version check) because they have been applied in a better way in the current codebase, the LP versions were workarounds.
I also updated the actual changelog for v35 here.
Make sure CI works as it was working before
---
> Bring releases 34.x changes from launchpad

- features/usg.feature
- uaclient/entitlements/cis.py
- uaclient/entitlements/tests/test_cis.py
This PR solves all of our problems because when the user runs `pro enable usg`, it is expected by product that `usg` is installed in the system.
In time: I know this could be done via contracts, setting `additionalPackages` there - but we would still need a workaround for `focal`, so change by change I preferred this one.
If in the future having this hardcoded bite us back, we can consider changing the resource in the backend.
Note that the USG resource already has this in place, it's just the CIS resource that will not return the additionalPackages we expect. But that is the resource this client will be using.
enable usg on a machine
verify the usg package is installed
---
> usg: install the `usg` package when enabling

- uaclient/entitlements/fips.py
- uaclient/entitlements/tests/test_fips.py
This PR solves all of our problems because it
Fixes: #3390 
This is a temporary fix for the bug, as it only includes the missing package when calculating what to install/upgrade on Jammy.
There are ongoing conversations with @Ek0n about creating a metapackage for containers, only with the userspace dependencies, and this will be a definitive solution in the future.
Enable `fips-updates` or `fips-preview` on Jammy, and verify `openssl-fips-module-3` is present.
---
> fips: include `openssl-fips-module-3` when enabling FIPS on Jammy

- tools/apidocgen.py
- uaclient/api/u/pro/security/cves/v1.py
- uaclient/data_types.py
This fix the docgen for the `u.pro.security.cves.v1` endpoint
Run `python tools/apidocgen.py u.pro.security.cves.v1` and check that it is producing a valid output
---
> Fix api docgen for cves endpoint

- custom_wordlist.txt
- docs/explanations/which_services.rst
Anbox Cloud is a service available via Ubuntu Pro and hence it should be included in the services topic.
> Add Anbox Cloud to recommended services

- docs/_static/css/header.css
- docs/_static/js/header-nav.js
- docs/_templates/header.html
- docs/_templates/sidebar/search.html
This PR solves all of our problems because it addresses SD-1780 - this is part of the effort to implement a seamless-like experience for users reading the Ubuntu Pro Client docs and the Ubuntu Pro Handbook
- added links to the handbook and to the CLI docs to the header, highlighting the CLI one here
- Removed cis and added anbox to the pro services dropdown
- JS and CSS to make dropdowns work and adjust header size (ugly ugly but that's what it is)
Please review and merge this together with https://github.com/canonical/ubuntu-pro-docs/pull/61
Build docs and see the magic, ahem
---
> docs: standardize the page header to match the Ubuntu Pro Handbook

- features/apt_messages.feature
- features/cli/attach.feature
- features/cli/help.feature
- features/cli/security_status.feature
- features/cli/status.feature
- features/daemon.feature
- features/enable_fips_vm.feature
- features/fix.feature
- features/landscape.feature
- features/realtime_kernel.feature
- features/steps/ubuntu_advantage_tools.py
This PR solves all of our problems because it fixes and adjusts tests to match the desired capabilities of the Pro Client. Those cases were found when validating v35.
None of those changes are modifying the package behavior, or fixing bugs, or changing messaging. If a test is being changed here, it's because the test was wrong.
Run the changed tests with `tox -e behave -- -n "<test name>"` and see they pass.
---
> Test adjustments for version 35 validation

- debian/ubuntu-pro-client.postrm
We will no longer ship that file on the package, so there is no need to remove it on postrm
---
> debian: remove mention to /var/lib/ubuntu-pro

- tools/check-versions-are-consistent.py
- uaclient/version.py
This PR solves all of our problems because we don't need the suffixes in `pro version`
`python tools/check-versions-are-consistent.py`
---
> version: don't present the ubuntu0 suffix in pro version

- features/lxd.feature
- features/steps/ubuntu_advantage_tools.py
We are now adding a missing step when running the lxd integration test with a package coming from proposed
Check that  the LXD integration test works with a package from proposed
---
> tests: fix lxd test setup

- .github/workflows/cla-check.yaml
This PR solves all of our problems because cla check v2 is here
Fixes: #3408
just make sure the check still works in the CI runs
---
> ci: bump has-signed-canonical-cla

- features/anbox.feature
- uaclient/messages/__init__.py
- uaclient/messages/urls.py
The Anbox Cloud appliance installation message is missing a step before initialising it. Adding this to the CLI output so that users can follow the correct sequence of commands.
1. Enable `anbox-cloud` on Ubuntu Pro
2. Verify if the output contains the updated text.
---
> cli: update Anbox installation output message

- debian/apparmor/ubuntu_pro_esm_cache.jinja2
ubuntu_pro_esm_cache apparmor profile is denying access to custom ssl engine configurations.
1. Modify `/etc/ssl/openssl.cnf` to include another file supported by the apparmor openssl abstraction, example `.include /etc/ssl/engines.d/custom.cnf`.
2. Run the cache service: `systemctl start esm-cache.service`
3. Review the kernel log (dmesg), there will be a apparmor deny message like:
> [1831.626508] audit: type=1400 audit(1745170012.847:58): apparmor="DENIED" operation="open" profile="ubuntu_pro_esm_cache//cloud_id" name="/etc/ssl/engines.d/custom.cnf" pid=19229 comm="cloud-id" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
---
> use openssl abstraction in apparmor profile

- features/cli/collect_logs.feature
- features/cli/help.feature
- uaclient/cli/collect_logs.py
- uaclient/messages/__init__.py
We no longer override any file when an user runs the collect-logs command
Check that the modified integration tests are passing
---
> cli: do not overwrite file on collect-logs

- custom_wordlist.txt
- docs/howtoguides/enable_fips.rst
This PR solves all of our problems because we now recommend `fips-updates`, as `fips` is deprecated from Jammy
Fixes: #3388 
---
> docs: suggest fips-updates instead of fips

- docs/explanations/data_collection.rst
This PR solves all of our problems because from version 35, this data is sent to the backend.
Check docs build.
---
> docs: add CPU data to the collected telemetry

- features/subscription_attach_restrictions.feature
- uaclient/actions.py
- uaclient/messages/__init__.py
- uaclient/tests/test_update_contract_info.py
- uaclient/update_contract_info.py
If a token is associated with a `onlySeries` directive, we will allow the `onlySeries` release and all previous releases to attach using the token, instead of only the release specified by `onlySeries`
---
> relax onlySeries directive check

- .github/workflows/tiobe.yaml
The jenkins this runs on currently is being decommissioned. We'll run it here instead.
Ensure the job is working and uploading results properly and they match the results from the old jenkins job.
---
> CSS-15158 ci: move weekly tiobe job to github actions

- features/logs.feature
This PR solves all of our problems because we like to see tests passing.
This test was overwriting the target file for collect-logs, which is not supported anymore.
Fixes: #3451
Run the modified test.
---
> tests: fix collect-logs test

- .github/workflows/tiobe.yaml
the tics action wasn't using our venv and so wasn't using pylint or flake8
Look for errors in the output. TICS should not have any pylint or flake8 errors.
---
> Pass venv PATH forward so that the TICS action sees flake8 and pylint

- debian/po/pt_BR.po
- debian/po/ubuntu-pro.pot
- uaclient/api/u/pro/attach/guest/get_guest_token/v1.py
- ubuntu-advantage.1
This PR solves all of our problems because it brings all the automated script outputs for the manpage + translations + base for the docs
run
`tools/clidocgen.py manpage` 
and
`tools/update-pos.sh`
and see there is no diff (expect for the datetime of course)
run `python3 tools/apidocgen.py` and see it does not fail, and brings the new docstring as the endpoint description for the guest token one
> Update docs and translations for release 36

- uaclient/actions.py
- uaclient/tests/test_actions.py
If the series doesn't yet exist, the Pro client should not emit a notice related to onlySeries, only allow the attach process to proceed.
Fixes: #3485
Run the modified unit test for this change.
Also, perform an attach operation with a LTS + 1 token and see that it no longer fails
> CSS-16885 Fix notice for LTS + 1 onlySeries

- features/_version.feature
- features/api/configure_retry_service.feature
- features/cli/attach.feature
- features/contract_expired.feature
- features/livepatch.feature
- features/lxd.feature
- features/proxy_config.feature
- features/steps/files.py
- features/subscription_attach_restrictions.feature
- features/ubuntu_upgrade.feature
- features/ubuntu_upgrade_unattached.feature
- uaclient/tests/test_actions.py
This unit test is breaking builds in environmentes without distro-info-data. Bringing the package as a build dependency for a single unit test is overkill.
TBH this only shows how our unit tests cry for refactoring :/
> tests: turn future onlyseries unit test into a behave test
