canonical/ubuntu-pro-client

.travis.yml, tests/test_ubuntu_advantage.py, ubuntu-advantage
Fixes #4 and #5:
- validate the format of the token
- check that the command is run as root
=> Validate token format and check for root

debian/changelog, debian/control, debian/tests/control, debian/tests/update-motd-run, debian/tests/usage, tests.py, ubuntu-advantage, update-motd.d/99-esm
Scripts now variable-ized to install correctly on >= precise.  Script should be entirely silent on non precise releases now.
To test:
```
autopkgtest-build-lxd ubuntu:<series>
autopkgtest . --- lxd ubuntu:<series>
```
=> Add dep8 tests, should work for non-precise releases now.

README.md, debian/tests/update-motd-run, tests.py, ubuntu-advantage
- Add testing instructions to README
- unit tests
- Fix dep8 text matching issue on precise.
=> Install ca-certificates (Fixes #25).

README.md, debian/changelog, tests.py, ubuntu-advantage, ubuntu-advantage.1, update-motd.d/99-livepatch
This branch adds a set of livepatch commands to the ubuntu-advantage script. It includes:
- tests
- manpage update
- README update
- --help output update
- MOTD script for livepatch
- enable and disable commands for livepatch
About my documentation, help and MOTD content and format, let's not try to get it absolutely right here. Unless something is terribly wrong, let's please have someone from Product give it a pass and then we can change it in a follow-up branch.
Given that ubuntu-advantage will get more and more commands, at some point this script should be perhaps refactored into something resembling an ubuntu-advantage.d/ directory, where all subcommands exist. Let's not do it in this branch, though :)
=> ubuntu-advantage livepatch support

update-motd.d/99-esm
In the ESM update-motd.d script, check if the ubuntu-advantage script is available before calling it.
=> Check if ubuntu-advantage script is there before calling it (Fixes #28)

debian/changelog, tests.py, ubuntu-advantage
This branch adds a running kernel check just before enabling livepatch. If running an unsupported kernel for snaps, we print a message instructing the user to reboot into a supported kernel and then run the enable-livepatch command again. This will catch the trusty fresh install case, where you get a 3.x kernel, and also people who for some reason have downgraded their kernel on xenial.
This is not a livepatch issue: any snap will break if running on a kernel less than 4.4.0. At first it will seem to be fine (snap list, snap install, snap remove, all work), but the moment you try to use a snap, it fails.
=> Check the running kernel version before trying to enable livepatch

debian/changelog, tests.py, ubuntu-advantage
Collect all the output of apt calls and save the result code. If it indicates there was an error, then display it and exit.
This was mainly done for the trusty case, where apt-get install snapd pulls in a new kernel and that package's postinst prints out a lot of info to stderr. Other packages we might install are cleaner and only output to stderr when there is an error. So while not really needed for these other apt-get calls, I decided to wrap them in the say way for consistency, both in terms of coding and script output.
Previous Trusty output: http://pastebin.ubuntu.com/25271508/
Output with the proposed changes: http://pastebin.ubuntu.com/25271514/
=> Only display apt output in the case of errors.

Makefile, debian/rules
We were even running the tests twice, because of the Makefile: once  as a result of "make", and the second run as a result of "make test" which was found by dh_auto_test.
=> Disable tests in package builds

.travis.yml, Makefile
Run tests on precise (with python 3.4) and trusty (python 3.5 and 3.6)
=> use travis matrix builds

tests/test_esm.py, tests/test_fips.py, tests/testing.py, ubuntu-advantage
=> check credentials before adding repositories

Makefile, ubuntu-advantage
Since `bash` is marked as `Essential` in Ubuntu (same as `dash`), the change doesn't introduce any new dependency.
=> Use bash shell instead of dash

.travis.yml, Makefile, modules/apt.sh
- add makefile target to run shellcheck from docker, so it's always the latest (this needs to run on trusty as precise images don't support docker)
- add separate lint Travis stage (which runs before the test one)
- run tests with python 3.4 and 3.6 (both on precise)
This PR depends on #97
=> use shellcheck docker image for travis builds

modules/service-esm.sh, modules/service-fips.sh, modules/service-livepatch.sh, modules/service.sh, modules/support.sh, modules/utils.sh, tests/test_script.py, ubuntu-advantage
Unify the logic for `enable-<service>` and `is-<service>-enabled` commands, reducing duplication.
A followup branch will take care of `disable-<service>` as well
=> Refactor enable-* and is-*-enabled commands

modules/service.sh
Use sed instead of awk because the minimal awk we get installed by default does not support the expression we were using. Fixes #107.
=> Use sed instead of awk

Makefile
I left the commands without a @ prefix on purpose. I generally like to see what cleaning is being done.
=> Add a clean Makefile target.

modules/apt.sh, modules/service-esm.sh, modules/service-fips.sh, tests/fakes.py, tests/test_esm.py, tests/test_script.py
Include schema in repository URLs. This also makes the match a bit safer when removing repository credentials from the auth file.
Fixes #100 
Note: depends on #117
=> Cleanups to repository URLs

debian/dirs, debian/postrm, debian/ubuntu-advantage-tools.cron.hourly, tests/test_livepatch_motd.py, tests/testing.py, update-motd.d/99-livepatch
Ideas for follow-up branches:
- update the cache every time the user calls "ua status"
- update the cache right after an enable or disable call
PPA with (manual) test builds: https://launchpad.net/~ahasenack/+archive/ubuntu/ua-livepatch-motd-cache/+packages
=> Implement a cache for the livepatch motd (fixes #122)

ubuntu-advantage, update-motd.d/99-livepatch
instead of in the other scripts that might call ua. (Fixes #126)
=> Add the snap bin directory to PATH in the main ubuntu-advantage script

modules/apt.sh, modules/service-esm.sh, modules/service-fips.sh, modules/service-livepatch.sh, tests/test_fips.py
Fixes #102 
Also, prefix all package-related functions with `apt_` (for namespacing)
=> check that all prerequisite packages are installed when enabling FIPS

debian/changelog, modules/service-livepatch.sh, modules/service.sh, tests/fakes.py, tests/test_livepatch_motd.py, tests/test_script.py, update-motd.d/80-livepatch
Fixes #142 
This branch updates the MOTD and "ua status" outputs to cope with an unsupported kernel for livepatch.
The livepatch case is a bit odd because we can only know if the running kernel is supported or not after the canonical-livepatch snap is installed and the canonical-livepatch command is run.
Sample MOTD output:
```
andreas@nsnx:~$ ssh 192.168.122.170
Warning: Permanently added '192.168.122.170' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 18.04 LTS (GNU/Linux 4.15.0-1010-kvm x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage
System information as of Thu May 24 21:29:27 UTC 2018
System load:  0.02              Processes:           62
Usage of /:   19.4% of 7.58GB   Users …
```
=> Livepatch unsupported kernel

modules/service-cis.sh, tests/test_cisaudit.py, tests/testing.py, ubuntu-advantage, ubuntu-advantage.1
The patchset introduces new flags enable-cisaudit and disable-cisaudit to
install automated tooling package for cis auditing on a machine running xenial. 
The new flag enable-cisaudit enables the security-benchmarks
PPA and installs the cis audit tooling package and the flag disable-cisaudit uninstalls
the cis audit tooling package, removes the repository and clears the apt entries.
Signed-off-by: Vineetha Kamath <vineetha.hari.pai@canonical.com>
=> Add new flag enable-cisaudit to support cis audit

modules/service-cc.sh, tests/test_cc.py, tests/testing.py, ubuntu-advantage, ubuntu-advantage.1
Signed-off-by: Vineetha Kamath <vineetha.hari.pai@canonical.com>
This patch-set adds support for 'disable-cc-provisioning' command to disable provisioning a machine for Common Criteria artifacts installation. It removes the Common Criteria PPA repository and also removes the ubuntu-commoncriteria DEB package installed on the machine.
=> Add support for disable-cc-provisioning #151

modules/service-livepatch.sh, ubuntu-advantage
Use -n when checking if a variable was defined. Solves shellcheck SC2244.
=> Fix shellcheck SC2244

README.md, debian/changelog, ubuntu-advantage
This updates master with what was uploaded to ubuntu disco as v18. Besides syncing `debian/changelog` (the v17 changelog entries were incomplete), the following two changes were done in the ubuntu upload:
- Mention the CIS audit tool in the README.md file
- Remove the word "PPA" from the help output, as it's a needless implementation detail.
The last one can be considered a follow-up to PR #153
=> V18 update

.gitignore, requirements.txt, setup.py, test-requirements.txt, tox.ini
This utilizes nose2 so we can also turn on coverage for the python
files. By setting the envdir the tests also run considerably faster.
The file was cleaned up to make it easier to read.
The setup.py was added to tox and corrections made to clean up lint errors.
The *requirements.txt files were alphabetized and cleaned up.
=> tox: use nose2, speed up run, and add coverage

.travis.yml
This adds coverage of all the required Python versions found in
Ubuntu Trusty, Xenial, Bionic, and the current development release.
This also only runs tox now as it does both unittests and linting.
=> travis: enable additional python versions

debian/control, debian/rules, dev/bddeb, uaclient/config.py, uaclient/entitlements/base.py, uaclient/entitlements/fips.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/tests/test_base.py, uaclient/serviceclient.py, uaclient/sso.py, uaclient/testing/helpers.py, uaclient/tests/test_util.py, uaclient/util.py
Trusty is now buildable in an sbuild.
This removes dependencies on python-six, which was getting used
throughout. This is meant to be a Python 3 only application so there is
no need for python-six. Here is how various usage was updated:
python-six     --> python-3
string_types   --> str
binary_types   --> bytes
StringIO       --> io.StringIO
six.moves      --> import urllib or input()
@add_metaclass --> function signature
Due to differences in the way that flake8 can be installed across Trusty
to Bionic, this simplifies the dependency list and deals with the
different mechanisms for calling it. The trusty found flake8 errors are
fixed and one error is ignored.
Closes #169 #170 #172
=> Enable Trusty build, remove python-six, fix flake8

debian/control
Recipe builds are currently failing because they don't have git installed, which our version determination requires; I don't know for sure that Build-Depends is honoured in recipe builds, but this seems like a good place to start.
=> One Build-Depends per line, and add git to Build-Depends

uaclient/config.py
This suppresses a warning from PyYAML (which fixes #181).  We only need
to construct simple Python objects (i.e. strings, in our case), so we
don't need to use the unsafe yaml.load function.
=> config: use yaml.safe_load

uaclient/entitlements/tests/test_base.py
pytest attempts to collect TestConcreteEntitlement as a test class, and
emits a warning when it fails to do so.
(This change is fully compatible with continued use of nose2.)
=> test_base: rename TestConcreteEntitlement to not have Test prefix

uaclient/cli.py, uaclient/tests/test_cli_attach.py, unittest.cfg
If a token is passed on the command-line, it will already be a string so
we don't need to decode it before use.
This fixes #177.
=> attach: only decode responses from SSO

uaclient-devel.conf, uaclient.conf, uaclient/cli.py, uaclient/tests/test_cli_attach.py
Add production and staging contracts urls to uaclient.conf and uaclient-devel.conf files.
Also reference production contracts URL from ua attach --help/usage.
Add minimal unit tests for attach argument parser.
Fixes #193
=> Set staging and production ua-contracts service URLS in config files

debian/control, debian/rules, test-requirements.txt
We are already using nose2 in our tox environments. This change set add an official package build-dependency on python3-nose2.
Also drop unittest2 from tox environment because I *think* we don't have any test dependencies or imports using that package. python3-unittest2 is also not available in trusty.
This branch should address missing dependency build failures on our daily build recipe page 
https://code.launchpad.net/~canonical-server/+recipe/ua-client-daily
"ModuleNotFoundError: No module named 'nose2'"
per https://launchpadlibrarian.net/416606184/buildlog_ubuntu-disco-amd64.ubuntu-advantage-tools_19.1-0ubuntu1~339~git.ee1a615~ubuntu19.04.1_BUILDING.txt.gz
=> deb: add python3-nose2 as a package build-dependency

debian/rules, uaclient/config.py, uaclient/tests/test_config.py
Avoid tracebacks when referencing deleted configuration which
was incorrectly persisted in memory even after a `ua detach`
operation.
Since our only current caller is Config.delete_cache, drop the key-specific
parameter/logic from Config.delete_cache.
Fixes #196
=> config: reset cached class attributes during config.delete_cache

uaclient/apt.py, uaclient/entitlements/cis.py, uaclient/entitlements/esm.py, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_fips.py
ua-contracts surfaces an aptURL directive to specify the entitlement's production/staging URL.
Fix the remaining cases where serviceURL was still being used in esm, fips and cis entitlements.
Fixes #215
=> apt: fips, cis and esm now use aptURL instead of serviceURL directive

uaclient/apt.py, uaclient/tests/test_apt.py
ua-contracts service provides a macaroon for a resourceToken instead of generally PPA credentials of the format username:password.
When obtaining a single auth token from ua-contracts service, apt authentication will bearer:.
Handle a ValueError if credentials are not of the format username:password and instead use bearer as the username and as the password.
This diff is only big while we await prerequisite #216.
Here is the incremental diff
http://paste.ubuntu.com/p/byvKGBg4c6/
=> apt: handle macaroon resourceToken from ua-contract instead of username:passwd

uaclient/entitlements/livepatch.py, uaclient/entitlements/tests/test_livepatch.py
contracts.staging.canonical.com surfaces remoteServer and caCerts directives for livepatch,
Allow ua client to pass those config options to canonical-livepatch config X=y
Fixes #211
=> livepatch: honor config directives caCerts and remoteServer

Makefile, apt-hook/20apt-esm-hook.conf, apt-hook/Makefile, apt-hook/hook.cc, debian/control, debian/rules
This integrates the hook for apt into the package. What's missing is the whole gettext shenanigans, and maybe you want to do things slightly differently in places, but this feels like a good start.
=> integrate apt esm hook

uaclient/cli.py, uaclient/config.py, uaclient/entitlements/__init__.py, uaclient/entitlements/cc.py, uaclient/entitlements/cis.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py
Adding initiall Common Criteria entitlement which will rely on a 'cc' entitlement type surfaced
by the ua-contract backend service.
This is a PPA-based entitlement which should work like fips* or cis-audit entitlement types.
CC entitlement does the following:
- It sets up an authenticated PPA
- installs a common-criteria package dependency
- adds RepoEntitlement.messaging class attribute for emitting custom instructions post enable
Drive-by fixes:
- entitlements.repo: simplify apt package install message 
-  entitlements.cis : add capture=True on package changes to log them
- entitlements.tests.test_cis:  mock stdout to avoid leaking printed messages during unit tests as well as
validate messages printed
Fixes #175
=> cc: add initial common criteria entitlement and unit tests

uaclient/tests/test_cli_attach.py
This means that they don't require the symbols from typing to actually be imported just for the code to run; this is important because trusty doesn't have the typing module either in its Python distribution or in the archive as a standalone package.
Fixes #232.
=> Convert type annotations to strings

unittest.cfg
It configures nose2, which we no longer use.
=> unittest.cfg: remove as no longer needed

uaclient/entitlements/tests/test_cc.py
Currently it doesn't mock os.path.exists, so the behaviour of the
function under test depends on whether these packages are installed in
the test environment (which they aren't during package build but
generally are on developer systems).
=> test_cc: expand test to mock apt-transport-https/ca-certificates 

uaclient/apt.py, uaclient/entitlements/esm.py, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_fips.py, uaclient/tests/test_apt.py
add_apt_pinning incorrectly assumed that FIPS repositories would live behind a private-ppa.launchpad.net/ url and would incorrectly calculate origin based on the expected LP_PPA origin line.
Staging and production FIPS/ESM/CC services now live behind a separate haproxy service that is not hosted as a Launchpad private-ppa. So, aptURLs related to those services live at something like esm.staging.canonical.com/fips instead of private-ppa.launchpad.net.
As a result, the entitlements should reference a expected PPA Origin which will be common across either production and staging services instead of calculating that origin.
Fixes #238
=> apt: pinning to use hardcoded origin for each entitlement

uaclient/apt.py, uaclient/entitlements/cc.py, uaclient/entitlements/cis.py, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_fips.py, uaclient/tests/test_apt.py
* apt: install prerequisites as single apt cmd
* apt: don't pass invalid --frontend to apt-get remove calls
* add auth cfg setup after prefilght check and prerequisite install
* fips: drop FIPSEntitlement.enable duplicate code. rely on Repo.enable
* apt: fix spurrious apt test by ordering glob.glob output for find_apt_list_files
Fixes: #234 
Fixes: #258
=> Bug/gh 234: fips install packages. Fix invalid apt install/remove command flags

uaclient/entitlements/base.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/status.py
- allow entitlements to honor kernelFlavor affordance vs uname -r
- on trusty Fixtures + mock.Mock decorators don't work too well.
Fixes: #212
Fixes: #264
=> livepatch: honor kernelFlavor. Fix trusty unit tests

debian/control
pkg_resources is imported when the /usr/bin/ua script is run.
This fixes issue #271
=> Depend on python3-pkg-resources

uaclient/conftest.py, uaclient/entitlements/tests/test_livepatch.py
This is a workaround for caplogs on bionic not defaulting to
INFO level or higher.
It also appears that pytest.ini config log_level and caplog.set_level
options have no affect on this setting.
Fixes: #269
=> caplog: bionic caplog fixture defaults to debug-level messages

debian/changelog
This just makes a single changelog entry for the last version we had.
This does not yet change the version back to a native package version (just 19.1, without an ubuntu fix), because our daily ppa already has 19.1-0ubuntu1 and 19.1 is less than 19.1-0ubuntu1. We still have to talk about this.
Fixes issue #284
=> Condense the changelog

debian/postinst, debian/postrm, debian/prerm, uaclient/apt.py, uaclient/entitlements/esm.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/tests/test_apt.py
Package postinst hook will now perform two tasks:
- call configure_default_apt_sources to write ESM unauthenticated apt source file
- call migrate_apt_sources to upgrade existing enabled entitlements to a new series
Package postrm will;
- clean any apt source files written by uaclient
Fixes: #213
=> apt/deb: write esm apt sources on trusty. handle upgrade path to new series

uaclient/apt.py, uaclient/tests/test_apt.py
Since Release files for esm and other repos are not authenticated
uaclient now attempts to access the /pool subdirectory which results in
403 if credentials are invalid.
Fixes: #273
=> apt: valid_apt_credentials needs to check pool

uaclient/cli.py
This sets the default logging level to info by default for both file and
console output. If a user uses the --debug option, then both will also
default to debug as well.
Fix #287
=> cli: default log level to info

uaclient/util.py
The value for the 'caveat_id' key can contain sensitive information like
a secret, therefore this adds it to the list of sensitive keys that are
filtered out.
Fixes #286
=> util: add caveat_id to sensitive keys

uaclient/entitlements/livepatch.py
If a failure occurs when trying to install the livepatch snap, catch the
exception and print out the error message.
Fixes #267
=> livepatch: catch failures of snap install

uaclient/cli.py
Setting log_file to logging.DEBUG was copied from the earlier log_level one
just before the try block, but it doesn't make sense with log_file.
Fix #240
=> logging: fix debug logging

Makefile, debian/rules
This started as an investigation of why the tarball was shipping an empty `__pycache__` directory, and that showed some packaging inconsistencies along the way. Basically two build systems shouldn't be used, and the clean target needed was affected.
Fixes issue #281
=> Packaging fixes

debian/postinst, uaclient/apt.py, uaclient/config.py, uaclient/entitlements/esm.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_fips.py, uaclient/tests/test_apt.py
ua-contracts service provides a 'suites' directive which can
be a list or None and describes the supported apt source suites
that can be enabled for a given entitlement.
Also adds default trusty-security and trusty-updates to package postinst.
Enable any supported suites that match the current running series
Fixes: #329
Fixes: #315
=> apt: obtain supported suite directives for apt entitlements

uaclient/config.py, uaclient/contract.py, uaclient/tests/test_apt.py, uaclient/tests/test_config.py, uaclient/util.py
Create private subdir for ua-contracts responses.
Config.read_cache and write_cache now handle perm errors and fallback
to public files if non-root runs ua status
Fixes: #254
=> security: redact sensitive tokens from ua-contracts responses for public

uaclient/apt.py, uaclient/tests/test_apt.py
ua-contracts sends a 'suites' directive for each entitlement which is a
list of potential suites to enable. For esm, those suites are:
suites: ['precise', 'trusty-security', 'trusty-updates']
The client will only enable any '*-updates' apt source, if the machine
has already opted into <series>-updates via an apt-cache policy check.
Fixes: #343
=> apt: ignore *-updates suite if system not configured for series-updates

debian/postrm, debian/prerm
Since prerm calles migrate_apt_sources(clean=True) all sources list
files are already removed in prerm.
Also prerm doesn't take a purge param
=> deb: prerm and postrm cleanup no need to remove esm list file in postrm

uaclient/entitlements/livepatch.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_livepatch.py
This also includes a fix for a trusty package build unit test failure, required so I could build a package to test with.
=> Wait for snapd to initialise before using it

apt.conf.d/51ubuntu-advantage-esm, debian/postrm, setup.py
Fixes #355 
With ESM enabled we can see it would upgrade ansible and some krb5 packages. Also note the allowed origins:
```
root@trusty-ua:~# unattended-upgrade -v --dry-run
Initial blacklisted packages: 
Starting unattended upgrades script
Allowed origins are: ['o=Ubuntu,a=trusty-security', 'o=UbuntuESM,a=trusty', 'o=UbuntuESM,a=trusty-security']
Option --dry-run given, *not* performing real actions
Packages that will be upgraded: ansible krb5-locales libgssapi-krb5-2 libk5crypto3 libkrb5-3 libkrb5support0
Writing dpkg log to '/var/log/unattended-upgrades/unattended-upgrades-dpkg_2019-04-11_19:58:49.428473.log'
/usr/bin/dpkg --status-fd 9 --unpack --auto-deconfigure /var/cache/apt/archives/libk5crypto3_1.12+dfsg-2ubuntu5.4+esm1_amd64.deb …
```
=> Ship unattended-upgrades configuration

apt-hook/hook.cc
Emergency hotfix, as disco image builds are broken:
Only run the self-test if we can access the file, and ignore any
errors from reading status files, so that things fail silently
where we can't read them for whatever reasons.
This broke live image building for server.
=> apt-hook: Do not crash/fail if we can't read /proc/self/status

apt-hook/hook.cc, debian/changelog
Drop the self test
<juliank|away> andreas: powersj: Just drop the self-test for getppid_of
=> Disco hotfix 1824523, part 2

apt-hook/hook.cc, debian/changelog
This brings back the last hotfix update in disco, and bumps the changelog version.
=> Disco changes, new 19.5

.travis.yml
Minimal changes to get CI working again on this branch. Note that "ua-trusty-esm-old-client" is our target here, NOT master.
=> Update travis for trusty esm

apt.conf.d/51ubuntu-advantage-esm, debian/install
Install an unattended-upgrades config for the ESM -security pocket.
Fixes issue #390
=> OC: Install unattended-upgrades config

uaclient/cli.py, uaclient/config.py, uaclient/status.py
Add the ability to specify --format json|tabular to status output.
Also address that ua-contracts can omit date related fields (such as contract expiry)
Fixes: #227 
Fixes: #384
=> status: add --json cli formatting option

uaclient/cli.py, uaclient/config.py, uaclient/contract.py, uaclient/entitlements/base.py, uaclient/entitlements/tests/test_base.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/status.py, uaclient/testing/fakes.py, uaclient/tests/test_cli_attach.py, uaclient/tests/test_cli_refresh.py, uaclient/tests/test_contract.py, uaclient/util.py, ubuntu-advantage.1
- create separate function contract.request_updated_contract since this
logic is common to both attach, enable and refresh
- Add new UAContractClient.request_machine_token_refresh which use existing machine_token to request updated machine-token
- call request_updated_contract prior to enable operation
- call request_updated_contract in attach and refresh operations 
Fixes: #342
=> refresh: add subcommand to refresh all contract details

tools/constraints-bionic.txt, tools/constraints-trusty.txt, tools/constraints-xenial.txt, uaclient/apt.py, uaclient/entitlements/esm.py, uaclient/entitlements/tests/test_esm.py, uaclient/tests/test_apt.py
We only remove the repo from the apt auth file, because ESM is a
special-case: we want to be able to report on the available ESM updates
even when it's disabled.
Fixes #351
=> esm: remove only the apt auth entry on disable

debian/postrm, tests/test_esm.py, tests/testing.py, ubuntu-advantage
This is not changing FIPS to use auth.conf.d, because FIPS does not exist in trusty. If we want to do that work, to keep things consistent, then that is a matter for another branch.
=> OC: support auth.conf.d for ESM

uaclient/contract.py, uaclient/entitlements/cc.py, uaclient/entitlements/cis.py, uaclient/entitlements/esm.py, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_base.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/status.py, uaclient/tests/test_util.py, uaclient/util.py
Any repo-based entitlement can not check apt-cache policy to determine
if the entitlement is enabled because apt will automatically pin -32768
for a non-root user of an authenticated apt source because the non-root
user does not have permission on /etc/apt/auth.conf.d/<secureconffile>
due to mode 600 on those files.
As a result uaclient will fallback to our localEnabled flag in public
cache files which is set True after enable and False at disable.
Contained in this merge
- move redact_sensitive function out of contract and into util
- cis, fips*, esm, cis-audit will amend public redacted cache files with localEnabled True|False on enable|disable operations
- RepoEntitlement.operational_status  checks  to localEnabled == True value for non-root user if magic apt pin -32768 was found.
- …
=> repo: persist a localEnabled flag in machine-acces for non-root status

debian/control, debian/rules
These were disabled in 10ubuntu0.14.04.2.
I located a failed build in launchpad of 10ubuntu0.14.04.1, when tests were last enabled: https://launchpad.net/ubuntu/+source/ubuntu-advantage-tools/10ubuntu0.14.04.1
Looks like the `flake8 | python3-flake8` build-dep didn't work. I tried in a PPA, and it worked just fine:
https://launchpad.net/~ahasenack/+archive/ubuntu/ua-tests-pkg-build-time/+build/16646028
We could just drop the `flake8 |` bit, which doesn't exist in trusty, and use `python3-flake8` directly. The `flake8` package was there because of precise I believe.
Fixes issue #391
=> Re-enable tests at build time.

debian/changelog
Since the trusty package has a d/changelog entry about having the test disabled, this is now mentioning that they are back.
=> OC: changelog update for tests update

.travis.yml, tools/constraints-trusty.txt
This means that we aren't going to get false test failures if a combination we don't care about fails (i.e. we don't care if we break trusty's versions of packages when running on Python 3.6, because that's a combination that we will never encounter in the wild).
It also allows us to fix up the constraints used for trusty (as we no longer need versions that work on anything other than Python 3.4); this fixes #398.
(This will mean that more tox tests fail on developer machines, but those tests weren't actually testing the right combination of versions anyway; we should address that properly in #397.)
=> travis: only run suite-specific tests on their corresponding Python version

debian/changelog, debian/control, debian/rules
Trusty has a stricter policy regarding universe dependencies. In later ubuntu releases, a universe build dependency was allowed as long as it didn't introduce an equivalent runtime dependency, but in trusty they are just not allowed. Universe is not enabled in the build environment. As a result, we cannot have python3-flake8 as a build-dep, because it's in universe.
This branch removes just the flake8 check, but keeps the unittest one, since those deps are in main:
```
$ rmadison python3 python3-fixtures fakeroot lsb-releae|grep trusty
python3          | 3.4.0-0ubuntu2   | trusty          | amd64, arm64, armhf, i386, powerpc, ppc64el
python3-fixtures | 0.3.14-1ubuntu2  | trusty          | all
fakeroot         | 1.20-3ubuntu2    | trusty          | source, amd64, arm64, armhf, i386, …
```
=> OC: ua trusty disable flake8

uaclient/config.py, uaclient/entitlements/base.py, uaclient/serviceclient.py, uaclient/status.py
As we are Python 3-only, we don't need to inherit from object to get
"new-style" class behaviour.
=> drop inheritance from object

uaclient/cli.py, uaclient/status.py, uaclient/tests/test_cli_attach.py
This implements `enableByDefault` support so that ubuntu-advantage-client will enable the appropriate entitlements at attach time.
(More code will follow to address #411, so that we only attempt to enable entitlements if they are applicable to the current system.)
Fixes #239.
=> honour enableByDefault obligations from contract server

debian/changelog, tests/test_esm.py, ubuntu-advantage
Addresses review comments from https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1825239/comments/1
In the esm-is-already-enabled case, I opted to exit 1, which is documented in the manpage as:
```
1
Invalid command or option
```
Only in later releases did we add an exit code for `<service> is already enabled`, and that was 8.
enable-fips already checks for "fips is already enabled", and also exits non-zero (6 in this case).
=> Review fixes

uaclient/config.py, uaclient/testing/fakes.py
This makes our "please don't output" parameter consistent across the
codebase.
=> config: rename read_cache quiet parameter to silent

uaclient-devel.conf, uaclient.conf, uaclient/cli.py
The default console log level is logging.INFO.
The console output can be set to debug level with --debug parameter.
The default log file logging level is logging.DEBUG and can be changed
by either providing UA_LOG_LEVEL=(debug|info|warning|error) or changing
log_level setting in /etc/ubuntu-advantage/uaclient.conf.
Fixes: #370
=> logs: separate console log devel from logfile level

uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_repo.py
Expectation is that a machine that is enabling a service would need to
access that services packages from the repo they just enabled.
Fixes: #377
=> esm: all repo entitlements now call apt-get update on enable

uaclient/apt.py, uaclient/tests/test_apt.py
The original implementation would join the strings of an array
with a newline. However, when that array only consisted of a single
element the new line would not get added. This ensures there is always a
newline in every auth entry.
Fixes #376
=> /etc/apt/auth.conf: ensure newline always exists

uaclient/cli.py, uaclient/tests/test_cli_attach.py, uaclient/tests/test_cli_enable.py
`ua enable` will emit messages when determining if an entitlement is
applicable to the current system.  For a less noisy user experience, we
don't want to emit these messages when enabling default entitlements
during `ua attach`.  This patch silences that output (but retains the
output from entitlements that are applicable).
Fixes #411.
=> attach: suppress messages from inapplicable default entitlements

tools/install-staging-keyrings.sh
This script is intended to be pushed in to test instances and run there;
it will replace the package-installed keyrings with a keyring that
contains all known staging keys.  If ubuntu-advantage-tools is
re-installed, the script will need to be re-run.
Fixes #437.
=> tools/install-staging-keyrings.sh: add helper to install staging keys

uaclient/config.py, uaclient/contract.py, uaclient/entitlements/base.py, uaclient/entitlements/esm.py, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_base.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/entitlements/tests/test_repo.py, uaclient/status.py, uaclient/testing/fakes.py, uaclient/tests/test_cli_attach.py, uaclient/tests/test_contract.py, uaclient/tests/test_util.py, uaclient/util.py
Log and handle changes to resourceToken, aptURL and suites directives during a ua
refresh operation. When an active entitlement transitions to unentitled, that entitlement will be disabled.
Refactor Fips and ESMEntitlement.disable methods up into a common RepoEntitlement.disable() method which calls a new remove_apt_config() to manage removal of apt config files. RepoEntitlement.process_contract_deltas calls remove_apt_configto ensure stale apt config information is removed prior to writing updated apt config content.
While livepatch delta disable is handled, handling livepatch token and service configuration deltas will be handled in a separate issue.
Fixes: #385
Fixes: #436
=> contract: process_entitlement_delta to react to apt directive deltas

uaclient/entitlements/tests/test_fips.py
This is preparatory refactoring work for #440. The next step will be to parametrize the entitlement fixture so that we're applying all of these tests to both FIPS and FIPSUpdates, and then I'll write tests for the existing installation behaviour.
I'm submitting now because (a) I'm about to finish for the day, and (b) this is self-contained work that can land by itself.
=> test_fips: refactoring

uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_repo.py, uaclient/tests/test_contract.py
On fresh ua attach deltas, old aptURL does not exist.
process_contract_deltas will not attempt apt_auth_apt_repo in this case.
Drive by add unit test for contract ordering.
Fixes: #449
=> bug: do not try remove_apt_auth_apt_repo if old_url is None

uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_fips.py
This makes the tests more correct, and also speeds them up by ~a second
(almost half their running time) on my local system.
=> tests: add some missing mocks

uaclient/apt.py, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py, uaclient/tests/test_apt.py
The effect of this is to upgrade the optional FIPS packages that a user already has present (as well as installing their HMACs).  Previously, we would install _every_ optional FIPS package, whether or not the user was likely to want them.
Fixes #440
=> fips: only install/upgrade optional packages that are already on the system

uaclient/entitlements/base.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/entitlements/tests/test_repo.py
Only report inactive if service is both entitled and meets all affordances.
Report n/a for the following cases:
- service is **not** entitled
- service is entitled, but doesn't pass affordance (platform requirements) checks like proper series, kernel, kernelflavor, is/is-not container
Fixes: #442
=> status: unentitled services will report n/a

uaclient/apt.py, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py, uaclient/tests/test_apt.py
As suggested by @blackboxsw in a review comment on #458, this will only require us to shell out once for all packages, making FIPS enablement a little quicker.
=> fips: replace is_pkg_installed with get_installed_packages

uaclient/config.py, uaclient/tests/test_util.py, uaclient/util.py
On docker ubuntu images, neither /etc/machine-id nor
/var/lib/dbus/machine-id exist. Fix the path where uaclient generates
and persists its own machine-id using uuid4().
Fixes: #489
=> docker: fix persisting generated uuid on images without machine-id files

tox.ini
pytest 4.5.0 modified the default log format, breaking our tests.  This
configures pytest explicitly with the previous log format.
Fixes #499
=> tox.ini: configure pytest log format

tox.ini
This means that developers running tox locally will see any mypy errors
that they introduce.  It _doesn't_ introduce mypy in to our Travis
configuration, so mypy errors will not block merges.
=> tox.ini: add mypy to envlist

README.md, tools/ua.bash, uaclient/cli.py, uaclient/config.py, uaclient/entitlements/cc.py, uaclient/entitlements/tests/test_cc.py, uaclient/tests/test_apt.py, ubuntu-advantage.1
cc: update cc to cc-eal in docs, parameters and commandline help
Per product review in Lyon, change cc to cc-eal to aid in better
search resolution for Ubuntu Support offerings.
This branch depends on fixes landing for:
- ua-contracts backend per
https://github.com/CanonicalLtd/ua-contracts/issues/295
- new ubuntu.com/cc-eal top-level redirect per
https://github.com/canonical-web-and-design/www.ubuntu.com/pull/5164
Fixes: #502
=> cc: update cc to cc-eal in docs, parameters and commandline help

uaclient/serviceclient.py, uaclient/util.py
In a Python 3-only project, we shouldn't need a generic "ensure bytes"
function, so update the two places it was used to be explicit about
types and perform the encoding themselves.
=> util: remove encode_text function

uaclient/apt.py, uaclient/entitlements/cc.py, uaclient/entitlements/cis.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_esm.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_repo.py, uaclient/tests/test_apt.py, uaclient/tests/test_util.py, uaclient/util.py
This PR does two things.
Firstly, it replaces shelling out to `uname` with calls to `os.uname()` from the stdlib; this improves the performance of the function (called without arguments) from ~2.5ms per call to ~20µs per call (i.e. over a 100x speed-up).
Secondly, given the substantially improved performance, it simplifies the call signature and implementation (by removing the `key` parameter) to always determine every piece of information, rather than optionally excluding parts of the return dict.
=> util: simplify get_platform_info and improve performance 

tox.ini
It no longer runs successfully on the Ubuntu development release,
meaning developers on eoan (and perhaps disco) can't expect running
`tox` to pass.  This makes tox less useful.
(Note that this _doesn't_ remove py3-trusty from our tox.ini entirely,
and it will still run as appropriate in CI.)
=> tox.ini: drop py3-trusty from default list

uaclient/cli.py, uaclient/config.py, uaclient/contract.py, uaclient/entitlements/cc.py, uaclient/entitlements/cis.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_repo.py, uaclient/testing/fakes.py, uaclient/tests/test_cli_disable.py, uaclient/tests/test_cli_enable.py, uaclient/tests/test_config.py, uaclient/tests/test_contract.py
Instead of redacting all of our data and storing it in the public directory, this pull request moves us to only store a JSON representation of the current status which is updated whenever root runs attach/enable/disable. This substantially reduces the footprint of world-readable data, and also means that new data coming from the contract server won't be automatically world-readable.
Fixes #494.
=> Store only a status cache in the world-readable data directory

uaclient/entitlements/livepatch.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/entitlements/tests/test_repo.py
Prerequsite branch https://github.com/CanonicalLtd/ubuntu-advantage-client/pull/497
-----
Apt commands can fail for a variety of reasons:
- obtaining a dpkg lock during an apt daily update
- remote network connectivity
- remote repository maintenance or remote ppa accessibility
Add simple retry logic which logs failure attempts and retries
3 times on failure performing a sleep for the provided retry_sleeps.
Apt retry sleeps of 10 seconds are used by charm-helpers for any juju charm which installs packages.
While juju attempts to wait 10 * 30 retries, we won't instrument 5 minutes of retries as we are most-likely a human sitting at a commandline.
Fixes: #496
=> apt: retry apt install and update commands 3 times simple backoff

uaclient/conftest.py, uaclient/entitlements/tests/test_livepatch.py
caplog_text now logs at INFO by default, so we no longer need to filter
out debug log messages.
(Also remove the TODO that this addresses.)
=> test_livepatch: remove unnecessary log level workaround

debian/changelog, debian/postinst
Newer versions of ubuntu-advantage-tools only publicly store in
/var/lib/ubuntu-advantage exactly the data required for `ua status` to
run as a non-root user.  This postinst change removes all files in
/var/lib/ubuntu-advantage (but not in /var/lib/ubuntu-advantage/private,
which is where the non-public files are stored) and then runs `ua
status` to (re-)populate the status cache.
Fixes #522.
=>  d/postinst: remove public files and generate status cache on upgrade

uaclient/config.py, uaclient/status.py, uaclient/tests/test_config.py
The backend service returns a 'supportLevel' affordance value that
should be reported by `ua status` as the Techincal support level.
When no supportLevel value is present in the machine token response,
return 'n/a' (status.INAPPLICABLE) from ua client.
Fixes: #486
=> status: technical support level comes from ua-contract service

uaclient/cli.py, uaclient/tests/test_cli.py
`UAConfig.is_attached` relies on access to non-world-readable data, so this guards against calling it when we aren't root.
Fixes #533
=> cli: check for root before checking for attach in assert_attached_root

uaclient/cli.py, uaclient/tests/test_cli.py
This introduces a wrapper around main() which handles
KeyboardInterrupts.  This could also be used in future for sanitising
other exceptions that bubble all the way out to the console.
Fixes #535
=> cli: handle KeyboardInterrupts gracefully

.travis.yml, tools/constraints-disco.txt, tox.ini
This excludes cosmic, because there are incompatibilities between pycodestyle and flake8 that are handled in the distro packaging. (As cosmic is EOL in a couple of months, I didn't investigate any further.)
=> CI: add disco to tox/travis runs

debian/postinst
When upgrading ubuntu-advantage-tools from version < 18 on trusty, there
are no files in /var/lib/ubuntu-advantage. Fix xargs call to not run rm
if there are no files to remove.
Fixes: #541
=> packaging: trusty postinst upgrade old client to new client clean status

debian/postinst
v1 was viewed as compromised and has been retired in favor of
ubuntu-esm-v2-keyring.gpg. Remove this from the machines list of
acceptable keys if present as the esm repo is signed with v2.
Fixes: #423
=> packaging: trusty should remove v1 esm key if present after upgrade

uaclient/apt.py, uaclient/config.py, uaclient/entitlements/base.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_base.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/entitlements/tests/test_repo.py, uaclient/status.py
This refactors the internal state of the codebase so that we're passing around three types of enum: `ContractStatus`, `ApplicabilityStatus` and `ApplicationStatus`. Entitlements have methods that match these names, which return the entitlement's status for that axis.
operational_status remains (albeit moved to a shared implementation for all entitlements), but will be removed in favour of direct use of the `contract_status()`, `applicability_status()` and `application_status()` methods in a future PR.
=> Refactor internal status to be stored across three axes

debian/postinst, uaclient/entitlements/esm.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_esm.py
Instead of relying on Packages-Require-Authorization header for the ESM
repo, disable the repo initially on package install setting
Pin-Priority: never. Upon enabling, we'll remove that preference file thus
enabling package installs from the repo.
Fixes: #520
=> esm: use Pin-Priority never apt preference file to disable esm initially

debian/postinst
=> esm: on upgrade do not install preferences to pin never if esm enabled

uaclient/config.py, uaclient/contract.py, uaclient/tests/test_config.py
We never actually read the account-contracts cached file (as we only
need it when we're performing an attach, at which point we obviously
won't have it cached), so we can drop it entirely.
(In 3fd37d3 we switched to using the contract information in the machine
token, and in 9cf48da we dropped the last of the MOTD support; that was
the point at which we stopped using it.)
=> config: drop unused UAConfig.contracts property

debian/prerm, uaclient/apt.py, uaclient/tests/test_apt.py
migrate_apt_sources was only called with clean=True, so refactor it to remove the non-clean code path.
(`migrate_apt_sources` used `operational_status` within the unused code path; instead of refactoring the unused code path to the new APIs, it makes more sense to just drop it and reduce our ongoing maintenance burden.)
=> apt: refactor migrate_apt_sources to clean_apt_sources

uaclient/cli.py, uaclient/config.py, uaclient/entitlements/base.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_base.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/entitlements/tests/test_repo.py, uaclient/status.py, uaclient/tests/test_config.py
This renames `operational_status` to `user_facing_status` and modifies the non-display-related call sites of `operational_status` to use `applicability_status`, `application_status`, and `contract_status` instead.
=> Replace operational_status with other APIs

uaclient/entitlements/tests/test_fips.py
This broke unit test runs on containers because fips static_affordances
does not allow for enabling when is_container == True. Intercepting the
applicability_status call avoids having to mock is_container False.
=> tests: fix leak of applicability_status on fips.

.travis.yml
mypy currently fails to install on Python 3.8 (due to it relying on a
version of typed-ast that doesn't yet include this fix:
https://github.com/python/typed_ast/pull/119).  There's no reason to be
running it on 3.8, so just run it on 3.7 instead.
=> travis: use Python 3.7 for mypy runs

uaclient/cli.py, uaclient/conftest.py, uaclient/sso.py, uaclient/tests/test_cli.py, uaclient/tests/test_sso.py, uaclient/tests/test_util.py, uaclient/util.py
This is the first PR towards addressing #504. It puts the framework in place for the new error reporting, and addresses the errors that are handled in `discharge_root_macaroon`.
(The following PR(s) will update the exceptions produced by the interaction with SSO itself, to directly address #504.)
=> Start improving discharge_root_macaroon error handling

debian/control, debian/rules
Bug #1821308 fix is required to honor pin-priority: never in apt
preferences files. This fix comes in different libapt-pkg<abi> versions on trusty, xenial, bionic and disco.
- trusty: libapt-pkg4.12 version 1.0.1ubuntu2.23 
- xenial: libapt-pkg5.0 version 1.2.30
- bionic: ibapt-pkg5.0 (>= 1.6.9)
- cosmic: libapt-pkg5.0 (>= 1.7.3)
- disco: libapt-pkg5.0 (>= 1.8.0~rc1)
- eoan ++ libapt-pkg5.0 (>= 1.8.1)
UA client depends on this version to prevent installing packages from esm repositories until esm is enabled.
=> packaging: depend on libapt-pkg4.12 version to use pin-priority never

uaclient/entitlements/repo.py
We no longer use the localEnabled attribute to produce status for
non-root users, which means this if statement would always evaluate as
False.  Therefore, we can just drop it.
=> repo: drop unreachable if clause from application_status

uaclient/entitlements/base.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_base.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/entitlements/tests/test_repo.py, uaclient/status.py
This is a third ApplicationStatus that represents "enabled but not yet
fully operational".  This commit updates the code paths that deal with
ApplicationStatus to treat ApplicationStatus.PENDING as equivalent to
ApplicationStatus.ENABLED; we don't yet have any code paths that diverge
based on it.
(The first examples of this will be FIPS/FIPS Updates; they aren't fully
enabled until you have rebooted into the linux-fips kernel.)
=> uaclient: introduce ApplicationStatus.PENDING

uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py
=> fips: display as pending when linux-fips is not the running kernel

uaclient/apt.py, uaclient/tests/test_apt.py
Before this, we would match against the -updates stanza for ESM that's
in-place at install time; this would effectively mean that -updates was
always enabled.
=> apt: enable -updates iff -updates from the Ubuntu archive is enabled

uaclient/cli.py, uaclient/tests/test_cli.py
This information makes it much easier to determine what is happening
when the client is apparently stuck, because you can just Ctrl-C to get
a good idea of what's going on.
=> cli: log traceback when KeyboardInterrupt is handled

uaclient-devel.conf
/tmp doesn't persist over reboots, by design, so use /var/tmp which
does.
=> uaclient-devel.conf: use /var/tmp for data_dir

debian/postrm
If purging, remove the log file(s). Globbing there is to catch rotated and compressed or not logs.
Fixes #586
=> postrm: remove log files on package purge

debian/postrm
If purging the package, also remove the pinning file that was created in postinst.
Fixes #584
=> postrm: remove the ESM pinning file on purge

tools/refresh-keyrings.sh
We need to ensure that the keyrings we produce are compatible with trusty; the best way to do this is to generate them on trusty.  (This will help avoid recurrence of #602.)
=> refresh-keyrings.sh: refuse to run anywhere but trusty

uaclient/sso.py, uaclient/tests/test_sso.py
Sometimes the 2fa token expires before typing it, or the user mistypes
the 2fa. No longer exit non-zero, forcing the person to re-enter login
and password. Just re-prompt for two factor authentication.
Fixes: #561
=> attach: two-factor auth reprompt only two-factor auth on failed 2fa

uaclient/entitlements/base.py, uaclient/entitlements/tests/test_base.py
This is inaccurate and confusing.
Fixes #599
=> base: don't message about disabling already-disabled entitlements

debian/postinst
Create an empty log file if none found, and adjust its permissions and
ownership, also during upgrades.
Fixes issue #591
=> d/postinst: adjust logfile permissions

uaclient/apt.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_esm.py, uaclient/tests/test_apt.py
ESM has a sources.list.d file whether or not it is enabled, so that
users get reporting on what would be available if they enabled ESM.
When we enable ESM, we comment out the -updates line in that file if
-updates isn't enabled on the system.  This commit ensures that we
un-comment that line on disable.
Fixes #396
=> repo: un-comment ESM sources.list lines on repo disable

debian/postinst, debian/preinst
We can just rm -rf the directory, it's quicker and simpler.
`d/preinst` had only this content, and is no longer necessary.
I was trying to remember why I was so careful with `dpkg --compare-versions`, but couldn't come up with a reasonable explanation. Maybe because it was in `preinst`, or I wanted to avoid a useless `rm -rf` on every upgrade, but `dpkg --compare-versions` doesn't look cheaper. Feel free to point out flaws in this thinking.
Note that `d/preinst` is still needed because of `d/ubuntu-advantage-tools.maintscript`, which adds code to the `#DEBHELPER#` marker all over the place.
Fixes issue #352
=> Remove the old CACHE_DIR in postinst

apt-hook/hook.cc
APT 1.9 cleans up the APT headers ever so slightly, so we
need to include a few more.
=> apt-hook: Add missing headers for APT 1.9

uaclient/entitlements/base.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/entitlements/tests/test_repo.py, uaclient/tests/test_util.py, uaclient/util.py
This does the following:
* remove some unused members from the return value of `get_platform_info` and cleans up its regexes
* adds determination of the user-facing version string for our current platform as 'version' to the return value of `get_platform_info`
* The normalisation performed to get a consistent user-facing string also means we can simplify down to just having a single regex which operates against the normalised version
* uses that value when informing users that their current Ubuntu release is unsupported
Fixes #314
=> Be consistent when using Ubuntu release names

uaclient/entitlements/base.py, uaclient/entitlements/cc.py, uaclient/entitlements/cis.py, uaclient/entitlements/fips.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_esm.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_repo.py
The first commit fixes #434 by not performing any actions on disable of a FIPS entitlement (other than messaging).
This meant that the only place passing `force=True` to a `disable()` call was the exception handler for failed installs in `RepoEntitlement.enable()`. As this is happening _during_ enable, it can't logically be a "disable" because we aren't enabled yet. So to clean up the logic, I then refactored the cleanup code to a `_cleanup()` method which both the exception handler and `.disable()` call. (I stopped short of introducing `.cleanup()` on `UAEntitlement` because at the moment we only have one caller of it, in a sub-class.)
This then meant that nothing was calling `.disable()` with `force=True`, so we could remove it from the definition of `disable()`.
This, in turn, meant …
=> Remove the force parameter from .disable()

uaclient/entitlements/livepatch.py, uaclient/entitlements/tests/test_livepatch.py
This uses the full path to `/usr/bin/snap` to ensure that we don't end up using some other binary named `snap` that happens to be in the PATH on a system. And, as there is more than one package in trusty that installs `/usr/bin/snap`, we ensure that `snapd` is installed before using `/usr/bin/snap`.
Fixes #356
=> livepatch: use /usr/bin/snap directly and raise an error if snapd is not installed

uaclient/cli.py, uaclient/tests/test_cli_attach.py
This will skip enabling any services that are marked as autoEnable.
Fixes #366
=> attach: add --no-auto-enable option

uaclient/apt.py, uaclient/entitlements/repo.py, uaclient/tests/test_apt.py, uaclient/util.py
Refactor and valid_apt_credentials to assert_valid_apt_credentials.
The new function will raise different UserFacingError messages on
repo url timeout versus credentials/authentication errors.
Fixes: #613
=> apt: failure to acccess repo url will result in timeout error message

uaclient/entitlements/tests/conftest.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_esm.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/entitlements/tests/test_repo.py
This reduces a lot of re-definition of common data structures, making it
clearer what actually differs between different test cases.
=> entitlements/tests: refactor to a shared entitlement_factory fixture

uaclient/config.py, uaclient/entitlements/base.py, uaclient/entitlements/tests/test_base.py, uaclient/tests/test_config.py, uaclient/tests/test_util.py, uaclient/util.py
Due to the memory cost and the cost of also installing
systemd on trusty, livepatch is not auto-enabled.
To obtain series-specific behavior, ua-contracts now provides
a new 'series' key under each entitlement which will contain
any overrides for behavior on a specific series.
UA client now honors overrides via a new util function
apply_series_overrides.
Fixes: #618
=> livepatch: do not autoenable livepatch on trusty

uaclient/util.py
When investigating #649, having this in the log was desirable, and it's likely to be useful in future.
=> util: log read files in load_file

uaclient/apt.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_esm.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/entitlements/tests/test_repo.py, uaclient/status.py, uaclient/tests/test_apt.py, uaclient/tests/test_util.py, uaclient/util.py
apt has a default timeout of 2 minutes for tools like apt-helper.
Add a timeout parameter to util.subp allowing ua client to raise custom
timeouts from subprocess.communicate for specific commands.
Apply a 20 second timeout to the apt-helper call used when validating
credentials against an apt repo url. If we don't see a response from the
repo in that apt-helper call in 20 seconds, chances are we something is
wrong that a 2 minute timeout isn't going to resolve.
Fixes: #626
=> subp: reduce apt-helper call timeout from 2 mins to 20 seconds

uaclient/apt.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_esm.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/entitlements/tests/test_repo.py, uaclient/status.py, uaclient/tests/test_util.py, uaclient/util.py
When automated updates occur, or apt-get update is run from another
process apt-cache policy and apt-get update from ua client can face
contention on dpkg lock files. Contention time can exceed client's
retries on apt commands.
Present a simple error message about APT contention instead of traceback
so that the user can resolve the apt contention, or await completion
of a long-running apt process.
Also in this branch:
- add cleanup on failure during setup_apt_config to remove any apt auth, pin or sources files
- Add retries to apt-cache policy calls
Fixes: #629
```
To test: 
terminal 1:
sudo ua attach
sudo ua disable esm # because it should be auto-enabled
terminal 2:
sudo with-lock-ex -f /var/lib/dpkg/lock sleep 150
terminal 1:
sudo ua enable esm
```
=> apt: provide simple error message instead of traceback on dpkg lock

uaclient/contract.py, uaclient/sso.py, uaclient/tests/test_sso.py
This makes two changes:
1) When 2fa fails and asks for 2fa again it updates the message.
Currently the message makes it sound like the individual needs to
re-enter the exact same 2fa. Similar to how signing up for a website
asks you to 're-enter' your email and password.
2) This hides some of the detail of failures to attach from the user.
These messages are noisy and we should point the user at the logs.
=> output: clean up strings

debian/rules
All other cases will rely on dh_shlibdeps as usual.
Fixes #668
=> d/rules: only hardcode the libapt-pkg<abi> dependency for known cases

uaclient/tests/test_util.py, uaclient/util.py
=> util: handle missing target keys when handling series overrides

uaclient/contract.py, uaclient/tests/test_contract.py
Our orig_access has already had the series overrides applied, which
means it will never be equal to the contract server's response.  As a
result, we would _always_ determine that there was a delta, and apply
it.
This is simply fixed by applying the series overrides to the new access
dict before we determine if there are any deltas.
Fixes #666
=> contract: apply_series_overrides before computing deltas

uaclient/cli.py, uaclient/tests/test_cli_attach.py
=> docs: help documentation link to token URL points to auth.contracts.c.c

debian/changelog, debian/tests/usage
Update master with what was uploaded to eoan as 19.5.1. A followup commit will open up d/changelog for 19.6 development, with the "UNRELEASED" special keyword back in.
=> Master eoan update 19.5.1

uaclient/config.py, uaclient/entitlements/__init__.py
mypy has started warning about them, but the warnings are spurious.
=> ignore noop cast definitions

uaclient/config.py, uaclient/serviceclient.py, uaclient/testing/fakes.py, uaclient/tests/test_config.py, uaclient/tests/test_serviceclient.py, uaclient/tests/test_util.py, uaclient/util.py
This adds classes which handle the encoding/decoding of datetimes (to/from an ISO string format) and uses them when writing to/reading from the cache.
This also remove `util.maybe_parse_json`. One of its call sites, in `readurl`, was no longer needed (we used to parse the JSON to mutate it for log redaction, but we no longer redact the logs so we can just log the unparsed string). The remaining two call sites now have different behaviour (one should decodes datetimes transparently from the cache, the other should not decode datetimes transparently from remote services), and it's less code to just inline the try/except in each callsite than to handle that difference in a single function.
This fixes #694
=> Handle encoding/decoding datetimes to/from JSON when using the cache

.travis.yml
It's passing, and has been for a while. I'm pretty sure this is a holdover from when we were first introducing it.
=> .travis.yml: don't ignore mypy failures

uaclient/apt.py, uaclient/cli.py, uaclient/contract.py, uaclient/entitlements/base.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_fips.py, uaclient/gpg.py, uaclient/tests/test_apt.py, uaclient/tests/test_contract.py, uaclient/tests/test_gpg.py
Except in a couple of cases where we were mistakenly doing a %-format
for a log message, where the fix is to pass the %-format arguments as
parameters.
=> uaclient: replace % formatting with .format()

uaclient/cli.py, uaclient/contract.py, uaclient/entitlements/tests/test_base.py, uaclient/exceptions.py, uaclient/status.py, uaclient/tests/test_cli.py, uaclient/tests/test_cli_enable.py, uaclient/tests/test_contract.py
- exceptions.UnattachedError accepts an optional msg param allowing for
override with specific "Cannot use `blah` with Personal or community
subscription"
- On unattached machine, a ua enable <x> will message about Personal and
community subscription availability @ https://ubuntu.com/advantage
- Upon contract expiry and alert "Subscription has expired" during
ua enable X
- On ua enable <invalid service name>, Cannot enable ‘foobar’...
- Drop leading ERROR: prefix for UserFacingErrors on the console
Fixes: #723
=> ux: new messaging during ua enable failures

uaclient/cli.py, uaclient/tests/test_cli_disable.py
- On ua enable <invalid service name>, Cannot enable 'foobar'...
- When unattached,  ua disable <x> will message about Personal and
community subscription availability @ https://ubuntu.com/advantage
Fixes: #725
=> ux: new messaging on ua disable failures

uaclient/cli.py
Changes the help text from:
```
usage: ubuntu-advantage enable [flags] <name>
Services:
name        The name of the support service to enable
Flags:
-h, --help  show this help message and exit
```
to the more clear:
```
usage: ubuntu-advantage enable [flags] <name>
Arguments:
name        The name of the support service to enable
Flags:
-h, --help  show this help message and exit
```
(And does the same for disable, too.)
=> cli: fix minor nit in help output for enable and disable

uaclient/serviceclient.py, uaclient/tests/test_serviceclient.py
The code previously was attempting to access `e.code`, which will only
exist on HTTPError instances.  As a result, more general URLErrors would
cause an unexpected traceback, which would be exposed to users.
Fixes #740
=> serviceclient: handle non-HTTPErrors gracefully

uaclient/apt.py, uaclient/status.py
- Drop quotes around service name when Enabling default service 'x'
- Drop apt authenticated repository messages to the 
Fixes: #728
=> ux: simplified attach console messages

uaclient/apt.py, uaclient/tests/test_apt.py
This avoid tracebacks that occur if apt-helper deletes the path that it
is passed (which happens on older versions of Ubuntu).
Fixes #755
=> apt: use a TemporaryDirectory instead of NamedTemporaryFile

uaclient/config.py, uaclient/status.py, uaclient/tests/test_config.py, uaclient/tests/test_status.py
- Add new status template for attached machines that includes description column
- Rename UserFacingStatus.(ACTIVE|INACTIVE) printed values:
active -> "enabled"
inactive -> "disabled"
- Add new UserFacingStatus.UNAVAILABLE -> "—"
=> ux: add attached status description column and headers

uaclient/cli.py, uaclient/tests/test_cli_attach.py
In practice, we never use the parser=None codepath in real usage, so (a)
remove it from all the *_parser functions, and (b) update the tests in
test_cli_attach which relied on it to instead use get_parser or a mock.
=> cli: remove unused *_parser codepaths

uaclient/entitlements/livepatch.py, uaclient/entitlements/repo.py, uaclient/status.py
This is part of addressing #726, and gets the UX in-line for livepatch. Another change for repo entitlements will follow, which will complete the fix.
=> ux: remove "<entitlement> disabled." messaging on disable

uaclient/entitlements/fips.py
FIPS: generic messaging for reboot required during post_enable. Don't mention pending state.
=> fips: generic reboot required message

uaclient/cli.py, uaclient/contract.py, uaclient/entitlements/__init__.py, uaclient/entitlements/base.py, uaclient/entitlements/cc.py, uaclient/entitlements/cis.py, uaclient/entitlements/esm.py, uaclient/entitlements/fips.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/tests/test_esm.py, uaclient/tests/test_cli.py, uaclient/tests/test_cli_disable.py, uaclient/tests/test_config.py, uaclient/tests/test_contract.py
User docs, cli and contracts backend will now all refer to esm as esm-infra in preparation for the eventual esm-apps service.  Even though ESM for Apps will not be on trusty, we want to align the service name on all distributions to avoid confusion.
To support this change
- ESMEntitlement.name is now esm-infra
- ua --help docs now source *Entitlement.description values to avoid updating two places in source
with the same text
Fixes: #724
=> ux: esm service renamed to esm-infra

tools/ua.bash
tab completion needs to use esm-infra service name instead of esm.
=> bash: auto-completion of esm-infra instead of esm

debian/postinst, uaclient/gpg.py
Both debian/postinst and uaclient/gpg call to gpg on the command line in
order to extract a known GPG key for a service we are enabling.
Update both of these callsites to use the same gpg parameters.
Also, add --no-options parameter which prevents custom gpg config
options from being sourced as well as preventing the creation of
.gnupg in the current user's homedir.
Fixes: #776
=> gpg: do not create .gnupg dir during key extraction from shared keyring

debian/postinst, uaclient/config.py, uaclient/tests/test_config.py
Set the private subdirectory permissions in two places:
- package upgrade
- runtime, when the private subdirectory is created
Fixes issue #645
=> Make private dir 0700

debian/postinst, debian/postrm
Ensure that esm apt list files are not installed on non-trusty or
removed across package upgrade.
Also add upgrade path from existing ubuntu-advantage-tools v8 (the shell version) which named the apt 
/etc/apt/sources.list.d/ubuntu-esm-trusty.list.
Since service-name is now esm-infra we needed to mv the old filename to the new ubuntu-esm-trusty.list
to maintain properly configured esm apt sources, as well as overwrite the settings if the new-client attaches.
Fixes: #718
Also fix #778 
- Emit Priority-Pin: Never if we are also installing the apt/sources.list.d/*esm file (because we are not enabled for esm package downloads yet)
ESM repos are essentially read-only public for package lists in order to allow non-root users to see upgradable esm packages. Change debian/postinst to …
=> packaging: enable esm trusty-infra-updates and -security suites on trusty

debian/postinst
using --output in postinst results in a lot of noise on stdout. Prefer
redirect to create the desired esm keyring file
Fixes: #798
=> pkg: postinst esm keyring creation redirect stdout instead of --output

Makefile
The in-cloud mirrors are more prone to error conditions which older
versions of apt don't handle gracefully, so avoid using them.
=> Makefile: don't use a DEBOOTSTRAP_MIRROR for trusty

uaclient/config.py, uaclient/testing/fakes.py, uaclient/tests/test_cli_attach.py, uaclient/tests/test_config.py
Attached machines should surface subscription-id and account-id to aid
in triage for backend account lookup issues.
Fixes: #805
=> status: add account-id and subscription-id to status json

Makefile
It turns out that archive.ubuntu.com exhibits the same issues as the
in-cloud mirrors, so we may as well use the in-cloud mirrors for
improved performance.
This reverts commit 5904e79ed4c7000f27ed75f4e9643fd02567fb6a.
=> Revert "Makefile: don't use a DEBOOTSTRAP_MIRROR for trusty"

uaclient/cli.py, uaclient/tests/test_cli.py
As discussed in #777, we want to interject a new check after we've checked that a user is root, but before we check if they are attached or not. To that end, this PR refactors `assert_attached_root` into `assert_root` and `assert_attached` for the two checks it performs. (As `refresh` and `detach` will both continue wanting it, `assert_attached_root` is retained as sugar for using the two decorators together.)
(Side note: I normally prefer to include usage of new functions being introduced in my PRs and while this doesn't include any new, direct use of the two decorators, they are still used by every command definition, so I'm relaxing my rule a little to split this review across more than 1 PR.)
=> Refactor assert_attached_root into separate decorators

apt.conf.d/51ubuntu-advantage-esm
i.e. trusty-infra-security instead of trusty-security
Fixes #825
=> 51ubuntu-advantage-esm: update Allowed-Origins for new naming

debian/postinst
Precise legacy creds are entitled to esm on trusty. do-release-upgrade
will have re-written existing apt sources list files replacing 'precise'
pockets with 'trusty'.
On precise machines which had ESM enabled, the debian/postinst will now
migrate valid apt sources filename during do-release-upgrade from:
/etc/apt/sources.list.d/ubuntu-esm-precise.list
to:
/etc/apt/sources.list.d/ubuntu-esm-infra-trusty.list
This way precise credentials are retained and uaclient runtime will
update or remove /etc/apt/sources.list.d/ubuntu-esm-infra-trusty.list if
"ua disable or enable esm" operations are performed on trusty.
Fix: #693
=> pkg: precise to trusty upgrade move valid apt creds to trusty apt source

uaclient/cli.py, uaclient/tests/test_cli.py, uaclient/tests/test_cli_disable.py, uaclient/tests/test_cli_enable.py
It does so by introducing a new decorator for the "is this a valid service name" check which is interjected between the root check and the attached check.
Fixes #777
=> Display the correct wording for unattached enable/disable of invalid services

uaclient/entitlements/base.py, uaclient/entitlements/tests/test_livepatch.py
livepatch: check is_container before recommending kernel upgrade
On a container, livepatch isn't every going to be supported, so
there is little sense in checking kernel version first and telling
the user to upgrade their kernel only to find out after reboot that
they still can't enable livepatch because livepatch doesn't run on the
container.
Reorder static_affordances (which tend to be uncorrectable on a
platform) before more dynamic environment affordances like <series>
or kernel revision which can up updated on a machine to bring it into
compliance.
Fixes: #807
=> livepatch: check is_container before recommending kernel upgrade

debian/postinst
Update postinst to look for previous package version 1 to know that it
is upgrading from precise to trusty. Can't use 12.04 series because that series wasn't included
in the published precise package ver.
Fixes: #693
=> pkg: prev_version in precise is version 1 and doesn't contan 12.04

uaclient/cli.py, uaclient/tests/test_cli.py, ubuntu-advantage.1
Namely:
* start with lower case (to match the built-in help text for argparse)
* drop trailing periods (also to match argparse's behaviour)
* standardise on "Ubuntu Advantage" (instead of a mix of that, "ubuntu
advantage" and "ubuntu-advantage")
* refer to "Ubuntu Advantage services" instead of "support services"
=> cli: make help text consistent

uaclient/cli.py, uaclient/tests/test_cli_attach.py
Instead of "ubuntu-advantage".  This will make us consistent with other
documentation.
Fixes #844
=> cli: use "ua" as the command name in help messages

debian/rules
Fixes issue #845 
Mostly based on https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1840091/comments/3. Interesting bits:
- apt-transport-https was merged with apt in v1.5, and the package became a transitional package and was moved to universe. That's why we don't depend on it past xenial
- likewise, `libapt-instXX` was merged with `libapt-pkg` in version 1.9.0 and that's why we don't depend on it in eoan
- I picked the version to depend on based on this changelog entry: `Add test case for local-only packages pinned to never`, which was a test case for another feature we need (the `Never` pinning case), and came after support for `auth.conf.d` was added.
- I debated whether to add the dependencies for eoan or not, since the released version will have the fixes we …
=> Update apt deps

uaclient/cli.py, uaclient/tests/test_cli.py, uaclient/tests/test_cli_status.py, uaclient/tests/test_contract.py
status: better user-facing error on connectivity errors
Generalize exception handling for any util.UrlError raised by the
commandline. Log any urlerror tracebacks and emit the message:
Failed to connect to authentication server
Check your Internet connection and try again
Fixes: #858
=> status: user-facing-error on get_available_resources connectivity issues

uaclient/cli.py, uaclient/tests/test_cli_status.py
When we detect that stdout's encoding isn't UTF-8, we replace \u2014 with -.
This is specifically targeted to fix #859, there may be more general changes to follow.
=> cli: replace UTF-8 dash with ASCII dash for non-UTF-8 output 

README.md, features/steps/steps.py, features/unattached_commands.feature, features/unattached_status.feature, mypy.ini, test-requirements.txt, tox.ini
This PR introduces integration testing for the project. It leverages the [behave](https://behave.readthedocs.io/en/latest/index.html) BDD framework to allow us to write tests that look similar to the UX documentation we've been given, with the implementation of those steps written in Python code.
This PR is enough for people to start iterating on new tests locally, but there is more work to be done: #853, #854, #855, #856, #857
=> Introduce integration testing driven by behave

uaclient/entitlements/tests/test_base.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_repo.py, uaclient/status.py
We removed unnecessary periods from a number of messages, but not everything. This grabs a few more. There are some additional messages that should also be cleaned up in future releases as we add additional services.
=> output: remove unecessary periods

debian/changelog
I looked at the git log from 19.5.1 to 7f277d09a48dc073fda6a91f2000a6275d4fc962 and these are the important changes I think should be mentioned in `debian/changelog`.
Once this lands, there should be another MP opening up 19.7 for development, with the ubuntu release name field set to `UNRELEASED`. I don't want to do that together here because I want to be able to use a 19.6 tag in the repository for the basis of building the trusty package.
=> d/changelog: 19.6 entries

debian/postinst
UA client for root and non-root both can succeed in absence of
/var/lib/ubuntu-advantag/status.json. Running ua status from
postist will break dep8 tests due to ua status requiring external
network connectivity.
Fixes: #881
=> pkg: postinst no longer need to call ua status to update cache files

uaclient/cli.py, uaclient/status.py, uaclient/tests/test_cli.py
In the event of unhandled UrlErrors from ua-client operations log
the same connectivity error message seen to the console and the error
string instead of a full traceback in the logs.
Only log the exception traceback if the UrlError doesn't have a defined
url.
Fixes: #868
=> log: log connectivity error message and url instead of traceback

sru/1832757/esm-trusty-test-1.md, sru/1832757/esm-trusty-test-2.md, sru/1832757/esm-trusty-test-3.md, sru/1832757/esm-trusty-test-4.md, sru/1832757/esm-trusty-test-5.md, sru/README.md
Add a collection of SRU manual verification scripts to an ./sru subdirectory.
We can leverage these scripts in filing SRU results as well as having a tome of scripts for reference when we have other SRU verfications to exercise.
=> sru: add sru subdirectory to track SRU verification scripts

debian/postinst
When upgrading from precise to trusty and esm is enabled,
ubuntu-advantage-tools v 10ubuntu0.14.04.4 does not rename
any apt precise apt sources files to trusty.
So if customers have already upgraded from precise enabled-esm to trusty
10ubuntu0.14.04.4, a subsequent upgrade to version 19.6 will
skip trying to rename:
ubuntu-esm-precise.list -> ubuntu-esm-infra-trusty.list.
postinst unconditionally renames ubuntu-esm-precise.list to
ubuntu-esm-infra-trusty.list. It no longer limits this rename
operation to the case where postinst is upgrading from version 1 (the precise
package version)
Fixes: #899
=> pkg: rename existing ubuntu-esm-precise.list file to trusty

.travis.yml, features/environment.py, features/steps/steps.py, features/unattached_commands.feature, features/unattached_status.feature, features/util.py
`lxc exec` runs as root by default, so we modify the way we call it to specify UID 1000. This also updates other code that uses `lxc_exec` to add `sudo` if needed, and fixes the feature files to reflect the actual non-root output.
=> Integration tests: actually run non-root tests as non-root

setup.py
Fixes: #903
```
lxc launch ubuntu-daily:trusty dev-t
lxc exec dev-t bash
git clone this branch
cd ubuntu-advantage-client
make deps
dpkg-buildpackage -us -uc
dpkg -c ../ubuntu-advantage-tools_19.6_amd64.deb | grep feature
```
=> pkg: dpkg-buildpackage should not package integration tests features dir

setup.py
Fixes: #903
```
dpkg-genchanges  >../ubuntu-advantage-tools_19.6_amd64.changes
dpkg-genchanges: including full source code in upload
dpkg-source --after-build ubuntu-advantage-client
dpkg-buildpackage: full upload; Debian-native package (full source is included)
root@dev-t:~/ubuntu-advantage-client# dpkg -c ../ubuntu-advantage-tools_19.6_amd64.deb | egrep 'sru|entitlements|feature'
drwxr-xr-x root/root         0 2019-10-30 19:28 ./usr/lib/python3/dist-packages/uaclient/entitlements/
-rw-r--r-- root/root      3056 2019-10-29 18:45 ./usr/lib/python3/dist-packages/uaclient/entitlements/fips.py
-rw-r--r-- root/root     13728 2019-10-29 18:45 ./usr/lib/python3/dist-packages/uaclient/entitlements/base.py
-rw-r--r-- root/root       803 2019-10-29 18:45 …
```
=> pkg: dpkg-buildpackage should also ignore all modules under features dir

uaclient/config.py, uaclient/status.py, uaclient/tests/test_config.py, uaclient/tests/test_status.py
The response from machine attach (machine-token.json) provides an
availableResources list.  Any item in availableResources which is not
"available" will provide a "description" that should be surfaced as a
user-facing custom description for any n/a service.
The command `ua status` should surface these custom descriptions in the
DESCRIPTION column for any n/a service.
In the absence of a custom status "description" for an inapplicable
service, use the static entitlement.description.
Fixes: #790
=> status: custom descriptions for n/a service status

debian/postinst
Same change as https://github.com/CanonicalLtd/ubuntu-advantage-client/pull/915 but for master
=> d/postinst: only configure ESM on supported architectures (LP: #1851858)

debian/changelog, debian/postinst
Fixes issue #911 
I'm using `dpkg --print-architecture` and not `uname -a`, but it's fine since it's contained in the postinst script. This does introduce another point where the list of supported architectures for esm-infra is stored, however. If this list ever changes, an SRU will be needed.
@blackboxsw wondered if we couldn't do something dynamic in postinst, but that would involve a network call, like `ua status` already does. It could be an option I guess, and fallback to a hardcoded list if the network isn't available, but it might be frowned upon, and will not work in our builders and DEP8 runners (egress filtering would block it).
=> Ua nonx86 fix

uaclient/cli.py, uaclient/clouds/__init__.py, uaclient/clouds/aws.py, uaclient/clouds/identity.py, uaclient/clouds/tests/test_aws.py, uaclient/clouds/tests/test_identity.py, uaclient/contract.py, uaclient/exceptions.py, uaclient/status.py, uaclient/tests/test_cli.py, uaclient/tests/test_cli_attach.py, uaclient/tests/test_cli_attach_premium.py
Provide a new attach-premium subcommand that will crawl AWS premium
metadata and provide that to new aws ua-contacts backend route to
allow for easy attach of premium images without having to obtain a
token from ubuntu.com/advantage
=> premium: add aws support for premium images

uaclient/entitlements/cc.py, uaclient/entitlements/cis.py, uaclient/entitlements/esm.py, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_repo.py, uaclient/exceptions.py, uaclient/status.py
Before this commit, we had a hard-coded default that we would use if the
contract server failed to provide us with an aptURL directive.  The
logic for that default becomes more complex with xenial/bionic, because
the URLs have changed.
Instead of introducing more complexity into the client, we instead drop
that defaulting, with the assumption that the contract server will
always provide an aptURL directive.
=> entitlements: rely solely on contract server for repo_url

uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_repo.py
Instead report the service as disabled, as without an aptURL it's very
unlikely that we could have enabled it.
=> repo: don't raise exception in application_status if aptURL missing

Makefile, debian/control, debian/rules, setup.py, systemd/ua-premium.service, upstart/ua-premium.conf
Add upstart script and systemd unit which will wait for cloud-init to complete before attempting to run ua attach-premium on a machine.
On non-premium images, `ua attach-premium` exits 0 and logs that attach a platform is not detected as a premium image.
On attached machines after reboot, `ua attach-premium` logs a message that the machine is already attached and exits 0.
=> ua premium: add upstart  and systemd boot scripts to automatically attach premium images

uaclient/clouds/aws.py, uaclient/clouds/tests/test_aws.py, uaclient/util.py
Since metadata services could go down intermittently for maintenance,
add a retry decorator that acceepts a list of sleep times to use when
catching an exception.
Add this retry decorator and a simple backoff of three retries at
1s 2s and 5s to attempt to allow for short downtimes of
the indetity_doc route for AWS.
=> premium: add retry decorator around aws.identity_doc to handle failure

uaclient/cli.py, uaclient/contract.py, uaclient/exceptions.py, uaclient/tests/test_cli_attach_premium.py
Contracts server returns the api error "missing instance information"
when non-premium identity docs are sent to the aws token request route.
Handle this error and emit a message about being a non-premium image.
Also refactor attach_premium function to be a bit easier to test.
=> premium: aws handle contract error for non-premium pkcs7 identity

debian/rules
The hook only reports for esm-infra, not for esm-apps.  We don't have
time to address that before the deadline we are working towards, so drop
it to avoid an inconsistent user experience.
(Note that for xenial and later, the hook only reports when entitlements
are enabled, so this will retain the unattached/un-enabled behaviour we
already have.)
=> d/rules: don't install the apt hook

uaclient/config.py, uaclient/contract.py, uaclient/testing/fakes.py, uaclient/tests/test_cli_attach.py, uaclient/tests/test_config.py, uaclient/tests/test_contract.py
For attached machines only.
When `ua enable <SERVICE>` or `ua refresh` is called, the client
now POSTs updated arch, kernel and OS information to the contracts
server. The contract server response will contain an updated
'availableResources' key which updates the 'status' and 'description'
columns for each applicable/inapplicable service.
This is a followup branch iteratively improving the behavior introduced
by fixing #790 to add dynamic description content from the backend
server. Now uaclient performs less API calls by avoiding a round trip to
contracts.canonical.com/v1/resources to obtain updated status
information.
There will need to be a single followup branch that will address a  gap in this behavior (#913): 
On trusty vm with stock kernel:
```
sudo ua attach
sudo apt-get install …
```
=> status: dynamic available status now from refreshed machine-token

uaclient/clouds/aws.py, uaclient/clouds/tests/test_aws.py
On some AWS instance types, it doesn't exist.  We have the fallback
logic for those cases already, but we need to ignore FileNotFoundError
to get to it.
Fixes #946.
=> aws: handle missing SYS_HYPERVISOR_PRODUCT_UUID

debian/rules
Previously, installation of ubuntu-advantage-tools would automatically
reload systemd and trigger auto-attach on supported platforms.
Avoid that side-effect by providing --no-start to dh during package
build.
Fixes: #948
=> pkg: provide --no-start to debhelper to avoid auto-attach on pkg install

features/util.py
The text parameter was added to subprocess.run, as a more understandable alias
of universal_newlines, in Python 3.7.
This allows users to run the behave tests in Pre 3.7 Python versions.
=> fix text parameter for pre3.7 Python versions

tox.ini
This is required to get full tracebacks, which are very useful for
debugging.
=> tox.ini: run behave with --verbose

tools/constraints-bionic.txt, tools/constraints-disco.txt, tools/constraints-eoan.txt, tools/constraints-trusty.txt, tools/constraints-xenial.txt
This is #959 but for `master` instead of the `trusty-auto-attach` branch.
=> Constrain PyYAML for all releases

uaclient/cli.py, uaclient/contract.py, uaclient/tests/test_cli_auto_attach.py
Note that some errors from the contracts server don't set HTTP status and raise 403.
Errors like API_ERROR_MISSING_INSTANCE_INFORMATION for AWS resulted in 500s on the server and have now been changed per https://github.com/CanonicalLtd/ua-contracts/pull/517/files to return HTTP status code 404
Fixes #939
=> auto-attach: handle 403 errors raised by contract server for invalid vms

uaclient/clouds/__init__.py, uaclient/clouds/aws.py, uaclient/clouds/tests/test_aws.py
AutoAttachCloudInstance.identity_doc now returns a dict to allow
for different clouds to return more complex identity data during
auto-attach.
(This contains pieces that were missed in the previous merge into master.)
=> clouds: generalize identity_doc to return dict instead of string

uaclient/status.py
If already attached, and a user wants to switch. Message about
running `sudo ua detach` in order to change from the current
subscription.
Fixes: #935
=> output: add messaging using a different subscription if attached

uaclient/cli.py, uaclient/config.py, uaclient/tests/test_cli_attach.py
There can be cases where auto-enablement of a service results in an
error. Or, intermittent connectivity to ua-contracts routes end up
resulting in an error during `ua attach`.
In the event that attach succeeds, but auto-enablement actions fail
status needs to be persisted to reflect whether attach succeeded and
any services have been successfully enabled.
Fixes: #952
=> attach: persist any status config changes after attach failures

uaclient/clouds/identity.py, uaclient/clouds/tests/test_identity.py
Sync commit from trusty-auto-attach to master
Fixes: #977
=> azure-pro: fix detection of DatasourceAzureNet as azure on trusty

.travis.yml, uaclient/tests/test_cli.py
We recently saw our first in-focal regression, so now is the time to start gating on it (and to fix the regression, of course!).
=> add focal builds to CI and fix focal build failure

Makefile
We're currently seeing test failures because the version of six
pre-installed in the Travis virtualenv is too old, and it isn't upgraded
of its own accord.
Fixes #987
=> Makefile: in testdeps, upgrade six before installing tox

uaclient/cli.py, uaclient/tests/test_cli_detach.py
If passed, the confirmation prompt will be skipped.
Fixes #949
=> Add --assume-yes parameter to `ua detach`

uaclient/tests/test_cli_attach.py
When referencing these tests for the detach work, I noticed that we
could split this test up a little to give more granular feedback.
=> test_cli_attach: split apart some parser tests

uaclient/entitlements/esm.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_esm.py, uaclient/entitlements/tests/test_repo.py
Differentiate ESMInfra's repo_pin_pririority and disable_apt_auth_only
Retain Xenial and Bionic behavior for ESMInfra which will behave like
ESMApps which removes any apt artifacts (preferences, auth or list
files) when ESMInfra is disabled.
Fixes: #940
=> esm: restore trusty apt pinning behavior

uaclient/contract.py, uaclient/defaults.py, uaclient/status.py, uaclient/tests/test_contract.py
Continue to process all entitlements if hitting unexpected errors
during service enablement during attach or refresh. Previously,
if UA client hit APT failures during enablement of repo-based services
the UA client would exit with a traceback and avoid enabling any remaining
services.
Now, log any unexpected failures and only raise it once all service deltas
have been processed. Unexpected errors will now alert the user with a
message to check /var/log/ubuntu-advantage.log and file a bug.
Fixes: #953
=> contract: handle unexpected errors when processing contract deltas

uaclient/testing/fakes.py, uaclient/tests/test_cli.py, uaclient/tests/test_cli_attach.py, uaclient/tests/test_cli_auto_attach.py, uaclient/tests/test_cli_detach.py, uaclient/tests/test_cli_disable.py, uaclient/tests/test_cli_enable.py, uaclient/tests/test_cli_refresh.py, uaclient/tests/test_cli_status.py, uaclient/tests/test_config.py, uaclient/tests/test_contract.py
Once landed this FakeConfig tmp data_dir support will be used in both of the PRs:
#994 and #985
=> testing: simplify FakeConfig to only leverage tmpdir fixture

uaclient/conftest.py, uaclient/testing/fakes.py, uaclient/tests/test_cli.py, uaclient/tests/test_cli_attach.py, uaclient/tests/test_cli_auto_attach.py, uaclient/tests/test_cli_detach.py, uaclient/tests/test_cli_disable.py, uaclient/tests/test_cli_enable.py, uaclient/tests/test_cli_refresh.py, uaclient/tests/test_cli_status.py, uaclient/tests/test_config.py, uaclient/tests/test_contract.py
This simplifies test code currently, and also gives us a cleaner
interface for any future modifications that might be required for
FakeConfig.
=> uaclient: convert FakeConfig to a fixture

uaclient/cli.py, uaclient/contract.py, uaclient/status.py, uaclient/tests/test_cli.py, uaclient/tests/test_contract.py
In the event that client hits an unexpected error, tracebacks at the
CLI don't help most users. We want to prompt users to inspect
/var/log/ubuntu-advantage.log if possible and file a bug with
ubuntu-bug ubuntu-advantage-tools
Fixes: #643
=> ux: catch any unexpected tracebacks and report a user-friendly message

features/environment.py, features/util.py
Integration tests using behave will now observe the environment variable
UACLIENT_BEHAVE_DESTROY_INSTANCES=0 which will allow behave to leave
the test instance running after completion of the integration test.
=> testing: override destroy_instances to avoid vm teardown by behave

debian/postinst, uaclient/config.py, uaclient/contract.py, uaclient/entitlements/base.py, uaclient/entitlements/tests/conftest.py, uaclient/entitlements/tests/test_base.py, uaclient/entitlements/tests/test_repo.py
Drop remaining call site of request_resource_machine_access and any UAConfig support
for machine-access data paths.
Entitlements will now call contract.request_updated_contract instead of request_resource_machine_access when entitlement is found expired.
Additionally we want to clean the unused /var/lib/ubuntu-advantage/private/machine-access*json files upon upgrade, since they will not be read again by ubuntu-advantage-tools
=> contract: drop remaining support for request_resource_machine_access

setup.py
Unattended-upgrades package now delivers the following apt config on
xenial, bionic, eoan and focal:
Unattended-Upgrade::Allowed-Origins {
...
"${distro_id}ESMApps:${distro_codename}-apps-security";
"${distro_id}ESM:${distro_codename}-infra-security";
Ubuntu-advantage-tools now only needs to deliver this apt config file
on trusty.
Fixes: #1005
=> deb: only deliver apt esm allow-origins cfg on trusty

uaclient/entitlements/tests/test_livepatch.py, uaclient/tests/test_util.py, uaclient/util.py
As well as adding some patches that were missing (and started causing failures once `get_platform_info` was invoking `util.subp`).
Fixes #914
=> util: use `dpkg --print-architecture` in get_platform_info

features/attach_validtoken.feature, features/environment.py, features/steps/steps.py
TODO list:
- figure out a way of checking the colored status
- currently it is not working because if you are entitled to a service and if
it is enabled - they are green.
- improve skip option: the test do not run, but didn't show the message
- maybe check if contract_token is None inside `UAClientBehaveConfig` class
=> testing: add integration test for behavior of attaching a valid_token

debian/changelog, debian/control, debian/postinst, debian/rules, debian/ubuntu-advantage-tools.maintscript, debian/ubuntu-advantage-tools.templates, uaclient/version.py
In 20.2, a separate ubuntu-advantage-pro package will deliver the systemd or upstart unit which performs the Ubuntu Pro auto-attach.
Package separation of ua-pro from ua-tools allows the ubuntu-advantage-tools package to avoid complexity in determining whether a platform is certified as Ubuntu Pro before running the systemd or upstart auto-attach functionality on boot.
By delivering the systemd or upstart units in a separate deb package, both the init scripts and ubuntu-advantage-tools package can remain simple because the auto-attach features will only be
present and "active" when ubuntu-advantage-pro package is installed, which will only be on Ubuntu Pro images.
Due to the migration of upstart units and systemd services out of ubuntu-advantage-tools package,
the following changes have …
=> pkg: introduce a separate ubuntu-advantage-pro package v. 20.2

features/environment.py, features/steps/steps.py
changes for reusing a container with userdata config
It allows to run behave choosing an existent container to run the tests in.
I've added it via `userdata` config, so just add `-D reuse_container=existent_cont`.
From that point, it will then proceed to install UAT.
If you don't add this config it stays the same.
=> Reuse container

features/attach_validtoken.feature, features/steps/steps.py
It will avoid calling this step sending `contract_token` parameter that
is not taken into account, as it is provided via CLI environment variable `UACLIENT_BEHAVE_CONTRACT_TOKEN=...`.
The current way, doesn't matter what the function has received
because `contract_token = context.config.contract_token` overrides it.
=> refactor contract_token parameter

features/attach_invalidtoken.feature
it adds a new feature file when it tries to attach a machine to an UA subscription using an invalid_token
=> add test for behavior of attaching an invalid_token

README.md, RELEASES.md, debian/changelog, tools/make-release, tools/make-tarball
Add scripts and doc guidance for releasing ubuntu-advantage-tools.
Generally we'll be using ./tools/make-release -p <your_PPA_URL_FOR_TESTING>
Used this branch to push to a test PPA for build and test:
sudo add-apt-repository ppa:chad.smith/test-release-ua-tools
Fixes: #1009
LP: #1869980
=> tool: add make-release script for releasing ubuntu-advantage-tools

features/environment.py, features/steps/steps.py, features/util.py
Currently it is not checking the correct series to run the tests in.
It fixes the issue: if you provide a container `-D reuse_container=cont_name`
it will run either series tests with the same container.
=> fix reuse_container option

uaclient/cli.py, uaclient/tests/test_cli_detach.py, uaclient/tests/test_util.py, uaclient/util.py
Foundational to supporting FIPS custom confirmation messages on enable/disable.
Custom prompts will be used by `ua enable fips` and `ua disable fips` to address #1031 
As a note, the final branch for the prompt features which contains this PR will be this branch:
https://github.com/blackboxsw/ubuntu-advantage-client/tree/feature/fips-support
=> util: prompt_for_confirmation custom msg and assume_yes

uaclient/entitlements/cc.py, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_repo.py
Consolidate messaging hook processing under a single function
handle_message_operations.
Make messaging an instance property so it can dynamically leverage instance variables at runtime.
This is groundwork for FIPS pre-enable and pre-disable custom
messaging and prompts for #1031.
As a note, the final branch for the prompt features which contains this PR will be this branch:
https://github.com/blackboxsw/ubuntu-advantage-client/tree/feature/fips-support
=> repo: allow for pre_enable messaging interactions

tools/constraints-bionic.txt, tools/constraints-xenial.txt
pyflakes versions older than 2.1.0 are incompatible with Python 3.8
(which is the Python version in the Focal release).
See https://github.com/PyCQA/pyflakes/issues/367 for details.
2.1.1 is the latest version ATM, so bump to that.
Fixes: #1023
To test:
tox -e flake8-xenial  # expect traceback with CONSTANT
tox -e flake8-bionic  # expect traceback with CONSTANT
success on both tox -e flake8-xenial and flake8-bionic 
Comparable change done in cloud-init as well https://github.com/canonical/cloud-init/commit/64c33704853087c05c54e157fc42a340a4350159
=> tox.ini: bump pyflakes version to 2.2.0

uaclient/cli.py, uaclient/contract.py, uaclient/entitlements/base.py, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/conftest.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_repo.py, uaclient/status.py, uaclient/tests/test_cli_disable.py, uaclient/tests/test_cli_enable.py, uaclient/util.py
Add the following prompts to FIPS and FIPS with Updates:
* ua enable fips-updates: 
```
This system will NOT be considered FIPS certified, but will include security    
and bug fixes to the FIPS packages.
Are you sure? (y/N)
```
* ua disable fips and ua disable fips-updates:
```
This will disable access to certified FIPS packages.                            
Are you sure? (y/N)
```
This addresses parts of https://github.com/canonical/ubuntu-advantage-client/issues/1031
Expect one more branch which will add remaining prompts and messaging for post_disable messaging.
to test:
```
cat > ua-dev.yaml <<EOF
#cloud-config
packages:
- git
- make
runcmd:
- git clone -b feature/fips-support https://github.com/blackboxsw/ubuntu-advantage-client.git /var/tmp/uac
- cd /var/tmp/uac/
- make deps
- …
```
=> fips: add console prompts during to fips and fips-updates

uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py, uaclient/status.py
Addresses the last remaining FIPS-related prompt and message when
running: ua enable fips.
Fixes: #1031
To test:
```
cat > ua-dev.yaml <<EOF
#cloud-config
packages:
- git
- make
runcmd:
- git clone -b feature/fips-pre-enable-prompt https://github.com/blackboxsw/ubuntu-advantage-client.git /var/tmp/uac
- cd /var/tmp/uac/
- make deps
- dpkg-buildpackage -us -uc
- apt-get remove ubuntu-advantage-tools   # Issue: #1044
- dpkg -i /var/tmp/ubuntu-advantage-tools_20.4_amd64.deb
- ua attach <YOUR_TOKEN>
EOF
multipass launch daily:xenial --cloud-init ua-dev.yaml  -n dev-xx
multipass connect dev-xx
cloud-init status --wait --long
sudo ua status
sudo ua enable fips
=> fips: add pre_enable prompt indicating that additional debs required

features/attach_invalidtoken.feature, features/attach_validtoken.feature, features/attached_enable.feature, features/unattached_commands.feature, features/unattached_status.feature
focal: add integration tests for all .features' files.
This way we are going to be able to run only one specific Ubuntu series using behave tags option `--tags=series.focal`.
Closes: #1022
=> focal: add integration tests

uaclient/entitlements/livepatch.py, uaclient/entitlements/tests/test_livepatch.py
Before installing additional snaps, we need to wait for snap seeding
to complete. Make sure blocking is called always instead of just
when we have installed the snapd deb package.
Fixes: #1049
=> livepatch: run snap wait system snap.seeded before trying to install

debian/changelog, uaclient/entitlements/livepatch.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/version.py
Update the released versioning scheme for ubuntu-advantage-tools to be milestone-based (24.0)
* Apply a single bugfix for livepatch enablement that calls snap wait system seed.loaded
`git cherry-pick 97643f9b9627887d8329f4c1c7fd76856214a37a`
* Increment the minor version to 24.1 to represent a bug-fix only release
`dch --newversion 24.1`   # add new bug-fix-only release
=> bug-fix "livepatch snap wait" into release-24 branch 

debian/changelog, uaclient/tests/test_version.py, uaclient/version.py
In order to use git-ubuntu workflow, we have to replay git commits from our release-XX branches onto a git-ubuntu pkg/ubuntu/devel branch in order to submit merge proposals such as the following [git-ubuntu MP to release ubuntu-advantage-tools on groovy](https://code.launchpad.net/~chad.smith/ubuntu/+source/ubuntu-advantage-tools/+git/ubuntu-advantage-tools/+merge/384297)
Bryce, caught that tox and autopkgtest both fail because git describe --match [0-9]* doesn't find an valid signed upstream tag.  
This branch falls back to dpkg-parsechangelog -S version in the event that git describe fails. This allows pkg testing and verification to proceed during the package build process.
To put together an MP for git-ubuntu upload release-24 we follow this mechanism:
```
snap install git-ubuntu …
```
=> Fix uaclient/version for git-ubuntu pkg branches release 24.1

features/attached_commands.feature, features/unattached_commands.feature, uaclient/cli.py
Right now, ua-client does not support both `ua --version` and `ua -v` commands. This PR adds these commands and test them through behave. This feature is related to #663
=> Fix version command

debian/changelog, uaclient/tests/test_version.py, uaclient/version.py
Bump the version of ua-tools under active development to version 25 to ensure that daily recipe
builds from 'master' are greater than any public releases of ubuntu-advantage-tools which
were published from a release-24 branch.
The master branch will remain in version 25 until release-25 branch is created for public release.
At that time, master' will open version 26 for active development.
This version follows our new versioning scheme proposal which is a milestone-based versioning instead of year-based versioning scheme as documented in the [branch release strategy spec](https://docs.google.com/document/d/1rmq-Vm18lmCmxT-aTzErtzL0AZt3-ZRWtny6FQE2Ah4/edit#) 
Also in this branch:
- manually add debian/changelog entries for 24.0 and 24.1 in existing release-24 to ensure master
does not lose …
=> Open milestone 25 for active development

uaclient/pip.py, uaclient/tests/test_pip.py
This PR creates the pip module in ua-client. This module will be used when we deploy `esm-python` service. This service will need to configure the `/etc/pip.conf` file with some extra configuration.
Right now we make the following considerations regarding `/etc/pip.conf`:
* If the file exists and has extra configuration on it, we maintain them
* If the file has configuration that conflicts with the configuration we want to use, we override the existing configuration with the new one.
=> Add pip module

tools/ua-dev-cloud-config.yaml
When creating a new development environment for ua-client, there is an error when installing the deb package. Since we are now in version 25.0, we need to update this version on the `ua-dev-cloud-config` file as well.
=> Update package version on dev tools

features/attach_validtoken.feature, features/attached_commands.feature, features/attached_enable.feature, features/environment.py, features/staging_commands.feature, features/steps/steps.py, features/unattached_commands.feature
Add the ability to pass a UACLIENT_BEHAVE_CONTRACT_TOKEN_STAGING environment variable into behave tests to exercise staging service cc-eal.
To test:
Grab your staging credentials from https://auth.contracts.staging.canonical.com/
```
UACLIENT_BEHAVE_CONTRACT_TOKEN_STAGING=<yourtoken> tox -e behave features/staging_commands.feature
```
The intent is to provide a mechinism for ease of test for services which only have proper service
definitions on contracts.staging.canonical.com
Fixes: #1074
=> Test against staging

uaclient/entitlements/cc.py, uaclient/entitlements/cis.py, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/conftest.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_fips.py
Right now, ua-client is not using the `additionalPackages` field when enabling repo services, like `cc-eal` and `fips`. This PR adds the possibility for ua-client to start using these data when enabling repo services.
For fips, we are now using it understand which extra packages should be installed when enabling the service.
=> Use additionalPackages from service payload

features/environment.py
Right now we are missing the `build_pr` command created by #1057 . Because of that, the behave test  for PR #1069 are failing, since we are not building the ua-client from the PR source code.
We are adding the command back in this PR.
=> Add missing build_pr command to environment

features/attached_enable.feature, features/unattached_status.feature, uaclient/cli.py, uaclient/config.py, uaclient/entitlements/base.py, uaclient/entitlements/cc.py, uaclient/entitlements/cis.py, uaclient/entitlements/fips.py, uaclient/tests/test_cli_enable.py, uaclient/tests/test_config.py
Right now, services that are in a beta stage, such as `fips` are shown normally when an user run `ua status`. We are now changing that behavior for `ua status` to only show production ready services. If the user wants to see all services, the command to run will be `ua status --beta`.
Also, if the user tries to enable a beta service using: `ua enable fips`, ua-client will raise an error saying that the service could not be found. To enable beta services, users will need to run the following command: `ua enable fips --beta`
Fixes: #1079
=> Disable beta services to be show/enabled without flag

uaclient/clouds/identity.py, uaclient/clouds/tests/test_identity.py
China and US GovCloud are separate partitions of AWS' cloud.  The `cloud-id`
tool used to identify the clouds and map them to their auto-attach logic only
works in the primary aws partition.  This patch adds support for China and GovCloud.
=> Add AWS cloud partitions (#1077)

debian/changelog, uaclient/clouds/identity.py, uaclient/clouds/tests/test_identity.py, uaclient/version.py
Cherry-pick a bug fix from master for detecting aws-gov and aws-china as valid platforms.
Bump pkg release version from 24.1 -> 24.2
How I created the branch:
```
git checkout upstream/release-24 -B release-24
git cherry-pick 1d75bc84e6c42c42e7d9b6221a68d4fcaf4c3142
git cherry-pick 8a080cb946507a7e9954804ec54fb17f7e65ed01
cat > 1.patch <<EOF
diff --git a/debian/changelog b/debian/changelog
index 6d37794..af0a6ef 100644
--- a/debian/changelog
+++ b/debian/changelog
@@ -1,3 +1,11 @@
+ubuntu-advantage-tools (24.2) groovy; urgency=medium
+
+  * New bug-fix-only release 24.2:
+    - uaclient.version bump to 24.2
+    - pro: Add AWS China and GovCloud partitions support (GH #1077)
+
+ -- Chad Smith <chad.smith@canonical.com>  Wed, 03 Jun 2020 16:12:41 -0600
+
ubuntu-advantage-tools (24.1) …
```
=> Release 24

uaclient/apt.py, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_esm.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_repo.py, uaclient/util.py
Since we currently expect FIPS* package installs to run into local config customization prompts on cloud-images, emit the appropriate apt commandline options to avoid prompting to the console, and preserve the locally modified config files for openssh-server and /boot/grub/menu.lst.
Since we hope to address this config file difference properly in the openssh-server package and fips-metapackage, add a RELEASE_BLOCKER comment to fips.py to ensure we address this with the security and cloud images team before fully supporting FIPS.
Inspired by  jaredledvina's PR #1086
Fixes: #1084
=> fips-only: force apt noninteractive prompts during package installs

debian/postinst
As stated on #1095, when we upgrade ua-client with esm-infra enabled, we end up removing the `ubuntu-advantage-esm-infra-trusty.gpg` file, which puts the system in an incorrect state, since ua-client will state that `esm-infra` will be enabled, but we cannot update its packages.
To fix that, we have updated the `postinst` script to check if `esm-infra` is already enable and only if it is not we let the unconfigure step run.
To test that feature, the following script was used:
```
#!/bin/sh
UA_ACCESS_KEY="UNSET"
check_esm_key() {
name=$1
lxc exec $name -- sudo apt update
lxc exec $name -- ls /etc/apt/trusted.gpg.d/
}
replicate_issue() {
cat > config_error.yaml <<EOF
#cloud-config
packages:
- git
- make
runcmd:
- sudo ua attach $UA_ACCESS_KEY
- sudo ua enable esm-infra
- git clone …
```
=> Update postinst to check if esm is already enabled

features/attached_commands.feature, features/attached_enable.feature, features/unattached_commands.feature, uaclient/cli.py, uaclient/status.py, uaclient/tests/test_cli.py, uaclient/tests/test_cli_disable.py, uaclient/tests/test_cli_enable.py
This PR creates an initial abstraction to allow multiple entitlements to be enables/disabled using the uaclient command. Right now, the idea is to try to enable/disable as much entitlements as we can. This means that we will not abort if we find an invalid entitlement or cannot disable/enable one of them.
To be more clear, this is an example of the output of the following command:
`ua disable ent1 ent2 ent3 --asume-yes true`
Where:
* ent1 is an invalid entitlement
* ent2 is not enabled
* ent3 is enabled
The command output will be the following:
```
ent2
ent2 is not currently enabled
See: sudo ua status
ent3
Updating packages lists
Disabled results:
Services not found: ent1
Services not disabled: ent2
Services disabled: ent3
```
What I am trying to achieve is a better way to give the user …
=> Update disable and enable commands

features/util.py
When specifying UACLIENT_BEHAVE_BUILD_PR=1 in developer environment
the behave tests expect to find a compressed copy of the current
source tree at /tmp/pr_source.tgz because .travis.yml does this.
If running locally, and no TRAVIS environment variable is present,
tar the current working dir to /tmp/pr_source.tgz so the integration
tests will build a deb in and use it.
=> tests: create /tmp/pr_source.tgz when not in travis and build_pr=1

features/attached_commands.feature, features/unattached_status.feature, uaclient/cli.py
Currently, to show all services in uaclient, we must run `ua status --beta`. We are now updating the `beta`flag to `all`, meaning that the command is now `ua status --all`. 
Fixes: #1091
=> Update beta flag name

features/steps/steps.py, features/unattached_commands.feature, features/unattached_status.feature, uaclient/cli.py, uaclient/config.py, uaclient/conftest.py, uaclient/status.py, uaclient/tests/test_cli_enable.py, uaclient/tests/test_config.py, uaclient/tests/test_util.py, uaclient/util.py
As stated in #1080, we need a way to override some configurations for uaclient. This is an initial step in that direction, by allowing users to override the `beta` behavior in uaclient. This PR allows for users to visualize all beta service by adding the following lines to `uaclient.conf`:
```yaml
features:
allow_beta: true
```
=> Override ua config for beta services

features/attach_invalidtoken.feature, features/attach_validtoken.feature, features/attached_commands.feature, features/attached_enable.feature, features/environment.py, features/staging_commands.feature, features/steps/steps.py, features/unattached_commands.feature, features/unattached_status.feature, features/util.py
Allow the ability to drive behave tests on either lxd containers or kvm-based machines.
This toggle is set via environement variabe UACLIENT_BEHAVE_MACHINE_TYPE which can
be either `lxd.container` or `lxd.vm`. In the future I'd expect we may grow `machine_type` to include Ubuntu PRO instances like `aws.pro` or `azure.pro` etc.
The following work was necessary to support this:
- Add feature.util.lxc_create_vm_profile which creates a profile which attaches a cloud-init:config
drive to a kvm instance that is booting
- features.util.wait_for_boot() retry changes
- vms take a while to boot, so change our retry logic on Xenial and later to block on
`cloud-init status --wait` until cloud-init is done
- Adjust retry backoff seconds because lxd VM instances take about 15 seconds to be able to …
=> tests: add lxd vm support for behave tests.

features/attach_validtoken.feature, features/attached_commands.feature, features/attached_enable.feature, features/steps/steps.py
Testing `UACLIENT_BEHAVE_CONTRACT_TOKEN` use in travis while also fixing some behave tests.
There is sill on scenario failing, that is is related to the problem in #1104, where the `ua enable INVALID_TOKEN` command does not raise the expected errror because the server is returning a different error than the one expected.
=> Contract token test

.travis.yml, features/attach_invalidtoken.feature, features/attach_validtoken.feature, features/attached_commands.feature, features/attached_enable.feature, features/environment.py, features/steps/steps.py, features/unattached_commands.feature, features/unattached_status.feature, tox.ini
Additionally, add separate tox env targets for behave to run
each Ubuntu release. This allows for more parallel job runs in travis
and avoiding the default 50 minute job timeout for travis on public
repos.
Travis job matrix now calls the separate tox envs:
behave-14.04, behave-16.04, behave-18.04, behave-20.04
To avoid duplciation of test metadata:
- introduce a @series.all tag alias for any tests which have common
expectations on each Ubuntu release
- Use Scenario Outlines to drive testing across multiple releases
There is some minor duplication in Scenario Outline Examples columns for
tests which represent the cartesion product of Releases by "expected outputs".
We may try to address that by providing separate custom example tables in a
subsequent PR.
Fixes: #1110
=> testing: add xenial and bionic support for integration tests

features/attached_enable.feature, features/steps/steps.py, uaclient/entitlements/base.py, uaclient/entitlements/fips.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/status.py
Users should not be able to enable `livepatch` if `fips` is active or `fips` if `livepatch` is active as stated in #1029 . We are now add the possibility for verifying if `blocking services` are enabled before activating a service. If this happens, we will not enable the service and show the user which services are responsible for that behavior.
Furthermore, we are only testing this feature now in `Bionic`. Although there are some improvements we can achieve for testing that feature, there are some potential issues that I have found (#1111 and #1112) that are posing a difficult for developing vm tests
Fixes: #1029
=> Do not enable services if blocking services is active

features/attached_enable.feature, features/util.py
Since the vms test are costly to create, when developing new vm behave tests, it is really useful to be able to reuse them.
We found out that the issue is that when we publish the vm images locally, we end-up losing the image information on it. This PR adds a way to bring back at least the `image.release` info back into the image, since this is the info we need to reuse it.
Fixes: #1111
=> Add back release info to published vms

README.md, features/aws-ids.yaml, features/environment.py, features/steps/steps.py, features/ubuntu_pro.feature, features/util.py, integration-requirements.txt, setup.py, test-requirements.txt, tools/refresh-aws-pro-ids, tox.ini
This branch would be part 1 of 2 for AWS Pro support.  It addresses part of Issue: #1093
In this branch:
- fix setup.py to handle test-requirements which use remote git links for dependencies
- Add pro.aws machine_type definition and @uses decorator for feature tests
- Use pycloudlib to perform ec2 key creation, vpc creation and launch_ec2 instances from a common vpc
- Allow building ec2 Ubuntu PRO images which install the ubuntu-advantage-tools from daily PPA
- separate integration-requirements.txt file as some pycloudlib deps are not available on trusty
We will not run integration tests from trusty, so this dependency mismatch is irrelevant to our test runs
=> tests: add aws pro integration coverage for daily PPA

features/steps/steps.py
Daily builds broke on non-feature tests due to the recent version overrides commit 4b37254b5d3f20b6c7b0f72c4f9ec200cc96ebe5
This results in travis build failures like this: https://travis-ci.org/github/canonical/ubuntu-advantage-client/jobs/710801369
Set proper default feature_str="" instread of None, so we don't break CI when parameter is absent.
=> tests: version test feature_str default needs to be an empty string

features/util.py
Right now, the `cleanup_instances`method is not be added to the overall context cleanup list. We are adding it to that list, allowing AWS images to be deleted after we remove that context.
=> Add cleanup to aws instances

.travis.yml, features/environment.py, features/steps/steps.py, features/ubuntu_pro.feature, features/util.py, tox.ini
Add support to build the local branch and test on aws pro images.
Add a new tox target and travis job `behave-aws-pro` to run using your AWS credentials.
To allow building PRO images that don't auto-attach on first boot, we provide custom user-data to cloud-init which will overwrite/usr/bin/ua with an empty script. This is required because PRO images don't currently have ua-tools version 25.0 
Once version 25.0 is included in AWS PRO images, this user-data can be dropped in favor of using `disable_auto_attach: true` feature override in uaclient.conf.
PRO images also need to installed ubuntu-advantage-pro.deb, so refactor of the build_deb related functions was necessary in this branch.
Additionally pro.aws integration tests require AWS crednentials via the environment variables: …
=> testing: aws pro support for locally building a pr and updating pro images for test.

.travis.yml, features/environment.py, features/steps/steps.py, features/util.py, tox.ini
Note: I'd like to merge this branch with separate commits instead of squash merging.
This PR activates the travis job behave-aws-pro
It also drop a 'make clean' in favor of tar --exclude-vcs* flags which ignore .tox and .git subdirs when
creating a source tar file to build from during testing.
Additional features:
- print launched instance.id right after launch and add retries on instance.wait failuress
- modify some print statements
=> test: travis add aws-pro job avoid 'make clean' when build_pr is set

features/steps/steps.py, features/ubuntu_pro.feature
In the pro images test, verify if the both `esm-infra` and `esm-apps` are properly configured and packages originated from those sources can be downloaded and installed without an issue.
This is a working solution, but there is still a discussion about if we should add dummy packages to both of these origins in an attempt to simplify and guarantee a more reliable test for pro images. But since we have not reached a consensus on it yes, this is a working solution nonetheless, although it suffers from some flaws, like checking the package version directly for esm, which is not mandatory for the package maintainer to add when uploading a new package.
=> Improve pro testing

.travis.yml, README.md, features/attach_validtoken.feature, features/cloud.py, features/environment.py, features/steps/steps.py, features/ubuntu_pro.feature, features/util.py, tox.ini
Add AWS and Azure integration test support for non-Ubuntu PRO images.
This PR adds two new tox targets and travis jobs: behave-azure and behave-aws which run BDD scenarios decorated with 
the tags `uses.context.config.machine_type.aws.generic` or `uses.context.config.machine_type.azure.generic` for AWS and Azure respectively.
These tox targets/travis jobs will use pycloudlib's released_image(<series>) to obtain the latest public image on the cloud platform instead of specifically requesting the PRO image ids on the cloud.
Each generic (non-pro) image requires proper cloud credentials as UACLIENT_BEHAVE_* environment variables as well
as a UACLIENT_BEHAVE_CONTRACT_TOKEN in order to attach the maching to Ubuntu Advantage.
Additionally, we make the travis jobs depend on conditional inclusion …
=> tests: add integration tests for aws canonical cloud-images (non Ubuntu-pro)

features/attached_commands.feature, features/attached_enable.feature, features/staging_commands.feature, uaclient/cli.py, uaclient/exceptions.py, uaclient/tests/test_cli_enable.py
Improve `esm` test by verifying if both `esm-infra` and `esm-apps` when enabled can download and install packages from those services.
PS: This PR is still not complete because the current contract token does not support enabling `esm-apps`
=> Improve esm tests for containers

debian/rules
Fixes: #1150
To test on focal or any non-trusty series:
```
dpkg-buildpackage -us -uc
dpkg -c ../ubuntu-advantage-tools_25.0_amd64.deb | grep apt
```
make sure apt-hook and config are included in built binary
I built and installed this deb on a focal container with one downgraded package "hello" that was available in esm-infra-updates:
* when esm-infra enabled, cmdline reports the package count
* when esm-infra disabled, cmdline does not report pkg count
* when all applicable updates are applied from esm-infra, no pkg count listed
```root@dev-f:~# apt update
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease                         
Hit:3 http://ppa.launchpad.net/canonical-server/ua-client-daily/ubuntu focal …
```
=> apt-hook: package apt-hook and apt configuration files on all releases

.travis.yml, Makefile, features/environment.py
Update `travis.yaml` to allow reusing the packages built in the build in the behave integration tests. The idea here is to avoid having the behave tests reconstructing those packages, since this is a costly operation, specially in`aws` and `azure` tests
=> Travis reuse debs

debian/changelog, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_repo.py, uaclient/status.py, uaclient/util.py
Only report reboot required text for fips enable disable if
/var/run/reboot-required file is present.
backport of 02de4df
to test:
1. launch aws pro image and provide the following cloud-config userdata
```
#cloud-config                                                                   
write_files:                                                                    
- path: /usr/bin/ua                                                           
content: |                                                                  
#!/bin/bash                                                             
DATE=`date -u`                                                          
echo "$DATE: exec ua $@" >> /root/ua-runs                               
permissions: '0755' …
```
=> fips: conditional reboot text after enabling/disabling

features/environment.py, features/ubuntu_pro.feature
Right now, we have travis issues when running the travis CI branch on master. The reason for that is that we fail to install the uaclient packages from the daily PPA.
Also, unrelated to master branch, we have currently an issue with livepatch on focal, as can be seen here: https://bugs.launchpad.net/canonical-livepatch-client/+bug/1892908
To not block other PRs at the moment, we are changing the behave test for aws focal pro machines regarding livepatch status
=> Fix travis master build

features/ubuntu_pro.feature
After the issue raised by this livepatch [bug](https://bugs.launchpad.net/canonical-livepatch-client/+bug/1892908) is addressed, we can rollback to the expected behavior of livepatch on AWS focal PRO machine
=> Fix livepatch behaviour on aws pro focal machine

debian/postinst, debian/postrm, debian/prerm, uaclient/apt.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_esm.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_repo.py, uaclient/tests/test_apt.py
Since we plan to release uaclient on `xenial` and `bionic`, we will now be supporting upgrading between releases. The idea here is that, if an user is already subscribed to uaclient and attached to some services, the upgrade should keep that and update the services to the new version.
However, currently we are `unconfiguring esm` when we do a postinst, which creates a conflict with our idea to support upgrading between releases. This PR removes that from postinst.
Furthermore, regarding `postrm`, it appears that we can remove the call for `rm -f /etc/apt/sources.list.d/ubuntu-esm-infra-trusty.list` since this seems to be handled by this part of [prerm](https://github.com/canonical/ubuntu-advantage-client/blob/master/debian/prerm#L17) and also because this part is only covering `trusty` …
=> Do not unconfigure esm on postinst

.travis.yml, features/attach_validtoken.feature, features/cloud.py, features/environment.py, integration-requirements.txt, tools/constraints-eoan.txt, tox.ini
commit fd6f4c28740d36334623f192f2e826eac01a406c leaked development testing
pycloudlib dependency
The following integration test changes are included in this branch:
- Provide the `timestamp_suffix=False` param to cloud_api setup to make sure pycloudlib doesn't append
a second timestamp suffix to the tag used during resource and instance creation
- separate trusty vs non-trusty apt source cloud-config because cloud-config option formats differ on trusty
- drop Ubuntu Eoan tox and travis test targets as that release support hit EOL on 07/2020.
- replace leaked blackboxsw/pycloudlib with canonical/pycloudlib integration dependency
=> tests: fix pycloudlib integration-reqs, support trusty and drop eoan

debian/postrm, features/attached_commands.feature, features/steps/steps.py, uaclient/apt.py, uaclient/tests/test_apt.py
Create behave integration test for `apt purge ubuntu-advantage-tools`
To do that we had to:
* Fix the `clean_apt_files` method
* Update the `remove_postinst_created_files` function to only delete gpg keys. The other files should be handled by `clean_apt_files`in `prerm`
* Update postinst to not recreate old apt files for esm-infra for the trusty package
=> Add integration test for purge command

lib/upgrade_lts_contract.py, release-upgrades.d/ubuntu-advantage-upgrades.cfg, setup.py, uaclient/tests/test_upgrade_lts_contract.py
Add tests to the `upgrade_lts_script`. To do that, we have moved the script inside a new folder named `lib`.
=> Add tests to upgrade_lts_contract script

.travis.yml, features/attached_enable.feature, uaclient/entitlements/livepatch.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_repo.py
When we perform a `disable` or `detach` operation, we end up removing packages that were installed to enable the services. We are now keeping those packages installed when we perform those operations.
Also, this PR is removing the `azurepro-16.04` from `allow_failures`, since the job is running without issues
=> Do not remove packages

features/attached_commands.feature, features/unattached_commands.feature, help-data.yaml, help_data.yaml, setup.py, uaclient/cli.py, uaclient/config.py, uaclient/defaults.py, uaclient/entitlements/base.py, uaclient/entitlements/cis.py, uaclient/entitlements/esm.py, uaclient/entitlements/fips.py, uaclient/entitlements/livepatch.py, uaclient/tests/test_cli.py
Currently, help command for the service does not provide only a basic information for the services. We are now adding the right content for all those services when we run the help command.
=> Add help content for services

features/attached_commands.feature, features/attached_enable.feature, features/unattached_commands.feature, lib/upgrade_lts_contract.py, uaclient/cli.py, uaclient/config.py, uaclient/entitlements/__init__.py, uaclient/status.py, uaclient/tests/test_cli.py, uaclient/tests/test_cli_disable.py, uaclient/tests/test_cli_enable.py
Subclass argparse.ArgumentParser to simplify error messages.
Rename service_name param to service in help, enable and disable.
Add valid ENTITLEMENTS_STR to help docs for enable and disable.
Fix usage strings for help, enable and disable.
On invalid service names in enable or disable, emit error:
Unknown service 'your-input'.
Try cis-audit, esm-infra, esm-apps, fips, fips-updates ....
Fixes: #1190
Fixes: #1061
=> cli: improve errors on invalid service_name param

debian/changelog, uaclient/status.py, uaclient/tests/test_status.py
Handle upgrade case for non-root `ua status` across trusty upgrade to xenial.
=> Status trusty upgrade

features/attached_enable.feature, tox.ini
Add `tox` commands that allow us to run only vm tests. Also, we are fixing some vm tests, since we are now not uninstalling packages when we disable services.
=> Add vm test commands in tox.ini

features/attached_enable.feature, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py
We are adding a static affordance to verify the status of fips-updates before enabling fips. If fips-updates is enabled, we cannot enable fips, since that would cause package downgrades.
=> Do not enable fips when fips-updates is active

features/attach_validtoken.feature, features/attached_commands.feature, features/attached_enable.feature, features/staging_commands.feature, features/unattached_status.feature, uaclient/cli.py, uaclient/entitlements/esm.py, uaclient/tests/test_cli.py
This PR updates two aspects of uaclient:
* Turn `esm-apps` into a beta service
* Do not show beta services on `ua help` command, unless the user runs the `ua help --all`.  Also `ua --help` will now display the help with only the non-beta services
=> Update beta info for services

features/attached_commands.feature, uaclient/apt.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_esm.py, uaclient/status.py, uaclient/tests/test_apt.py
When we enable a service and a user has an invalid repository in the system, apt update commands will fail to run. Because we run apt update when we enable repo type services, we stumble upon this issue and fail to enable the service. However, we are not showing the user the reason why the enable command failed. We are now updating the logic to display this apt issue when this problem happen during an enable operation.
=> Show error when enabling service with invalid repo

features/attach_validtoken.feature
Master build is failing due to an azure generic test that expects `esm-apps` to appear on `ua status` output. We are now removing this from the test
=> Fix azure generic integration testing

features/staging_commands.feature
Because we had deleted the staging token variable from our travis setting, some integration tests were not running. After adding that token again, we can see that we still have some `esm-apps`  related issues on the `staging_commands`  test. This PR fixes that issue
=> Update esm-apps check on staging_commands tests

features/attached_enable.feature, features/staging_commands.feature, features/util.py, sru/release-26/xenial-enable-fips, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py
Currently, we our fips service is expected to install a range of packages that represent the `FIPS`  service. However, we are now expecting `FIPS`  to provide a single metapackage which will install all of the necessary `FIPS` packages for us. To test this feature, we are using the staging contract environment, since the contract in production is still not updated to use the `FIPS` metapackage.
Also, the BDD test for fips are performed only for bionic at this moment. On xenial. when we install the `FIPS` kernel and reboot the machine we cannot access it anymore through `lxd`. That is because the `FIPS` kernel on xenial is missing the required modules to run the `lxd-agent` component of `lxd`, which allow us to communicate with the vm. As a temporary solution, we are testing `FIPS` on …
=> Install fips metapackage when enabling service

tools/run_azure_travis_integration_tests.sh
Went to look at the output of a job to check the exact version being used by the tests, and noticed this easy-to-fix error.
=> Fix shell condition in run_azure_travis_integration_tests.sh

features/attached_enable.feature
Our Jenkins job for vm testing is failing due to one of our tests still assuming that `esm-apps` is not a beta service.
=> Fix vm tests

features/staging_commands.feature, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_fips.py
ua disable fips or fips-update will now uninstall the ubuntu-fips
meta package. This will remove package holds and disable fips-related
settings in grub.
Add post_disable messaging mentioning reboot-required.
Fixes: #1168
=> fips: allow disable

features/staging_commands.feature, features/steps/steps.py, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py
When enabling FIPS we will now be checking if the user has some predefined packages installed. If they are, we will update them to the FIPS version and also install the corresponding hmac package.
Fix #1239
=> Conditionally install packages when enabling FIPS

features/attach_invalidtoken.feature, features/attach_validtoken.feature, features/attached_commands.feature, features/attached_enable.feature, features/staging_commands.feature, features/steps/steps.py, features/ubuntu_upgrade.feature, features/unattached_commands.feature
On the `Attached enable of a know service shows update in a ubuntu machine` we were failing to install the `libkrad0` package on xenial, which makes the test fail. We are now confirming that the package is installed while updating the package version that is installed on xenial.
=> Update esm-infra lxd test

debian/rules, systemd/ua-auto-attach.path, systemd/ua-auto-attach.service
Ensure esm-related services are attached as soon as possible on Ubuntu PRO images.
Don't wait until after cloud-init userdata is processed.
Fixes: #1234
=> pro: trigger auto-attach as soon as instance-data.json is available

features/staging_commands.feature, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_repo.py
* FIPSEntitlement.setup_apt_config will unhold deb packages to support Ubuntu PRO FIPS images which were built before UA client official support of FIPS.
* Separate RepoEntitlement.install_packages method out of `enable` method so it can be called during delta processing.
* Handle apt-based contract deltas that include changes in additionalPackages directives during
`repo.process_contract_deltas`. 
Fixes: #1109
=> Unhold fips pkgs

features/cloud.py, features/environment.py, features/staging_commands.feature, features/steps/steps.py, features/util.py, uaclient/entitlements/fips.py
Refactor integration tests to use pycloudlib LXD implementation. This also allows us to test enabling `FIPS` for xenial.
PS: This PR depends on the following pycloudlib [PR](https://github.com/canonical/pycloudlib/pull/40)
=> Refactor integration tests to use pycloudlib LXD

systemd/ua-auto-attach.service
Declare the ua-auto-attach.service unit as being run explicity Before  and WantedBy cloud-config.service to ensure auto-attach completes before any cloud-config userdata attempts to install or update deb packages.
This guarantees that any packages will be pulled from ESM PPAs if applicable on a given machine if cloud-config requests
package installs.
=> ua-auto-attach: finish auto-attach.service before cloud-config.service starts

tools/run_aws_travis_integration_tests.sh, tools/run_lxd_travis_integration_tests.sh
One check on both lxd and azure setup scripts were incorrect.
We are fixing that check to allow the builds to function as expected
Fixes: #1253
=> Fix integration test setup scripts

features/steps/steps.py
When upgrading trusty machines to xenial, cloud-init has a bug in
re-constituting the pickled trusty-based datasource on xenial.
That cloud-init bug is LP: #1899299
This results in the following error from cloud-init status --wait:
'Paths' object has no attribute 'run_dir'
To avoid this error until an SRU fixes cloud-init on Xenial,
integration tests can use:
instance.shutdown(wait=True)
instance.start()
instance.wait(raise_on_cloudinit_failure=False)
Fixes: #1257
=> upgrade-test: fix upgrade path restart failures on trusty

features/ubuntu_upgrade.feature, lib/upgrade_lts_contract.py, uaclient/tests/test_upgrade_lts_contract.py
* upgrade-lts-conract: noop during do-release-upgrae on unattached
Fast exit and don't print any messages during do-release-upgrade
if the machine is not attached to a UA contract
Fixes: #1255
commit 72bf82e458064403d4829a6e6e027a8210015911
*  behave: upgrade test requires @uses.config.contract_token
=> Unattached noop upgrade process deltas

features/staging_commands.feature
On the fips test, we are running apt-mark hold on some package
before enabling fips. This works for FIPS, because we unhold
those packages before we setup fips. However, this is not the case
for fips updates. We are now splitting the fips integration tests
to avoid this issue.
=> Remove package hold from fips updates test

uaclient/clouds/gcp.py, uaclient/clouds/identity.py, uaclient/clouds/tests/test_gcp.py
This adds the ability to detect if on a Google Cloud Platform system
using a combination of the cloud-init datasource and DMI data using the
product name. The client will retreive a JWT token and send it to the
contract service for verification.
A note on naming, the contract service is expect 'gcp'. cloud-id and
cloud-init datasources use 'gce'.
=>  Add Google Cloud Platform support

features/attached_commands.feature
We have a test to verify if uaclient is behaving as expected if we have an invalid ppa in the
system. To produce that invalid ppa, we add the uaclient daily ppa and we use a sed to edit it.
However, the path we were using on the sed command changes, breaking the test.
=> Fix invalid ppa integration test

debian/changelog, features/environment.py, tools/base_travis_integration_tests.sh, tools/run_aws_travis_integration_tests.sh, tools/run_azure_travis_integration_tests.sh, tools/run_lxd_travis_integration_tests.sh
cherry-pick two functional changes from release-25:
-    e7497b7512e2b93cf160305f902dc4b087ab8564 travis: cron runs on release-\d+ run against ppa:ua-client/staging
- 7df8eebef8a806a2fe201230d5a71d7cb127220b tests: add ppa and ppa_keyid overrides for integration runs
- import debian/changelog entries
=> Sync release 25

tools/constraints-mypy.txt, tox.ini
pytest was recently updated to a version that breaks the mypy tests. The reason for that is because the new version of pytest uses a type annotation that is only supported on python3.6 and later. Therefore we cannot run all of the mypy tests using the latest version. Because of that we are now splitting the mypy test for each release, making sure the command is respecting the release dependencies freezes, which include pytest
File on pytest with type annotation:
https://github.com/pytest-dev/pytest/blob/6.2.x/src/_pytest/assertion/__init__.py#L86
=> Add pytest constraint for pytest on mypy tests

features/attach_validtoken.feature, features/cloud.py, features/environment.py, tox.ini
Add support for launching GCE instances and running integration test scenarios on them
PS: This can only be merged after this pycloudlib [PR](https://github.com/canonical/pycloudlib/pull/79) is accepted
=> Add GCE support for integration tests

features/cloud.py
pycloudlib is now handling setting the correct environment
variables for GCP. We no longer need uaclient to do that on
our tests
=> Remove setting GCP credentials for behave tests

Jenkinsfile
After cleaning up jenkins workers and removing a stale py2-based tox
installed in .local/bin on our systems, we can now use the tox installed
on the jenkins worker without having to specify the full path.
Also add the following integration testing environment vars:
- UACLIENT_BEHAVE_BUILD_PR=1: force local building of the PR under test.
- UACLIENT_BEHAVE_CONTRACT_TOKEN_STAGING: allow running our staging tests.
=>    jenkins: drop tox path add contract_token_staging and build_pr env vars

debian/control, debian/postinst, debian/rules, lib/reboot_cmds.py, systemd/ua-reboot-cmds.service, uaclient/config.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_repo.py, uaclient/tests/test_reboot_cmds.py
After `do-release-upgrade` there could still be operations that should still be performed after a user reboots the machine. For example, when upgrading from trusty to xenial, we cannot enable livepatch after `do-release-upgrade`, only after the user reboots the machine. To handle those situations, we are creating a init script that performs the remaining operations on uaclient to leave the system in a desired state.
What could be improved:
* Right now, the script is running the `upgrade_lts_contract`  script, since we need to perform the exact same operation on reboot. However, our logging can be really confusing because of that, since we will "repeat" the command and this may not be easy to understand why by just looking at the logs
* We can add an integration test for this feature as …
=> Add init script to run remaining uaclient commands after do-release-upgrade

features/environment.py, tools/constraints-mypy.txt
Currently, when performing integration tests, we install both the default package and the pro package in the same
instance. However, now that we are running the auto-attach init script before cloud-init process the userdata, we are no longer ensuring that this script will not run. Since the auto-attach command will fail on non-pro instances, we must avoid installing the pro
package on those instances.
Related to bug #1297
=> Do not install pro debs on non-pro instances

Jenkinsfile, features/environment.py, features/steps/steps.py
Currently, if there is a failure in our integration tests,
we do not remove the lxd instances from the machine. We are
now adding a stage that does exactly that
=> Add lxd cleanup stage on Jenkinsfile

Jenkinsfile
Currently, we are not destroying the instances after running the behave tests. However, since we are now
avoiding failures if we cannot delete an instance after the test, we can bring that behavior back
=> Allow destroy instances on Jenkins PR build

debian/postinst, features/attach_validtoken.feature, features/attached_commands.feature, features/attached_enable.feature, features/environment.py, features/staging_commands.feature, features/unattached_commands.feature, features/unattached_status.feature, lib/reboot_cmds.py, uaclient/cli.py, uaclient/config.py, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/status.py, uaclient/tests/test_cli.py, uaclient/tests/test_cli_detach.py, uaclient/tests/test_cli_disable.py, uaclient/tests/test_cli_status.py, uaclient/tests/test_config.py, uaclient/tests/test_reboot_cmds.py, uaclient/util.py
Address FIPS support in two ways:
- add debian/postinst awareness to create marker-reboot-cmd
- add reboot_cmds.py function fix_pro_pkg_holds which will remove any FIPS apt-holds during reboot
- add status notices to indicate on main status output that reboot is required per #1251 
Things to address, integration testing and more unit tests for reboot_cmds.py changes
=> Fips post update cmds and notices

tox.ini
To run GCP behave tests in Jenkins, we need to setup the https_proxy env variable. However, tox only pass env variables
to the test environments if they are specified on passenv. We are now adding that variable there to unblock the GCP tests
=> Add https_proxy to passenv in tox

Makefile, tox.ini
When we run flake8 and pytest jobs using dependencies based on older ubuntu releases, we must ensure that
we are using an older version of pip. If we do not do that, new versions of pip will not be able to parse the specified
dependencies tree and it will fail to run the test
To pin the pip version, I had to add a dependency to a tox plugin called `tox-pip-version`. Initially I thought about using the `VIRTUALENV_PIP` variable to set this, but it is not working as I expected, since pip is always being upgrade to the latest  version anyway
=> Set pip version for testing older releases

features/attach_validtoken.feature, features/attached_enable.feature, features/staging_commands.feature
Currently, after we upgrade a release with fips enabled we run a grep command on the source list files to see
if we can find a disable or the name of the past release on them. However, the deb-src files are appearing commented
out with the past release. Since this is not an issue, we can remove grepping for the release on that part of the test
=> Remove grep for release in fips upgrade test

features/steps/steps.py, uaclient/apt.py, uaclient/tests/test_apt.py
When running the behave tests in Jenkins, it is pretty hard to debug why one of the steps failed. The reason is that we only output that the command returned a status different than 0. Now we are also going to print the stdout and stderr returned by the command in that situation, allowing us to better debug this issue.
Also, the current timeout for apt to download service credentials is 20 seconds. We are bumping that to 60 seconds in an attempt to reduce flaky errors on the Jenkins builds
=> Show errors when behave test fails

features/attached_enable.feature, features/ubuntu_pro.feature, uaclient/entitlements/base.py, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_base.py, uaclient/entitlements/tests/test_fips.py, uaclient/status.py
When we are enabling a service in uaclient, we may end up finding that we have an incompatible service
already enabled in the system. Currently, we alert the user about this issue and abort the enable operation.
We are updating that to allow the user to decide if the incompatible services should be disabled or not
before enabling the requested service.
To make that happen, we are creating a new abstraction called `incompatible_services`. Every entitlement that has an incompatible service needs to define this parameters, which is a list of strings containing the name of the incompatible services.
We are also adding the feature override named `block_disable_on_enable` to never allow a service to be disabled during an enable operation. Those flags were created due to testing purposes, since …
=> Allow uaclient to disable services during enable

features/attach_validtoken.feature, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py, uaclient/status.py
Currently, Azure and GCP do not have fips specific kernel versions for the xenial kernel. Because of that, when enabling fips on
those instances, we would end up installing the stock fips kernel on them, which is problematic, since that kernel is not optimized
for those clouds and could generate problems for the user. Therefore, we are now blocking enabling FIPS on Azure and GCP cloud instances.
We are still missing the GCP integration tests and defining what the message will be when we block FIPS because of this problem
=> Block enabling FIPS on clouds using Xenial

tools/tox-lxd-runner
When running the tox-lxd-runner script on a xenial machine, we end up downloading a pip
file that uses fstrings on its code. This is not supported on python 3.5, which is used by xenial.
To fix this issue, we are downloading the right pip version when using python 3.5
=> Fix tox-lxd-runner script for xenial

features/environment.py, features/steps/steps.py, features/ubuntu_pro.feature, lib/reboot_cmds.py, lib/upgrade_lts_contract.py, systemd/ua-auto-attach.service, systemd/ua-reboot-cmds.service, tox.ini, uaclient/exceptions.py, uaclient/tests/test_reboot_cmds.py
Fix multiple system unit issues with reboot cmds:
* Make system unit ordering explicit to avoid lockhelderror collisions by adding the following
which orders ua-reboot-cmds after auto-attach:
Add Wants=ua-auto-attach.service
After=ua-auto-attach.service
* Fix ua-auto-attach.service moving WantedBy=cloud-config.service out of Unit and into Install section
* Add flake and black style checks of lib/ directory
* Add 3 retries on lock_held error in lib/reboot_cmds.py because auto-attach may still be running.
Fixes: #1331
=> Reboot cmd ordering

features/attach_validtoken.feature, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py
Currently, the contract backend will always return the ubuntu-fips metapackage as the package to be installed when we enable fips.
However, we have specific metapackages for Bionic Azure and AWS instances, called ubuntu-aws-fips and ubuntu-azure-fips. Until we do not support that on the contracts backend, we will be performing this override directly on the uaclient code
=> Override fips metapackage when on bionic cloud

uaclient/contract.py, uaclient/status.py, uaclient/tests/test_contract.py
The contract backend will now allow contract token that have expired to keep working for 14 days. Also, the contract
backend already covers the situation were the contract is no longer valid, which will return a 403 error that is already
treated in the code. Because of that, we are dropping the expiry check for contracts
fix #1335
=> Remove expiry check from contract update

features/attached_commands.feature, features/attached_enable.feature, features/steps/steps.py
When rebooting the machine on trusty, we were using the raise_on_failure as False to not raise exceptions if cloud-init failed to successfully complete. However, pycloudlib does not throw those exceptions anymore and no longer support that parameter
either. We are removing it from the method call.
Also, some of our integration tests are redundant, in the sense that they are already being test by other scenario or they can be integrated into an existing test. We are now removing those redundant tests.
=> Fix trusty upgrade test

uaclient/cli.py, uaclient/tests/test_cli.py
When the commandline encounters an unexpected error, the
main_error_handler needs to call UAConfig.delete_cache_key("lock")
to ensure any Operation in progress notices messages are also
removed. This most often happens during auto-attach on PRO machines
because it raises a UserFacingError saying:
This machine is already attached to <some-account>
Since main_error_handler doesn't have direct access to an
instantiated UAConfig, we store that UAConfig.delte_cache_key
callable on _CLEAR_LOCK_FILE
Fixes: #1326
* Launch an Ubuntu PRO Machine with this branch
```bash
UACLIENT_BEHAVE_BUILD_PR=1 UACLIENT_BEHAVE_DESTROY_INSTANCES=0 
UACLIENT_BEHAVE_AWS_ACCESS_KEY_ID=<YOUR_AWS_ACCESS_KEY_ID>  UACLIENT_BEHAVE_AWS_SECRET_ACCESS_KEY=<YOUR_AWS_SECRET_ACCESS_KEY> tox -e behave-awspro-18.04 
--no-capture …
```
=> notices: clear lock file and notice when encountering any exception

features/attach_validtoken.feature, features/environment.py, features/steps/steps.py, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py, uaclient/status.py
Currently, we do not have a gcp optimized fips kernel. Installing the default fips kernel on those instances could case
performance or even system issues. Because of that, we are now blocking enabling fips on those instances until we have the
optimized kernel for gcp.
We can override this behavior but adding the following directive into `uaclient.conf`:
```
allow_default_fips_metapackage_on_gcp: true
```
Fix #1317
=> Block enabling fips on GCP instances

Jenkinsfile, uaclient/cli.py, uaclient/tests/test_cli_status.py
Add logic to show_beta=True services when --format=json --all params
are provided on the commandline.
Fixes: #1341
=> status: include beta services in json formatted output with --all

features/attach_validtoken.feature, features/staging_commands.feature, features/ubuntu_pro.feature, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py
Update check that verifies if fips is enabled
Currently, we to check if fips is enabled, we verify if the fips apt sources are present in the system and the fips kernel is being used. However, if the /proc/sys/crypto/fips_enabled file doesn't exist or is set to 0, the system will not be on fips mode. Because of that, we are checking the proc file instead of the running kernel to dictate if fips is enabled or not.
We are also updating our fips tests:
* We are no longer checking for the `/proc/sys/crypti/fips_enabled`  file after disabling fips
* Adding a test for enabling fips-updates on fips enabled machine
Fix: #1345 
Just run the integration tests in this PR
=> Check proc file to verify if fips is enabled in a machine

uaclient/config.py, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py, uaclient/status.py
Point to discourse documentation in notice messaging for
manual steps to remove the FIPS kernel from the system.
Fixes: #1348
from this branch root:
```bash
git diff upstream/master > fips.patch
multipass launch daily:bionic -n dev-b
multipass transfer fips.patch dev-b:.
multipass connect dev-b
cd /usr/lib/python3/dist-packages/
sudo add-apt-repository ppa:canonical-server/ua-client-daily
sudo apt-get update
sudo apt-get install ubuntu-advantage-tools
sudo patch -p1 < /home/ubuntu/fips.patch
sudo ua attach <TOKEN>
sudo ua enable fips
sudo reboot
multipass connect dev-b
sudo ua status   # check that status says enabled
sudo ua disable fips
sudo reboot 
sudo ua status  # should show notice about FIPS in disabled state
```
=> fips: add notice if running a deactivated FIPS kernel

uaclient/cli.py, uaclient/tests/test_cli_auto_attach.py
Given an attached machine, when we run auto-attach we verify if the current instance id matches the instance id in the uaclient
cache. If they do not match, we proceed with the auto-attach. If the instance id could be converted to a number we would have a problem, since we read the old instance id from a json file, which automatically converts the instance id to int while the current instance id always returns a string. Even if the instance id matches, we would say that they don't because of the type difference.
We are fixing that type mismatch comparison now
Fix auto-attach issue when comparing numeric iid
Run the new unit test
=> Fix auto-attach issue when comparing numeric iid

features/gcp-ids.yaml
gcp: update PRO image ids for integration testing of 26.0.1 release
Product images were published 02/05/2021 and can now be exercised
by our integration tests.
UACLIENT_BEHAVE_BUILD_PR=1 UACLIENT_BEHAVE_DEBS_PATH=/root/ubuntu-advantage-client/DEBS tox -e behave-gcppro-18.04 -- --no-capture --no-color --format=plain
=> gcp: update gcp ids for 26.0.1

features/environment.py, features/steps/steps.py
integration: block auto-attach on PRO base images
Currently, we only create the disable_auto_attach entry on uaclient.conf when we are launching the test image. This is not working on trusty because cloud-init is editing that file after we have already run the auto-attach script. Therefore, we are moving the creation of this directive to the base image (the one that will be snapshoted), which will guarantee that the directive will be there once the test image runs
Run both AWS and Azure trusty PRO integration tests
=> integration: block auto-attach on PRO base images

.gitignore, Jenkinsfile, uaclient/contract.py, uaclient/tests/test_contract.py
contract: check machine id on detach
When we running a detach operation we also call the contracts backend to delete the machine from there as well. However, if we detect a machine id change in the system, that call will not succeed, failing the entire operation. To avoid that, we are now checking if the machine id in the cache and current machine id match before doing the detach call to the contracts backend
=> Check machine id on detach from machine

Jenkinsfile, features/environment.py, features/ubuntu_pro.feature, features/unattached_commands.feature, uaclient-devel.conf, uaclient.conf, uaclient/cli.py, uaclient/config.py, uaclient/contract.py, uaclient/defaults.py, uaclient/entitlements/tests/test_fips.py, uaclient/security.py, uaclient/serviceclient.py, uaclient/status.py, uaclient/testing/fakes.py, uaclient/tests/test_config.py, uaclient/tests/test_contract.py, uaclient/tests/test_security.py, uaclient/tests/test_serviceclient.py
Add a full UASecurityClient to allow querying applicability of CVEs against a running machine.
Add basic `ua fix CVE` subcommand which will introspect the running system against a known CVE and 
report whether or not the CVE affects the given system.
USN handling is non-functional in this PR.
This is a simple spike intended to build very basic functionality and allow us to iterate on CLI flow.
Expect additional PRs to improve functionality for prompt the user about required CVE update actions.
Test steps:
- ua fix --help
```bash
PYTHONPATH=. python3 -m uaclient.cli fix --help
```
- ua fix invalid-value
```bash
PYTHONPATH=. python3 -m uaclient.cli fix USN-bogus
```
- ua fix valid already installed CVE on Focal
```bash
PYTHONPATH=. python3 -m uaclient.cli fix CVE-2020-28196
```
- ua fix …
=> UA Fix spike: New UASecurityClient for querying CVE and USNs basic CLI

uaclient/tests/test_util.py, uaclient/util.py
Use functools lru_cache to avoid repeated reading of files that will
not change except across reboot. This cuts down both on noisy
Reading file messages and costly, repeated processing of the same
static responses.
Fixes: #1329
run the following in your cwd and expect to only see one log message on the console (because we are caching the response)
DEBUG: Reading file: /etc/machine-id
```bash
cat > test.py <<EOF
from uaclient.cli import setup_logging
from uaclient.util import get_machine_id
import logging
setup_logging(logging.DEBUG, logging.DEBUG, "/tmp/uaclient-test.log")
get_machine_id("/does/not/exist")
get_machine_id("/does/not/exist")
EOF
PYTHONPATH=. python3 test.py
```
=> util: use lru_cache to avoid re-reading os-release and machine-id

features/unattached_commands.feature, uaclient/cli.py
Since we won't release until `ua fix` is production ready,
we can remove the --beta param and allow this command to show
in ua --help.
CI should cover this, just a revert of a previous accepted commit.
- [*] Rebase and merge, no merge commit, rely only on existing commit messages
- [*] I have updated or added any unit tests accordingly
=> fix: make subcommand public and remove --beta required flag

features/staging_commands.feature, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py, uaclient/status.py
Add reboot notices for fips operations
When we enable/disable fips, we need to restart the system to properly configure it. We are now adding notices that will
remember users that fips needs to be rebooted after unable/disable operation.
Fix #1368
=> Add reboot notices for fips operations

uaclient/cli.py, uaclient/security.py, uaclient/tests/test_cli_fix.py
fix: correct regex to be permissive of upper and lowercase
Now allow for case insensitive matching if CVE, LSN and USN.
Make sure the regex for valid formats is strict for matches and
add unit tests for this validation.
Unit tests cover this changeset.
=> fix: correct regex to be more permissive and strict

uaclient/serviceclient.py, uaclient/tests/test_serviceclient.py, uaclient/tests/test_util.py, uaclient/util.py
Add general retry logic to the service client to set a 10 second timeout and retry twice to avoid failure due to intermittent network/service outages
rebase individual commits
Since the service  API seems to have fairly frequent 30 second API timeouts, run the following a few times to reproduce the failure we have seen on integration test runs. Expect to a a retry log and success.
```bash
PYTHONPATH=. python3 -m uaclient.cli --debug ua fix USN-4539-1
```
=> serviceclient: add retry logic to avoid long timeouts during intermittent failures

features/attached_enable.feature
Fix bionic vm test when enable fips with livepatch
We have a bionic vm test where we enable livepatch and we try to enable fips afterwards. On that scenario, we also create a uaclient.conf directive to block disabling services on enable operations. We want to verify if in that situation, fips is not enabled
becaused livepatch is. However, we are checking the error message on stdout, but with the new incompatible services
abstraction, that message will be on stderr if we have the uaclient.conf directive
Run the modifed integration test
=> Fix bionic vm test when enable fips with livepatch

features/cloud.py, features/util.py, integration-requirements.txt
Make lxd containers execute commands by ssh
Currently, we are only using ssh to execute commands on lxd virtual machines. With recent modifications on pycloudlib, lxd instances are using ssh by default. We are now migrating our lxd containers to execute commands by ssh too.
Also, pycloudlib now handles the profile creation of lxd virtual machines. Therefore, we don't need to support that code on uaclient anymore
PS: We are still waiting on this pycloudlib [PR](https://github.com/canonical/pycloudlib/pull/117) to land, so we can bump the pycloudlib version we are using in the project
=> [WIP] Update pycloudlib

features/staging_commands.feature
Drop traceback checks on fips integration tests
Currently, afer we enable FIPS and reboot the machine, we check uaclient logs to see if any traceback was raised during this
process. However, unrelated tracebacks can also make this test fail. For example, timeouts issues may create tracebacks on the logs but they are not directly related to FIPS problems. Since I believe our test already looks at different aspects of FIPS enablement, we can drop the traceback check from these tests
Using a practical example, this is one scenario where the test failed:
```
2021-02-24 13:39:11,527 - util.py:(438) [DEBUG]: URL [POST]: https://contracts.staging.canonical.com/v1/context/machines/token, headers: {'content-type': 'application/json', 'accept': 'application/json',        'Authorization': 'Bearer …
```
=> Drop traceback checks on fips integration tests

uaclient/config.py, uaclient/tests/test_config.py, uaclient/tests/test_version.py, uaclient/version.py
Support environment vars of the format UA_FEATURES_SOME_NAME to
override uaclient.conf values.
For example:
UA_FEATURES_ALLOW_BETA=true ua enable cis
Fixes: #1395
Use rebase and merge
```bash
csmith@downtown:~/src/ubuntu-advantage-client (feature-overrides-in-env)$ PYTHONPATH=. python3 -m uaclient.cli version
20.3-355-gb867d073
csmith@downtown:~/src/ubuntu-advantage-client (feature-overrides-in-env)$ UA_FEATURES_ALLOW_BETA=true PYTHONPATH=. python3 -m uaclient.cli version
20.3-355-gb867d073 +allow_beta
```
=> config: environment variable support for feature overrides

uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py, uaclient/status.py
Fix FIPS message when disable operation fails
As seen in #1389, FIPS is incorrectly using an enable message when the disable operations fails. We are now updating that to display the right disable message
Run the new unit test added in this PR
=> Fix FIPS message when disable operation fails

uaclient/apt.py, uaclient/tests/test_apt.py
Allow printing apt commands
For ua fix, we will need to print some useful apt commands that we are performing to the user, such as `apt update`, `apt upgrade`. We are now allowing the run_apt_command function to print those commands when needed
As discussed in issue #1400, we will only need to print a subset of the commands that we run on uaclient. They are:
* uaclient top level commands (`attach`, `enable`
* Apt commands like `apt update`, `apt upgrade <pkg-name>`
Because of that, I think `ua fix` will be able to control how to print those commands directly by adding this functionality
Run the new unit test introduced in the PR
=> Allow printing usefull cmds on uaclient operations

uaclient/security.py, uaclient/status.py, uaclient/tests/test_security.py, uaclient/util.py
Prompt for ua attach when unattached and `ua fix CVE-XX` reports
an available package affected.
Add a util.prompt_choices function which defines the input string
and desirable choices/responses. prompt_choices will loop until the
valid choice is provided.
In testing ua fix CVE-2021-27135 it was noted that xterm wasn't
listed as installed. Fix dpkg-query to determine package name based
on either ${Source} or ${Package} if Source is not set.
Fixes: #1397, #1398
Rebase and merge
```bash
cat > 1.yaml <<EOF
#cloud-config                                                                   
package_upgrade: true                                                           
apt:                                                                            
sources: …
```
=> fix: correct installed_pkgs query. prompt when unattached

uaclient/config.py, uaclient/security.py, uaclient/tests/test_config.py, uaclient/tests/test_security.py
Create config to add extra params to security url
We are now creating a feature config that will allow users to pass extra params to the security url we are using on ua fix
Run the modified unit tests on this PR
=> Create config to add extra params to security url

features/ubuntu_pro.feature, uaclient/config.py, uaclient/tests/test_config.py
Show beta services in status if they are enabled
Currently, we are always hiding beta services from ua status, even if a beta service is enabled. However, we should always show
the user which services are enabled in the machine by default, being beta services or not.
Fixes: #1410
=> Show beta services in status if they are enabled

features/unattached_commands.feature, uaclient/security.py, uaclient/status.py, uaclient/tests/test_security.py
Install pkg fixes when they are on standard pocket
When running ua fix on a given USN/CVE we may need may find update that are present on the Ubuntu Standard Updates.
In that scenario, we can just install those updates. We are now allowing ua fix to do exactly that.
Fixes: #1401
Run the new integration test added to this PR
=> Install pkg fixes when they are on standard pocket

integration-requirements.txt
test deps: bump pycloudlib for 60 second banner timeout
Fixes: #1428
CI tests should cover this hoping to avoid intermitetent Banner timeout errors.
n/a
=> test deps: bump pycloudlib for 60 second banner timeout

features/attach_invalidtoken.feature, features/attached_commands.feature, features/attached_enable.feature, features/staging_commands.feature, features/unattached_commands.feature, features/unattached_status.feature, uaclient/cli.py, uaclient/entitlements/fips.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/tests/test_base.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/entitlements/tests/test_repo.py, uaclient/gpg.py, uaclient/status.py, uaclient/tests/test_apt.py, uaclient/tests/test_cli.py, uaclient/tests/test_cli_disable.py, uaclient/tests/test_cli_enable.py, uaclient/tests/test_cli_status.py
Add stop "." punctuation to messages
Add missing "." punctuation to some uaclient messages.
Fixes: #1320
Run the modified integration tests in this PR
=> Add stop "." punctuation to messages

features/unattached_commands.feature
tests: correct ua fix integration test for krb5
trusty now properly detects installed packages
and reports krb5 upgrades required.
Correct integration test to prompt about installing
```bash
tox -e behave-lxd-14.04 features/unattached_commands.feature:185
```
=> tests: address ua fix for krb5

uaclient/cli.py, uaclient/status.py, uaclient/tests/test_cli_auto_attach.py, uaclient/tests/test_cli_disable.py, uaclient/tests/test_cli_enable.py, uaclient/tests/test_cli_fix.py, uaclient/tests/test_cli_refresh.py, uaclient/tests/test_cli_status.py
Add unit test coverage for all help output, fix discovered bugs:
- Fix ua subcommand --help which repeated its printed output twice
- Fix traceback on ua enable due to a stay end of line comma
- Fix ua refresh --help adding a refresh_parser to align help
formatting with all other subcommands
- Add subcommand descriptions to give context on the intent for the
subcommand
Fixes: #1440
```bash
PYTHONPATH=. python3 -m uaclient.cli  enable --help
PYTHONPATH=. python3 -m uaclient.cli  refresh--help
```
=> cli: drop subcommand repeated help output, fix enable & refresh

tools/tox-lxd-runner
Fix bootstrap links in tox-lxd-runner script
Update the broken bootstrap links we use to download pip in the tox-lxd-runner script.
To better understand this fix, our flake8 jenkins jobs are outputting the following text before exiting:
```
Hi there!
The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:
https://bootstrap.pypa.io/pip/3.5/get-pip.py
Sorry if this change causes any inconvenience for you!
We don't have a good mechanism to make more gradual changes here, and this
renaming is a part of an effort to make it easier to us to update these
scripts, when there's a pip release. It's also essential for improving how we
handle the `get-pip.py` scripts, when pip drops support for a Python minor …
```
=> Fix bootstrap links in tox-lxd-runner script

features/unattached_commands.feature, uaclient/security.py, uaclient/status.py, uaclient/tests/test_security.py
Handle other package status when running ua fix
Currently, when we are fixing a USN or CVE, we are just handling the case where a package has a released status. However, a package can have different status. If we have an affected package which status is not released, that CVE/USN cannot be completely fixed. We are now updating the ua fix logic to handle those status and correctly report to the user that a CVE/USN was not fixed when we found one of the other status.
PS: The original idea on this work was to group the packages based on the status and present a summarized view of those packages for each status. Although we can do this in the code, my rationale for not doing it is just that it could potentially modified
the output a lot. For example, for each affected package in the system, …
=> Handle other package status when running ua fix

features/unattached_commands.feature, uaclient/cli.py, uaclient/tests/test_cli_fix.py
Update message for invalid issue in ua fix
We are now updating the error message we output when an invalid CVE/USN is given to the ua fix command.
Fixes: #1433
Run the modified unit test and integration tests
=> Update message for invalid issue in ua fix

uaclient/exceptions.py, uaclient/security.py, uaclient/tests/test_security.py
Since binary packages derived from a source package can have
different versioning schemes, check binary package versions
reported by USN.release_packages if present.
CVE package statuses only report the source package version, so
only fallback to use CVE package statuses versions if USN does not
report either the specific binary package version or the related
source package version.
Fixes: #1436
```bash
lxc launch ubuntu-daily:trusty dev-t
lxc exec dev-t add-apt-repository ppa:canonical-server/ua-client-daily
lxc exec dev-t apt-get update
lxc exec dev-t apt-get install ubuntu-advantage-tools
lxc file push uaclient/security.py dev-t/usr/lib/python3/dist-packages/uaclient/security.py
lxc exec dev-t ua fix -- ua --debug fix USN-4754-4
lxc exec dev-t ua fix -- ua --debug fix USN-4754-1
```
=> fix: prefer USN.release_packages binary pkg versions to CVE src ver

uaclient/apt.py, uaclient/tests/test_apt.py
Add retry for apt-helper command
We have experience some flaky issues regarding the apt-helper download-file command. Because of that, we are now retrying on that command to try to avoid those flaky issues.
Fixes: #1431
Run the modified unit tests
=> Add retry for apt-helper command

features/unattached_commands.feature, uaclient/exceptions.py, uaclient/security.py, uaclient/tests/test_security.py
Two fixes here,
- Aggregate all related USNs #1451 
- fix: use pocket values from USNs  #1439
fix: parse all related USNS to a given CVE when fixing
ua fixing a USN instead of CVE will pool all related USNs based on
calls to client.get_notices(details=cve_id) for each usn.cve_ids.
Change Security API calls to use notices.json?details=<CVE-ID> when
fixing CVEs instead of cves/<CVE-ID>.json to get a single response
containing all related USNs.
merge_usn_released_binary_package_versions now takes a list of USNs
instead of a single CVE and merges the set of all usn.released_packages
to provide binary package API responses.
Now print "Related CVEs: X, Y, Z" message when fixing a USN.
Also reorder logic to prompt for subscription URL and fall through
to prompt for token when the user hits …
=> fix: parse all related USNS to a given CVE when fixing

features/unattached_commands.feature, uaclient/security.py, uaclient/tests/test_security.py
fix: provide related CVE URLs instead of USNs
During a `ua fix USN-XXX` provide related CVE URLs for context
instead of USN URLs.
Fixes: #1456
```bash
PYTHONPATH=. python3 -m uaclient.cli  fix USN-4575-1
PYTHONPATH=. python3 -m uaclient.cli  fix USN-4754-1
```
=> fix: provide related CVE URLs instead of USNs

features/steps/steps.py, features/unattached_commands.feature, uaclient/security.py, uaclient/status.py, uaclient/tests/test_security.py
Update output for released packages in ua fix
Currently, we list every released package in the output of ua fix and only after that we start installing them. This is not optimal since depending on the source of the package we need to perform different actions to install those packages. Therefore, we are now grouping the released packages by pocket origin and acting on them as soon as we can.
Fixes: #1438
This branch is not yet complete. I still need to add more unit tests and integration tests to it.
However, it is possible to verify the current expected behavior by running the modified unit tests
=> Update output for released packages in ua fix

features/unattached_commands.feature, uaclient/security.py, uaclient/tests/test_security.py
CVEPackageStatus of not-affected should be honored for a given
release. Do not group and report these packages during a fix
because there will be no released fixes for "not-affected" packages.
Add human-readable messaging for CVEs with not-affected status:
Source package is not affected on this release.
Fixes: #1467
CVEPackageStatus of not-affected should be honored for a given
release. Do not group and report these packages during a fix
because there will be no released fixes for "not-affected" packages.
Add human-readable messaging for CVEs with not-affected status:
Source package is not affected on this release.
Fixes: #1467
```bash
tox -e behave-lxd-16.04 features/unattached_commands.feature:226
```
=> fix: get_cve_affected_source_packages_status won't list not-affected

features/steps/steps.py, features/unattached_commands.feature, uaclient/security.py, uaclient/status.py, uaclient/tests/test_security.py
Prompt to enable service during ua fix
Currently, when we are running ua fix and a necessary ua service is not enabled, we abort the operation and report that the CVE/USN was not solved. However, if the user is entitled to that service through uaclient, we can prompt the user to enable that service during the fix operation. We are now adding this functionality to the ua fix command.
Fixes: #1455
Run the modified integration test in this PR
=> Prompt to enable service during ua fix

uaclient/cli.py, uaclient/tests/test_util.py, uaclient/util.py
Add regex log redacting for uaclient/cli.py and
uaclient.util.readurl call and response logging.
This is a step toward eventually making ubuntu-advantage.log
world-readable.
Fixes: #1424
checkout this branch on a xenial container
```bash
make deps
dpkg-buildpackag -us -uc
dpkg -i ../*deb
ua --debug attach <yourTOKEN>
egrep '<yourToken>|REDACT' /var/log/ubuntu-advantage.log
```
=> logs: emit error response on API errors and redact sensitive logs

uaclient/security.py, uaclient/tests/test_security.py
fix: filter usns by cve details
When we are querying for related USNs to fix, we use find all related USNs to a given CVE. However, the query that we are using to get the related USNs is using applying the CVE match as a substring instead of an exact match. This means that we will be return USNs that are not related to our query CVE, but have are fixing a CVE which id is a substring of our original CVE. We are filtering the returned USNs to only those that actually contain the exact CVE id in them.
Fixes: #1470
Run the new unittest added
=> fix: filter usns by cve details

features/attach_invalidtoken.feature, features/attached_commands.feature, features/attached_enable.feature, features/unattached_commands.feature, features/unattached_status.feature, uaclient/cli.py, uaclient/defaults.py, uaclient/entitlements/tests/test_base.py, uaclient/security.py, uaclient/status.py, uaclient/tests/test_cli_status.py, uaclient/tests/test_security.py
fix: prompt for new token when expired one is used
When running ua fix we may need to install packages that depend on a UA service. Even if the user is already attached
to a UA subscription, this may not be enough, since the token used may be expired. If we encounter that situation, we would
need to ask the user to get a new token before proceeding with the package fixes. We are now adding the necessary code to allow us to handle that scenario.
Fixes: #1475
Run the new unittests for this feature
=> fix: prompt for new token when expired one is used

features/unattached_commands.feature, uaclient/security.py, uaclient/status.py, uaclient/tests/test_security.py
fix: show packages that were not fixed
When running ua fix when may end up in a state where we cannot fix all the packages. If we get into that situation, we will not display to the user what were the packages that were not fixed and are still affected by the CVE/USN that the command tried to fix.
Fixed: #1448
Run the modified integration tests in this PR
=> fix: show packages that were not fixed

features/environment.py
tests: run status wait before detach in PRO tests
When we are creating a PRO instance, we install the latest uaclient package on the machine and then snapshot it to be used as a base image for all other tests. This base image should be a clean image, meaning that it should not be attached to uaclient. To ensure that, we run a detach operation on the base image and config it to block auto-attach. However, when we run detach, the auto-attach operation may still be running. We are now running ua status --wait before detach to avoid that.
Run any of the GCP PRO integration tests
=> tests: run status wait before detach in PRO tests

uaclient/security.py, uaclient/tests/test_security.py
Reduce the number of API calls needed to query related CVEs and USNs
by processing the keys USN["cves"] and CVE["notices"] which now
contain detailed metadata response for the CVE and USN objects.
- Drop unneeded USN.get_cves_metadata and CVE.get_notices_metadata
- add CVE.notices to cache a list of USNs based on new "notices"
key which contains full USN metadata from API response
- adapt CVE.notices_ids to rely on new "notices_ids" key from API
- add USN.cves to cache a list of CVEs based on the new "cves"
full metadata from API response
- adapt USN.cves_ids to rely on new "cves_ids" key from API
- add equality checks for USN and CVE instances
=> fix: parse full API responses for related CVEs and USNs

features/environment.py, features/gcp-ids.yaml
CPC team just published official GCP images.
Add a secondary commit to allow specifying UACLIENT_BEHAVE_PPA="" to avoid altering PRO images under test
Update our gcp test image ids to reference the public images.
```bash
UACLIENT_BEHAVE_PPA="" UACLIENT_BEHAVE_GCP_PROJECT=ubuntu-rickh UACLIENT_BEHAVE_GOOGLE_APPLICATION_CREDENTIALS=/root/gcp-cred.json tox -e behave-18.04-gcp  # on a machine with gcloud credentials installed
```
=> gcp: update public gcp images for integration testing

Jenkinsfile
Make lint and style stage run sequentially
We are experiencing some issues running mypy tests. We believe that reason is because we are running tox inside
a virtualenv. To fix that, we removing the virtualenv creation from this stage and also making the jobs in that stage run sequentially
We can spot the behavior on the CI
=> Make lint and style stage run sequentially

uaclient/clouds/identity.py, uaclient/tests/test_security.py
fix: add links to ubuntu.com/gcp/aws in messaging when on non-PRO
Use our identity string mappings in uaclient.clouds.identity.CLOUD_TYPE_TO_TITLE to 
map cloud-specific messaging which instructs customers to use Ubuntu PRO images for 
easier security maintenance.
Unit tests exercise this notification message logic
```bash
tox -e py3 -- uaclient/tests/test_security.py -k test_messages_for_affected_packages_based_on_installed_and_usn_release
```
=> fix: add links to ubuntu.com/gcp/aws in messaging when on non-PRO

uaclient/tests/test_util.py, uaclient/util.py
Some apt errors contain % in the failure messages.
When concatenating this str(e) with a python %-formatting there
will be collisions when trying to report the number of retries
remaining.
Avoid this formmatting collision by first rendering any %-formatted
retry message and concatenating it to str(e) seperately.
Fixes: #1520
New Unit test will exercise this, otherwise one could do something like the following:
```bash
lxc launch ubuntu-daily:xenial dev-x 
lxc exec dev-x -- sudo add-apt-repository ppa:ua-client/daily
lxc exec dev-x -- sudo apt-get update
lxc exec dev-x -- sudo apt-get install ubuntu-advantage-tools
edit /usr/lib/python3/dist-packages/uaclient/util.is_container to return False
sudo ua attach <your_token>
sudo ua enable fips
See traceback
lxc file push uaclient/util.py …
```
=> subp: separate % format strings when logging

debian/control, uaclient/tests/test_util.py, uaclient/util.py
util: improve is_container check for chroot
When on a chroot, we don't want to say that the system is a container type. To avoid that, we are first calling the ischroot command. If it returns 0, we assume that we are on a chroot and inform that we are not in a container.
Run the modified unit tests
=> Update container check for chroot environments

uaclient/config.py, uaclient/security.py, uaclient/tests/test_cli_attach.py, uaclient/tests/test_cli_auto_attach.py, uaclient/tests/test_cli_status.py, uaclient/tests/test_config.py, uaclient/tests/test_security.py
fix: notify users if reboot is required
When upgrading packages during ua fix we may install a package that requires a system reboot to fully fix the issue at hand. We are now alerting the user if a reboot is required when running ua fix.
Fixes: #1476
PS: The approach used here some shortcomings:
* If the user has installed a package that requires reboot and then run ua fix, we will not known if the reboot is need because of ua fix or the package installed by the user.
* If we detect that a reboot is required, should we say that the CVE/USN was not fixed ? I am using that approach, but I am not sure if that is the intended behavior.
Run the new unittest added
=> fix: notify users if reboot is required

uaclient/cli.py, uaclient/tests/test_cli_detach.py
cli: pass assume_yes param to services on detach
Currently, we are not passing the assume_yes parameter to each service that we will disable during a detach operation. We are now updating detach to pass assume_yes for all services that it will disable during the operation.
Fixes: #1530
Run the modified unit test
=> cli: pass assume_yes param to services on detach

features/steps/steps.py, features/unattached_commands.feature, uaclient/cli.py, uaclient/config.py, uaclient/defaults.py, uaclient/security.py, uaclient/tests/test_security.py
fix: update how the expired token logic works
We are now updating the logic to verify if an UA subscription has expired. Instead of requesting an ua refresh and verifying if the
contract backend has raised any errors, we are now going directly to the machine-token.json file and verifing until which date the contract is valid through the effectiveTo field.
Run the modified unit tests and run the modified trusty integration test
=> fix: update how the expired token logic works

lib/reboot_cmds.py, uaclient/status.py, uaclient/tests/test_reboot_cmds.py
lib: fix notice handling on reboot script
When the reboot script fails, we keep the notice that show that it is running. This happens because the assert_lock_file decorator cannot complete and remove the notice. We are now fixing that by catching the exceptions in the reboot script. Furthermore, we also issue a notice if the reboot script fails for some reason.
Fixes: #1518
Run the new unit test on this PR
=> lib: fix notice handling on reboot script

uaclient/clouds/identity.py, uaclient/clouds/tests/test_identity.py, uaclient/config.py
config: create settings_overrides on config
Currently, we need cloud-init to identify if FIPS can be correctly installed in an instance. This behavior is making
it harder to use uaclient in other scenarios, for example, when building an image using chroot. To better handle that, we are
creating a settings_overrides dict in ua config. Users will be able to override specific settings by just updating the uaclient.conf
file.  For example, to override the cloud type users will need to add this to `uaclient.conf`:
```yaml
settings_overrides:
cloud_type: "gce"
```
To use these overrides, we have created a decorator that can modify a function return based on the override defined in the config. As of today, this is only being used in the get_cloud_type function.
Fixes: #1507
This is a WIP branch …
=> {WIP] config: create settings_overrides on config

uaclient/config.py, uaclient/tests/test_config.py
status: do not remove notices on non-root call
When we run ua status we try to remove notices that are created by fix operations. However, non-root users do not have the right permissions to remove them. We are now fixing the code to only attempt to remove the notices if ua status is run by root users.
Fixes: #1550
Run the modified tests
=> status: do not remove notices on non-root call

apt-hook/20apt-esm-hook.conf, apt-hook/Makefile, apt-hook/hook.cc, features/attached_enable.feature, features/staging_commands.feature, features/unattached_commands.feature
* on `apt upgrade/dist-upgrade`
* find esm packages (names and count)
* will insert values into message template for contract-expiry message if the template exists and print the message
* when called as `hook process-templates`
* find esm packages (names and count)
* will insert values into hardcoded message templates that exist
* outputs those messages to static files with the values filled in
* on `apt update`
* updates all the template files, but no longer prints the messages it used to
> apt-hook: process template files and print messages with esm stats
>
> apt-esm-hook will now process a set of .tmpl files in the ua messages
> directory, both when apt calls it and when called separately with the
> "process-templates" argument. It replaces variables in the tmpl files
> with the values …
=> apt-hook: print static messages on apt upgrade/dist-upgrade

debian/ubuntu-advantage-tools.postinst, features/steps/steps.py, features/unattached_commands.feature
Ship esm-infra pref file only on xenial and trusty
Currently, we are shipping the esm-infra preference file on all LTS releases. However, our codebase only supports that preference file for trusty and xenial. Because of that, we are updating our postinst script to onoy ship that file for trusty and xenial
Run the `Attach command in a ubuntu lxd container` scenario on `attach_valitoken.feature` without this change and with this change
=> Ship esm-infra pref file only on xenial and trusty

debian/ubuntu-advantage-tools.postinst, uaclient/entitlements/esm.py, uaclient/entitlements/tests/test_esm.py, uaclient/tests/test_util.py, uaclient/util.py
esm: enable infra when EOL LTS and apps on all LTS
Enable showing unauthenticated APT package counts for the following:
- ESM Infra on any end of life Ubuntu LTS release
- ESM Apps when non-beta on any Ubuntu LTS release except Trusty
Fixes: #1558
---
util: add is_lts and is_active_esm funtions to support ESM
Shell out to ubuntu-distro-info to determine the following:
- is_lts: the provided Ubuntu release is an LTS release
- is_active_esm: the provided Ubuntu release has entered EOL and is
entitled to ESM Infra
---
d/postinst: configure esminfra when is_active_esm and apps on LTS
use ubuntu-distro-info to check_is_lts and check_is_active_esm.
When on LTS, setup unauthenticated ESM Apps APT sources when
apps is not beta.
Setup ESM Infra on pkg install when ESM lifecycle has started
via …
=> Esm apps all lts

apt-hook/hook.cc, debian/rules, features/attach_validtoken.feature, features/attached_enable.feature, features/staging_commands.feature, features/steps/steps.py, features/unattached_commands.feature, lib/ua_update_messaging.py, setup.py, systemd/ua-messaging.service, systemd/ua-messaging.timer, tox.ini, uaclient/cli.py, uaclient/config.py, uaclient/defaults.py, uaclient/entitlements/esm.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_esm.py, uaclient/status.py, uaclient/tests/test_cli_attach.py, uaclient/tests/test_cli_auto_attach.py, uaclient/tests/test_cli_detach.py, uaclient/tests/test_ua_update_messaging.py, uaclient/tests/test_util.py, uaclient/util.py, update-motd.d/88-esm-announce, update-motd.d/91-contract-ua-esm-status
shared MOTD and APT messaging generation
APT and MOTD messaging share a number of common messages.
To share those message template between apt-hooks and MOTD-hooks
the ua_update_messaging script will generate message templates
appropriate for both APT and MOTD and store them in
/var/lib/ubuntu-advantage/messages/*tmpl.
The ua_update_messaging script will be triggered on every apt update
and will call esm-apt-hook to render those templates replacing
template variable names with dynamic ESM Apps and Infra package counts
and/or package names.
Fixes: #1536
Fixes: #1561
build the package from this PR
install on a test system
```bash
sed -i 's/UNRELEASED/xenial'
git commit -am 'changelog'
build-package
sbuild-it ../out/*dsc
lxc launch ubuntu-daily:xenial test-x
lxc file push *deb test-x/
lxc …
```
=> shared MOTD and APT messaging generation

apt-hook/hook.cc, features/attach_validtoken.feature, lib/ua_update_messaging.py, uaclient/status.py, uaclient/tests/test_ua_update_messaging.py
Currently, uaclient is advertising esm services by allowing motd to show messages saying that additional packages could be installed if esm service was enabled. We don't need those type of messages because update-notifier will handle them.
Also, we are updating the code to always show expired message for esm-infra services, even if the distro is not ESM
Message in update-notifer:
https://git.launchpad.net/update-notifier/tree/data/apt_check.py#n119
Remove redundant messaging from uaclient
=> Remove redundant messaging from uaclient

uaclient/config.py, uaclient/tests/test_config.py, uaclient/tests/test_util.py, uaclient/util.py
If /etc/ubuntu-advantage/uaclient.conf contains unexpected values
in features: settings log a warning and return an empty dict.
Avoid tracing on every ua subcommand call.
Fixes: #1564
```bash
lxc launch ubuntu-daily:xenial test-ua
lxc exec test-ua -- add-apt-repository ppa:ua-client/daily -y
lxc exec test-ua -- apt update
lxc exec test-ua -- apt install ubuntu-advantage-tools --assume-yes
cat > uaclient.conf <<EOF
features: null
EOF
lxc file push uaclient.conf test-ua/etc/ubuntu-advantage
lxc exec test-ua -- ua status   # expect to see failure
lxc file push uaclient/config.py test-ua/usr/lib/python3/dist-packages/uaclient
lxc exec test-ua -- ua status   # expect no failure
```
=> config: avoid tracebacks on invalid features value in uaclient.conf

tools/test_xenial_upgrade.sh
I commented out these lines when testing the last couple fips changes and forgot to take them out before we merged last time :facepalm: 
It's probably a good idea to run the script with these lines uncommented again before merging. I already did and it was all good on my end.
=> test: uncomment additional xenial upgrade tests

apt-hook/hook.cc, features/attach_validtoken.feature, uaclient/status.py
apt-hook: avoid reporting and counting duplicate package names
Only track unique named package upgrades in ESM.
Both esm -updates and esm-security pockets can contain same
packages. Avoid counting duplicates.
Fixes: #1578
- messages: add optional (s) to apt messaging to include singular/plural pkgs
```bash
UACLIENT_BEHAVE_DESTROY_INSTANCES=0 UACLIENT_BEHAVE_BUILD_PR=1 UACLIENT_BEHAVE_CONTRACT_TOKEN=<YOUR_CONTRACT_TOKEN> tox -e behave-lxd-16.04 features/attach_validtoken.feature:117
```
=> Hook no dupes

uaclient/cli.py, uaclient/status.py, uaclient/tests/test_status.py
status: do not show info if not on contract
When running status on an attached machine, we present the account and subscription info in the the end. However, if the contract does not have that info, we will present them as empty. We are now updating the status to not show that info at the end if it is not present in the contract.
Fixes: #1592
Run the modified unit test
=> status: do not show info if not on contract

lib/reboot_cmds.py, uaclient/cli.py, uaclient/contract.py, uaclient/tests/test_cli.py
> logging: remove tracebacks for UserFacingErrors
> 
> UserFacingErrors are used for known situations that
> our code can handle and present the correct message to
> the user. They are not truly "exceptional" and do not
> warrant printing a traceback when they occur. This commit
> changes our logging of these types of errors to continue
> to use the ERROR logging level but no longer include
> tracebacks.
> 
> Fixes: #1586
To reproduce:
On a xenial container you'll get tracebacks in logs for several things
```
apt update && apt upgrade
ua detach
ua attach # no token
ua attach <token>
ua attach <token>
ua enable esm-apps
```
To see fix, install this version and run through the above steps. You should still see error messages, but no tracebacks.
=> logging: remove tracebacks for UserFacingErrors

uaclient/entitlements/livepatch.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/status.py
livepatch: alert when snapd does not have wait cmd
When enablig livepatch, we run a snapd wait operation before
installing the canonical-livepatch snap. On older system that did
not upgrade snapd, the wait command may not be available. In that
situation, enabling livepatch will fail. We are now updating the code
to alert the user about this situation, but we proceed with enabling
livepatch.
LP: #1927905
Run the new unit test
=> livepatch: alert when snapd does not have wait cmd

features/staging_commands.feature, uaclient/entitlements/cis.py, uaclient/entitlements/tests/test_cis.py
Update of CIS URL to https://security-certs.docs.ubuntu.com/en/cis until ubuntu.com/security/cis is available
Also add a commit to fix failing integration tests due to messaging url changes for ESM on Xenial https;//ubuntu.com/16-04
=> cis: update cis help url

uaclient/clouds/aws.py, uaclient/clouds/tests/test_aws.py, uaclient/tests/test_util.py, uaclient/util.py
Avoid 401 Unauthorized errors from IMDSv2 API on AWS by
obtaining an API token from latest/api/token.
The Unauthorized errors result in inability to auto-attach on
Ubuntu PRO instances which are configured at launch to only
allow IMDSv2 traffic.
Use this token with any GET calls to read the pkcs7 metadata
by providing the API token as a header X-aws-ec2-metadata-token.
Some regions may not have IMDSv2 support, in those cases fallback
to using no token.
Also redact this IMDSv2 token from GET and PUT response logs.
Fixes: #1608
```bash
1. Click the button to launch Ubuntu PRO 18.04 on AWs instance https://ubuntu.com/aws/pro
2. "Continue to subscribe"
3. "Continue to configuration"
4. "Continue to Launch"
5. "Choose Action: Launch through EC2"   # not launch through website   then "Launch" …
```
=> pro: obtain AWS IMDSv2 API token before trying to grab pkcs7 doc

features/unattached_commands.feature, uaclient/cli.py, uaclient/status.py, uaclient/util.py
> errors: print a more helpful message when ssl fails
> 
> Fixes: #1618
* In some way, mess with ssl's ability to verify a certificate.
* For example, uninstall `ca-certificates`
* Try to run any `ua` command that talks to the network (attach, fix, etc.)
* Verify that a descriptive and actionable message is printed
=> errors: print a more helpful message when ssl fails

features/staging_commands.feature, uaclient/cli.py, uaclient/entitlements/base.py, uaclient/entitlements/esm.py, uaclient/entitlements/fips.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_base.py, uaclient/entitlements/tests/test_cc.py, uaclient/entitlements/tests/test_esm.py, uaclient/entitlements/tests/test_fips.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/entitlements/tests/test_repo.py, uaclient/status.py, uaclient/tests/test_cli_enable.py, uaclient/util.py
> enable: correct messaging for beta service
>
> Previously, if the user tried to enable a beta service
> that was already enabled without using --beta, they
> would get incorrect messaging. Now they are correctly
> told that the service is already enabled.
> 
> Fixes: #1588
Enable a beta service such as esm-apps
Then run `ua enable esm-apps` without the `--beta` flag.
Verify that the output correctly states that esm-apps is already enabled.
=> enable: correct messaging for beta service

features/staging_commands.feature, uaclient/config.py, uaclient/entitlements/fips.py, uaclient/entitlements/tests/conftest.py, uaclient/entitlements/tests/test_fips.py
Block enabling fips if fips-updates once enabled
When fips-updates is enabled in the system, we emit a file that will allows us to kept track of this status. This will be necessary if an user disables fips-updates and tries to enable fips. In that scenario, we cannot allow users to enable fips.
Fixes: #1600
=> Block enabling fips if fips-updates once enabled

Jenkinsfile, uaclient/entitlements/tests/test_fips.py
We have a wrong test now that is incorrectly mocking `handle_message_operations`. This PR is fixing that test while also adding pytest runs for xenial and bionic
Run the modified unittest
=> Fix pytest run

apt-hook/Makefile, debian/lintian-overrides
*   apt-json-hook: fix lintian warnings based on compiled binary
Provide -ldflgas and -buildmod=pie to go build of this hook.
Fixes: #1626
*    lintian: override ubuntu-advantage-pro wanted-by-target cloud-init
Silence warning for pro wanted-by-target cloud-init.service.
```bash
sed -i 's/UNRELEASED/focal/' debian/changelog
git commit -am 'changelog bump for testing'
build-package
sbuild-it ../out/*dsc
should emit less lintian warnings
```
=> Lintian fixes per SRU of 27.0.2

RELEASES.md, apt-hook/hook.cc, features/attach_validtoken.feature, features/unattached_commands.feature
WIP: Based on integration test fixes in https://github.com/canonical/ubuntu-advantage-client/pull/1643. Land that PR first. then rebase this on upstream/main before landing
-----
Wrap apt.File.Origin in DeNull in case the Origin is not yet setup or
in the event that an APT repo does not have a valid origin set.
This will allow the apt-esm-hook to compare "(null)" to "ESM*" and
avoid segfaults.
LP: #1929123
New integration test should cover this by adding a known APT repo which has an empty Origin: value in the repo Release file.
=> apt-hook: avoid segfault when comparing null Apt file origin to esm (SC-2)

debian/changelog, debian/lintian-overrides, debian/source/lintian-overrides, debian/ubuntu-advantage-pro.lintian-overrides, uaclient/version.py
Final round of missing changelog commits which resolve:
* lintian warnings such as changelog spelling errors and lintian overrides
* separate package-specific debian/lintain-overrides
* bring in redacted line in debian/changelog from 27.0 which was released to Bionic -> Hirsute but not publishing in impish
Also open version 28.0 for active development so daily PPA is greater than released version of ua-tools
* changelog: amend redacted line in 27.0 which was already released to B-H
* lintian: rename package-specific overrides for pro vs tools
* open version 28 for active development
* changelog: open 28.0 for active development
* changelog: sync from impish release of 27.0.2
```bash
sed -i 's/UNRELEASED/focal/' debian/changelog
git commit -am 'testchangelog'
build-package
sbuild-it …
```
=> Lintian fixes, changelog sync and open 28.0 for development (SC-12)

uaclient/cli.py, uaclient/entitlements/base.py, uaclient/entitlements/tests/test_base.py
If we fail to enable a service, we call the can_enable method directly. We do that to verify if the reason we failed to enable a service is because the service is in beta mode. However, the can_enable method calls the handle_incompatible_services method, which may prompt users to disable the incompatible service again. Since this check is only used to see if the service is beta, we should not allow for disabling incompatible services when we do it.
Fixes: #1652
PS: I believe we could have a better solution for this issue if we make the [enable](https://github.com/canonical/ubuntu-advantage-client/blob/main/uaclient/entitlements/base.py#L148) method return the reason why it failed. In that way, we would not need to perform the second `can_enable` call. However, this will be a bigger change …
=> enable: don't allow disabling services on beta check

features/attach_validtoken.feature, features/attached_commands.feature
tests: fix apt and motd messaging test
Both xenial and focal now have esm-infra packages that show up in the `motd` message. Also, xenial now has more `esm-infra` packages that can be installed, therefore we are also updating the apt upgrade message as well
Run the modified integration test for xenial and focal
=> tests: fix apt and motd messaging test

README.md, features/environment.py, features/util.py
***Not intended for 27.1. Wait to merge until 27.1 release is finalized***
> tests: add config for not caching source
>
> It may be confusing for some that the source is cached when using
> UACLIENT_BUILD_PR=1 when running the integration tests. Here we add
> documentation that instructs the developer to remember to remove the
> source cache, and also introduces a new environment variable to ignore
> the cache altogether.
* Run an integration test with `UACLIENT_BEHAVE_BUILD_PR=1 UACLIENT_BEHAVE_CACHE_SOURCE=0`.
* make a change to the uaclient source
* do not `rm /tmp/pr_source.tar.gz`
* Run the integration test again with the same envvars, and verify the changes to uaclient are reflected in the test
=> tests: add config for not caching source

uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_cis.py, uaclient/entitlements/tests/test_fips.py
repo: allow downgrading packages during enable
When enabling a repo entitlement, like FIPS, we are currently not allowing for package downgrades. This is problematic if users are using package from a third party, that could have versions higher than the ones we are delivering. To enforce that users will run the right packages for the services we are enabling, we are now supporting downgrading packages when enabling a service.
Fixes: #1659
Since we are just adding a new apt flag, run an existing FIPS vm test to confirm that the flag is not breaking the enable step
=> repo: allow downgrading packages during enable (SC-69)

features/environment.py
We need this change before we upgrade pycloudlib to incorporate https://github.com/canonical/pycloudlib/pull/148
> tests: remove clashing lxd user-data
>
> lxd relies on a write_files vendor-data directive to set up the
> lxd-agent on lxd vms of some ubuntu releases. Our use of write_files was
> overwriting the vendor-data and preventing the lxd-agent from coming up.
> 
> Here we use a runcmd to accomplish the same thing we were using
> write_files for in our integration tests.
Make sure integration tests still pass
=> tests: remove clashing lxd user-data (SC-91)

debian/ubuntu-advantage-tools.postinst, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py, uaclient/status.py
fips: add gov clouds to metapackage override logic
When overriding the metapackage to be installed on cloud instances, we are not taking into consideration the cloud-id of government clouds. This is a problem, because those clouds should also install the cloud specific fips metapackages.
Run FIPS tests for aws and azure generic scenarios
=> fips: add gov clouds to metapackage override logic (SC-71)

uaclient/config.py, uaclient/tests/test_config.py, ubuntu-advantage.1
> config: only allow some fields to be set by envvar
Verify `UA_CONTRACT_URL=https://contracts.staging.canonical.com ua attach STAGING_TOKEN` doesn't work
Verify `LOG_LEVEL=debug ua status` does work
=> config: only allow some fields to be set by envvar (SC-111)

integration-requirements.txt
bump pycloudlib version
Bump pycloudlib to fix the problem of running xenial vm tests. From now on, we will not even try to install the lxd-agent on xenial anymore
Run a xenial vm test
=> bump pycloudlib version

features/environment.py, features/proxy_config.feature, features/steps/steps.py, uaclient/cli.py, uaclient/config.py, uaclient/util.py
Allow setting proxy for web requests
During some uaclient operations, we perform requests to communicate with the contract backend. If an user wants uaclient to respect a proxy configuration, we need to allow proxy configuration for these types of requests.
=> Allow setting proxy for web requests (SC-105)

features/proxy_config.feature, features/steps/steps.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/tests/test_livepatch.py
proxy: allow configuring snap and livepatch
Allow configuring both snap and livepatch proxies during the enable operation of livepatch
PS: There are still some points on this PR that we could improve. Currently, it seems that
requests for livepatch are arriving with a delay into the squid log, that's why I am running a sleep command
in the test. I can confirm that only running `canonical-livepatch refresh` does not remove that delay.
Furthermore, I am not seeing any log entries we I run 'ua detach`. Since we hit the contract backend on that
operation, I was expecting a log entry for it.
Run the new vm test
=> proxy: allow configuring snap and livepatch (SC-87)

uaclient/cli.py, uaclient/config.py, uaclient/defaults.py, uaclient/status.py, uaclient/tests/test_cli_status.py
status: show env vars on json output
We are now displaying if there is any ua specific environment variables set when the user runs ua status --format json
Run the updated unittest or set a valid UA env variable locally and verify that it appears in the json output
of `ua status --format json`
=> status: show env vars on json output (SC-155)

features/proxy_config.feature, uaclient/apt.py, uaclient/entitlements/livepatch.py, uaclient/entitlements/tests/test_livepatch.py, uaclient/status.py, uaclient/tests/test_apt.py
This replaces #1687 
Note this also includes the same bugfix as mentioned here: https://github.com/canonical/ubuntu-advantage-client/pull/1687/files#r658167087
> proxy: print message when setting proxy
Set the proxy variables in the config.
Enable an apt based service and livepatch.
Verify concise messages are printed that help you understand what UA is doing.
=> proxy: print message when setting proxy (SC-179)

uaclient/config.py, uaclient/status.py, uaclient/tests/test_cli.py, uaclient/tests/test_cli_status.py, uaclient/tests/test_config.py
status: do not show unavailable services on json
We are now only showing available services in the status json output. Because of that, we are also dropping the available key from the json output, since now it is a redundant key.
Run the modified unittests
Launch a container and verify that `cc-eal` does not appear when unattaches and attached
=> status: do not show unavailable services on json

features/attach_validtoken.feature, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py
fips: don't install openssh hmac packages on focal
On Focal, we don't have the openssh hmac packages. Because of that, we must exclude then when enabling any FIPS service on Focal
PS:  Originally, i though about using a different solution that check if the package can be installed before adding it to the list of installable FIPS packages. However, this could create scenarios were we partially install FIPS packages, which is not ideal. That's why I am explicit on which package should be included based on the distro version
1) attach a valid fips-preview contract on a focal machine
2) manually change the name of `fips-updates'  to `fips-preview`
3) enable `fips-preview`  and test to see if everything is working as expected
=> fips: don't install openssh hmac packages on focal

uaclient/config.py, uaclient/conftest.py, uaclient/status.py, uaclient/tests/test_cli_attach.py, uaclient/tests/test_cli_status.py, uaclient/tests/test_config.py, uaclient/tests/test_status.py
status: update contract info on status json output
We are now removing from root contract based information and adding that info into a contract specific object. Additionally, the products and created_at info for the contract are now present in the json output as well
Launch a container and verify that the contract object appears on the json output of `ua status --format json` when unattaches/attached
=> status: update contract info on status json output

debian/changelog
Just bringing in the changelog entry for 27.1 that is currently only on the `release-27` branch
=> changelog: release 27.1

uaclient/config.py, uaclient/conftest.py, uaclient/status.py, uaclient/tests/test_cli_status.py, uaclient/tests/test_config.py, uaclient/tests/test_status.py
status: add account info into json output
We are now creating a separate account object in the status json output. We are moving all account related info into that object while also adding new fields to into, such as created_at
Launch a PRO instance and check that the account info we are adding appears when running `ua status --format json`
=> status: add account info into json output (SC-152)

uaclient/cli.py, uaclient/config.py, uaclient/conftest.py, uaclient/status.py, uaclient/tests/test_cli_attach.py, uaclient/tests/test_cli_status.py, uaclient/tests/test_config.py
```
status: update root level keys of json status
* changes expires to null when not present instead of "n/a"
* ensures expires is always iso format
* adds _schema_version
* adds version
* adds machine_id
* adds effective
* changes configStatus to execution_status
* changes configStatusDetails to execution_details
* changes services[].statusDetails to services[].status_details
```
Run `ua status --format=json` as {nonroot, root} {unattached, attached} and ensure changes described in commit message are applied appropriately.
@blackboxsw @lucasmoura some of these may be breaking changes. If they are then I can revert them for now. Do you know if desktop team (or anyone else) relies on the old camelCase keys or on the expires value "n/a"?
=> status: update root level keys of json status (SC-150)

uaclient/cli.py, uaclient/entitlements/fips.py, uaclient/status.py, uaclient/tests/test_cli_status.py
status: allow output to be in yaml format
We are now allowing users to specify the yaml format when looking at the status output
Launch a machine and test running `ua status --format yaml` on an unattached an attached uaclient
=> status: allow output to be in yaml format (SC-158)

tools/constraints-mypy.txt
mypy: add packaging constraint
packaging was recently updated to a version that uses type hints. This is not supported on python 3.5, which is a version we are running mypy tests on. We are now freezing packaging to a version that doesn't break mypy checks for python 3.5
Run mypy test without this change and see the python 3.5 error. Apply this change and confirm that the problem is fixed
=> mypy: add packaging constraint

features/environment.py
tests: do not prompt when installing uaclient
We have recently changed uaclient.conf config file. On PRO test, we have custom config to block auto-attach. Because of that,
when we install the new uaclient package, we are prompted about config changes. We are now updating our install command to not prompt under those circumstances
Run the azurepro-16.04 integration test without this change and confirm that uaclient is not properly installed. Add this change and verify that the test now succeeds as expected
=> tests: do not prompt when installing uaclient

uaclient/config.py, uaclient/conftest.py, uaclient/status.py, uaclient/tests/test_cli_status.py, uaclient/tests/test_config.py
status: add config info in the status output
We are now adding config info in the status output. This will be reflected whenener the user runs ua status with the --format flag
Launch a machine and check if the output of `ua status --format json` has the config keys. Also, check if changing the path to load the config file from will reflect in ua status
=> status: add config info in the status output

uaclient/config.py, uaclient/conftest.py, uaclient/tests/test_cli_status.py, uaclient/tests/test_config.py
config: remove config_path from config dict
We are now removing the config_path entry from the config dict and pushing that logic into a dedicated function. We are using that to not clash with the write_cfg method which by default writes all content of the config dict into disk. Since the config_path is a variable that is being used only internally, we don't need it on disk.
Run the modified unit tests and check that `config_path` is still working as expected when running any of the `ua status --format` commands
=> config: remove config_path from config dict

debian/ubuntu-advantage-tools.postinst, lib/patch_status_json.py, uaclient/tests/test_config.py, uaclient/tests/test_patch_status_json.py
There were a couple key renames and drops in in `/var/lib/ubuntu-advantage/statu.json` which would break non-root users runnning `ua status` after upgrade because non-root tries to read the old status.json cache which is only updated once a root user runs any UA subcommand.
Add postinst script to fix status.json for non-root users for the 27.2 release  of ubuntu-advantage-tools. It will only be triggered if /var/lib/ubuntu-advantage/status.json exists and we are upgrading from a ua-tools version prior to 27.2.
Also perform a drive-by bug fix: ua status on 27.2 emits warning messages about the config_path key added in an unrelated PR.
change write_cfg to avoid persiting "config_path" to uaclient.conf and move config_path additions below valid key checks in parse_config
- 
postinst: add …
=> non-root patch status.json file to avoid tracebacks (SC- 190)

uaclient/cli.py, uaclient/tests/test_cli.py
The variables are the same registered on the status JSON, as in **8f10bc5d761a5d3da1ab237db34937d20ddc45e8**
- Run a command with the aforementioned environment variables
- Check `/var/log/ubuntu-advantage.log` - it should be there
=> Log relevant env vars when running ua commands (SC-213)

features/staging_commands.feature, uaclient/entitlements/fips.py, uaclient/entitlements/repo.py, uaclient/entitlements/tests/test_fips.py, uaclient/status.py
fips: do not block enable on conditional packages
When enabling fips we install FIPS version of some packages if they are already installed in the system. Currently, we
block enable if we can't install any of those conditional packages. Now, we are alerting the user about errors on installing those
packages, but we don't block the enable operation
Run the new integration test added
=> fips: do not block enable on conditional packages (SC-216)

features/staging_commands.feature
Remove FIPS contract overlays for focal on staging, as they are not needed anymore.
=> tests: drop fips contract overlays for focal on staging (SC-217)

debian/changelog
Remove 24.4 lintian entry on 27.2 changelog
It seems that release 24.4 changelog was not modified for release 27.2. Because of that, we are removing that entry from the changelog
=> Fix 27.2 changelog

debian/changelog
We have a changelog entry for fixing lintian errors on the release 27.0 changelog. However, this was already reflected on 27.1. We are now removing that changelog entry from 27.2
=> Remove changelog entry already reflected on 27.1

debian/changelog
The 20apt-esm-hook.conf fix was already covered in the past release. We don't need that entry again for 27.2
=> Remve apt-hook entry from release 27.2 changelog

README.md, features/proxy_config.feature, ubuntu-advantage.1
Add information to the manpage on how to authenticate to proxy servers if needed, and add an integration test to ensure this authentication is working.
Fixes: #1727
=> Information about proxy authentication (SC-238)

debian/control, debian/rules
d/control|d/rules: use substvars for distro-info for Xenial deps
Xenial is specific and requires distro-info >= 0.14ubuntu0.2 but
Bionic and later should be >= 0.18ubuntu0.18.04.1.
Leave trusty unset because we haven't released support which
requires distro-info on trusty.
```bash
sed -i 's/UNRELEASED/xenial/'
build-package
sbuild-it ../out/*dsc
dpkg-deb  -I ubuntu-advantage-tools_28.0_amd64.deb | grep distro-info
```
=> Subst distro info

lib/patch_status_json.py, uaclient/tests/test_patch_status_json.py
Ignore potentially non-existing keys when patching the status JSON.
Fixes: #1734
=> postinst: ignore configStatus when not present (SC-240)

lib/patch_status_json.py, uaclient/tests/test_patch_status_json.py
Ignore potentially non-existing keys when patching the status JSON.
=> postinst: ignore configStatus when not present

features/environment.py
tests: don't run apt update on userdata
When installing ua directly from proposed, we create an userdata that create the proposed source file and runs apt update. This can cause race conditions on the start up process of an instance, since another apt command might be running. To try to avoid that, we are now running the apt update command only when we really need it
Run the gcp generic xenial test without this change and verify that it fails because of a cloud-init error. Apply that change and confirm that the test works as expected
=> tests: don't run apt update on userdata

debian/changelog, debian/ubuntu-advantage-tools.postinst
cloud-id will only do anyting useful if cloud-init ran and fails
otherwise (e.g. in a chroot while building an image) so do not run it at
all if /run/cloud-init/instance-data.json is not present.
LP: #1936833
=> postinst: do not run cloud-id if cloud-init did not run

features/steps/steps.py, features/ubuntu_upgrade.feature, features/ubuntu_upgrade_unattached.feature, tox.ini
This PR is based on #1738, only dropping the cis check on the integration test were we upgrade from focal into groovy
=> Integration tests upgrade unattached (SC-265)

features/cloud.py, features/environment.py, features/steps/steps.py, features/util.py, tox.ini
This adds a timestamps the logs of our integration tests and replaces many `print` calls with `logging.info` calls. The goal is to be able to identify the points in our tests that are taking up the most time.
> tests: logging with timestamps
To see the output try running the following:
```
env UACLIENT_BEHAVE_BUILD_PR=1 UACLIENT_BEHAVE_CHECK_VERSION=28.0 tox -e behave-vm-20.04 -- features/_version.feature --no-junit --logging-level DEBUG
```
=> tests: logging to determine what takes up time

features/cloud.py, features/environment.py, features/steps/steps.py, integration-requirements.txt
Allow running tests with ephemeral instances
We are now allowing running the integration tests with ephemeral instances. This will allow LXD to better handle deleting the instance, since we can now just stop the ephemeral instance and LXD will properly handle the deletion of the instance
Run any integration test with `UACLIENT_BEHAVE_EPHEMERAL_INSTANCE=1` and verify that the instance created instance
is an ephemeral one
=> Allow running tests with ephemeral instances (SC-266)

features/environment.py, features/util.py
tests: always build packages on a LXD container
When running integration tests with BUILD_PR=1, we build the ua package using in the same instance type that we are going to run the test on. This is not ideal, since we run integrations tests on clouds and LXD vms. We are now building the packages through sbuild, which is a faster and more correct approach for building the packages to be used in the test
Run either a vm or a cloud test with UACLIENT_BEHAVE_BUILD_PR=1 and verify that the package is built using sbuild.
To verify that run the tests with `--no-junit` and take a look at the logs to see references for the sbuild process running
=> tests: always build packages using sbuild (SC-267)

features/environment.py
```
tests: only use -proposed for ua
```
This is hard to test now that our latest release is in -updates. I suggest the following in a fresh xenial container:
1. Create the files that the new `printf` commands in this PR are creating
2. Change the specific package in `/etc/apt/preferences.d/uaclient-proposed` to `autopkgtest`
3. `apt update`
4. `apt install autopkgtest`
5. `apt policy autopkgtest`
* Ensure that -proposed is pinned at 400 but this package is pinned at 1001. Make sure the version of autopkgtest from proposed is installed
6. `apt upgrade`
* Ensure that nothing else is installed from -proposed
Also, still run `env UACLIENT_BEHAVE_ENABLE_PROPOSED=1 tox -e behave-vm-16.04 -- features/staging_commands.feature:479 --no-junit` and ensure it passes.
=> tests: only use -proposed for ua (SC-270)

Jenkinsfile, README.md, features/environment.py, features/steps/steps.py
Initial investigation into the cost of the snapshot strategy is summarized here: https://docs.google.com/spreadsheets/d/1ceahTwO7wy_Kb2i2nw7oII2PaGqm_26ZNSKw5ema4FI/edit#gid=0
Please ask if anything in there doesn't make sense.
```
tests: default to installing ua for each scenario
The strategy of creating a snapshot with ua installed before running any
integration test has a significant upfront cost. There are cases, such
as local development on one feature, where this upfront cost is not
worth it. This commit adds an option so that the snapshot strategy with
upfront cost can be optionally turned on, but defaults to off.
```
Run some integration tests with and without snapshot_strategy.
Use `--no-junit` so you can see the timestamps and logs to understand what is happening with and …
=> tests: default to installing ua for each scenario (SC-268)

features/staging_commands.feature, features/steps/steps.py, uaclient/clouds/identity.py, uaclient/clouds/tests/test_identity.py, uaclient/config.py, uaclient/entitlements/fips.py, uaclient/entitlements/tests/test_fips.py, uaclient/security.py, uaclient/tests/test_cli_auto_attach.py, uaclient/tests/test_security.py
`get_cloud_type` now returns a tuple of (result, failure), and if it fails because of `cloud-id`, FIPS enablement has a warning about it.
Fixes: #1541
=> cli: catch errors when determining cloud type 

debian/ubuntu-advantage-tools.postinst, features/postinst.feature
Cloud ID is used during postinst to warn users about potentially wrong FIPS packages on Azure or AWS.
If `cloud-id` fails on top of those, then there would be worse problems with the instance.
If `cloud-id` fails anywhere else, the message is unnecessary.
Thus, we can completely ignore `cloud-id` fails here, and make sure we don't fail.
=> postinst: ignore any cloud-id error on postinst (SC-280)

README.md, debian/rules, lib/timer.py, systemd/ua-timer.service, systemd/ua-timer.timer, uaclient/jobs/update_messaging.py, uaclient/serviceclient.py, uaclient/tests/test_serviceclient.py
- Finalize ua-timer systemd renames
-  Add API response overlay functionality enabled by uaclient.conf features: serviceclient_url_responses
- systemd: rename ua-messaging.service to ua-timer.service
-     testing: add overlay for any serviceclient API response
To enable development testing of features that are not yet
available on the contract server or security API endpoints,
We can now provide API response overrides from a file on disk for any
matched URL.
uaclient.conf can add
features:
serviceclient_url_responses: <some_json_file>
The represented some_json_file will contain a JSON dict keyed
by full URL path.
Each value for the URL key will be a list containing response dicts
with a HTTP "code" key and a "response" key.
Any servicelicent URL requests to URLs matching the …
=> Systemd timer rename and API response overlays

uaclient/contract.py, uaclient/tests/test_util.py, uaclient/util.py
If we receive a value for machine ID, it is persisted in config and should be preferred over any other value.
=> contract: try to get machine ID from the config (SC-294)

uaclient/contract.py
For now, there is still logic that depends on Machine ID being persisted separately.
If a new Machine ID is sent to us in the Machine Token, this should be the one we persist.
=> fix: make sure the latest value of machine-id is persisted

uaclient/tests/test_contract.py
test: update contract response to a dict
We now try to get the machine id info from the contract response first. On our test, the mocked response was a string. We are now updating it to be a dict to fix that issue
Run the modified test
=> test: update contract response to a dict

uaclient/contract.py, uaclient/tests/test_util.py, uaclient/util.py
CS is going to send us the machine ID inside of `machineTokenInfo`, and we should try to get it from there.
=> fix: get machine ID from inside of machineTokenInfo (SC-319)

lib/timer.py, uaclient/jobs/gcp_auto_attach.py, uaclient/tests/test_ua_timer.py
jobs: add gcp auto-attach job
Add gcp job that tries to run an auto-attach operation every 30 minutes. Before we try to run that command we verify that we are running on a GCP cloud and that we are not already attached. If we detect any of those scenarios, the job will not execute
Launch a GCP PRO instance, then:
1) Run a detach command
2) Stop the systemd timer: `systemctl stop ua-timer.service`
3) Enable the systemd timer: `systemctl start ua-timer.service`
4) Wait a couple of minutes and verify that the instance is now attached to an UA subscription
5) Verify that the jobs status json file was created
=> jobs: add gcp auto-attach job (SC-333)

uaclient/clouds/azure.py, uaclient/clouds/tests/test_azure.py
```
azure: support Azure published images bump IMDS API version
Update the API_VERSION to 2020-09-01 to support grabbing both
publisher and SKU information which helps discern whether
an image is published by Microsoft itself versus one published
by Canonical.
Azure PRO based images will require an update to the IMDS APIcw
version so the contract server can see whether the image is
Canonical PRO or a Microsoft derivative image based on PRO.
```
=> azure: support Azure published images bump IMDS API version
